### ISSUE TITLE
Permissions to access logging data in Kibana

### ISSUE THREAD

**Issue by ronensc** [operate-first/support#100]
**Describe the bug**
I'm part of the `open-aiops` team and as part of the work on DeCorus, I need access to the logging data in Kibana.

**To Reproduce**

**Expected behaviour**
Being able to query logging indices in Kibana

**Screenshots**
![image](https://user-images.githubusercontent.com/31612939/109643933-8a748880-7b5d-11eb-91f1-d7ff9c77abf3.png)

I'm able to list the indices in the Dev Tools
![image](https://user-images.githubusercontent.com/31612939/109644177-d3c4d800-7b5d-11eb-81b8-58bd9e2c94f4.png)

but, I get a "no permissions" error when I try to query `infra-*` or `app-*` indices
![image](https://user-images.githubusercontent.com/31612939/109644222-de7f6d00-7b5d-11eb-8a31-be15c1cf2d66.png)
![image](https://user-images.githubusercontent.com/31612939/109644300-f9ea7800-7b5d-11eb-90f0-148406ff4da1.png)

**Additional context**
@drbwa who is a member in my team, has access to these indices.

relevant issues:
https://github.com/operate-first/support/issues/44
https://github.com/operate-first/apps/issues/171
https://github.com/operate-first/apps/pull/175

**Comment by tumido** [comment]
May this be related to https://github.com/operate-first/SRE/issues/98 ? Can you please try again after the `.kibana` resources are reset?

I've cross checked your and @eranra's permissions to the cluster and I don't see any difference in there. So if there's any discrepancy, it shouldn't be propagated from the OCP RBAC, since that's the same for both of you.

We're also planning on fully reinstalling this cluster next week, so ultimately by that time, all the issues should be resolved.

**Comment by HumairAK** [comment]
Hello @ronensc --- we had some issues with Kibana earlier this morning (possibly earlier, though I'm not sure as I wasn't around then), these issues should be resolved -- can you try again and get back to us ?

**Comment by ronensc** [comment]
@tumido @HumairAK thanks for checking. I tried again and I have the same permission errors. A few moments later, Kibana's status went yellow again. Actually, I think also yesterday, Kibana got into this state a few moments after I tried querying these indices. I suspect that somehow this "yellow status" is related to my actions. Although, I really didn't do anything unusual.

**Comment by HumairAK** [comment]
@ronensc Thanks for the update, you're right, Kibana is down to yellow again -- you can follow the progress [here](https://github.com/operate-first/SRE/issues/98#event-4401869962) as we look into this we'll be posting updates there.

**Comment by ronensc** [comment]
It turns out that I don't have permissions to get information about the indices but to do have to query them (by adding `/_search` to the URL)

**Comment by HumairAK** [comment]
@ronensc  I'm still getting used to how CLO does permissions etc.  

Can you paste the queries that you don't have perms to (and you require) ?

**Comment by ronensc** [comment]
The following request ([Search API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html)) works for me:
```
ROUTE_ES=elasticsearch-openshift-logging.apps.cnv.massopen.cloud
curl -k -H "Authorization: Bearer ${TOKEN}" "https://${ROUTE_ES}/app-000096/_search"
```

While, the following request ([Get index API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html)) doesn't
```
ROUTE_ES=elasticsearch-openshift-logging.apps.cnv.massopen.cloud
curl -k -H "Authorization: Bearer ${TOKEN}" "https://${ROUTE_ES}/app-000096"
```
I get this error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "no permissions for [indices:admin/get] and User [name=ronen.schaffer@gmail.com, roles=[admin_reader], requestedTenant=null]"
      }
    ],
    "type": "security_exception",
    "reason": "no permissions for [indices:admin/get] and User [name=ronen.schaffer@gmail.com, roles=[admin_reader], requestedTenant=null]"
  },
  "status": 403
}
```

I guess it's because `Search API` requires the `read` index privilege while `Get index API` requires the `view_index_metadata` or `manage` index privilege that I probably don't have.

**Comment by HumairAK** [comment]
Since `kibana` is no longer being maintained, closing this issue.
