### ISSUE TITLE
expose a `ray-ml-notebook:latest` option from the JH launcher in MOC ODH dash

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/support#102]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

At a high level, my goal is to port my demo integration[1] into the MOC so that any MOC user of the ODH dashboard can also use Ray with Jupyterhub by choosing `ray-ml-notebook:latest` from the JH launcher menu, and get a ray cluster they can connect to. 
In other words, it will work very much like choosing `s2i-spark-minimal-notebook` does today, except instead of creating a spark cluster under the hood, it creates a ray cluster.

[1]https://github.com/erikerlandson/ray-odh-demo

**Additional context**
The primary goal of this integration is to allow the ODH community to experiment with Ray as a distributed computing tool for ML workloads, in the context of ODH. The desirable outcome is to understand the level of community interest in Ray and more specifically learn what ML practitioners use Ray for, when provided with an easy way to access it.

My secondary goal is to create the pull request that adds the ray integration into `https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/hub/spawn`, so that I can also learn the process of doing operate-first modifications to the MOC.

The components being installed are:

- [x]  the ray notebook imagestream (https://github.com/operate-first/apps/pull/302)
- [x]  the ray operator CRD (https://github.com/operate-first/apps/pull/321)
- [x]  the ray operator pod itself (https://github.com/operate-first/apps/pull/336)
- [x]  a singleuser profile for ray ML notebook (https://github.com/operate-first/apps/pull/361)

Other PRs that were part of this integration:
- https://github.com/operate-first/apps/pull/346
- https://github.com/operate-first/apps/pull/350

**Comment by durandom** [comment]
cc @goern 

@tumido @HumairAK  can help. Looking at https://github.com/erikerlandson/ray-odh-demo/blob/main/deploy/operator/ray-cluster-crd.yaml it seems the CRDs are namespaced - so we don't have to bother with cluster wide resources...

**Comment by tumido** [comment]
> In general, all of the yaml objects in this repository would need to be installed onto the namespace that is running https://odh-dashboard-opf-dashboard.apps.cnv.massopen.cloud/

Not sure if I understand. We're running the ODH dashboard in a separate namespace to all of the other ODH components and we don't want to deploy additional things to that namespace. That being said, it's worth pointing out, that we're running our own fork of the ODH Dashboard, which can see into different namespace and aggregate components across all namespaces where a `kfdef` resource is deployed. So if you want something to show up on a dashboard, you're not limited to deploying to the same namespace.

Your manifests, shows to me that the only problem you may have with "our way" is that we require all cluster scoped resources to be managed centrally - therefore the CRD definition will have to live in here:
https://github.com/operate-first/apps/tree/master/cluster-scope/base/crds

For further reading see this ADR: https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0009-cluster-resources.md

Other than that, I don't see any obvious blocker, though I need to spend some more time looking into this probably. :slightly_smiling_face:

**Comment by erikerlandson** [comment]
@tumido I was using "space where the dashboard runs" as a way to say "where all the odh components are running", since that is the way it works everywhere else.

**Comment by erikerlandson** [comment]
The pull request should not have been merged, since only one of the six tasks was completed

**Comment by erikerlandson** [comment]
Are the rest of the ODH components living in the same namespace? If I add the singleuser profile objects and the ray operator pod onto my pull request (do I now need to make another PR, or can you revert the other one that was merged prematurely?) will it run in the proper namespace?

Side note, in my demo, I installed the ray operator as a naked pod, and for this integration I want to use a deployment so that the pod will be properly restarted if it happens to crash.

**Comment by tumido** [comment]
> Are the rest of the ODH components living in the same namespace? If I add the singleuser profile objects and the ray operator pod onto my pull request (do I now need to make another PR, or can you revert the other one that was merged prematurely?) will it run in the proper namespace?

We prefer to keep the components separate. Therefore we have JupyterHub in one namespace, Data catalog in another, Kafka in another one. As you can see here, each folder corresponds with a different namespace:
https://github.com/operate-first/apps/tree/master/odh/base

Do you want to revert that PR? I don't see any harm in keeping it. It's adding an image to the JH, which is totally fine with me.

**Comment by erikerlandson** [comment]
I'm OK with multi-PR.  (see discussion on https://github.com/operate-first/apps/pull/302).

One caveat - if people start choosing that image, it will not have a ray cluster behind it until the rest of the PRs get added.

**Comment by erikerlandson** [comment]
> We prefer to keep the components separate. Therefore we have JupyterHub in one namespace, Data catalog in another, Kafka in another one.

OK, so I need to re-think where other ray-related components are going to live.  Those components are:
- the ray operator CRD  (I think I was installing that into my demo namespace, but never actually looked)
- the ray operator pod itself (this will be analog to the spark operator pod)
- the singleuser profile configmap, and its associated ray template config-map
- the ray operator imagestream
- the ray worker imagestream

The ray operator controls the creation of ray-head and ray-workers (both use same image) - more or less like the spark operator, except the ray operator also auto-scales all the ray clusters it is managing.

Can you detail out which namespace each of these components needs to get installed into?  I did get the new namespace `ray-odh-integration` so wherever we need a ray-specific namespace I assume we can use that.

**Comment by erikerlandson** [comment]
In a sense, what matters for pull requests is where in the kustomize directory tree these components need to go.

**Comment by tumido** [comment]
Let me try. I'd say it should probably go like this:

1. the ray operator CRD: `CustomResourceDefinition` requires cluster-admin privileges to deploy, therefore it has to be placed into: https://github.com/operate-first/apps/tree/master/cluster-scope/base/crds
2. the ray operator pod itself: Your namespace
3. the singleuser profile configmap: Into the ODH JH namespace here: https://github.com/operate-first/apps/tree/master/odh/base/jupyterhub (we're not storing any custom singleuser profiles yet, so this may be a bit of an experiment, a welcomed one)
4. ... and its associated ray template config-map: Since this is used by the single userprofile, it has to live along the profile configmap, right? Then the answer is easy: Same location as 3)
5. the ray operator imagestream: Your namespace (since the pod will be deployed in here)
6. the ray worker imagestream: Your namespace, since this is probably used from the operator, right? And then distributed to wherever the Ray cluster lives...

That made me think... this is a namespaced operator, right? Like.. operator operating within a single namespace. If that's the case then everything (except the CRD) may have to go into the JH namespace, since the JH spawner would create the `RayCluster` resources in there. And if a namespaced operator wants to see the `RayCluster` resource, it needs to live in the same namespace...

**Comment by erikerlandson** [comment]
I agree, I was thinking last night it may all need to live in the JH namespace.

**Comment by erikerlandson** [comment]
Ported component checklist to this issue
