### ISSUE TITLE
Kernel crashing

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/support#104]
**Describe the bug**
I'm using Jupyterhub with the user ID shanand@redhat.com, trying to run this [notebook](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb)
My kernel crashes probably due to some resource problem. I have attached the screenshot of resource usage on the Grafana dashboard. 

**To Reproduce**
1. Go to your mass open Jupyterhub instance
2. git clone https://github.com/aicoe-aiops/ocp-ci-analysis.git
3. Go to notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
4. Run all cells

**Expected behaviour**
The notebook should run without the kernel crashing.

**Screenshots**

![Screenshot from 2021-03-03 17-13-58](https://user-images.githubusercontent.com/8916126/109879918-48059580-7c9c-11eb-97ab-67e3148efa58.png)

![Screenshot from 2021-03-03 17-13-39](https://user-images.githubusercontent.com/8916126/109879943-4fc53a00-7c9c-11eb-8d38-41d7baa430ce.png)

**Comment by Shreyanand** [comment]
Also, where can I see the pod logs of my user's Jupyterhub pod?

**Comment by durandom** [comment]
@martinpovolny I would expect that the user knows about the resource limits for his notebooks. 

a) Is there a way to show the limits in the grafana dashboard or at some other point?
b) Can he log into the ocp UI and the jupyterhub namespace and see the logs for his pod?

What are the options? Is see Grafana, Kibana, OCP. Anything else?

**Comment by martinpovolny** [comment]
In Elyra there's an indicator at the bottom of the UI:

![kernel-mem-1](https://user-images.githubusercontent.com/51095/109939199-1c50d280-7cd1-11eb-8a7d-ed6f1b1b0cbc.jpg)

You can see the limit for the kernel there: ^^^

When you are getting over the memory limit,  the numbers turn red.

![kernel-omm](https://user-images.githubusercontent.com/51095/109939307-38ed0a80-7cd1-11eb-9b7d-a2e228a39818.jpg)

You can get more memory by requesting in the launcher. If you choose the "Default" you unfortunately do not see what you are getting (we have to open an issue on that with the launcher if we find it wrong [let's discuss]):

![jh-request-limit](https://user-images.githubusercontent.com/51095/109940223-20312480-7cd2-11eb-914c-36fe22413cfe.jpg)

Anyway you can  try a bigger one:

![jh-large](https://user-images.githubusercontent.com/51095/109940294-30e19a80-7cd2-11eb-97c2-e03aed1e2002.jpg)

**Comment by martinpovolny** [comment]
BUT: even though I requested the 4 Gigs Elyra tells me I have only 1 Gig.


![elyra-mem-2](https://user-images.githubusercontent.com/51095/109941741-c2054100-7cd3-11eb-8dca-49f481238511.jpg)

However, the computation of the notebook ended well. It was not killed. There may be some disconnect between the numbers in the launcher and what Elyra shows (have to search for some documentation).

**Comment by martinpovolny** [comment]
Grafana presented above is here:
https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/YuYfkHYMk/jupyterhub-usage?orgId=1

**Comment by martinpovolny** [comment]
@Shreyanand : I'd conclude that you need to request a bigger system as shown in the screenshots above. Does that solve your problem?

**Comment by Shreyanand** [comment]
@martinpovolny Thank you! that does solve the problem, and iiuc the Large instance requests 4 GB and limits at 8? So the data/computation in this version reaches close to 5 GB and it works with the instance. 

Also, the memory that Elyra shows is a sum of memory used by all the active kernels instead of just this notebook's kernel, right?

**Comment by martinpovolny** [comment]
> Also, the memory that Elyra shows is a sum of memory used by all the active kernels instead of just this notebook's kernel, right? I was wondering because we often work with multiple kernels.

I do not know :-(

Observation: If I install stuff in a terminal the number shown in the toolbar goes up the same as if I run cells in a notebook. The same goes for running multiple notebooks. If I restart a "kernel" the terminals live on. So it has to be something that is above the jupyter kernel.

But I do not know how it works. I did not find any documentation related to the memory widget.

**Comment by Shreyanand** [comment]
> Observation: If I install stuff in a terminal the number shown in the toolbar goes up the same as if I run cells in a notebook. The same goes for running multiple notebooks. If I restart a "kernel" the terminals live on. So it has to be something that is above the jupyter kernel.
> 
Hmm that's what I thought. No worries, I think using the Grafana dashboard and this toolbar should be enough for usual debugging. I'll reach out to you if I find some interesting edge cases or if I need more memory. Thanks again, closing this issue :)
