### ISSUE TITLE
Contributing docs mention Prow

### ISSUE THREAD

**Issue by tumido** [operate-first/support#106]
We have this, though it would definitely need some polishing.. 
https://github.com/operate-first/apps/blob/master/contributing.md

We also use Prow for chat ops, so this can be used as a reference:
https://prow.k8s.io/command-help

But I admit we don't link that or explain that anywhere. Filing an issue for that rn.

_Originally posted by @tumido in https://github.com/operate-first/apps/issues/302#issuecomment-790710865_

Our Operate First docs are lacking on how to use prow and what commands are available. Do we have any docs in AICoE-CI we can refer users to?

/cc @goern

**Comment by HumairAK** [comment]
@harshad16  ^^

**Comment by harshad16** [comment]
Thanks for opening this, i will take this.
