### ISSUE TITLE
NEW PROJECT: WildFly

### ISSUE THREAD

**Issue by kabir** [operate-first/support#1102]
### Target cluster

Smaug

### Team name

wildfly

### Desired project names

wildfly-service

### Project description

[WildFly](https://www.wildfly.org) is Red Hat's open source Jakarta EE application server. It runs well on OpenShift, but still there is quite a lot of setup the user has to do. We would like to understand better how to run this as a service in the cloud, among other things to move the burden of ensuring users are on the latest version from them to us, and to share our progress with internal and external stakeholders.

### Users needing access

kabir, jmesnil, maeste

### Namespace Quota

Small

### Custom quota

No response

**Comment by durandom** [comment]
@kabir I'll take care of onboarding the project.

* Do you need anything beyond compute, memory and storage?
* Can you estimate in cores and GB how much compute and memory you'll expect to request?

/assign @durandom

**Comment by kabir** [comment]
@durandom Thank you!

I don't really know the numbers. Is 4 cores and 16GB doable? And if not enough, I guess I can always ask to increase it?

**Comment by schwesig** [comment]
ping

**Comment by kabir** [comment]
@durandom @schwesig Would my request be easier if I start with a Small instance? think that should be enough for me to get set up, and have updated the description. 

I guess if it turns out we need more once we start involving more users, it is a case of opening another issue?

I will be running s2i builds to provision WildFly servers, and then deploy user's demo apps in the resulting servers.

I don't think I need anything beyond what @durandom mentions is needed initially. As I gain more understanding, we might look into Argo CD. Also, at some stage we will need Observatorium, but I am not familiar with that yet, so I don't know if that runs outside of my stuff or is provided by the cluster.

**Comment by durandom** [comment]
@kabir thanks for the bump. This just got forgotten

https://github.com/operate-first/apps/pull/2585

**Comment by kabir** [comment]
@durandom Thank you!
