### ISSUE TITLE
NEW PROJECT: Ray on MOC

### ISSUE THREAD

**Issue by syedmohdqasim** [operate-first/support#1108]
### Target cluster

Smaug

### Team name

ray-bu

### Desired project names

ray-bu

### Project description

we want to Integrate Ray with ODH on the smaug cluster so that people using the smaug cluster can leverage Ray to scale their ml workloads. This is part of a student project with BU.

### Users needing access

syedmohdqasim,sumatra-dhimoyee,Oscarzhangzxj,hmyi,saadullah01,mtoslalibu,mosayyebzadeh

### Namespace Quota

Large

**Comment by syedmohdqasim** [comment]
Hi @MichaelClifford does this look good to you?

**Comment by MichaelClifford** [comment]
@erikerlandson @durandom Could we get some support getting this namespace setup for the BU team?

**Comment by durandom** [comment]
sure, I'll take care of setting up the namespace.
@MichaelClifford @syedmohdqasim can you provide links to the workloads being deployed? E.g. do you plan to leverage a ray operator? Will it be part of ODH?

**Comment by syedmohdqasim** [comment]
@durandom yes we want to install a ray operator, we want to make it part of ODH.
