### ISSUE TITLE
Red Hat Service Mesh deployment

### ISSUE THREAD

**Issue by tumido** [operate-first/support#111]
**Is your feature request related to a problem? Please describe.**
In order to fully support Telemetry WG (https://github.com/open-infrastructure-labs/telemetrywg) we need to have a RH Service Mesh (2.0) deployed on the cluster

**Describe the solution you'd like**
Subscribe to this thing and deploy Jaeger+Kiali+the rest

**Describe alternatives you've considered**
n/a

**Additional context**
This should be a competing deployment to Istio, so we can provide "both ways" https://github.com/operate-first/support/issues/63

**Checklist**
- [ ] Install ElasticSearch operator
- [ ] Install Jaeger operator
- [ ] Install Kiali operator
- [ ] Install Service mesh operator
- [ ] Remove `istio-system` from Kubeflow
- [ ] Configure `ServiceMeshControlPlane` resource
- [ ] Update Kubeflow to latest master and make it work with this ServiceMesh

**Comment by goern** [comment]
/sig devops
cc @harshad16

**Comment by paoloantinori** [comment]
hi there. is the deployment of Istio something still in the pipeline for Operate First?

**Comment by tumido** [comment]
Hey! We're reprioritizing this, since we got rid of Kubeflow from the main user workload cluster - we can now deploy Service Mesh in there.

/kind feature
/priority important-soon
