### ISSUE TITLE
URGENT: Install Trino Python Client 0.317.0 to fix Trino 398 blocker

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [operate-first/support#1110]
### Describe the Problem

Trino 398 exposes a bug in the python client 0.316.0 and earlier.  The nature of the problem is that Trino 398 is UNUSABLE with OpenMetadata due to this bug.  Version 0.317.0 is now available with a fix.

https://github.com/trinodb/trino-python-client/blob/master/CHANGES.md#release-03170

### Steps to Reproduce

All attempted OM ingestions fail.

### Expected behaviour

OM ingestions of known-good pipelines should work.

### Screenshots

N/A

### Additional context

OS-Climate is blocked until this can be updated.  We know it is used by Airflow, but all OS-C services that offer the Trino Python Client should be updated to version 0.317.0.

**Comment by HumairAK** [comment]
AFAIK we don't install trino client ourselves, if it's being used it's being used internally and provided within each service's image. 

We would need to know: 

1. What these services are (you identified airflow for example) 
2. What version do these _services_ need to be upgraded to to resolve this issue.
