### ISSUE TITLE
Use Operate First clusters for CS 549 Boston University course

### ISSUE THREAD

**Issue by oindrillac** [operate-first/support#1111]
### Description

Hello,

I am teaching an ML course this semester at Boston University (CS 549) and I would like to give the students an option to use the Operate First Community Cloud for their workloads. They would use apps such as Jupyterhub, Kubeflow, Trino, S3 bucket etc

To onboard a student or a group of students to the _Smaug_ cluster, where can we open an issue? Can you please point me to the config where they can be added to get access to an app on Smaug - Jupyterhub for instance. 

Thanks!

**Comment by durandom** [comment]
@oindrillac this is the right place
I believe everybody can use these applications, IIRC. You can do a dry-run by signing up for a play GitHub account and see how far you get.
If you need a project/namespace we can do this too. Then you'd need to provide similar input as in e.g. https://github.com/operate-first/support/issues/1108
