### ISSUE TITLE
OpenMetadata 0.12.1.2 available; fixes data profiling with Trino

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [operate-first/support#1114]
### Describe the Problem

OpenMetadata has a data profiling feature (one of the two major surface features of the `ingestion` functionality).  It was broken for Trino before 0.12.1.2.  We would like to be able to use this major feature of OpenMetadata, that presently works not at all.

The updated package is ready to go on PyPi: pip install openmetadata-ingestion (now version 0.12.1.2)

### Steps to Reproduce

1.  Go to https://openmetadata-openmetadata.apps.odh-cl2.apps.os-climate.org/service/databaseServices/OSC-Trino/ingestions
2. Click the 'Run' tab of the `profiler_essd` ingestion (which will run the profiler)
3. Notice that it fails, due to an unexpected '%' character

### Expected behaviour

OpenMetadata should be able to profile data that sits inside of Trino.

### Screenshots

N/A

### Additional context

This is a blocker for data profiling.

**Comment by MichaelTiemannOSC** [comment]
I just learned about this from OM channel: ./bootstrap/bootstrap-storage.sh migrate-all

**Comment by MichaelTiemannOSC** [comment]
OpenMetadata 0.12.2 was released a few weeks ago.  0.13-preview is available as of yesterday, and may be the best way to align our development efforts with OM.

xref https://github.com/operate-first/support/issues/1121
xref https://github.com/os-climate/os_c_data_commons/issues/183

**Comment by eb-oss** [comment]
@MichaelTiemannOSC How does this square with issue https://github.com/os-climate/os_c_data_commons/issues/183 ? Do we need both open? We're actively working on that issue, but I came across this one and was wondering if it needs any separate handling.

**Comment by MichaelTiemannOSC** [comment]
I see this as the urgent need to get a good current version of OM (that can support data profiling), so platform related.  The other issue is more developer community oriented.  It depends on this, and will be enabled for work once we have the OM we need.  Thanks!
