### ISSUE TITLE
install Prometheus-Operator, awx-Operator & MySQL-Operator

### ISSUE THREAD

**Issue by sostrades-radouanbouadel** [operate-first/support#1117]
hello, 
We plane to install a package of our application with all our DevOps process on sostrades project on CL2, we dont have enough rights to deploy customresourcedefinitions, role, … 

Can you please help us to deploy :
- Prometheus-Operator:  
- awx-Operator
- MySQL-Operator
- Jenkins
- harbor, 

you can use the Following  helm command:

> helm repo add mysql-operator https://mysql.github.io/mysql-operator/
> helm repo add rfy-awx https://raw.githubusercontent.com/rfyio/ansible-awx-helm-chart/master/
> helm repo add harbor https://helm.goharbor.io
> helm repo add jenkins https://charts.jenkins.io
> 
> helm repo update
> 
> helm install mysql-operator mysql-operator/mysql-operator
> helm install awx  rfy-awx/awx
> helm install harbor harbor/harbor
> helm install jenkins jenkins/jenkins

Thanks in advance
SOSTrades team

**Comment by redmikhail** [comment]
@sostrades-radouanbouadel cl2 cluster resources are managed using gitops approach via kustomize and argocd tools. While we support helm charts , general preference is not to use them as it introduces additional source of the artifacts outside of the operate-first github repository.  Prometheus operator may conflict with user-workload-monitoring that is enabled on cluster 2 https://docs.openshift.com/container-platform/4.9/monitoring/enabling-monitoring-for-user-defined-projects.html#enabling-monitoring-for-user-defined-projects_enabling-monitoring-for-user-defined-projects . I was wondering if you would be open to moving to separate cluster where we can grant you higher level of privileges ?
