### ISSUE TITLE
Request to add SCC to OCP Cluster for Kruize HPO

### ISSUE THREAD

**Issue by rbadagandi** [operate-first/support#1123]
### Team name

Kruize

### Explain why this resource is needed

We are working on deploying our project [Kruize HPO](https://github.com/kruize/hpo) on Operate First. We have some restricted privileges and we would want to request Operate First team to enable the following SCC to proceed with our deployment. Currently, the project runs easily locally and on Minikube but when deploying on an Openshift environment such as OF, it needs additional permission. Requesting to add the following [SCCs](https://github.com/kruize/hpo/blob/main/manifests/hpo-scc.yaml):

### Resource(s) being requested

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowedCapabilities: null
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1001
  uidRangeMax: 1001
seLinuxContext:
  type: MustRunAs
  User: hpo

**Comment by HumairAK** [comment]
@rbadagandi any particular reasons why the container user needs to run as uid `1001`, can the same not be accomplished if the arbitrary user is is part of the [root group as described here](https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids) ? this way no special privileges will be needed for your deployment
