### ISSUE TITLE
[Workshop] Allocate resource 

### ISSUE THREAD

**Issue by acidonper** [operate-first/support#113]
### Requested actions

Select all that apply:

- [ X] Create a user group
- [ X] Add users to a group
- [ X] Create a namespace (*2 per user _*-jump-app-cicd_ and _*-jump-app-dev_)

**Meetup Title**: Native Kubernetes CI/CD Pipelines (Tekton, ArgoCD, Helm and more)
**Abstract**: In this meetup, we will explore the new era of Kubernetes CI/CD pipelines based on a set of fancy tools as Tekton Pipelines, ArgoCD or Helm. During this session, we are going to walk through the new DevOps and GitOps technologies landscape and we have a real demo of how these tools work together in order to make developers and sysadmins lives easier.

URL: https://acidonper.github.io/redhat-workshop-cicd-gitops

Group
@lab-cicd-users

Users
@lab-admin @lab-cicd-user1 @lab-cicd-user2 @lab-cicd-user3 @lab-cicd-user4

**Comment by tumido** [comment]
Hi @acidonper, welcome!

Hmm, I'm not sure how to approach this. We don't use a canned users and so on. Our user management works a bit differently here. We have SSO enabled so each person can create their own account, based on the account we assign a group membership (`Group` resource). Then we can create namespaces that are accessible for a certain user group only. Is there a way how we can use this to drive your workshop? For example we can create a user group for you as an workshop admin + then we can create a set of namespaces that are publicly accessible - so they can be accessed by your workshop users.

Would that work for you?

**Comment by acidonper** [comment]
Hi @tumido,

First of all, thank you so much and I am so sorry for the delay.

Sure, it sounds great for me. My user is @acidonpe.

Regards!

**Comment by tumido** [comment]
I think we can close this issue. The workshop has been successfully onboarded and if there's any further issues we should rather open new tickets for those particular problems. :slightly_smiling_face:
