### ISSUE TITLE
NEW PROJECT: apex

### ISSUE THREAD

**Issue by russellb** [operate-first/support#1131]
### Target cluster

Smaug

### Team name

apex

### Desired project names

apex

### Project description

I'm working with a team that's prototyping an open-source networking service.

### Users needing access

russellb, nerdalert, dave-tucker, vishnoianil

### Namespace Quota

Large

**Comment by durandom** [comment]
@HumairAK can we try out Robozome on this onboarding PR?

**Comment by durandom** [comment]
trying out bot onboarding via https://github.com/operate-first/support/issues/1142

**Comment by durandom** [comment]
and again https://github.com/operate-first/support/issues/1143
