### ISSUE TITLE
Request to add: ai4cloudops

### ISSUE THREAD

**Issue by syedmohdqasim** [operate-first/support#1132]
### Team name

ai4cloudops bu group

### Explain why this resource is needed

We are trying to install quarkus superheros application and then run telemetry data analysts on it. we need more CPU's as it is a large distributed application.

### Resource(s) being requested

please increase the CPU limit to 10*Large. like 40 cpu.

**Comment by durandom** [comment]
@syedmohdqasim 40 CPUs sounds like a lot for a demo app :) 
I'll add this, but let's try to not use too many resources
