### ISSUE TITLE
Jupytherhub can not be started

### ISSUE THREAD

**Issue by mersin35** [operate-first/support#1137]
### Describe the Problem

![error_screenshot](https://user-images.githubusercontent.com/75088617/200880335-7a701ece-ef5a-4939-baca-160f03f13b6c.png)

### Steps to Reproduce

https://jupyterhub-odh-jupyterhub.apps.odh-cl2.apps.os-climate.org/hub/spawn

can not be started. Additionally the container size can not be selected.

### Expected behaviour

I expect that the Jupyterhub could be started

### Screenshots

added 

### Additional context

nothing

**Comment by MichaelTiemannOSC** [comment]
I just tried starting a Jupyter notebook myself and noticed the same 600 second timeout:

<img width="1088" alt="Screen Shot 2022-11-10 at 5 10 27 AM" src="https://user-images.githubusercontent.com/72577720/200882318-cde63734-be67-4b58-81ca-d52952791458.png">

This seems to be a new problem.  I successfully started and ran a notebook just two days ago.

**Comment by MichaelTiemannOSC** [comment]
We have been unable to run any notebooks for 3 days.  I still cannot get a working notebook instance.

@durandom please escalate!

**Comment by MightyNerdEric** [comment]
@MichaelTiemannOSC @mersin35 Ryan and I are unable to reproduce this error. Could one of you please provide full steps to reproduce? I was able to start a PyTorch notebook without issue. And I went back to try to open a different notebook, I did see that the container size option was not available. However, it showed up after a few seconds. Very strange, and that definitely needs to be looked into, but I want to focus on getting Notebooks to spawn for everyone before we look into that.

**Comment by MichaelTiemannOSC** [comment]
I've used Custom Elyra notebook since forever.  PyTorch sounds like AI and not needed for straight CSV or XLSX (Pandas) ingestion into SQL (Trino).

**Comment by MightyNerdEric** [comment]
@MichaelTiemannOSC What container size? Number of GPUs? Any env vars?

**Comment by MichaelTiemannOSC** [comment]
Container size 8GB, 1CPU.  No GPU.  Env cars include passing my GITHUB_TOKEN (secret) and bash as SHELL.  It has worked that way for past 18 months

**Comment by MightyNerdEric** [comment]
Ok, looks like I can reproduce the issue like that. Thanks.

**Comment by MichaelTiemannOSC** [comment]
I was able to start a notebook using the "regular" Elyra notebook.  I don't know what's broken in the current "custom" Elyra notebook, but I think that both Mutlu and I can get by using the "regular" notebook for now.  We still need this problem fixed, and it would still be nice if https://github.com/operate-first/apps/issues/2009 could be addressed.  Namely, it would be nice to have a "minimal" python environment that was not also "an unusably obsolete" python.

**Comment by MightyNerdEric** [comment]
Ok, Custom Elyra Notebooks are back in working order. Please let me know if you run into any further issues.
