### ISSUE TITLE
NEW PROJECT: example-team

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#1140]
### Target cluster

Smaug

### Target environment

moc

### Team name

teamx

### Desired project names

teamx-ns

### Project Owner

marcel

### Project description

the greatest project on the planet

### Link to project documentation

https://teamx.com

### Users needing access

tom,marcel,michal,gregory,thor

### Namespace Quota

Medium

**Comment by tumido** [comment]
Nice demo! Closing to declutter. 🙂
