### ISSUE TITLE
Request to add: RH-SSO

### ISSUE THREAD

**Issue by tumido** [operate-first/support#1145]
### Team name

operate-first  and apex

### Explain why this resource is needed

[Apex](https://github.com/operate-first/support/issues/1131) wants to utilize a Keycloak instance.

It seems it's currently not possible to install Keycloak as a cluster scoped operator - only a single namespace is allowed through OLM. There's some discussion around this in the upstream but so far not much traction (see: 
https://github.com/keycloak/keycloak/issues/12545 ). The question is: do we want to install this and provide a shared single instance or install this into the `apex` namespace (and if other teams want to experiment with Keycloak on their own, add another namespace scoped subscription)

![image](https://user-images.githubusercontent.com/7453394/201986805-74a6b5ab-a256-42d0-a693-62235bddd230.png)

### Resource(s) being requested

RH-SSO operator and (maybe) a Keycloak instance

**Comment by russellb** [comment]
In the immediate term, it would be nice for us to have full control over our keycloak instance. That way we can blow it up as many times as we want as we continue bootstrapping our new service.

We could do that within the `apex` namespace, or you could just give us access to the shared one and let us work on it since we'll be the only ones using it.  As soon as the next service comes along that wants to use it, we can coordinate and make sure we lock down the shared instance so everyone can rely on it.

**Comment by russellb** [comment]
cc @nerdalert, @dave-tucker, @vishnoianil

**Comment by tumido** [comment]
Ok, one more question. Do you plan on installing any other operator into your `apex` namespace? If we go through and install keycloak as a namespace scoped operator into `apex` namespace it will require a `OperatorGroup` resource into your namespace with target namespace `apex`. By desing, OLM allows only a single operator group per namespace - that means any additional operator installed into this namespace will be scoped to this namespace only. Is that fine with you?

**Comment by tumido** [comment]
This PR will install the rhsso operator into `apex` namespace: https://github.com/operate-first/apps/pull/2624

You than should be able to provision a `Keycloak*` resources locally. If you want to see how our previous `Keycloak` instance was configured you can find it here: 

https://github.com/operate-first/apps/blob/fd8f5c3c60ddd1d3d3c302081f6bcbb3cdee8590/keycloak/base/keycloak.yaml

https://github.com/operate-first/apps/blob/fd8f5c3c60ddd1d3d3c302081f6bcbb3cdee8590/keycloak/overlays/moc/infra/realm.enc.yaml
