### ISSUE TITLE
NEW PROJECT: bragi

### ISSUE THREAD

**Issue by goern** [operate-first/support#1151]
### Target cluster

MOC/Smaug

### Team name

thoth

### Desired project names

bragi

### Project Owner

goern

### Project description

Der Gott Bragi gehört zum Geschlecht der Asen und ist der Gott der Dichtkunst. Er ist verheiratet mit der Jugendgöttin "Idun" und begrüßt die gefallenen Krieger in Walhalla. Außerdem ist er Odins und Friggs Sohn.
Bei den Germanen war Bragi hochgeschätzt, da sie ihr Wissen und historische Ereignisse durch die Dichtung von Liedern bewahrten. Außerdem verwendeten sie Zaubersprüche, die durch gezielte Dichtung auf das Unterbewusstsein einwirken sollten. Zum Gott wurde Bragi erst ab dem 12. Jahrhundert erklärt.

### Link to project documentation

https://operate-first.cloud/bragi/

### Users needing access

goern,durandom

### Namespace Quota

Medium

**Comment by durandom** [comment]
```
++ QUOTA=medium
++ GROUP_PATH=/mnt/shared/apps/cluster-scope/base/user.openshift.io/groups/thoth
++ mkdir /mnt/shared/apps/cluster-scope/base/user.openshift.io/groups/thoth
mkdir: cannot create directory '/mnt/shared/apps/cluster-scope/base/user.openshift.io/groups/thoth': File exists
Script path finished failed execution. Check task/pod logs for details.
```
