### ISSUE TITLE
As an Apex developer, I want to store secrets, so I can keep my credentials private.

### ISSUE THREAD

**Issue by dave-tucker** [operate-first/support#1154]
### Additional context

👋 over in the `apex` namespace we'd like access to vault to store some secrets.
We'd like to add secrets using the ui/cli and be able to consume these in our project via the external-secrets operator.

### Acceptance Criteria

- [ ] `apex` is onboarded onto vault

### Relevant links

Same request, different team: #973

**Comment by tumido** [comment]
Hey @dave-tucker please confirm you can create secrets in

https://vault-ui-vault.apps.smaug.na.operate-first.cloud/ui/vault/secrets/k8s_secrets/list/moc/smaug/apex/

This PR should add the secret store to your namespace: https://github.com/operate-first/apps/pull/2678

**Comment by dave-tucker** [comment]
@tumido confirmed! Thanks
