### ISSUE TITLE
Increase JH memory

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/support#116]
1. **User details** : aduggal
2. **Desired resource change** : Memory increase to32 Gi

**Comment by tumido** [comment]
@aakankshaduggal Just to clarify, do you want to increase the RAM or storage capacity?

**Comment by aakankshaduggal** [comment]
> @aakankshaduggal Just to clarify, do you want to increase the RAM or storage capacity?

@tumido I want to increase the RAM.

**Comment by tumido** [comment]
/kind feature

![image](https://user-images.githubusercontent.com/7453394/111160538-789dd700-859a-11eb-9c1c-af1baef04e13.png)

Aakanksha would like to see a new size profile available here with greater memory portion.

**Comment by chauhankaranraj** [comment]
> Aakanksha would like to see a new size profile available here with greater memory portion.

Just for some context, [this](https://github.com/aicoe-aiops/ocp-ci-analysis/issues/149#issuecomment-797090342) comment describes why @Shreyanand @aakankshaduggal and I felt the need for a higher memory JH profile :)
