### ISSUE TITLE
Project status and community cloud feedback requested: api-designer

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1163]
# Operate First Community Cloud end-of-year housekeeping

Dear @andreatp @carlesarnal @ericwittmann @jsenko @paoloantinori @riprasad,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **api-designer** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=api-designer&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=api-designer&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by paoloantinori** [comment]
I've just submitted this. Do you needed it for project or are you interested in individual feedback?

**Comment by schwesig** [comment]
@paoloantinori thanks!
both, whatever you like to comment.
