### ISSUE TITLE
Hue storage not accessible

### ISSUE THREAD

**Issue by xtuchyna** [operate-first/support#117]
**Describe the bug**
When on main page, I click on the `S3` on left panel. After a moment of loading, Server error appears.

**To Reproduce**
1. Go to https://hue-opf-datacatalog.apps.zero.massopen.cloud/
2. Login
3. Click on 'S3' at the left panel 
![image](https://user-images.githubusercontent.com/46632404/110954269-970c9400-8348-11eb-99f4-3470dc0c7c6e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/46632404/110954323-a855a080-8348-11eb-8250-853d6159c2d7.png)

**Comment by tumido** [comment]
/kind bug

Thank ouu for reporting @xtuchyna I'll take a look! :slightly_smiling_face:

**Comment by tumido** [comment]
We have an incorrect endpoint set for the bucket. Fix is on the way.

**Comment by xtuchyna** [comment]
Hello @tumido, I've noticed that meanwhile the fix is on the way, the 'S3' option disappeared. Should I make an Issue out of it?

**Comment by tumido** [comment]
Nono, the the dissapearing s3 option is part of the problem - it is hidden if Hue can't access the S3 server (so it doesn't bother user with something which doesn't work). I still need to spend some time investigating this, sorry for the inconvenience.

**Comment by tumido** [comment]
Thank you for your concern though! :+1: :slightly_smiling_face: 

I think one issue to track it all is enough for now. :smile:

**Comment by xtuchyna** [comment]
Hello @tumido , wassup! Do you see this resolved today or should I wait for next week?

**Comment by tumido** [comment]
I've fiddled with this on Tuesday, but without any progress I'm missing something somewhere but I can't figure out what it is. Sorry I wasn't able to progress with this one much... :disappointed:

**Comment by xtuchyna** [comment]
No problem @tumido, just lemme know whenever you see this resolved, I am all hyped to use it! :)

**Comment by tumido** [comment]
Trying to spend some time on this today. It seems I'm able to get Hue working, though Thriftserver is giving me a ton of troubles see https://github.com/operate-first/support/issues/131

I'm gonna make Hue usable as a single creds S3 explorer now but the Triftserver problem is persistent.

Note: It seems each user in Hue is fixed to S3 creds associated their group membership only. Therefore I can't grant you access to your user bucket right now for file exploration (the S3 icon). Once Thriftserver is fixed you can source tables (in Hive via `LOCATION` on `CREATE TABLE`) from there without problems though, despite whatever creds are attached to Hue.
