### ISSUE TITLE
Project status and community cloud feedback requested: ddas-proj

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1172]
# Operate First Community Cloud end-of-year housekeeping

Dear @eldritchjs @wjs3 @wtheisen,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **ddas-proj** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=ddas-proj&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=ddas-proj&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by schwesig** [comment]
ping @EldritchJS @wjs3 @wtheisen

**Comment by schwesig** [comment]
🏆 @EldritchJS @wjs3 @wtheisen 🏆 thanks for your time and for filling out the survey.
We also appreciate your project on the community cloud.
