### ISSUE TITLE
Project status and community cloud feedback requested: debezium-ui

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1173]
# Operate First Community Cloud end-of-year housekeeping

Dear @gunnarmorling @indraraj @mdrillin @rk3rn3r @uidoyen,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **debezium-ui** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=debezium-ui&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=debezium-ui&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by schwesig** [comment]
ping @gunnarmorling @indraraj @mdrillin @rk3rn3r @uidoyen

**Comment by gunnarmorling** [comment]
Hey @schwesig, thanks for the reminder. I've left Red Hat and am not involved with Debezium on a day-to-day basis any longer. Summoning @jpechane who took over as the Debezium project lead.

**Comment by jpechane** [comment]
@indraraj @rk3rn3r @uidoyen Are we still using it?

**Comment by rk3rn3r** [comment]
@jpechane I think there was only a plan once to use it? @uidoyen @indraraj 
See https://issues.redhat.com/browse/DBZ-5093

**Comment by jpechane** [comment]
@schwesig Please give us a copule more days to clear the things up. As there were some changes in the team it seems we need to make our minds again as the original plans has been lost.

**Comment by schwesig** [comment]
@jpechane sure, not a problem. Thanks for posting your status here.
