### ISSUE TITLE
Request onboarding Filecoin node or nodes

### ISSUE THREAD

**Issue by coryschwartz** [operate-first/support#1180]
I am a developer at [Protocol Labs](https://protocol.ai) and I am interested in onboarding to operate-first. 

One of our core software products at P.L. is [Filecoin](filecoin.io) and I would like to onboard filecoin to the operate-first project.

This is why I'm interested in onboarding:

1. We already run gitops internally, but most of our infrastructure code is not (yet) in public repos. Onboarding to operate-first would compel us to open source a bit of our infrastructure code, and we can point others to this installation to use as a guide to setting up their own installations.

2. For applications such as this, the more nodes that are running, the better.

3. If all goes well, we may be able to use this node as a bootstrapper node for the network, API gateways, or for some other real-world purpose.

** Filecoin nodes we would want to onboard are consensus-only nodes in the filecoin blockchain. These nodes maintain the blockchian itself, but they are not storing files in the filecoin storage network. That is to say that the nodes we would install would not be engaged in any storing or proving activities that would require any specialized hardware, large volumes, or GPUs. 

Consensus nodes can still use a lot of resources, however. In our system, we run with the following:

```
storage: 4T
cpu: 6 
memory: 48Gi  (we could do with less)
```

**Comment by tumido** [comment]
Hey @coryschwartz can you please fill out this form? Please select `MOC/Smaug` cluster in the questionnaire. It'll automatically create the PR so I can be lazy and I don't have to do it manually. :slightly_smiling_face: 

https://github.com/operate-first/support/issues/new?assignees=first-operator&labels=kind%2Fonboarding%2Cscript%3Ascripts%2Fonboarding.sh%2Ctask-type%3Abash%2Crepo%3Aapps&template=4_onboarding_to_cluster.yaml&title=NEW+PROJECT%3A+%3Cname%3E


I also find the storage request pretty high, is this the minimal requirement? We may need to find a place to accommodate this. Smaug currently has about 5TB storage available. The rest of the resources should not be a problem. Do you have any thoughts on this @durandom ?

**Comment by durandom** [comment]
👍  except for the high storage this looks ok to me. @coryschwartz what's the minimum storage you need for consensus nodes?

**Comment by coryschwartz** [comment]
Would 2T be do-able? We would be able to install with less, but we'd have to occasionally reset and the resets would be more frequent the smaller the volume. I definitely don't want to use too much if you have only 5T available in total!

**Comment by durandom** [comment]
@coryschwartz let's try 2T and I'll find out how high we can go.
