### ISSUE TITLE
NEW PROJECT: thoth-cre-test

### ISSUE THREAD

**Issue by goern** [operate-first/support#1184]
### Target cluster

MOC/Smaug

### Team name

thoth

### Desired project names

thoth-cre-integration

### Project Owner

goern

### Project description

This is a test/dev environment for CNBi/CRE feature of ODH.

### Link to project documentation

https://github.com/thoth-station/opendatahub-cnbi

### Users needing access

@codificat 
@VannTen
@harshad16 
@Gkrumbach07 
@KPostOffice 

### Namespace Quota

Custom

### Custom quota

16CPU, 64Gi memory, 32Gi storage

**Comment by codificat** [comment]
A potential problem here:



> MOC/Smaug

there is an existing deployment of meteor-operator in the cluster (powering https://shower.meteor.zone/) and we could be interferring with it; e.g. we share some CRDs

**Comment by goern** [comment]
True, even though meteor-operator v0.2.1 is downward compatible and should satisfy the requirements of shower.meteor.zone there needs to be one deployment of meteor-operator. 

@durandom do we have any other cluster we can use for testing/integration?
