### ISSUE TITLE
INCIDENT: Smaug: Object Storage is unreachable 

### ISSUE THREAD

**Issue by tumido** [operate-first/support#1188]
Yeasterday we've discovered Prow crashing. It seemed to be related to object storage. Later Service catalog lost connection to it's bucket as well.

Noobaa is reporting errors for backing store - the one low on storage space (this was existing precondition for a while). We've tried reclaiming storage by removing the largest bucket (`opf-observatorioum-logs` - it was stale unused data anyways). NooBaa/ceph took about 2 hours to finalize deletion of the OBC. After that Backing store is still reporting the same usage levels and noobaa/ceph is not reclaiming the storage.

rook-ceph-tools are unable to connect to the ceph cluster.

Noobaa database is reporting some errors which seems to be unrelated. Among others it's also reporting about full storage:

```
[32mJan-10 16:15:57.051[35m [WebServer/34] [36m   [L0][39m core.server.node_services.nodes_monitor:: noobaa-default-backing-store-noobaa-pod-fa07f9bf-noobaa_storage-fb321b40 item has issues. reasons: no rpc_address, storage is full (Thu Jan 01 1970 00:00:00 GMT+0000 (Coordinated Universal Time))
[32mJan-10 16:15:57.051[35m [WebServer/34] [36m   [L0][39m core.server.node_services.nodes_monitor:: noobaa-default-backing-store-noobaa-pod-fa07f9bf-noobaa_storage-fb321b40 not readable. reasons: no rpc_address, storage is full (Thu Jan 01 1970 00:00:00 GMT+0000 (Coordinated Universal Time))
[32mJan-10 16:15:57.051[35m [WebServer/34] [36m   [L0][39m core.server.node_services.nodes_monitor:: noobaa-default-backing-store-noobaa-pod-fa07f9bf-noobaa_storage-fb321b40 not writable. reasons: no rpc_address, storage is full (Thu Jan 01 1970 00:00:00 GMT+0000 (Coordinated Universal Time))
...
``` 

https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/pods/noobaa-core-0/logs

Replacing old pods with new replicas didn't made a difference on Noobaa side.

I'm out of ideas on how to move forward. @larsks can you please help/take a look? Is this something we need to reach out to NESE for support or can we troubleshoot it from our side?

**Comment by durandom** [comment]
This also seems to affect the `image-registry` and leads to failures creating new pods

```
Events:
  Type     Reason          Age                   From               Message
  ----     ------          ----                  ----               -------
  Normal   Scheduled       8m27s                 default-scheduler  Successfully assigned b4mad-racing/analyze--1-dfrfd to oct-03-24-compute
  Normal   AddedInterface  8m26s                 multus             Add eth0 [10.129.6.204/23] from openshift-sdn
  Warning  Failed          4m15s                 kubelet            Failed to pull image "image-registry.openshift-image-registry.svc:5000/b4mad-racing/paddock@sha256:cd3684211c175a175aa40415a589d16ce4cff797f503af8f591c8f34a4dee042": rpc error: code = Unknown desc = reading manifest sha256:cd3684211c175a175aa40415a589d16ce4cff797f503af8f591c8f34a4dee042 in image-registry.openshift-image-registry.svc:5000/b4mad-racing/paddock: received unexpected HTTP status: 500 Internal Server Error
  Warning  Failed          4m15s                 kubelet            Error: ErrImagePull
  Normal   BackOff         4m14s                 kubelet            Back-off pulling image "image-registry.openshift-image-registry.svc:5000/b4mad-racing/paddock@sha256:cd3684211c175a175aa40415a589d16ce4cff797f503af8f591c8f34a4dee042"
  Warning  Failed          4m14s                 kubelet            Error: ImagePullBackOff
  Normal   Pulling         4m1s (x2 over 8m26s)  kubelet            Pulling image "image-registry.openshift-image-registry.svc:5000/b4mad-racing/paddock@sha256:cd3684211c175a175aa40415a589d16ce4cff797f503af8f591c8f34a4dee042"
```

The https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/config.openshift.io~v1~ClusterOperator/image-registry is stuck in `Progressing` with the message

```
Progressing: Unable to apply resources: unable to sync storage configuration: GatewayTimeout: Gateway Timeout
Progressing: status code: 504, request id: , host id:
```

**Comment by durandom** [comment]
Maybe we can add another backingstore? As in https://github.com/operate-first/apps/pull/1231/files

In the comments @larsks says, we can get 20TB from NESE. The current backingstore has 20 volumes with 50Gi each, resulting in a capacity of 1TB

UPDATE:
I added https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/clusterserviceversions/ocs-operator.v4.8.17/noobaa.io~v1alpha1~BackingStore/noobaa-backing-store-2 and also selected it as a BackingStore in the BucketClass. But the backingstore doesn't changes it's phase to "Ready". 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/161888/211768234-8385e712-f83d-4c61-b7ae-5e1640724a0d.png">

<img width="789" alt="image" src="https://user-images.githubusercontent.com/161888/211768359-874a6596-5e44-4676-8b9e-5671ede6366f.png">

**Comment by larsks** [comment]
I have opened case https://access.redhat.com/support/cases/#/case/03410510 for this incident.

**Comment by codificat** [comment]
I'm not sure about the status of object storage —the mentioned support case seems to be still ongoing— but just wanted to point out that prow seems to be working correctly now.

**Comment by tumido** [comment]
Yes, @Gregory-Pereira migrated Prow to use bucket provided by the Infra cluster. That restored Prow functionality.

However the S3 storage is still unavailable. Current development on the support ticket indicates that support is unwilling to support us with an external non-managed cluster running non-RH ceph version. There's some back and forth going on, however it seems it'll lead nowhere. As a result we may loose all data stored in S3 and attempt to deploy the noobaa S3 from scratch again.

**Comment by tumido** [comment]
The support case is stalled, we probably want to just delete the object storage and recreate it and start from scratch.

Object storage recreate plan:
- Delete all [`BackingStore`s](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/operators.coreos.com~v1alpha1~ClusterServiceVersion/ocs-operator.v4.8.17/noobaa.io~v1alpha1~BackingStore)
- Delete [NooBaa](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/clusterserviceversions/ocs-operator.v4.8.17/noobaa.io~v1alpha1~NooBaa/noobaa) - this one is owned by the external [`StorageCluster`](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/clusterserviceversions/ocs-operator.v4.8.17/ocs.openshift.io~v1~StorageCluster/ocs-external-storagecluster/) so it may get recreated.
- Ensure all [PVCs](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/persistentvolumeclaims) associated with `NooBaa`/`BackingStore`s are deleted
- Let the `NooBaa` be recreated from the `StorageCluster`

**Do not delete the `StorageCluster` which owns Noobaa, this owns the (working) block storage as well and by deleting it we may lose access to the existing data.**

**Comment by durandom** [comment]
I managed to uninstall noobaa via the cli
```
noobaa uninstall
```
Downscaling the `ocs-operator` deployment to 0 helped to prevent it to be re-created while being deleted.
Unfortunately the `StorageCluster` does not recreate `NooBaa` 😢

**Comment by tumido** [comment]
That seems to caused the noobaa operator to uninstall. Not only the instance. I think you may need to run `noobaa install` or something (if that exists) if you want to get the noobaa operator back. Or we may need to reinstall the OCS operator, that should solve it by installing it all from the CSV.

![image](https://user-images.githubusercontent.com/7453394/218696981-44b5f5f1-6676-4b9a-ba0d-48899e0c4b2c.png)

https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/operators.coreos.com~v1alpha1~ClusterServiceVersion/ocs-operator.v4.8.17

See missing deployment:
https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/openshift-storage/deployments/noobaa-operator

**Comment by durandom** [comment]
I ran `noobaa install` and now everything seems to be working.

For the record, I needed to remove all existing 
```yaml
    finalizers:
    - objectbucket.io/finalizer
```
from all objectbucket instances
