### ISSUE TITLE
Project status and community cloud feedback requested: fybrik-applications

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1190]
# Operate First Community Cloud end-of-year housekeeping

Dear @eletonia @flora177 @michaelfactor @mohammad-nassar10 @revit13 @roee88 @ronenkat @roytman @shlomitk1 @simanadler @tomersolomon1,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **fybrik-applications** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=fybrik-applications&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=fybrik-applications&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by flora177** [comment]
@durandom - Thanks Marchel, Happy New Year, we are continuing the work on Fybrik.
In the meantime, we will not continue usage with operate first, we filled the form and survey 
Thanks, 
Alexey and Flora

**Comment by schwesig** [comment]
@flora177 thanks for keeping us posted and filling out the survey.
Good luck and success with Fybrik. 🎰
