### ISSUE TITLE
Project status and community cloud feedback requested: gingersnap

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1191]
# Operate First Community Cloud end-of-year housekeeping

Dear @dpanshug @fax4ever @jabolina @karesti @pminz @pruivo @rigazilla @ryanemerson @tristantarrant @wburns,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **gingersnap** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=gingersnap&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=gingersnap&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by ryanemerson** [comment]
We intend to keep the project. FYI to others in the team tagged, I have filled out the form.

**Comment by schwesig** [comment]
Thank you so much @ryanemerson for your time and the survey. 😶‍🌫️
And thanks to all of you for being a project on the Operate First community cloud. ⛅
