### ISSUE TITLE
Project status and community cloud feedback requested: humair-sandbox

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1193]
# Operate First Community Cloud end-of-year housekeeping

Dear @anishasthana @humairak @op1st @sallyom @traytorous,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **humair-sandbox** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=humair-sandbox&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=humair-sandbox&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by schwesig** [comment]
@HumairAK your feedback is appreciated. Thanks for the survey.
Yes, the automation idea, you started very well... we need more of it. 🤖
