### ISSUE TITLE
Project status and community cloud feedback requested: ipfs

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1194]
# Operate First Community Cloud end-of-year housekeeping

Dear @cooktheryan @djach7 @guymguym @jsawaya @robotsail @sallyom,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **ipfs** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=ipfs&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=ipfs&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by RobotSail** [comment]
Hi @durandom, everything was smooth sailing once we were onboarded to the cluster so I have no complaints. The only problem we faced with getting the project running was not related to Operate First but instead was the image we had used. We're not currently using this namespace but I would still like to complete the setup of an Estuary node if possible to see how it would run. This isn't mission critical though, so you could probably clean up the resources for the time being until I ping you for them again.

**Comment by schwesig** [comment]
@RobotSail - I appreciate your detailed answers here and filling out the survey.
See you all around now more often. I am excited.
Surfing the good wave 🌊
