### ISSUE TITLE
Project status and community cloud feedback requested: jet-linite

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1195]
# Operate First Community Cloud end-of-year housekeeping

Dear @3rikas @jokvar @theoem,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **jet-linite** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=jet-linite&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=jet-linite&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by jokvar** [comment]
Hey,

we heard about this initiative at CloudOpen. We signed up ready to go with a rough idea, but never got around to realizing it, or playing around much.
It would only be fair to free our resources for others (though I believe project is empty?)
