### ISSUE TITLE
Kubeflow is missing routes

### ISSUE THREAD

**Issue by tumido** [operate-first/support#120]
**Describe the bug**
```
oc get routes -n kubeflow
No resources found in kubeflow namespace.
```

/cc @4n4nd @pacospace

**Comment by 4n4nd** [comment]
For the Kubeflow dashboard, the route should be in the `istio-system` namespace [link](http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/).

For direct access to the ml-pipelines api (and any other service we deploy using kubeflow), I think we need to create a route manually for it.

**Comment by HumairAK** [comment]
looks like this was answered
