### ISSUE TITLE
Project status and community cloud feedback requested: okd-wg

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1203]
# Operate First Community Cloud end-of-year housekeeping

Dear @aleskandro @bdlink @binnes @cgwalters @cheesesashimi @dmueller2001 @geoeducator @jaimemagiera @lmzuccarelli @lorbuschris @sandrobonazzola @sherine-k @travier @vrutkovs,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **okd-wg** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=okd-wg&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=okd-wg&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by sandrobonazzola** [comment]
Hi, I haven't used Operate First Community Cloud.

**Comment by JaimeMagiera** [comment]
The OKD Working Group is growing and will be putting more emphasis on using Operate First in the coming year. We'll provide more detailed feedback after discussing OF usage in our next few meetings.

**Comment by schwesig** [comment]
Thanks for your answer.
Feel free to add more or reach out to us directly.
➭https://github.com/LorbusChris thanks for the upcoming meet up. Can't wait to hear more details.
🔗[https://op1.st/meetup](op1.st/meetup)

We are very happy to have you on board 🪩

**Comment by schwesig** [comment]
https://github.com/GeoEducator thanks for the survey.
