### ISSUE TITLE
Project status and community cloud feedback requested: rapidast

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1209]
# Operate First Community Cloud end-of-year housekeeping

Dear @jeremychoi @jpweiser,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **rapidast** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=rapidast&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=rapidast&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by jpweiser** [comment]
@durandom I filled out the form. Let me know if you need anything else from us.

**Comment by schwesig** [comment]
Hi @jpweiser, thanks for the feedback and for letting us know. 🚀
And thanks for your kind words. It is all in the community. 🪩
Glad to have your project here.
