### ISSUE TITLE
Project status and community cloud feedback requested: smart-village-view

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1214]
# Operate First Community Cloud end-of-year housekeeping

Dear @anlianni @computate @salomonw @yqchenn,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **smart-village-view** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=smart-village-view&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=smart-village-view&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by schwesig** [comment]
ping @anlianni @computate @salomonw @yqchenn

**Comment by computate** [comment]
Hello Opeate First Team! 
Sorry for the delay responding. We were waiting to submit the form until the Red Hat Collaboratory announces the winners of the projects some time this month. Do you need a response before February?

Thanks. 
To your health. Courage!  
Christopher Tate

**Comment by computate** [comment]
Hello Operate First, 

Now that the 2023 Red Hat Collaboratory Research Incubation Awards Recipients have been announced including our project renewal, I have completed the form. Thanks for your patience! 

https://www.bu.edu/rhcollab/2023/01/27/2023-red-hat-collaboratory-research-incubation-awards-recipients/

To your health. Courage!  
Christopher Tate

**Comment by schwesig** [comment]
@computate Hi Christopher,
no worries, for sure you waited until the announcement.
Awesome! Thanks for your feedback and keep up your good work.
Thanks for sharing the link to the Awards page 🚀
