### ISSUE TITLE
Project status and community cloud feedback requested: tremor-demo

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1218]
# Operate First Community Cloud end-of-year housekeeping

Dear @darach @drowe @garypwhite @hgies @jdhtml @lelia @mfelsche @natalisucks,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **tremor-demo** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=tremor-demo&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=tremor-demo&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by drowe** [comment]
@durandom I think I was mentioned via typo? I don’t know anything about this project or others mentioned here (noting here in the event you want to tag the correct person, as opposed to simply unsubscribing 🙂)

**Comment by schwesig** [comment]
Hi @drowe, thanks for letting us know.

I did some research and found these contributors. Is this correct?
ping [GaryPWhite](https://github.com/GaryPWhite)
ping [sostrades-radouanbouadel](https://github.com/sostrades-radouanbouadel)

**Comment by darach** [comment]
Hi folk,

This may have been impacted by layoffs. It is probably safe for someone to administratively delete so that
you can free up those resources!

Cheers,

Darach.
