### ISSUE TITLE
Project status and community cloud feedback requested: ttm-as-a-service

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1219]
# Operate First Community Cloud end-of-year housekeeping

Dear @aakankshaduggal @gkrumbach07 @goern @harshad16 @kpostoffice @michaelclifford @oindrillac @suppathak,

We would love to hear from you about how much and for what you used the Operate First Community Cloud. What did you like, what did you miss?

We also want to know about the status of your project **ttm-as-a-service** and potentially free up unused resources.

If you intend to keep the project, please complete the survey by filling out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=ttm-as-a-service&entry.1071705158=Yes), otherwise this [form](https://docs.google.com/forms/d/e/1FAIpQLSfTFlHnHkWXzl-_0UbmHa0NdhZZiHqfloNNs-s26oORwhfyBw/viewform?usp=pp_url&entry.1509979056=ttm-as-a-service&entry.1071705158=No).

Thank you for your time and feedback!

**Comment by Gkrumbach07** [comment]
The pod named `ttm-as-a-service` running in `thoth-deployment-example` is not used and can be removed.

**Comment by harshad16** [comment]
Submitted the Feedback with regards to project `ttm-as-a-service`.
Thanks for all the services.  :100:

**Comment by schwesig** [comment]
😍 @harshad16, I appreciate your feedback.
I also appreciate your feedback about the delay for specific requests. This should be faster. Agreed.
Thanks for being an active project and contributor.
