### ISSUE TITLE
Access to the clusters for Kogito Serverless Operator

### ISSUE THREAD

**Issue by davidesalerno** [operate-first/support#1227]
Since I would like to use the operate-first approach for the [Kogito Serverless Operator,](https://github.com/kiegroup/kogito-serverless-operator/) I would like to access the clusters for deploying it there.

**Comment by amadhusu** [comment]
Adding to the comment for visibility and access for the same reason.

**Comment by goern** [comment]
@durandom @tumido  what kind of access is required for this? is this similar to https://github.com/operate-first/apps/pull/2755
