### ISSUE TITLE
Requesting Kafka topic/user in smart-village-view namespace

### ISSUE THREAD

**Issue by computate** [operate-first/support#1233]
### Topic Name

smartvillage-sumo-run

### Topic Partitions

3

### Topic Replicas

3

### Topic Retention

6 hours

### Topic Configuration

none

### User Names

smartvillage

### Topic Access

smartvillage-sumo-run

### Group Ids

smartvillage-kafka-group

**Comment by goern** [comment]
/kind feature
/priority critical-urgent
/assign durandom
/assign computate

add some labels, as per the conversation seen on https://operatefirst.slack.com/archives/C01RMPVUUK1/p1678719403986439

**Comment by computate** [comment]
This issue is completed.
