### ISSUE TITLE
Requesting Kafka topic/user in smart-village-view namespace

### ISSUE THREAD

**Issue by computate** [operate-first/support#1234]
### Topic Name

smartvillage-sumo-run-report

### Topic Partitions

3

### Topic Replicas

3

### Topic Retention

6 hours

### Topic Configuration

none

### User Names

smartvillage

### Topic Access

smartvillage-sumo-run-report

### Group Ids

smartvillage-kafka-group

**Comment by goern** [comment]
/assign @computate 

set some labels as seen on slack #support ;)

**Comment by goern** [comment]
this seems to be a dup of #1233 

/close 
/triage duplicate
