### ISSUE TITLE
Request to add: 2 kafka topics

### ISSUE THREAD

**Issue by computate** [operate-first/support#1235]
### Team name

smart-village-view

### Explain why this resource is needed

We now have 2 applications, a Java frontend and API application, and a Python backend microservice for running traffic simulations. We would like to send messages on one Kafka Topic from the Java application to the Python application to start a traffic simulation, and send messages on another Kafka Topic when the Traffic Simulation is complete back to the Java application. I haven't seen any response on the issues I created below, so I was hoping you could please help me get these Kafka Topics created. 

### Resource(s) being requested

Here are the kafka topics we are requesting: 

- https://github.com/operate-first/support/issues/1234
- https://github.com/operate-first/support/issues/1233

**Comment by goern** [comment]
/kind feature
/priority critical-urgent
/assign durandom
/assign computate

add some labels, as per the conversation seen on https://operatefirst.slack.com/archives/C01RMPVUUK1/p1678719403986439

**Comment by computate** [comment]
This issue is completed.
