### ISSUE TITLE
Request to transfer repository from Operate First to Koku GitHub organization

### ISSUE THREAD

**Issue by gagansk** [operate-first/support#1237]
- Request to transfer [Curator Operator](https://github.com/operate-first/curator-operator) from Operate First to [Koku](https://github.com/project-koku) GitHub organization. 
- Koku GitHub admins have approved this transfer.

**Comment by gagansk** [comment]
@tumido Can you look into this?

**Comment by Gregory-Pereira** [comment]
I can do this but I need permissions on `project-koku` org to move it there. It says `You don’t have the permission to create public repositories on project-koku`

**Comment by tumido** [comment]
@gagansk I'm in the same boat as @Gregory-Pereira . I can't transfer it unless I can create repos in the target organization. Therefore I've made **you** the admin with full permissions over the https://github.com/operate-first/curator-operator repo. This way you should hopefully be able to initiate the transfer yourself. If it doesn't help we can arrange something else in coordination with `project-koku` admins.

**Comment by goern** [comment]
see https://operatefirst.slack.com/archives/C01RMPVUUK1/p1680187130893889

/unassign
/assign @gagansk

**Comment by gagansk** [comment]
@tumido , I am unable to transfer the repository. I see the message "Organization members cannot transfer repositories" under the transfer repository option. 

Do you want me to request Koku admins to add you to their contributor list so that you can transfer this repo from Operate First to Koku?

**Comment by gagansk** [comment]
![Screenshot 2023-03-30 at 2 58 33 PM](https://user-images.githubusercontent.com/47332731/228937192-a3ed8023-b313-4543-8aac-bc45d29c5c71.png)

**Comment by cooktheryan** [comment]
@gagansk yes that would be great if they could temporarily add on of the folks within this thread to their organization

**Comment by pgarciaq** [comment]
@tumido @gagansk I don't think you need to be admins in project-koku. Our admins are already waiting for this repo. Just request the transfer and we'll pick it up.

**Comment by goern** [comment]
I did that, and also clicked the 'I understand' button...

![image](https://user-images.githubusercontent.com/260331/229144585-2435bed1-40e3-4854-9d16-a27bfee70e32.png)

**Comment by tumido** [comment]
@pgarciaq I'm sorry, I'm not trying to be difficult. It just seems the workflow has changed on GitHub side and moving the repository to a different organization now requires permission to create repositories in an organization directly, instead of generating a transfer request. I'm just getting the same error as Gregory or Christoph...


https://user-images.githubusercontent.com/7453394/230018950-1a216bc5-fd05-46a8-9946-6290d37db53e.mov



As a workaround, I can suggest we try to transfer the repository directly to either you or @gagansk and you can then initiate a second transfer to project-koku yourself. I'm not sure if that would work either but we can try it. If it doesn't work, we can arrange a quick call between org owners (1 from each side), temporarily granting the necessary permissions and clicking all the buttons.

**Comment by pgarciaq** [comment]
@tumido sure. We'll have to wait till next week, since several Koku people are on PTO this week.

cc: @adberglund @maskarb

**Comment by goern** [comment]
is this still ongoing?

**Comment by gagansk** [comment]
Yes. This process is still in the works.

**Comment by tumido** [comment]
@gagansk what can we do to help you with it? Can we transfer the repository to you for example?

**Comment by kholdaway** [comment]
Do you want to make me an admin on this repo? I can transfer it.

**Comment by gagansk** [comment]
@kholdaway I have sent you a repo admin invite.

**Comment by kholdaway** [comment]
![image](https://github.com/operate-first/support/assets/32331547/f84e98e3-2b46-4bac-9062-8219248e3bd5)

**Comment by kholdaway** [comment]
This may have to be temporary, but I cannot transfer with just the repo access.

**Comment by gagansk** [comment]
@tumido Can you help @kholdaway with this?

**Comment by gagansk** [comment]
I believe we hit the same roadblock when we were trying to transfer the repo before as well. @tumido Can you tell us what needs to be done to complete this transfer?

**Comment by kholdaway** [comment]
As noted in the screenshot, organizational admins can do this not members. This person has to be an admin in both this org and project-koku. If you want to make me an org admin in operate-first (just for a short window so I can move the repo), we can do this easily.

**Comment by tumido** [comment]
FTR: we met online with @kholdaway and moved it by adding him temporarily to the org admins. An associated cleanup PR is https://github.com/operate-first/common/pull/167
