### ISSUE TITLE
housekeeping: are you still an org admin?

### ISSUE THREAD

**Issue by goern** [operate-first/support#1239]
### Description

Hey all,
 doing some housekeeping...

 Do you still feel like you are an GitHub org admin? 

 **If so**, please let me know by end of this week,
**if not**, do nothing, I'll open a PR to remove you.

thanks!!

/assign cooktheryan
/assign durandom
/assign goern
/assign Gregory-Pereira
/assign HumairAK
/assign quaid
/assign redmikhail
/assign ryanaslett
/assign schwesig
/assign tumido

**Comment by cooktheryan** [comment]
no. I could be removed

**Comment by quaid** [comment]
I still feel I'm an org admin, thanks for checking; I just haven't had much focused here this calendar year.

It's worth noting that Operate First is a long-play, when I signed up for the project I knew I might be involved or peripherally connected for most of a decade. But I appreciate the clean-up work and if I do ever bow out of here, I'll let you all know and/or not object when it comes time to cull the admin list.

**Comment by durandom** [comment]
Still in the game

**Comment by schwesig** [comment]
yes, I am in
