### ISSUE TITLE
Data Science Users: How should we be deploying our work to this environment?  

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#13]
**Description**

@durandom, you mentioned "the DS folks have notebooks and workflows" and also "We should only deploy stuff via argocd or PRs to the gitlab repo"; I'm not sure I understand how to deploy stuff via a PR, should we be getting some of our existing notebooks added by PR?  Is there documentation somewhere for how to do this?

Also, on @hemajv 's note, should DS folks be using the services deployed by others? or deploying our own (as we all start to get something running in this environment)? My dashboard shows no projects, so I am only aware that there is jupyterhub instance since Hema announced it via email. Shouldn't we be able to see all the projects on our dashboards?  

thanks!

**Comment by durandom** [comment]
once @HumairAK has argocd setup, @tumido can help with setting up e.g. argo workflows

@MichaelClifford what specific application/workflow/notebook/dashboard etc do you want to access or deploy?

**Comment by MichaelClifford** [comment]
@durandom I didn't have anything specific in mind, more a clarification on process. In the event a Data Scientists like myself would want to deploy an application, are there docs for doing this through a PR? In the past I've only evjust used the command line like "oc new-app ..." when testing stuff out our setting up a demo.

**Comment by MichaelClifford** [comment]
I think @anishasthana answered my question in an email, but thought I'd repost here for continuity. 

>Yep! I'd start with a look at https://github.com/operate-first/continuous-deployment/blob/master/docs/get_argocd_to_manage_your_app.md. 
These docs were written by people who are comfortable with Kustomize and ArgoCD

**Comment by HumairAK** [comment]
@MichaelClifford  I'm in the middle of setting up projects / permissions for argocd on moc, I've made an issue [here](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/52) with a proposed argocd project structure. Basically you guys would fall under the `data-science` project, and you'd be able to deploy apps/etc. to your namespaces under this project -- I'll provide docs on how to do this along with the pr to tackle the issue I just linked.

**Comment by martinpovolny** [comment]
I'll add myself here. I am currently struggling to deploy our anomaly detection project using argo-cd to an ocp4 cluster. 

Working in https://github.com/martinpovolny/ocp4-anomaly-detection/tree/argocd/manifests

I think I got basics right, secrets seem to be kept secret, resources are being created. Only as whole it does not work yet ;-)

**Comment by HumairAK** [comment]
@martinpovolny this is a separate argocd cluster we used to manage applications for `aicoe` teams and idh internally, please make an issue about this [here](https://github.com/AICoE/aicoe-cd)

**Comment by tumido** [comment]
@martinpovolny @MichaelClifford  We've introduced new issue templates and documentation to this repository. Please check if that is sufficient resolution for this issue.

https://github.com/operate-first/support/issues/new/choose
https://github.com/operate-first/support/tree/main/docs

**Comment by HumairAK** [comment]
This should be resolved via docs linked in last comment. Please feel free to re-open if they are insufficient, and/or unclear, and if there's need for additional documentation.
