### ISSUE TITLE
Should we move our public chat to a different platform?

### ISSUE THREAD

**Issue by larsks** [operate-first/support#134]
The "Operate First Ops" chat is hosted on Google Chat. This is convenient (most of us already have Google accounts), but it comes with some disadvantages. I think the ones with the biggest impact are:

- People can't join the chat without an invite.

  This is the sort of "file a ticket, wait for a response" workflow
  that we really want to avoid. People should be able to join that
  chat just because they're interested, without requiring the action
  of an apparent gatekeeper to approve their request.

- Some organizations have disabled Google Chat.

  Different organizations may have different suites of Google Services
  enabled for their organizational accounts. If Google Chat is
  disabled, people simply cannot join our public chat using their
  organization account. There aren't any good solutions to that, since
  people may not be comfortable using a personal account for what may
  be work purposes.

I think we should consider using an alternative platform.  Options
that I have in mind are:

- [GitHub Discussions](https://docs.github.com/en/discussions)

  This is GitHub's own chat service. A discussion is linked with a
  particular repository. From the docs:

  > If a repository administrator or project maintainer enables
  > discussions for a repository, anyone who visits the repository can
  > create and participate in discussions for the repository. Repository
  > administrators and project maintainers can manage discussions and
  > discussion categories in a repository, and pin discussions to increase
  > the visibility of the discussion. Moderators and collaborators can
  > mark comments as answers, lock discussions, and convert issues to
  > discussions.

- [Slack](https://slack.com/)

  Slack is another common chat platform with which many folks are
  familiar. There are limits in the free version (e.g., available chat
  history) that we would want to take into account.

- [Gitter.im](https://gitter.im/)

  Gitter allows one to create chats that are linked to particular
  GitHub repositories. They support authentication via GitHub, GitLab,
  or Twitter. In addition to the web UI, chats are also available via
  [Matrix](https://matrix.to) clients.

On paper, Gitter.im looks interesting because of the flexible
authentication and access options, but I've only used the service
occasionally and never as a chat room operator.

**Comment by tumido** [comment]
Some platforms and conferences started moving lately to Discord, which may be another option. Not sure what are the limitations on free plans, but the overall integration capabilities are comparable to Slack and it's a very versatile tool.

Gitter.im was always very resource demanding on the web client from my experience, not that much comfortable to use or search, the integration for bots was not as smooth as for Slack for example. I never liked it much, but that's just a personal preference

Slack has one of the best bot support platforms, many integrations are possible and many opensource communities are using it - the experience for newcomers from different communities would remain the same which is a huge plus. Most of the OpenShift and Kube-native communities are on Slack.

While I don't have a personal experience with GitHub discussion, it feels more like a enclosed forum platform - while integration with the rest of the GH is nice, any other integration seems a bit more problematic. It doesn't feel to me like a chat platform, it's rather suitable for ongoing, long term discussions than for a quick chatting.

**Comment by larsks** [comment]
@tumido I'm also fine with discord. I think the UI is a little more irc-like, but that's fine with me. I like their "scan qr code" login option, although I'm sad that they don't offer any sort of federated login.

Lastly, my kids will be impressed that I'm finally using Discord.

**Comment by durandom** [comment]
Unless somebody has a strong opinion, I'd stay with gchat or move over to the coreos slack until we have many external people and then revisit. 

For now, I'd stick with the "create issue -> gchat invite" workflow.

re: gitter.im - I liked it, and it has inifite history for free

**Comment by HumairAK** [comment]
I'm leaning towards Slack since that's what most folks are familiar with + the resources available for writing bots could really help us with adding some neat automation later down the road. Though I admit, lack of chat history is a major bummer, but any permanent discussions should be happening in github issues/prs anyways, and I feel like we do make a good attempt to move discussions to git when needed.

Other than that, I'm not sure what else discord can offer that slack doesn't.

**Comment by larsks** [comment]
> For now, I'd stick with the "create issue -> gchat invite" workflow.

@durandom the problem, as I noted earlier, is that someone people *can't join* the gchat because support for chat is disabled by their organization. This is true for everyone `@bu.edu`.

**Comment by tumido** [comment]
@durandom as it turned out the `@bu.edu` people can't join us in gchat. That's a big limitation for me... CoreOS Slack is fine with me, we don't need a full workspace for ourselves, :+1: to that option.

**Comment by larsks** [comment]
@tuido does coreos slack alllow people to join without an invite? If I visit https://coreos.slack.com from an incognito window, my options are:

- Log in with my `@redhat.com` google account, or
- Log in with a guest account if I have one

I'm not able to log in using another Google account, nor can I create an account for use on coreos.slack.com. I can "Contact the workspace administrator for an invitation", but that's not any better than what we have right now.

**Comment by tumido** [comment]
@larsks you're right. It doesn't solve that... I got carried away for a moment...

**Comment by tumido** [comment]
@larsks @durandom RH is also paying for Ansible slack, that one seems to be open to public though: https://ansible.slack.com/

**Comment by larsks** [comment]
@tumido I'm not sure that works either. If I try logging in there with a random Google account, I get e.g. "lars@bu.edu doesn’t have an account on this workspace.".  There doesn't seem to be a "request access" or "create an account" option.

**Comment by 4n4nd** [comment]
I am down for slack or discord, since I already use them both.

**Comment by durandom** [comment]
The `bu.edu` restriction is weird, given that they work a lot with RH, which is all over the place for google apps 🤷‍♂️
But, yeah, that's what I meant with "until ... revisit", seems we're blocking people.

Given the Slack Paywall, I'd vote for gitter.im which has auth with GH, unlimited messages and you can link to threads.
@larsks would even get his IRC integration :P

**Comment by tumido** [comment]
Ugh.. I don't like Gitter. :smile:. Searching and notifications are really bad... (Notifications on the same level of bad as GChat, search even worse). I'd rather spend my time arguing with BU to relax the policies and allow them to use GChat than use Gitter.

**Comment by larsks** [comment]
Unfortunately the BU policy is set at an institutional level and isn't something I think we'll be able to change. It sounds like the MOC folks have tried previously with no success.

**Comment by 4n4nd** [comment]
> @tumido I'm not sure that works either. If I try logging in there with a random Google account, I get e.g. "[lars@bu.edu](mailto:lars@bu.edu) doesn’t have an account on this workspace.". There doesn't seem to be a "request access" or "create an account" option.

that's weird, I get the same issue with my redhat account
![Screenshot from 2021-03-19 12-29-08](https://user-images.githubusercontent.com/22333506/111812792-d12ce700-88ae-11eb-81e0-45e504eff3d7.png)

**Comment by durandom** [comment]
https://github.com/mschimmer/docker-slack-export-toolbox - more hacking

**Comment by larsks** [comment]
@tumido can you provide more detail on the notification and search issues with gitter?

**Comment by tumido** [comment]
@larsks notifications are not tracked anywhere... If I remember it correctly from my time using it in ManageIQ, you have that green circle by a persons/channels name, no way to scroll back to the actual mention, see all the mentions if there are multiple ones in the same channel or to see where you've left of and so on... Compared to Slack, where you have threads tracked separately, dms and unread notifications in a single view etc.

Searching never returned me what I wanted in Gitter: If I don't remember the exact channel or person, I can only search globally (or write a sql-like query into a tiny input box) which usually returns tons of unrelated stuff. GChat has much better chat and Slack does fairly good as well. The UX is not good for me.

Additionally in Slack you can make thread from any message on the channel so discussions don't have to be linear, which is a huge plus to me since I find myself always juggling multiple topics in a single chat in GChat...

**Comment by HumairAK** [comment]
How about we go with free slack + some archival solution that runs daily or something?

**Comment by larsks** [comment]
@tumido thank you for the details!

@HumairAK I was just going to suggest something like that. It sounds like slack may have the feature set we want. Is it actually possible to create public workspaces? All the ones we've looked at so far require some sort of pre-approval.

**Comment by durandom** [comment]
then let's try a free slack instance and play with https://github.com/mschimmer/docker-slack-export-toolbox

or we just live with no history :)

**Comment by tumido** [comment]
Ok, I'm gonna create a workspace and we can try it out :)

**Comment by HumairAK** [comment]
> Is it actually possible to create public workspaces? All the ones we've looked at so far require some sort of pre-approval. 

The way I understand it is that it is invite only, however, you can have invitations be auto-approved for certain domains. So if you auto approve the domain for @redhat.com, then when you request an invitation from this e-mail, you are auto invited via an e-mail confirmation.

**Comment by tumido** [comment]
Try if you can join :) https://join.slack.com/t/operatefirst/shared_invite/zt-o2gn4wn8-O39g7sthTAuPCvaCNRnLww

**Comment by HumairAK** [comment]
I think we're getting pretty comfortable with slack, we'll keep testing the waters there but for now I think this issue has served it's purpose, closing. Feel free to open if there's more.

**Comment by larsks** [comment]
If we're settling on slack, can we close the gchat room or otherwise indicate that we're not using it anymore?

**Comment by tumido** [comment]
@larsks that's a concern worth reopening the issue.

Can we even close/lock channels in GChat? Or pin a post with the slack url?

**Comment by HumairAK** [comment]
We can just rename the channel with a `DEPRECATED-*` prefix with a pinned post, I feel like that would be enough.

**Comment by tumido** [comment]
The GChat channel was renamed to `[DEPRECATED] Operate First Ops - Use operatefirst.slack.com` and I've posted a message with invite to our Slack in there. I think we can put this ticket to sleep again. :slightly_smiling_face:
