### ISSUE TITLE
jupyter notebook can not be started

### ISSUE THREAD

**Issue by goern** [operate-first/support#136]
**Describe the bug**
500 : Internal Server Error
CERTIFICATE_VERIFY_FAILED

**To Reproduce**
1. Go to https://odh-dashboard-opf-dashboard.apps.zero.massopen.cloud/
2. Click on 'JupyterHub Launch'

**Expected behaviour**
I see a notebook

/kind bug
/priority critical-urgent
/sig devops

**Comment by tumido** [comment]
Yup, this is caused by https://github.com/operate-first/support/issues/132 

ODH Dashboard is picking up a wrong url for JupyterHub - please use:
https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/
not
https://jupyterhub-ds-ml-workflows-ws.apps.zero.massopen.cloud/ advised by ODH Dashboard

**Comment by durandom** [comment]
@tumido @HumairAK is this something we could catch via monitoring? 
Or is this going into the testing territory?

https://github.com/prometheus/blackbox_exporter

**Comment by durandom** [comment]
For testing we can engage with https://github.com/red-hat-data-services/ods-ci

**Comment by tumido** [comment]
Sure we can be catching that via monitoring somehow. However please know that the certificate issue is not happening on OPF supported instance of JupyterHub. Our instance works flawlessly. Just the ODH Dashboard is pointing in a wrong direction - hence the dashboard bug.
