### ISSUE TITLE
Is it possible to configure the bot to not assign me as a reviewer? by @naved000

### ISSUE THREAD

**Issue by tumido** [operate-first/support#137]
Is it possible to configure the bot to not assign me as a reviewer? 

I can be explicitly assigned for reviews when there's something specific I should be looking at. Just trying to cut down on some bot notifications. Thanks!

_Originally posted by @naved001 in https://github.com/operate-first/argocd-apps/issues/106#issuecomment-802872438_

**Comment by tumido** [comment]
@naved001 you've been removed from the reviewers list in all the repos :slightly_smiling_face: No more autoassigned issues for you! :+1: Closing

**Comment by naved001** [comment]
@tumido
The bot somehow still requested a review on a new PR: https://github.com/operate-first/SRE/pull/233

**Comment by tumido** [comment]
@naved001 seems I've forgotten one repo, sorry :smile: fixing it asap. :slightly_smiling_face:

**Comment by naved001** [comment]
hey, no worries! Thanks @tumido!
