### ISSUE TITLE
Introduce jupyerthub stagging namespace for jupyterhub related enhancement research 

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#140]
**Is your feature request related to a problem? Please describe.**
As Jupyterhub Image Developer, would like to have access to a jupyterhub stagging namespace so that all the developer can have a space to develop new image without having to create in local and then find a cluster to test it. 

The proposal is to have a separate deployment of jupyterhub for developer, the actions in here shouldn't affect the users of the operate-first jupyterhub. This deployment would be used for developing and testing new jupyterhub images , before passing them to operate-first jupyterhub or upstream opendatahub jupyterhub.

**Describe the solution you'd like**
Deploy jupyterhub on a separate namespace with kfdef, enabling developer to directly access the namespaces.

**Describe alternatives you've considered**
Developer and users(data  scientist) use the same deployment i.e operate-first jupyterub.

**Additional context**
As we have CI/CD systems we can configure them to auto-create pull requests and merge them to get new changes to this new namespace without having too many human interactions.

**Comment by tumido** [comment]
We already have a JupyterHub staging namespace declared. Anything happening in there? @4n4nd @HumairAK

**Comment by 4n4nd** [comment]
The intention was to test new updates in the namespace before deploying them in prod. But rn we are not using it for anything.
We should replicate our prod instance in there ideally.

**Comment by 4n4nd** [comment]
I can copy the kfdef from the prod env and deploy it in the staging namespace manually.

**Comment by tumido** [comment]
@4n4nd that sounds like a neat idea. Yup, I think we should do it. But rather by creating new stage overlay for jupyterhub allowing changes described above by @harshad16 , wdyt?

**Comment by harshad16** [comment]
I m in favor of deploying a new staging namespace, manually new change or new development is a good way to start. 
The we can slowly bring that to git or have the bots open pull request based on new change of the images

**Comment by 4n4nd** [comment]
> But rather by creating new stage overlay for jupyterhub allowing changes described above by @harshad16 , wdyt?

@tumido are you suggesting we use argocd to deploy it or just to keep track of what resources are deployed in the namespace?

**Comment by 4n4nd** [comment]
> The we can slowly bring that to git or have the bots open pull request based on new change of the images

@harshad16 Can you please elaborate on this a little? Where will the pull request be created? The pull request is for new images that have been tested in the namespace or other resources?

**Comment by harshad16** [comment]
The idea is to enable developer open a pull request in respective image they are working on for example. s2i-lab-elyra then used the `deploy` command provided by aicoe-ci, then the ci takes that pull -request and containerizes it and the opens another pull-request(this is one previously referred in above comments) to the designated repo where the manifests lives, and updates the imagestream to get this into the stagging deployment for testing and further work. 

we can start with normal flow, user would deploy their own images directly to the staging cluster.

**Comment by tumido** [comment]
@4n4nd :
For a "staging" namespace to serve @harshad16's purpose, we would have to have the JupyterHub managed by ArgoCD + allow users to define imagestreams and so on manually in the namespace. Like have the ArgoCD deployed JH as a stable foundation while allowing users to interact with the namespace and touch resources.  And I'd suggest to put such ArgoCD managed JupyterHub into a separate overlay - not deploy it from prod, since we might want to do some changes (e.g. not deploy/manage our imagestreams and so on)

**Comment by HumairAK** [comment]
@4n4nd can this be closed?

**Comment by 4n4nd** [comment]
yeah the `opf-jupyterhub-stage` namespace was added for this :+1:

**Comment by harshad16** [comment]
Yes this can be closed, thanks @4n4nd  for the setup.
