### ISSUE TITLE
"No Kernel" Error in MOC JupyterHub and JupyterLab

### ISSUE THREAD

**Issue by oindrillac** [operate-first/support#142]
**Describe the bug**

I see a "No Kernel" error as I try to spawn up any notebook in JupyterHub/JupyterLab.

**To Reproduce**

1. Go to 'jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/'
2. Spawn up Elyra Version 0.0.6 Image
3. Clone ocp-ci-analysis (https://github.com/aicoe-aiops/ocp-ci-analysis)
4. Spawn up notebooks/data-sources/TestGrid/testgrid_EDA.ipynb notebook and hit "Manage Dependencies"
5. Install Dependencies as per instructions in https://github.com/thoth-station/jupyterlab-requirements
6. After dependencies are installed, restart kernel and see "No Kernel" error at top of notebook.
7. Shut down Server and try spawning up any other JupyterHub image, and see the same "No Kernel" error for each notebook, in any repository.
8. Try `pipenv install` from root of any repo and see "No Kernel" error as a notebook is spawned.

**Expected behaviour**
Manage dependencies should have worked and installed dependencies within notebook

**Screenshots**

**JupyterHub**
![image](https://user-images.githubusercontent.com/32435206/112039122-0ee17800-8b1a-11eb-8c30-b0feb89bf9dc.png)

**JupyterLab**
![image](https://user-images.githubusercontent.com/32435206/112039795-d1c9b580-8b1a-11eb-8d97-98635af04204.png)
![image](https://user-images.githubusercontent.com/32435206/112039852-e017d180-8b1a-11eb-81e6-f1c23ef52bda.png)

**Additional context**

Error Traceback:

```Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/opt/app-root/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/app-root/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 72, in post
    type=mtype))
  File "/opt/app-root/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/app-root/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/app-root/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/opt/app-root/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/app-root/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/app-root/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/opt/app-root/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/app-root/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/app-root/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/jupyter_client/manager.py", line 305, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "/opt/app-root/lib/python3.6/site-packages/jupyter_client/manager.py", line 212, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/opt/app-root/lib/python3.6/site-packages/jupyter_client/launcher.py", line 135, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/app-root/src/.local/share/thoth/kernels/python3/bin/python': '/opt/app-root/src/.local/share/thoth/kernels/python3/bin/python'
```
related: https://github.com/aicoe-aiops/ocp-ci-analysis/issues/124
cc: @Shreyanand

**Comment by oindrillac** [comment]
this "No Kernel" error persists even if i spawn a new server. do we have any ideas about this?

**Comment by tumido** [comment]
Any idea @4n4nd @HumairAK ?

**Comment by 4n4nd** [comment]
@oindrillac Is this issue just in the Elyra image or does it persist when spawning other images as well?

**Comment by oindrillac** [comment]
@4n4nd this started with the Elyra image, but now it exists for all images

**Comment by HumairAK** [comment]
I followed the steps and was not able to reproduce this issue  
![image](https://user-images.githubusercontent.com/10904967/112361256-94dff900-8ca9-11eb-97c6-47c260853b2b.png)


After restarting the kernel:
![image](https://user-images.githubusercontent.com/10904967/112361216-87c30a00-8ca9-11eb-8f49-c11e2fe17526.png)



-- has anyone else encountered this?

**Comment by 4n4nd** [comment]
I could not reproduce this

**Comment by 4n4nd** [comment]
This is what it looks in the directory where the error is seen:
```bash
[1000950000@jupyterhub-nb-ochatter-40redhat-2ecom bin]$ pwd
/opt/app-root/src/.local/share/thoth/kernels/python3/bin
[1000950000@jupyterhub-nb-ochatter-40redhat-2ecom bin]$ ls -l pyt*
lrwxrwxrwx. 1 1000950000 root 18 Mar 22 16:20 python -> /usr/bin/python3.8
lrwxrwxrwx. 1 1000950000 root  6 Mar 22 16:20 python3 -> python
lrwxrwxrwx. 1 1000950000 root  6 Mar 22 16:20 python3.8 -> python
```
and none of the python bins work
```bash
[1000950000@jupyterhub-nb-ochatter-40redhat-2ecom bin]$ ./python
sh: ./python: No such file or directory
```

**Comment by harshad16** [comment]
i will take this one

**Comment by harshad16** [comment]
> Is this issue just in the Elyra image or does it persist when spawning other images as well?
on this question, currently the elyra image only has this support.
i will be updating the other image as well in upstream 
the image with python38 have the support for jupyterlab-requirements extension as of now.

**Comment by harshad16** [comment]
cc: @pacospace

**Comment by harshad16** [comment]
the restart of kernel is not giving error
![kernel](https://user-images.githubusercontent.com/14028058/112385871-83f1b080-8cc6-11eb-8d06-8982958d2829.png)

**Comment by harshad16** [comment]
is this issue occuring in v0.0.6 of elyra?

**Comment by oindrillac** [comment]
The issue is not occurring in Elyra 0.0.6 now, but the issue is occurring in all other JupyterLab and JupyterHub images.
I tried restarting the kernel and restarting the server and the issue still persists in the other images.

**Comment by pacospace** [comment]
I might have an idea of why that is happening. 
@oindrillac did you use the default name (python3) as kernel name when using jupyterlab-requirements?

Also can you please run from terminal `jupyter kernelspec list` command and report the result here please?

**Comment by harshad16** [comment]
> The issue is not occurring in Elyra 0.0.6 now, but the issue is occurring in all other JupyterLab and JupyterHub images.

On other image jupyterlab-requirment extension is not fully supported as they are pthon36 based image
any other image like s2i-pytorch-py38-notebook would have the support for this.
we would update the image and try to get them in odh soon.

**Comment by pacospace** [comment]
> I might have an idea of why that is happening.
> @oindrillac did you use the default name (python3) as kernel name when using jupyterlab-requirements?
> 
From the screenshot seems yes. I can replicate the issue and the solution is to put back the default jupyter configuration for the kernelspec. I will create a bug in jupyterlab-requirements and solve this inconvenient, I always used a different kernel name, so I did not identify this bug before!!

> Also can you please run from terminal `jupyter kernelspec list` command and report the result here please?

**Comment by pacospace** [comment]
> > I might have an idea of why that is happening.
> > @oindrillac did you use the default name (python3) as kernel name when using jupyterlab-requirements?
> 
> From the screenshot seems yes. I can replicate the issue and the solution is to put back the default jupyter configuration for the kernelspec. I will create a bug in jupyterlab-requirements and solve this inconvenient, I always used a different kernel name, so I did not identify this bug before!!
> 
> > Also can you please run from terminal `jupyter kernelspec list` command and report the result here please?

We definetly need tests in the cluster before providing jupyterlab-requirements :) 

Also elyra v0.0.6 actually has jupyterlab-requirements v0.4.7 which does not has the new features and the bug fixes for pipenv cache. cc @harshad16

**Comment by harshad16** [comment]
> Also elyra v0.0.6 actually has jupyterlab-requirements v0.4.7 which does not has the new features and the bug fixes for pipenv cache.

ack, lets have another release of elyra to have the pipenv cache feature

**Comment by pacospace** [comment]
> > Also elyra v0.0.6 actually has jupyterlab-requirements v0.4.7 which does not has the new features and the bug fixes for pipenv cache.
> 
> ack, lets have another release of elyra to have the pipenv cache feature

I will release patch tomorrow for the issue referenced so we can include jupyterlab-requirements v0.5.1

**Comment by oindrillac** [comment]
> I might have an idea of why that is happening.
> @oindrillac did you use the default name (python3) as kernel name when using jupyterlab-requirements?

yes, I think I did use the default name.

> Also can you please run from terminal `jupyter kernelspec list` command and report the result here please?

is there a specific image you want me to try this from?
from JupyterHub, ocp-ci image I get this 

**Available kernels:
  python3    /opt/app-root/src/.local/share/jupyter/kernels/python3**

**Comment by oindrillac** [comment]
thanks for debugging this @pacospace & @harshad16

**Comment by pacospace** [comment]
> > I might have an idea of why that is happening.
> > @oindrillac did you use the default name (python3) as kernel name when using jupyterlab-requirements?
> 
> yes, I think I did use the default name.
> 
> > Also can you please run from terminal `jupyter kernelspec list` command and report the result here please?
> 
> is there a specific image you want me to try this from?
> from JupyterHub, ocp-ci image I get this
> 
> **Available kernels: python3 /opt/app-root/src/.local/share/jupyter/kernels/python3**

You can do it from every image as these configurations are saved in your PVC.

**Comment by harshad16** [comment]
Thanks @pacospace  for the fixes.

**Comment by pacospace** [comment]
> > I might have an idea of why that is happening.
> > @oindrillac did you use the default name (python3) as kernel name when using jupyterlab-requirements?
> 
> yes, I think I did use the default name.
> 
> > Also can you please run from terminal `jupyter kernelspec list` command and report the result here please?
> 
> is there a specific image you want me to try this from?
> from JupyterHub, ocp-ci image I get this
> 
> **Available kernels: python3 /opt/app-root/src/.local/share/jupyter/kernels/python3**

can you try running `ipython kernel install --user --name=python3 --display-name 'Python (python3)'` to see if the issue still persists?

**Comment by oindrillac** [comment]
@pacospace that seemed to do the trick! 🎉 Now I am able to see the Kernel Python 3

**Comment by tumido** [comment]
Great read folks! Thank you @pacospace !

@oindrillac can we mark this issues as resolves? :+1:
