### ISSUE TITLE
Document how to restore python kernels in JupyterHub

### ISSUE THREAD

**Issue by tumido** [operate-first/support#148]
> > I might have an idea of why that is happening.
> > @oindrillac did you use the default name (python3) as kernel name when using jupyterlab-requirements?
> 
> yes, I think I did use the default name.
> 
> > Also can you please run from terminal `jupyter kernelspec list` command and report the result here please?
> 
> is there a specific image you want me to try this from?
> from JupyterHub, ocp-ci image I get this
> 
> **Available kernels: python3 /opt/app-root/src/.local/share/jupyter/kernels/python3**

@oindrillac  can you please try running `ipython kernel install --user --name=python3 --display-name 'Python 3'` from the terminal of any image and see if the issue still persists?

_Originally posted by @pacospace in https://github.com/operate-first/support/issues/142#issuecomment-806220803_

**Comment by pacospace** [comment]
@tumido  do we want this description under https://www.operate-first.cloud/users/support/ in Tab JupyterHub?

**Comment by tumido** [comment]
Actually, I think it would be ideal, if we can create an user story in here:
https://github.com/operate-first/blueprint/tree/main/docs/userstories/jupyterhub

and link to it from here:
https://github.com/operate-first/SRE/blob/master/runbooks/jupyterhub.md

We can than start thinking how to surface the runbooks on the website so the "resolutions" via user stories are available to all.

WDYT @HumairAK
