### ISSUE TITLE
Onboarding rbohne to zero

### ISSUE THREAD

**Issue by rbo** [operate-first/support#149]
**Describe the bug**
After login into the zero cluster with my Red Hat account, I was able to create a project/namespace without any quotas or limitation.

**To Reproduce**
1. Go to 'https://console-openshift-console.apps.zero.massopen.cloud/search'
2. Login with our Red Hat Account
3. Click on create project
4. Start some bit count mining ;) 

**Expected behaviour**

Can login but can not create a project/namespace.

**Screenshots**

**Additional context**

It looks like the self-provisioners is still assigned to the group system:authenticated:oauth

[1] https://docs.openshift.com/container-platform/4.7/applications/projects/configuring-project-creation.html#disabling-project-self-provisioning_configuring-project-creation

**Comment by tumido** [comment]
Duplicate of: https://github.com/operate-first/apps/issues/432 FIX pending

Re-purposing this ticket as an onboarding for your namespace.

namespace is: `rbohne-demo1`
Any desired team name @rbo ? 
Any secrets you want us to manage? 

See [this template](https://github.com/operate-first/support/issues/new?assignees=&labels=onboarding&template=onboarding_to_cluster.md&title=) for a template in what kind of info we need

**Comment by rbo** [comment]
### Questionnaire

1. **Team name**: rbohne
2. **Desired namespaces**: 
* rbohne-openshift-examples
* rbohne-acme
* rbohne-demo
* rbohne-anwendertreffen

3. **Users needing access**: rbohne@redhat.com (RedHat SSO) or my Kerberos Id rbohne

4. **Target cluster**:
* zero for namespaces above.
* infra to take a look for the upcoming hetzner deployment (If approval needed ask: @goern )

5. **Team or maintainer owned GPG key fingerprint along with a keyserver** (OPTIONAL): n/a

**Comment by durandom** [comment]
/hold

I'm not sure if we want personal demo namespaces and one-man teams on the zero cluster :)

@rbohne could you pick a demo that you already have and then work onboarding that to the cluster? Like https://github.com/operate-first/support/issues/113

I'm not sure about the team name in such a case. Maybe the team is the demo maintainers and the team name would be the demo name?! Or if its a workshop, it's similar to the workshop team?

**Comment by rbo** [comment]
It is to get experience in that env and later on to promote it to the german SA team. 
Demo/examples/use cases, I have a couple:
- https://examples.openshift.pub / https://github.com/openshift-examples -> Running on OpenShift online OCP 3.11 :-/ , maybe moved to zero. 
- http://www.openshift-anwender.de - a german openshift user group running on openshift online maybe move to zero.

I'm one of the go-to person around openshift for the German SA team, from my point of view it makes sense to know how it works and how it feels from the user perspective. 

Hope that helps to understand my viewpoint.

**Comment by durandom** [comment]
Thanks for the background.

Is http://www.openshift-anwender.de "just" a website app? If you're good with the kind of SLA we provide for the zero cluster https://github.com/open-infrastructure-labs/ops-issues/issues/32 (production cluster) we could target this as a first onboarding example? 

I'd suggest naming the group and namespace `www-openshift-anwender-de` (to avoid `openshift-` prefixes).

**Comment by durandom** [comment]
Oh, and you can start the onboarding yourself by following option 2 in https://www.operate-first.cloud/users/support/docs/onboarding_to_cluster.md

**Comment by HumairAK** [comment]
I agree -- let's avoid adding individual usernames as team names, maybe this should be better reflected in the onboarding template.

**Comment by goern** [comment]
Why dont we create a group 'sa-dach' with Robert as the goto/proxy/first?

Deploying  http://www.openshift-anwender.de seems to be a good idea, it will give us some insides on how 'content creators' will fit into our GitOps'ish workflows. And (I guess) the website will show a seasonality, using HPA and analysing metrics might be a nice project to come up with a little bit more cleaver pod autoscaler that is analysing traffic on the DPU and .....

**Comment by rbo** [comment]
sa-dach group sounds good.

openshift-anwender is wordpres with an MySQL backend and persistend storage. So how a legacy application fit into gitops :-)

**Comment by tumido** [comment]
So, let's sum it up again:

1. User group: `sa-dach` with @rbo as the sole member for now 
2. Namespaces:
    - `sa-dach-openshift-examples`
    - `sa-dach-anwendertreffen`
 
Did I miss anything?

:+1: If we can proceed with this setup.

**Comment by durandom** [comment]
ACK. 
@rbo is  https://examples.openshift.pub/ is also a webpage that you just want to host, or do you want to host those small examples? First I thought the latter, but if both NS just host webpages, let's do it :shipit: 

@rbo do you want to go through creating the onboarding PRs or shall we (@tumido && @HumairAK :P)

**Comment by rbo** [comment]
Feel free to create the PRs, I will take a look over the PR's to learn :-)
