### ISSUE TITLE
Document how to debug KFP issues when submitting pipelines

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#152]

**Comment by ptitzler** [comment]
Is the intention here to create a generic KFP topic or one that'd cover common Elyra/pipelines issues? If it's for the latter - we've improved the relevant code in Elyra (in > v2.2.1) and should surface the relevant information in a more user-friendly way.

**Comment by pacospace** [comment]
> Is the intention here to create a generic KFP topic or one that'd cover common Elyra/pipelines issues? If it's for the latter - we've improved the relevant code in Elyra (in > v2.2.1) and should surface the relevant information in a more user-friendly way.

Thanks @ptitzler, we can check new version of Elyra then and see if that is enough. This issue was related-to: https://github.com/operate-first/support/issues/145.

But testing v0.0.7 once available, can be useful, maybe we don't need more docs.

**Comment by pacospace** [comment]
> > Is the intention here to create a generic KFP topic or one that'd cover common Elyra/pipelines issues? If it's for the latter - we've improved the relevant code in Elyra (in > v2.2.1) and should surface the relevant information in a more user-friendly way.
> 
> Thanks @ptitzler, we can check new version of Elyra then and see if that is enough. This issue was related-to: #145.
> 
> But testing v0.0.7 once available, can be useful, maybe we don't need more docs.

To give more context actually, this issue was to have some docs on how to get into KFP UI and check what is happening in the pipeline and see if and why they failed, if errors are present.

This is because from ELyra UI there wasn't a pipelines status to check errors for specific steps. Not sure if that feature was introduced already and present in 2.2.1. But I think @ptitzler asnwered here: https://github.com/elyra-ai/elyra/issues/1498#issuecomment-810377134.

**Comment by ptitzler** [comment]
> To give more context actually

Thanks you!

> This is because from Elyra UI there wasn't a pipelines status to check errors for specific steps. Not sure if that feature was introduced already and present in 2.2.1. 

We do expose errors that occur during _pipeline preparation and pipeline submission_ - these are the only tasks that are performed in JupyterLab and under our control. (Most issues we've seen in the past are related to runtime configuration problems that lead to connectivity failures. Unfortunately there is no "Test connectivity" button on the runtime configuration screen that can be used to validate that the provided information is correct.) However, once a pipeline is submitted to KFP (or Airflow) users have to use the KFP/Airflow UI to monitor execution progress and to diagnose any runtime failures.

**Comment by pacospace** [comment]
> > To give more context actually
> 
> Thanks you!
> 
> > This is because from Elyra UI there wasn't a pipelines status to check errors for specific steps. Not sure if that feature was introduced already and present in 2.2.1.
> 
> We do expose errors that occur during _pipeline preparation and pipeline submission_ - these are the only tasks that are performed in JupyterLab and under our control. (Most issues we've seen in the past are related to runtime configuration problems that lead to connectivity failures. Unfortunately there is no "Test connectivity" button on the runtime configuration screen that can be used to validate that the provided information is correct.) 

Thanks @ptitzler!

Then this issue can be focused on this part: 

> However, once a pipeline is submitted to KFP (or Airflow) users have to use the KFP/Airflow UI to monitor execution progress and to diagnose any runtime failures.

Then we can describe `debug KFP (or Airflow) pipeline using KFP/Airflow UI` for users, adding some screenshots and description of the UIs (e.g. pipelines, experiments )

**Comment by pacospace** [comment]
> /assign @pacospace
> /kind documentation
> /sig user-experience

@tumido  do we want this description under https://www.operate-first.cloud/users/support/ in Tab Kubeflow?
