### ISSUE TITLE
Issue spawning an image from JH

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#154]
**Describe the bug**
Issue spawning an image from JH

**To Reproduce**
1. Go to JH on Operate First
2. Select an image

**Expected behaviour**
Image is spawned successfully

**Screenshots**
![Screenshot from 2021-03-25 18-19-31](https://user-images.githubusercontent.com/27498679/112515801-e619e680-8d96-11eb-8d09-fc4169c09f31.png)

**Additional context**

**Comment by tumido** [comment]
Yup, seems to be the same issue as https://github.com/operate-first/support/issues/153

Closing in favor of  https://github.com/operate-first/apps/issues/438
