### ISSUE TITLE
cant access grafana dashboard

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#157]
**Describe the bug**

The grafana dashboard is not available https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/
As i m part of operate-first group, i have access to the namespace of the deployment.
The pod is failing due to the `ImagePullBack` error
![grafana](https://user-images.githubusercontent.com/14028058/112556549-d7383180-8da0-11eb-97b2-731a9b1e6385.png)

This seems to be because the image no longer exists
https://quay.io/repository/app-sre/grafana

i m unaware if the image is private and needs secrets to pull. However it is reason for grafana dasbaord being down.

**To Reproduce**
1. Go to 'https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/
2. See error

**Expected behaviour**
A properly functioning grafana dashboard

**Comment by tumido** [comment]
Yup, the image is gone. We need to find a new one or clone it ourselves. I'm gonna clone the upstream for now and we can talk to the SRE team why it went down...

**Comment by tumido** [comment]
Image available here: https://quay.io/repository/operate-first/grafana?tab=tags
