### ISSUE TITLE
HTTP Url of odh dashboard

### ISSUE THREAD

**Issue by durandom** [operate-first/support#158]
**Describe the bug**
When accessing http://odh.operate-first.cloud/ I get a "Application is not available" - the https URL works
https://odh.operate-first.cloud/

**Expected behaviour**
I expect to be redirected to the https version. Is that possible with OpenShift route configuration?

**Comment by tumido** [comment]
/kind bug

Should be an easy change. Thanks for pointing that out. Let me take a look :+1:
