### ISSUE TITLE
opf-ci-prow is reserving ton of CPU but not using it

### ISSUE THREAD

**Issue by tumido** [operate-first/support#159]
**Describe the bug**
`opf-ci-prow` is reserving whopping **180** out of 288 available CPU cores for itself only, while the actual usage is 1.6 cores under max ever observed load

**To Reproduce**
```
topk(25, sort_desc(sum(kube_pod_container_resource_requests_cpu_cores) by (container,namespace)))
```
![image](https://user-images.githubusercontent.com/7453394/112622081-cf24d400-8e2a-11eb-8945-7998519209ed.png)

```
topk(25, sort_desc(sum(avg_over_time(pod:container_cpu_usage:sum{container="",pod!="",namespace='opf-ci-prow'}[5m])) BY (namespace)))
```
![image](https://user-images.githubusercontent.com/7453394/112628207-dc45c100-8e32-11eb-9f54-e590d0f50d98.png)

**Expected behaviour**
We will start enforing quota to mitigate that ever happening, but that doesn't solve the problem for Prow and CI.

We need to either lower the CPU requests (set very low requests and convert the current requests to limits if possible).

Also some kind of pod cleanup for prow containers can help a lot - CPU resources are left reserved even if the pod is completed/failed and remains reserved until the pod resource is deleted from the system.

**Additional context**
Related to https://github.com/operate-first/apps/issues/438

**Comment by tumido** [comment]
Purging those completed/failed pods should help short term

**Comment by tumido** [comment]
It seems to me that the Prow pods are actually never auto-deleted, if not removed manually they pollute the system forever, am I missing something?

**Comment by tumido** [comment]
cleaning up the pods manually to free up resources now

**Comment by tumido** [comment]
That should help a lot:
![image](https://user-images.githubusercontent.com/7453394/112639845-04d4b780-8e41-11eb-9fd8-6d99c1072310.png)

**Comment by harshad16** [comment]
ack, i will check on this 
and try to establish a cleanup system first and parallelly check on the prow side on how to resolve this

**Comment by harshad16** [comment]
>We need to either lower the CPU requests (set very low requests and convert the current requests to limits if possible).
The cpu request of 2 for each prow job seems bit too high, we would ask prow users to drop that and that should help a little with this.


>Also some kind of pod cleanup for prow containers can help a lot - CPU resources are left reserved even if the pod is completed/failed and remains reserved until the pod resource is deleted from the system.

found out that the prow has a configuration for this , setting it in a short while to restrict it to a day. This way users will be able to see the logs at least for a day.

**Comment by tumido** [comment]
Thank you @harshad16 :+1: :rocket: The Prow job TTL settings looks nice.

Yup... we should lower the requests across the board.. I'll start with the on-repo configs in operate-first, let's try `200m` for now. We don't need much CPU on these tasks anyways.

**Comment by tumido** [comment]
There's still no quota on this namespace @harshad16 can I assign this to you?

**Comment by harshad16** [comment]
Yes i will take care of this.
thank you.
