### ISSUE TITLE
Request for the cnv cluster ceph details and prometheus details 

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#16]
**Description**
we liked to request the details about the ceph and prometheus on cnv cluster, so that we can get to know how we can request the credentials. These details are required for project thoth to be able to create an overlay for thoth deployment in cnv cluster. 
How and where to request the details for these services?

**Additional context**
This would modified/enable our application to function on the cnv clusters.

**Comment by 4n4nd** [comment]
@harshad16 An issue on this repo should be the correct way to request any new components or credentials for any services.
Can you please make individual issues for each request?
Thanks!

**Comment by harshad16** [comment]
@4n4nd thanks for the information.
I have created separate individual issues for this request. 
Thanks, you can close this issue, if they feel correct and no other issue is required.
