### ISSUE TITLE
Cannot Access Jupyterhub - 403 Error

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#161]
**Describe the bug**
Attempting to log into `https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/` leads to 403 error. 

**To Reproduce**
1. Go to 'https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/`'
2. Click on 'moc-sso'
3. Click on 'google''
3. Enter your credentials
4. See  403 error

**Expected behaviour**
See Jupyterhub Spawner not 403

**Screenshots**

![image](https://user-images.githubusercontent.com/4494906/112636705-d42a5900-8e13-11eb-9303-f9420953b205.png)

**Additional context**
Clearing cookies and using an incognito window leads to the same result

**Comment by durandom** [comment]
let's try to catch this via an alert or a test in the future...

**Comment by tumido** [comment]
`system:authenticated` must be set instead of advised `""` for `allowed_users` configmap entry. @4n4nd is making a PR with a fix. This is an upstream issue. Filing ticket upstream.
