### ISSUE TITLE
Jupyterhub Image Documentation / Discovery

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#162]
**Is your feature request related to a problem? Please describe.**

As a user of the JupyterHub I want to know the contents (packages/files/data) of the images available to me on the spawner page before selecting it. For example, where can I find the difference between `s2i-lab-elyra:v0.0.5` and `s2i-lab-elyra:v0.0.6`? 

**Describe the solution you'd like**

Either documentation on the operate first site that provided a description of all the available images, or a on-hover description box (like with the "container size" drop down) that gives some indication as to what is in the image. Require the image creators to provide this information when publishing a new image.   

**Describe alternatives you've considered**
Have not considered any alternatives :smile: 

**Additional context**

**Comment by HumairAK** [comment]
> or a on-hover description box (like with the "container size" drop down) that gives some indication as to what is in the image 

Sounds like: https://github.com/opendatahub-io/jupyterhub-odh/issues/85 

While we wait for that, I think adding docs about current images would be useful. Good idea!

**Comment by ptitzler** [comment]
For Elyra we keep a summary in this [discussion thread in the forum](https://github.com/elyra-ai/elyra/discussions/1556). The thread links to other documents that outline what the main features are and how to use them.
