### ISSUE TITLE
requesting a namespace on zero cluster

### ISSUE THREAD

**Issue by Gkrumbach07** [operate-first/support#164]
### Questionnaire

1. **Team name**:

   fde

2. **Desired namespaces**:

   I already have a namespace setup on zero named `audio-decoder-demo`, but this can be deleted if a new namespace needs to be made. In that case it can be called `fde-audio-decoder` to comply with then naming recommendations.

3. **Users needing access**:

    gkrumbac@redhat.com

4. **Target cluster**:

    zero cluster

5. **Team or maintainer owned GPG key fingerprint along with a keyserver** (OPTIONAL):

    n/a

**Comment by tumido** [comment]
@Gkrumbach07 thank's for suggesting the namespace rename. :slightly_smiling_face: Can you please delete your project then? I'm creating the `fde-*` one in a PR asap. :slightly_smiling_face:
