### ISSUE TITLE
Document default "public" bucket credentials

### ISSUE THREAD

**Issue by tumido** [operate-first/support#165]
Make the datacatalog's default bucket public by telling the credentials

> This has to be fixed upstream. I don't think there's anything we can do about it. We can warn users though.
> 
> /kind documentation
> /sig user-experience

What about creating a bucket with public credentials (playpen bucket) for now (username: `operatefirst`, password: `operatefirstzero` that anyone can use to at least test pipelines, maybe with data that can be public or also just trying to learn about elyra and pipelines while upstream issue is solved?

_Originally posted by @pacospace in https://github.com/operate-first/support/issues/155#issuecomment-808303299_

**Comment by TreeinRandomForest** [comment]
@tumido this would be great! we are testing pipelines with synthetic (artificially generated) data and having a public bucket would be very convenient while the bug gets fixed upstream

**Comment by Shreyanand** [comment]
@tumido Do we already have a public bucket or is there an ETA on this one?

**Comment by tumido** [comment]
We don't have a public bucket per se, we have a bucket with credentials we don't care if they leak though. Something like `DH-PLAYPEN`. :slightly_smiling_face: 

It's not documented yet, but it's available:

Bucket name: `opf-datacatalog`
Access Key: `v3FnruQ78kfeULDjejUB`
Secret Key: `kJiDiHXncLJOXbaL7Zeb5Ok+gkLt9sWIa1rWAJa0`
Endpoint:
- `s3.openshift-storage.svc:443` or `https://s3.openshift-storage.svc` internally
- `https://s3-openshift-storage.apps.zero.massopen.cloud/` externally

**Comment by HumairAK** [comment]
Creds in this PR: https://github.com/operate-first/apps/pull/1273

**Comment by HumairAK** [comment]
You guys can start moving data to this bucket, will aim to get it set up with trino etc. tomorrow

**Comment by HumairAK** [comment]
public bucket added to trino
> Users will move data from backup bucket to new bucket
> Copy dashboards over to use new catalog 

I'll leave this portion to you guys, once done and confirmed let me know -- I'll remove the old catalog.

**Comment by codificat** [comment]
I just found this issue while searching for details about the "public" bucket, and thought I'd add a note here to mention that I found the credentials documented here: https://www.operate-first.cloud/apps/content/odh/trino/access_public_bucket.html

It's unclear to me if there is more to be done in this issue though, so I will not close it
