### ISSUE TITLE
Access to operate first cluster for SDAP and MSLSP data 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [operate-first/support#167]
### Questionnaire

1. **Team name**:

    sdap_mslsp

2. **Desired namespaces**:

    sdap

3. **Users needing access**:

    loubrieu@jpl.caltech.edu (thomas loubrieu)
    nchung@jpl.caltech.edu (nga chung)
    wphyo@jpl.caltech.edu (wai phyo)

    Note that if you are looking for access to the MOC `zero` cluster, you will first need to log in to the [console][5] using SSO (any Gmail account will work). Doing so will create your user. Your `username` will be the e-mail address you use. Please provide us this value. If this is sensitive, then please reach out to an Operate-First team member and directly message them your username. All this information is encrypted and stored in git.

4. **Target cluster**:

    Operate First

5. **Team or maintainer owned GPG key fingerprint along with a keyserver** (OPTIONAL):

    We store all OCP `groups` in git. Sometimes this info can be considered confidential, for example if the usernames in a `group` are e-mail addresses. To keep this information secure, these manifests are stored as [SOPS][6] GPG encrypted files. [Here][7] is an example of such a file. Your team will also have a similar OCP `group` file in that repo. If you or your team would like to be able to decrypt your team's encrypted OCP `group` then you can provide a GPG key that we could also include as part of the encryption procedure. If you already have such a key prepared, please provide it here. For example: `0508677DD04952D06A943D5B4DC4116D360E3276` available from keys.gnupg.net

---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the [docs/onboarding_to_cluster.md][4] guide.

[1]:https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
[2]:https://github.com/operate-first/apps/tree/master/cluster-scope/base/namespaces/
[3]:https://github.com/operate-first/apps/tree/master/cluster-scope/overlays
[4]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md
[5]:https://github.com/operate-first/apps/tree/master/cluster-scope/overlays/moc#available-clusters
[6]:https://github.com/mozilla/sops
[7]:https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/common/groups/thoth.enc.yaml

**Comment by 4n4nd** [comment]
@tloubrieu-jpl can you please give us a small description of your project?

**Comment by larsks** [comment]
@4n4nd these folks have been invited to use the cluster by the MOC. They're setting up some data processing involving Solr and Cassandra.

**Comment by 4n4nd** [comment]
Cool cool, I'll just add this description:
`Data processing of HDF and NetCDF files involving Solr and Cassandra`

**Comment by larsks** [comment]
@tloubrieu-jpl you should be all set! If you have any questions about this cluster, you can open a new issue [in this repository](https://github.com/operate-first/support/issues/), or you can drop by the `#support` channel in our public slack workspace. You can join the slack workspace by following [this link](https://join.slack.com/t/operatefirst/shared_invite/zt-o2gn4wn8-O39g7sthTAuPCvaCNRnLww(.
