### ISSUE TITLE
notebook content of an image deployed on JH is incorrect

### ISSUE THREAD

**Issue by martinpovolny** [operate-first/support#17]
When deploying a Thoth-built image to OpenShift 4 into JH then the notebooks from the source repository are not present.

This is a placeholder, before I figure out where to put the bugreport of figure a problem on my side.

**Describe the bug**

While experimenting with: https://github.com/operate-first/odh-moc-support/issues/2 I have successfully built an image.
The image is here: https://quay.io/repository/martin_povolny/colaboratory?tab=history

The image is correctly exposed to JH using an image stream and is available in the drop-down menu in when starting a Host in JH.

However in the image I do not see the notebooks: 

![jh-missing-image-2020-11-10_10-12](https://user-images.githubusercontent.com/51095/98653428-4efb4780-233d-11eb-81b3-eeb49a3c1b61.png)

When I restart the Host, date-time named directories are being added. When I work in the instance, my stuff is preserved. However the content of the repo that I built from does not appear anywhere.

This is the source repo that I used: 

https://github.com/martinpovolny/colaboratory

When I tried running the image locally:
`podman run -p 8080:8080 quay.io/martin_povolny/colaboratory:latest  start-singleuser.sh --ip="0.0.0.0" --port=8080`

Then opened http://127.0.0.1:8080/?token=a.... I got what was expected:

![jh-local-2020-11-10_10-16](https://user-images.githubusercontent.com/51095/98653811-c9c46280-233d-11eb-8cc8-a516cdfe0bf4.png)

So the files are present in the image.

**To Reproduce**

Following the steps in https://github.com/operate-first/odh-moc-support/issues/2 (I am actually trying to write a HOWTO) got me to this situation.

**Expected behavior**

A running jupyterhub with the correct data from users repo is what I expect.

**Additional Info**

I have tried to delete the PV and PVC and start a new host in JH. It did not help.

FYI: @harshad16, @tumido

**Comment by martinpovolny** [comment]
I have had the same problem with another image that I tried -- the cathegorical encoding notebook: quay.io/aicoe/categorical-encoding:v1.0.0

This image is built using the same process (same s2i build image and process).

On the other side when I tried another image:
`docker-registry.upshift.redhat.com/aicoe-notebooks/insights-configuration-files-analysis:latest`
It worked for me.

Please, note that to work with the later image one needs to add SSL CA cert for RH IT to the OCP4 cluster. Download the CA Cert first and then:

```
oc create configmap registry-cas -n openshift-config --from-file=docker-registry.upshift.redhat.com=/home/martin/Downloads/RH-IT-Root-CA.crt
oc patch image.config.openshift.io/cluster --patch '{"spec":{"additionalTrustedCA":{"name":"registry-cas"}}}' --type=merge
```

Image stream can be created from the command line using:
```
oc import-image insights-config2 --from='docker-registry.upshift.redhat.com/aicoe-notebooks/insights-configuration-files-analysis:latest' --confirm --insecure
```

but one need's to add the label to have it picked up by JH.

Also note that to have JH update it's list of images the JH pod needs to be killed (and restarted).

**Comment by harshad16** [comment]
Following through the issue and while trying to recreate, the same issue is hit if the assemble script in aicoe/s2i-custom-notebook is not executed properly. This can happen when the `--scripts-url` is not initialized in the s2i build process, the s2i-custom-notebook requires the `--scripts-url="image:///opt/app-root/builder"` to be set. 
As we are using the aicoe-ci tool to do the build, the scripts-url can be set via the configuration file of aicoe-ci. 
``` .aicoe.yaml
...
build:
  build-source-script: <value> 
...
```
`build-source-script` can be set in the .aicoe.yaml file. 

Some of these details are missing from aicoe-ci and s2i-custom-notebook will update them in the documentation.
@martinpovolny  can you please update the key in [here](https://github.com/martinpovolny/colaboratory/blob/01481a603e58973dd0a3a5ec4f9f14813d922bc5/.aicoe-ci.yaml#L6) to `build-source-script` and recreate the image. This should hopefully fix the issue.

**Comment by 4n4nd** [comment]
@martinpovolny did the fix work?

**Comment by martinpovolny** [comment]
Yes it did. I applied it in the PRs mentioned above: ^^^

**Comment by tumido** [comment]
@martinpovolny was this issue resolved, can you please verify?

**Comment by 4n4nd** [comment]
I think we can close this issue for now and if @martinpovolny is still facing issues, we can reopen it
