### ISSUE TITLE
User support: JupyterHub hardware requirements

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/support#172]
### Questionnaire

1. **User details**:
izimmerm

2. **Desired resource change**:
I currently have a 2GiB PVC, but would like to request 8GiB. This is in order to avoid an error in spawning JH at [https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/hub/spawn/izimmerm@redhat.com](https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/hub/spawn/izimmerm@redhat.com.
)

CC @tumido

**Comment by tumido** [comment]
On it! :+1:

**Comment by tumido** [comment]
Original issue tracked upstream: https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/issues/107

**Comment by durandom** [comment]
@isabelizimm did you check your PVC usage and quota? 
Maybe in the Grafana Dashboard?

**Comment by isabelizimm** [comment]
Is there an easy way to get to Grafana for this PVC? It does not look like it is enabled when I look at the ODH dashboard when logged in. 
Or maybe a better question is, is there a self-service way to tell if I hit this limit again?

**Comment by 4n4nd** [comment]
@isabelizimm We do have a grafana dashboard available where you can check your PVC usage ([link](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/YuYfkHYMk/jupyterhub-usage?orgId=1)). You should be able to select your user id and it should show you your PVC, CPU and Memory usage.

**Comment by 4n4nd** [comment]
A little more self service way would be checking the usage in your notebook terminal with a cli command.
For example, you can run `df -h /opt/app-root/src` and it would show you the disk usage.

**Comment by isabelizimm** [comment]
Hello!! I seem to have hit my limit again... am I able to request upgrade to 16Gi?

**Comment by HumairAK** [comment]
@isabelizimm the pvc was increased to 16Gi

**Comment by tumido** [comment]
@isabelizimm I think you want to cleanup your pipenv cache. It's consuming 8Gi of your storage now. Just remove it :wink: 

```
[1000950000@jupyterhub-nb-izimmerm-40redhat-2ecom ~]$ du -hc --max-depth=1 .
2.3M    ./.npm
512     ./.config
221M    ./.pyenv
36M     ./.local
45M     ./mailing-list-analysis-toolkit
254M    ./.flair
92M     ./.keras
8.0M    ./.virtualenvs
8.3G    ./.cache
25K     ./.jupyter
1.4M    ./.ipython
512     ./.kube
0       ./.ssh
215M    ./ocp-ci-analysis
0       ./.ipynb_checkpoints
5.5K    ./.virtual_documents
9.1G    .
9.1G    total

[1000950000@jupyterhub-nb-izimmerm-40redhat-2ecom ~]$ du -hc --max-depth=1 .cache
6.0K    .cache/pip-tools
22K     .cache/fontconfig
27K     .cache/matplotlib
0       .cache/yarn
38K     .cache/black
24M     .cache/jedi
63K     .cache/python-entrypoints
528M    .cache/pre-commit
7.7G    .cache/pipenv
684K    .cache/huggingface
8.3G    .cache
8.3G    total
```

If you want, you can delete the whole `.cache` directory, nothing bad is gonna happen.
