### ISSUE TITLE
opf zero cluster network issue cause CI connection break with PyPI

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#173]
**Describe the bug**
we have a CI which is currently running on the operate-first cluster. There is a task that tries to connect with upload.pypi.org and the connection is being timed out each time
we have tested this in a different environment and seem to have no issues.

```
+ twine upload dist/jupyterhub_singleuser_profiles-0.2.0-py3-none-any.whl dist/jupyterhub-singleuser-profiles-0.2.0.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading jupyterhub_singleuser_profiles-0.2.0-py3-none-any.whl

  0%|          | 0.00/238k [00:00<?, ?B/s]
  0%|          | 0.00/238k [39:17<?, ?B/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```
**Expected behaviour**

Should not have any issues.

Related-to: https://github.com/thoth-station/thoth-application/issues/1113

**Comment by harshad16** [comment]
The working is going on this front in here: https://github.com/CCI-MOC/ops-issues/issues/224

**Comment by goern** [comment]
@tumido Can this be closed, as the upstream issue is closed?

**Comment by tumido** [comment]
I have no idea.. @harshad16 said yesterday he'll check on this. When he says it works properly than it really works and we can close it :slightly_smiling_face: 

https://github.com/CCI-MOC/ops-issues/issues/224#issuecomment-860812054

**Comment by harshad16** [comment]
Thanks @tumido , i tested it.
The issue is fixed :heart: 
closing the issue
