### ISSUE TITLE
Deploy KFServing on Operate First

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#174]
**Is your feature request related to a problem? Please describe.**

As Data Scientist,

I want to deploy my model using KFServing.

**Describe the solution you'd like**
Deploy KFServing, report it back upstream to ODH: https://github.com/opendatahub-io/manifests/issues/63

**Describe alternatives you've considered**

**Comment by tumido** [comment]
Please use [General cluster-scoped resource request](https://github.com/operate-first/support/issues/new?assignees=&labels=onboarding&template=request_cluster_resources.md&title=) template next time :wink: 

I'll try solving this as part of the Kubeflow redeploy/update for Service Mesh. Will keep you posted. Would you be available to test the deployment on a different cluster once I make it ready? :slightly_smiling_face:

**Comment by pacospace** [comment]
> Please use [General cluster-scoped resource request](https://github.com/operate-first/support/issues/new?assignees=&labels=onboarding&template=request_cluster_resources.md&title=) template next time 
> 

Sorry @tumido :/ I will for sure!!

> I'll try solving this as part of the Kubeflow redeploy/update for Service Mesh. Will keep you posted. Would you be available to test the deployment on a different cluster once I make it ready?

Yes would be happy to help, we can try deploying one TF model :)

**Comment by pacospace** [comment]
cc @moficodes

**Comment by pacospace** [comment]
hey @moficodes do you have any update from ODH side? :)

**Comment by pacospace** [comment]
Any update on this issue?

**Comment by moficodes** [comment]
sorry for the delay in reply. My github notification is all sorts of busted. 

Havent had any direct communication with ODH in a few weeks. Trying to set more of a recurrent event. 

@pvaneck on our side has been doing some debugging kfserving on openshift. Will see where he is at right now.
