### ISSUE TITLE
A project to automate onboarding

### ISSUE THREAD

**Issue by rob-baron** [operate-first/support#177]
### Questionnaire

1. TARGET CLUSTER: zero

2. TEAM NAME:  moc-acct-mgt

3. PROJECT NAMES:  moc-acct-mgt

4.  LIST OF USERS: knikolla@bu.edu, robbaron@bu.edu

5. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by rob-baron** [comment]
This project requires permissions to create and modify and delete users/projects/quotas across the cluster.

**Comment by durandom** [comment]
@rob-baron do you have a link to a codebase and/or description of what that project would be doing?

**Comment by msdisme** [comment]
Perhaps it would be helpful if I gave some context.  For a variety of reasons, the MOC (and eventually the NERC) have requirements for onboarding.  Some of these include: 

- Tracking users and usage against funding mechanisms (something we currently do poorly) and across multiple services like ceph, openshift, openstack etc. which keep their information in different ways. 
- Ability to scale the process to support large numbers of users
- ability to ensure that EULA's have been seen and agreed to by the user (this goes to things like sharing data)

As we are in a state where the only 'working' OCP 4.x cluster is the zero cluster Rob wants to use it to test our code so that once the MOC OCP 4. x cluster is available we are in a better place to enable onboarding there. 

Longer term, for Operate First Projects to tie into the NERC production service we will likely have similar requirements (TBD) that we'll want to create around common onboarding, offboarding etc.

**Comment by durandom** [comment]
@rob-baron @msdisme thanks for the context. 

All three bullet points are useful for all op1st environments as well. 

1. Can we break it into smaller chunks, like starting with user- and resource tracking? 
2. Is there a public codebase already

**Comment by msdisme** [comment]
@HumairAK That is a good point - I think we've continued thinking of this cluster as a staging cluster not internalizing that it is being used in a different way.    As part of the longer term discussion about onboarding/offboarding I mention above I think the tracking in gitops is going to be a really cool requirement to add to the work around onboarding/offboarding and connecting to the systems that are used by Research computing groups (which is not to say our heads won't explode while we figure it out.)

**Comment by tumido** [comment]
@rob-baron @msdisme first of all, welcome! I hope we can find a way to collaborate on this and join our efforts.

Question: How does this onboarding request differs from https://github.com/operate-first/support/issues/169 and @rob-baron's `reporting-5` namespace? Based on what Rob has told me yesterday this should be the same project, is that correct assumption?

**Comment by tumido** [comment]
Also, @larsks or anybody, can we get some more insight how this project relates to the Curator project and the Curator cluster we've recently deployed via our ACM?

**Comment by rob-baron** [comment]
@tumido 

This project is part of our automation for our onboarding process.  We currently have a couple of large classes of students use the MOC ever semester, as well as professors with an ever changing list of students.  As we are 4 people, we cannot afford to spend days with everyone who needs access with potentially multiple services (1 OpenStack cluster, 1-3 OpenShift clusters, ... ). We have adopted more of a self service type model for this.

The moc-reporting (reporting-5) is about reporting on the usage of the systems so that we can do longer time scale analysis on all of our cloud services, including invoicing.

**Comment by durandom** [comment]
I think this is applicable to the Operate First environment as well and we should use our env to prototype it.
Do you have more written documentation on the requirements for this?

**Comment by msdisme** [comment]
The current project was to get us to parity for an google forms based solution for  openstack and some extensions for OpenShift and quota management (goal is to make things as self service as we can.)   My expectation is that the NERC will have a fair bit of additional requirements as will Operate first which may lead to a rethink of the original work.  We had been using Taiga to capture requirements and I will take a pass to make sure it is semi-coherent before you guys waste time on it and will then put the link here (semi-realistic timeframe is Monday April 5.

**Comment by durandom** [comment]
@msdisme @knikolla any updates on the requirements and how we could join forces on automating onboarding?

**Comment by msdisme** [comment]
We are working to embed Kristi with the NERC team to understand their requirements.    If that is not possible in the next sprint (starting Wednesday) than we should explore having him work with operate first first (I wanted to say that!).  I hope to have more details later today.

---
Michael Daitzman (He/Him)
***@***.***
cell:978-201-9965



From: Marcel Hild ***@***.***>
Date: Wednesday, April 7, 2021 at 7:40 AM
To: operate-first/support ***@***.***>
Cc: Daitzman, Michael S ***@***.***>, Mention ***@***.***>
Subject: Re: [operate-first/support] A project to automate onboarding (#177)

@msdisme<https://github.com/msdisme> @knikolla<https://github.com/knikolla> any updates on the requirements and how we could join forces on automating onboarding?
