### ISSUE TITLE
Error connecting to s3 from kfp

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/support#179]
**Describe the bug**
We see an error connecting to s3 from kfp. 

**To Reproduce**
1. Get https://github.com/Shreyanand/ocp-ci-analysis/tree/master/notebooks/data-sources/TestGrid/Elyra_test in your env
2. Open the https://github.com/Shreyanand/ocp-ci-analysis/blob/master/notebooks/data-sources/TestGrid/Elyra_test/test_public_bucket.pipeline to check the pipeline
3. Use this command to set the kfp runtime: 
```
elyra-metadata install runtimes --display_name="test_public_bucket" --api_endpoint="http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/pipeline" --engine=Tekton --cos_endpoint=https://s3-openshift-storage.apps.zero.massopen.cloud/ --cos_username=v3FnruQ78kfeULDjejUB --cos_password=kJiDiHXncLJOXbaL7Zeb5Ok+gkLt9sWIa1rWAJa0 --cos_bucket=opf-datacatalog
```
4. Click on run button and see the [pod logs in the UI](http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/pipeline/#/runs/details/3dbbfbc4-6aa8-4afa-bd8b-97df3ff5a454). You should see a connection error similar to the screenshot attached.

**Expected behaviour**
The pipeline should run without any errors.

**Screenshots**
![Screenshot from 2021-03-30 12-20-44](https://user-images.githubusercontent.com/8916126/113036199-9df12e80-91b1-11eb-88a8-d5db2f2883a4.png)

**Additional context**
We think that the notebook is able to connect to the bucket because if you look at the contents of the bucket, we see objects named by the pipeline, for e.g., "test_public_bucket-0330161933".

**Comment by Shreyanand** [comment]
cc @MichaelClifford @oindrillac @pacospace @4n4nd @tumido

**Comment by 4n4nd** [comment]
@Shreyanand Can you try changing the bucket endpoint to `https://s3-openshift-storage.apps.zero.massopen.cloud:443`?

It looks like the pipeline is using port 80 and using `http`

**Comment by MichaelClifford** [comment]
@4n4nd I got a similar error using a different set of notebooks but same op1st bucket. I also changed the endpoint like you suggested above, but still get the following slightly different error:

![image](https://user-images.githubusercontent.com/4494906/113052789-8bf19a80-9175-11eb-8655-d959cd35a8a3.png)

**Comment by 4n4nd** [comment]
@oindrillac no updates yet :(
Do you know if the issue persists with other buckets as well?

**Comment by oindrillac** [comment]
@4n4nd we tried this on a [public bucket ](https://github.com/operate-first/support/issues/165#issuecomment-810337239)as the kfp pipelines [was exposing bucket creds](https://github.com/operate-first/support/issues/155). We did not see this error with the [previous bucket](https://github.com/aicoe-aiops/ocp-ci-analysis/issues/162#issuecomment-799707059). Is there another public bucket we can try this on, whose creds we dont care if they get leaked though?

**Comment by 4n4nd** [comment]
I can make a temp public bucket that we can use for testing

**Comment by oindrillac** [comment]
Tried it with the temp bucket, and the [job](http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/pipeline/#/experiments/details/efafd236-b9d3-4701-baf4-c32c4cc02b8f) did not seem to run because of resource limitations

![image](https://user-images.githubusercontent.com/32435206/113181996-653c6e00-9220-11eb-9321-b011f75cdfbd.png)

Upon reducing the resource reqs and allocating low cpu to the notebooks, we see the same bucket [error](http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/pipeline/#/experiments/details/efafd236-b9d3-4701-baf4-c32c4cc02b8f)

![image](https://user-images.githubusercontent.com/32435206/113182155-961ca300-9220-11eb-854c-6a569777e6c1.png)

**Comment by 4n4nd** [comment]
I was able to run the pipeline using the internal endpoint `http://s3.openshift-storage.svc/`
Another issue was that different endpoints are being used in different parts of the pipeline.

**Comment by oindrillac** [comment]
We were able to get the pipeline working with the updated endpoint.
This is a part of our efforts in https://github.com/aicoe-aiops/ocp-ci-analysis/issues/124
