### ISSUE TITLE
Kibana in yellow state

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/support#181]
**Describe the bug**
https://kibana-openshift-logging.apps.zero.massopen.cloud/app/kibana is in yellow state and non functional.

I think this is because of the recent power outage.

**Comment by HumairAK** [comment]
I can take a look when I'm back this Wed, if no one else gets a chance to.

**Comment by tumido** [comment]
Sold to @HumairAK for.. _free_

![](https://media.giphy.com/media/QW3z72R8ALbqifnOHq/giphy.gif)

**Comment by HumairAK** [comment]
I had to wipe the `.kibana` indices again, same issue as described [here](https://github.com/operate-first/SRE/issues/98#issuecomment-788998681). Kibana is back up.
