### ISSUE TITLE
Superset - cannot create new Tables - blank page

### ISSUE THREAD

**Issue by xtuchyna** [operate-first/support#184]
**Describe the bug**
Currently there is no action available for `Tables` section on Superset - just a blank page with no records showing.

**To Reproduce**
1. Go to http://superset-opf-superset.apps.zero.massopen.cloud/
2. Go to Sources -> Tables
3. See unavailable option to create new table

**Screenshots**
![image](https://user-images.githubusercontent.com/46632404/113182748-8c606300-9253-11eb-8c92-9456e6ffebd7.png)

**Comment by tumido** [comment]
Superset is not properly connected to Hive. We will probably need a separate Hive cluster actually. So far we've been using the "demo" one packaged with data catalog...

**Comment by HumairAK** [comment]
@hemajv this is resolved now right?

**Comment by hemajv** [comment]
@HumairAK yes, we can close this out!
