### ISSUE TITLE
SLI / Status Email

### ISSUE THREAD

**Issue by durandom** [operate-first/support#187]
The Thoth project sends out nice summaries of SLIs and uptime reports, courtesy @pacospace 

1. Do we have similar metrics available in Prometheus/Grafana Dashboards
2. Can we re-use the Thoth workflows to produce such an email and send it to the op1st users mailing list?

![image](https://user-images.githubusercontent.com/161888/113323387-30aade00-9316-11eb-8dbe-26dc7e6e9668.png)

**Comment by HumairAK** [comment]
> Do we have similar metrics available in Prometheus/Grafana Dashboards

Hrm the metrics above don't seem analogous to devops / SRE procedures. I would think we would want to take more from how IDH does their uptime reporting (potential for some downstream collaboration here?). Maybe we should look to do something similar? We have some uptime metrics already (@hemajv  has created these). 

What would be also interesting is if we can also throw in number of users and projects, as we are continuing to onboard more every week.

We had also recently discussed making cluster metrics more visible, maybe we can report some weekly aggregates on things like compute resources trends/usage (i.e. showcase how much stress we're putting on the different clusters, not sure if this is interesting though). 

We could also throw in site statistics, unique weekly visits etc. 

I think most of this information is already there in grafana to some capacity (save for site analytics).

@durandom -- is this what you were thinking of? Or have I missed the mark entirely :)

**Comment by anishasthana** [comment]
We definitely had a similar report internally a while back. I'm happy to dig up the code and share those if you'd like. We have plans to do something similar again in the future with Argo. We've almost finished polishing up our jupyterhub SLO's, so that would actually be a nice place to start. i.e how are we actually performing vs our targets. 

Usage numbers are harder to determine. With things like Jupyterhub or Kafka it's easy to determine number of users, but as far as I am aware there isn't really a metric for # of users in OpenShift.

**Comment by HumairAK** [comment]
Hrm maybe we can identify some common elements, both teams would like to report on, and collaborate on this. Are there any links/docs you can forward us?

**Comment by anishasthana** [comment]
https://gitlab.cee.redhat.com/data-hub/dh-monitoring/-/tree/master/availability-metrics-job contains the job we had previously been running. As for SLOs, those actually already exist in your docs :-)

**Comment by durandom** [comment]
Yes to all of the above. Let's start simple though:

> We have some uptime metrics already (@hemajv has created these).

Let's get those into an email report. That's our MVP.
Is it those?
https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/r7WqgaBMk/operatefirst-availability

@pacospace what do we need to get those converted into percentage over time and into an email report?

**Comment by pacospace** [comment]
> Yes to all of the above. Let's start simple though:
> 
> > We have some uptime metrics already (@hemajv has created these).
> 
> Let's get those into an email report. That's our MVP.
> Is it those?
> https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/r7WqgaBMk/operatefirst-availability
> 
> @pacospace what do we need to get those converted into percentage over time and into an email report?

If you plan to reuse thoth workflow [1]:

- [ ] create a class for metrics specific to Operate First, we can reuse the template for User-API availability.

we consider avg_over_time(up[INTERVAL]) for User API instance.

where:
- INTERVAL can be configured to what you need, ~1, 7, 30 days. (depends on how much Thanos keeps data)

- [ ] add env variable to distinguish between Operate First and Thoth workflow run.
- [ ] crate an application for ArgoCD to deploy

It is 3 PRs and we can run it in the same environment where we run SLO reporter internally.

[1] https://github.com/thoth-station/slo-reporter

**Comment by hemajv** [comment]
> Let's get those into an email report. That's our MVP.
> Is it those?
> https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/r7WqgaBMk/operatefirst-availability

yes, these are the basic uptime metrics we have for the opf apps/services. I can try following the steps @pacospace mentioned to replicate the thoth workflow

**Comment by durandom** [comment]
@hemajv can you add graphs over time to that dashboard? So that, if we zoom in and out via grafana, we see 

* `avg_over_time(up[INTERVAL])` as a percentage
* `up` as a line (0/1) to see outages

**Comment by hemajv** [comment]
We are also working on adding recording rules to aggregate all the `up` metrics: https://github.com/operate-first/SRE/issues/82
This will help in having an `overall_status` metric which aggregates the uptime metric of all opf applications
