### ISSUE TITLE
sdap namespace access

### ISSUE THREAD

**Issue by tloubrieu-jpl** [operate-first/support#188]
**Description**

Hello, I am accessing the operate first cluster for the first time after our sdap namspace is set up (see ticket https://github.com/operate-first/support/issues/167)

But I don't see a project related to that and I cannot create a project. I can not open a terminal either (forbidden).

My login is loubrieu@jpl.caltech.edu

I was expecting to find a project I can use but maybe I am not following the right procedure. Thanks for your help.

**Additional context**

Screenshot of the console I'm seeing

![image](https://user-images.githubusercontent.com/60993872/113387055-62389f00-9340-11eb-88ce-5732092f3411.png)

**Comment by durandom** [comment]
cc @4n4nd 
could it be that https://github.com/operate-first/apps/pull/447 is not applied to the zero cluster?

https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/zero/kustomization.yaml

**Comment by 4n4nd** [comment]
@durandom I forgot to create an [argocd app](https://github.com/operate-first/argocd-apps/tree/main/envs/moc/zero) for this project. That's why the manifests were not applied

**Comment by 4n4nd** [comment]
@durandom we did not need a argocd app for this, the manifests were not added to their respective kustomizations. I have created a PR for the fix https://github.com/operate-first/apps/pull/475
