### ISSUE TITLE
Adding support for Jupyter{Book} integration

### ISSUE THREAD

**Issue by jappavoo** [operate-first/support#189]
As requested moving this from Slack to an issue.

To enable a Jupyter{book} to point to operate first JupyterHub resources requires the following support as per their documentation (https://jupyterbook.org/interactive/launchbuttons.html).

Adding this support would allow Operate First users to both author and use interactive textbooks in the form of Jupyter{Book}s.  These books incorporate both static web content and integrated Jupyter Notebooks.  The author of the book can point the book at an appropriately configure JupyterHub service to have readers (with accounts) use that service to transparently run the interactive content.  

From my reading of the docs the following is required on the JupyterHub side:

"On your JupyterHub server, you need two dependencies installed:
To clone the notebook with the launch link, the server needs nbgitpuller.
To open myst-markdown as notebooks, the server needs jupytext>=0.16.
You can add the following line to your DockerFile:
RUN pip install jupytext nbgitpuller"

jupyterbook.orgjupyterbook.org
Launch buttons for interactivity
Launch buttons for interactivity Because Jupyter Books are built with Jupyter notebooks, you can allow users to launch live Jupyter sessions in the cloud direc

**Comment by 4n4nd** [comment]
@harshad16 I think this is something we could add in the thoth base images so it is available for all images that are built from that

**Comment by jappavoo** [comment]
Is there anything else I can do to help?  Also if I would like to have a custom binary is there a process for requesting the creation of a new image?

**Comment by harshad16** [comment]
This seems like a good inclusion to be made.
we can start with a featured image, try it out if it liked then we can move that into the base image.

> Is there anything else I can do to help? 
surely you can help us with the checking of this feature if you have already used it.

> Also if I would like to have a custom binary is there a process for requesting the creation of a new image?

we don't have a proper process for requesting new images. everyone can open a request like this. 
The operate-first was more dedicated towards the developers, and the jupyterhub is from the opendatahub. so we rely on the images from there. 

we have a process with which users can build the custom image with python packages 
https://www.operate-first.cloud/users/data-science-workflows/docs/create_and_deploy_jh_image.md

This can't be used for the custom binaries like DNF, yum, RPMs install, for that users have to follow from the scratch.
 -  The https://github.com/thoth-station/s2i-minimal-notebook  can be used to create custom binaries
 -  To get the custom image into the https://github.com/operate-first/apps/tree/master/odh/base/jupyterhub/notebook-images

**Comment by 4n4nd** [comment]
Thanks @harshad16 :+1: 

> we can start with a featured image, try it out if it liked then we can move that into the base image.

This sounds like a good idea

**Comment by harshad16** [comment]
once the pr https://github.com/operate-first/apps/pull/476 is merged.
there would be `jupyter-book` image in the jupyterhub
if you can verify that image for us we can install this to the base image , so it available all the images.

**Comment by durandom** [comment]
cc @TreeinRandomForest

**Comment by jappavoo** [comment]
Thanks everyone.  I was able to verify that the JupyterBook functionality worked with respect to being able to point my book at the operate first JupyterHub image and it automatically cloned the book repo and ran the notebooks.    Now I just have to work on creating an image that has my custom binaries and kernels.  Thanks again!

**Comment by harshad16** [comment]
This might help with the creation of that image https://www.operate-first.cloud/users/data-science-workflows/docs/create_and_deploy_jh_image.md


**locally** 
you can use this image for the base image `quay.io/thoth-station/s2i-custom-py38-notebook:latest` and details about it: https://github.com/AICoE/s2i-custom-notebook.
all one has to do is put there work in this format https://github.com/aicoe-aiops/project-template
and use the base image to package it into a [s2i](https://github.com/openshift/source-to-image) based image 

for testing the image: `podman run -it -p 8888:8888 <image> jupyter lab`

please let us know if you need any further information.
