### ISSUE TITLE
[TASK] Request for the Prometheus connection details.

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#19]
**User story**
We thoth-devops, would like to update our gitops related manifest file with correct Prometheus details corresponding to the moc cnv cluster, so that we can have our deployment can send metrics successfully to the Prometheus endpoint and push-gateway endpoint.

**Additional context**
Project Thoth components require endpoint to send metrics and to store them.

**Acceptance Criteria**
- [ ] Provide Prometheus URL and push-gateway URL.
- [ ] Provide Thanos certs.

**Linked epics / issues**
Related-To: #16

**Comment by 4n4nd** [comment]
@harshad16 we are still working on setting up monitoring. Currently we have set up Prometheus, we still need to add Thanos and a Push-gateway. 
This might take a little time :(

**Comment by tumido** [comment]
@harshad16 @4n4nd do we have the docs for this already available somewhere?

Isn't adding the monitoring rbac aggregation to the namespaces sufficient for now. We still need to have some docs on the ServiceMonitors, right?

+ The Push gateways is still not available 

linking https://github.com/operate-first/apps/issues/193

**Comment by 4n4nd** [comment]
@tumido @harshad16 was able to set up monitoring for the thoth components (https://github.com/operate-first/apps/pull/159), but we still need documentation on how to add  the monitoring rbac and servicemonitors.

>The Push gateways is still not available

as for the Push Gateways, I think thoth-station has their own deployment. I will add something about this to the Prometheus onboarding doc that I write.

**Comment by harshad16** [comment]
Thanks for all the help.
