### ISSUE TITLE
Request onboard to the OF Zero cluster to deploy hpc-workload-generator

### ISSUE THREAD

**Issue by phpHavok** [operate-first/support#190]
## Questionnaire

1. **Project description**:

The project I will deploy is called hpc-workload-generator. Its purpose is to allow users to generate arbitrarily specified usage patterns (such as CPU load and RAM usage at specific time intervals) in order to mimic what an HPC job *might* do. The system should be sending Prometheus node_exporter metrics so that a monitoring expert can verify the the monitoring framework is picking up the load generated by the program. The whole purpose is to allow a granular monitoring framework to be better tested.

2. **Target cluster**:

Zero cluster

3. **Team name**:

uky-redhat

4. **Desired project names**:

hpc-workload-generator

5. **Users needing access**:

EDIT: I'll login using Mass Open Cloud SSO via the University Sign-ons option through UKY:

jdch223@uky.edu

6. **GPG Key** (OPTIONAL)

N/A

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by phpHavok** [comment]
Make edits to the "users needing access" section. I didn't realize MOC SSO was a sign-on option, but will use that.

**Comment by 4n4nd** [comment]
Awesome! Thanks for the issue, I'll create the onboarding PR as soon as I come back to work.

**Comment by 4n4nd** [comment]
@phpHavok I'll add a `uky-` prefix to the namespace name

**Comment by 4n4nd** [comment]
@phpHavok you should now have access to the namespace `uky-hpc-workload-generator` on the zero cluster. You can login [here](https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/uky-hpc-workload-generator).

**Comment by phpHavok** [comment]
@4n4nd Thanks very much! I logged in successfully but have a permissions error. It looks like my institution picks my alias email when I sign in through CI Logon (I wasn't aware of this until now):

```
projects.project.openshift.io "uky-hpc-workload-generator" is forbidden: User "jacob.chappell@uky.edu" cannot get resource "projects" in API group "project.openshift.io" in the namespace "uky-hpc-workload-generator"
````

Could you grant access to jacob.chappell@uky.edu ? Thanks so much!

**Comment by tumido** [comment]
@phpHavok I've replaced the username in the user group here: https://github.com/operate-first/apps/pull/480

Once merged it should work.
