### ISSUE TITLE
Cluster-scoped resources request for MOC Zero cluster 

### ISSUE THREAD

**Issue by eletonia** [operate-first/support#192]
### Requested actions

We would like the following cluster-scoped resources for Fybrik deployed on the MOC Zero cluster. 
@roee88 @ronenkat 

#### Resource request

Requesting these resources to be deployed:

- [CRDs](https://github.com/fybrik/fybrik/tree/master/charts/fybrik-crd/templates)
- Cluster Roles/Cluster Role Bindings:
    - [manager-auth-proxy-cr](https://github.com/fybrik/fybrik/blob/master/charts/fybrik/templates/manager-auth-proxy-cr.yaml)
    - [manager-auth-proxy-crb](https://github.com/fybrik/fybrik/blob/master/charts/fybrik/templates/manager-auth-proxy-crb.yaml)
    - [fybrik-admin-cr](https://github.com/fybrik/fybrik/blob/master/charts/fybrik/templates/fybrik-admin-cr.yaml)
    - [fybrik-admin-crb](https://github.com/fybrik/fybrik/blob/master/charts/fybrik/templates/fybrik-admin-crb.yaml)
- [Webhook Configs](https://github.com/fybrik/fybrik/blob/master/charts/fybrik/templates/webhook-configs.yaml) referencing [this](https://github.com/fybrik/fybrik/blob/master/charts/fybrik/files/webhook-configs.yaml)

### Questionnaire

1. **Team name**:       Fybrik

---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the docs [here](https://github.com/operate-first/apps/blob/master/cluster-scope/README.md).

**Comment by HumairAK** [comment]
context: https://github.com/operate-first/support/issues/41

**Comment by HumairAK** [comment]
@eletonia some of these charts are relatively heavily templated, can you tell us the helm commands to tempalte these, and which values files to use? even better if you can just direct us to the raw rendered yaml you would like for us to deploy.

**Comment by eletonia** [comment]
Hi @HumairAK 
We generated the raw rendered yaml files that we would like deployed on Operate First here: 
https://github.com/IBM/the-mesh-for-data/tree/master/samples/operate-first

Please ignore the `m4d-crd.yaml` and `m4d.yaml` files. The cluster-scoped resources we would like deployed are organized by kind into directories.

**Comment by HumairAK** [comment]
@eletonia I've made a PR https://github.com/operate-first/apps/pull/588 

Though I'm going over the cluster roles and they seem to be requesting clusterwide access for secrets [here](https://github.com/IBM/the-mesh-for-data/blob/master/samples/operate-first/clusterroles/m4d-system/m4d-proxy-cr.yaml) 

This would expose secrets belonging to other users to your team, which we would like to avoid. Can the permissions here be reduced? 

I'm not too familiar with `tokenreviews` and `subjectaccessreviews` which are requested [here](https://github.com/IBM/the-mesh-for-data/blob/master/samples/operate-first/clusterroles/m4d-system/m4d-proxy-cr.yaml). But I suspect this may also be too much access. 

@tumido @4n4nd

**Comment by roee88** [comment]
We will work on reducing rbac, we have an open issue for that. As for token review, it just allows to verify service account tokens and is part of any operator created by kubebuilder (see https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/config/rbac/auth_proxy_role.yaml) and operator-sdk (see https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/config/rbac/auth_proxy_role.yaml).

**Comment by HumairAK** [comment]
@roee88 sounds good, let us know when the rbac is reduced, and I'll update the pr to bring these resources to our zero cluster.

**Comment by roee88** [comment]
@HumairAK we're also working on https://github.com/IBM/the-mesh-for-data/issues/523 to automate sending a PR to this repo on each new tag the changes one of the cluster scoped resources. This should avoid manual work beyond reviews and would allow us to avoid having (duplicate) resources in git just for operate-first.

**Comment by eletonia** [comment]
We're also working on [this issue](https://github.com/IBM/the-mesh-for-data/issues/523) to automate sending a PR to this repo on each new tag the changes one of the cluster scoped resources. This should avoid manual work beyond reviews and would allow us to avoid having (duplicate) resources in git just for operate-first.

**Comment by eletonia** [comment]
Hi @HumairAK
We reduced our RBAC requirements and generated the raw rendered yaml files that we would like deployed on Operate First here:
https://github.com/fybrik/fybrik/tree/master/samples/operate-first 

Please ignore the `fybrik-crd.yaml` and `fybrik.yaml` files. The cluster-scoped resources we would like deployed are organized by `kind` into directories.

Sidenote: our project was renamed from `Mesh for Data` to `Fybrik`

**Comment by eletonia** [comment]
Reopened a new issue here: #370
