### ISSUE TITLE
Tune CPU reservation on thoth-backend-prod

### ISSUE THREAD

**Issue by tumido** [operate-first/support#196]
**Describe the bug**
`thoth-backend-prod` jumped up and is currently requesting and reserving for itself more than half of the cluster CPU capacity. 

currently `thoth-backend-prod` is requesting 171 CPU cores, it actually uses nearly 0 with occasional spikes.

**To Reproduce**
1. Go to [grafana query here](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/explore?orgId=1&left=%5B%22now-24h%22,%22now%22,%22opf-observatorium-thanos%22,%7B%22expr%22:%22sum(kube_pod_container_resource_requests_cpu_cores%7Bnamespace%3D%5C%22thoth-backend-prod%5C%22%7D)%22%7D,%7B%22expr%22:%22sum(kube_node_status_allocatable_cpu_cores)%22%7D,%7B%22expr%22:%22sum(rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate%7Bnamespace%3D%5C%22thoth-backend-prod%5C%22%7D%5B5m%5D))%20by%20(namespace)%22,%22hide%22:false%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
2. See error

**Expected behaviour**
Please lower the CPU requests to make it closer to the actual usage

**Screenshots**
![image](https://user-images.githubusercontent.com/7453394/114155885-44f86780-9922-11eb-85ee-738db8c6c91c.png)

**Additional context**
This will be solved by enforcing quotas

Additionally we should also set up general cluster wide alerts on drastic CPU request increases?

/cc @goern @harshad16 @HumairAK @4n4nd

**Comment by harshad16** [comment]
ack, we can have a set quota defined for all the thoth created namespaces.

out of curiosity, we have one time executable workflows running in the `thoth-backend-prod` namespace , i.e, when we have user request a single task start, completes and closes. Technically it would leave the resources which it requested once the pod is complete. 
It is blocking 171 cpu cores, or was it the highest number of cores used by it at a single instance ?

**Comment by tumido** [comment]
According to the metrics, it's blocking those CPUs. It seems to be due to CPU request on pods/deployments again. Sure, you can select quotas for your project since today. We've finalized the documentation, please coordinate that with @HumairAK

**Comment by HumairAK** [comment]
Resolved by implementation of quotas.
