### ISSUE TITLE
Feedback on onboarding_to_argocd.md

### ISSUE THREAD

**Issue by paoloantinori** [operate-first/support#197]
**Describe the bug**
I'm following the guide step by step and I've found some ambiguity.

Adding my whole list of feedback here:

1. Under the `Prerequisites` sections you can find this sentence: `Please fork/clone the operate-first/apps repository. During this whole setup, we’ll be working within this repository.` This is quite confusing since most of the page requires to operate on a different repo: `operate-first/argocd-apps`
2. Under the `Create project directories for this repository` there is a minor ambiguity: the title talks about "project directories" but the paragraph talks about "team directories" it's not obvious if I should have a directory per team or per project (looking in the other folders it seems it should be per team, with different yaml files inside that same folder for different projects.
3. Under `Create the ArgoCD Project`, the sample yaml has placeholders wrapped with different quotes: `<team-namespace-prefix>` is between single quotes, while `<cluster-name>` is between backticks
4. Under `Create the ArgoCD Project`, the explanation to identify the `<cluster-name>` is ambiguous, the value used in the other project on the repo are using `api.zero.massopen.cloud` that cannot be found at the link listed in the section.

**Comment by HumairAK** [comment]
Thanks for the feedback @paoloantinori -- all great points, I'll update the onboarding instructions as per the suggestions. 

> it's not obvious if I should have a directory per team or per project 

Project names and team names are a 1:1 mapping (with the exception of `cluster-management` and workshop projects), but I understand the confusion and will try to clear that up as well. 

 > Under Create the ArgoCD Project, the explanation to identify the <cluster-name> is ambiguous, the value used in the other project on the repo are using api.zero.massopen.cloud that cannot be found at the link listed in the section. 
 
 This portion is outdated, good catch. This will need to be updated, I think it would be better to just list the available options to alleviate confusion.

**Comment by HumairAK** [comment]
Project template also needs to have a label pointing to the global project template.

**Comment by HumairAK** [comment]
Also: https://github.com/operate-first/apps/pull/506#issuecomment-817101846
