### ISSUE TITLE
Deploy Cert Manager

### ISSUE THREAD

**Issue by goern** [operate-first/support#199]
**Is your feature request related to a problem? Please describe.**
As a User/Application Owner
I want my TLS routes to be auto-mantained
so that letsencrypt certs get renews automatically

**Describe the solution you'd like**
tbd

**Describe alternatives you've considered**
n/a

**Additional context**
This will reduce manual work. I think there is operators for this...

/kind feature
/sig user-experience

**Comment by tumido** [comment]
We're planning on bringing cert-manager back once we have upgraded Kubeflow. Cert-manager will be installed via operator and available to be used by the users.

https://www.redhat.com/sysadmin/cert-manager-operator-openshift

**Comment by tumido** [comment]
I'm gonna leave this issue open and tracking the cert-manager (this will come updated with Kubeflow soon) and use the other issue for `openshift-acme`

**Comment by tumido** [comment]
Resolved via https://github.com/operate-first/apps/pull/937
