### ISSUE TITLE
Update  Jupyter Hub spawner landing page to reflect GPU availability  

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#20]
**Description**
Not sure if this is the right place for this question.
 
Since we don't have GPU's available yet, but the UI contains the option to request one, if you select "1" GPU or any number, it will prevent the pod from spawning due to insufficient GPU's available. Should this option be removed until we have this kind of resource available? My concern is that this could be confusing/ off-putting to new users. 

Instead of removing the GPU field, could it be made into a drop down that shows the currently available GPU's? In future, when we do have them, this would also prevent people from requesting a GPU if they are all already allocated elsewhere.    

**Additional context**

![image](https://user-images.githubusercontent.com/4494906/99439132-cbb09780-28e2-11eb-99ed-311f9e92016e.png)

![image](https://user-images.githubusercontent.com/4494906/99422174-440c5e00-28cd-11eb-890c-3a7c5b4635ec.png)

**Comment by 4n4nd** [comment]
That's because there are no GPUs available on the cluster

**Comment by 4n4nd** [comment]
@vpavlin might know better

**Comment by pacospace** [comment]
@tumido @4n4nd @durandom I think this can be closed as there is a new JH UI in ODH 1.0 deployed on Operate First.

![Screenshot from 2021-02-11 16-35-03](https://user-images.githubusercontent.com/27498679/108213155-036feb00-712f-11eb-8a5c-22885e69e5ab.png)

**Comment by tumido** [comment]
Let's close it then.  Happy to close issues any time :smile:
