### ISSUE TITLE
Deploy event eventrouter or something similar to sink kubernetes events into Loki

### ISSUE THREAD

**Issue by tumido** [operate-first/support#204]
**Is your feature request related to a problem? Please describe.**
For Telemetry WG we need to be able to pair logs and events and also store events long term

**Describe the solution you'd like**
Deploy events collector/forwarder and sink it into Loki

**Describe alternatives you've considered**
n/a

**Additional context**
https://github.com/heptiolabs/eventrouter
https://grafana.com/blog/2019/08/21/how-grafana-labs-effectively-pairs-loki-and-kubernetes-events/

**Comment by HumairAK** [comment]
Let's first verify we aren't already getting this via CLO

**Comment by MichaelClifford** [comment]
FYI, from the DS side of things we are also interested in long term storage and accessibility of cluster events : )   
https://github.com/aicoe-aiops/operate-first-openshift-data/issues/15

**Comment by tumido** [comment]
@MichaelClifford that's why this issue was even created. Based on your questions we decided it's time to try to make you guys a bit happier. :smile:
