### ISSUE TITLE
On board to Hue and Superset use on Operate First

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#211]
As OpenDataHub user on Operate First,

I would likw to show managers and users of Thoth a Superset dashboard with all data relative to the use, content and status (similar to https://superset.datahub.redhat.com/superset/dashboard/17/ that we have internally). 

Therefore I need:

- [ ] public bucket where to store data accessible by Hue (credentials can be exposed in that case, no problem)
- [ ] access to Hue to create tables
- [ ] access to Superset to create dashboards 

End goal: Superset public dashboard accessible on Operate First with URL by anyone.

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/thoth-application/issues/842

**Comment by pacospace** [comment]
do we have an estimated time for this issue?

**Comment by pacospace** [comment]
@tumido @HumairAK cc

**Comment by HumairAK** [comment]
@pacospace as far as I know, we're waiting for the new ODH release which will include a lot of upgrades to superset, plus a Trino backend. The release was expected last week when we asked ODH team, but it seems to have been delayed. I'd imagine it shouldn't be more than a week or so. Once it's in, we can hopefully get @rimolive 's help and bring this in to operate first in a functioning order. I'll update the status of this issue so it doesn't continue to go unnoticed.

**Comment by pacospace** [comment]
@HumairAK thanks a lot 🍻!!

**Comment by rimolive** [comment]
I believe this one can be closed. Trino and Superset are deployed and integrated.
