### ISSUE TITLE
Quarkus Extension Registry

### ISSUE THREAD

**Issue by gastaldi** [operate-first/support#216]
## Questionnaire

1. **Project description**:

   

   Quarkus Extension Registry: This service will provide information for the Quarkus tooling about the existing Quarkus extensions. It's a Quarkus native application requiring a PostgreSQL DB backend.

2. **Target cluster**:

    

    Zero Cluster

3. **Team name**:

    

    quarkus

4. **Desired project names**:

    

    quarkus-extension-registry

5. **Users needing access**:

    

    ggastald@redhat.com

6. **Namespace Quota**

    

    QUOTA: Medium

7. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by HumairAK** [comment]
Hey @gastaldi you should have access to the requested namespace on the zero cluster here: https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/quarkus-extension-registry 

(there's a cluster upgrade in process so there may be some disruptions today).

**Comment by gastaldi** [comment]
Thank you @HumairAK! I am trying to deploy a PGSQL DB in there but I get errors like `0/9 nodes are available: 2 node(s) were unschedulable, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 4 Insufficient cpu.`. 

Should I have requested a bigger Quota? I appreciate the help

**Comment by HumairAK** [comment]
Nope, that's due to the upgrade, I'd suggest waiting until it's done.
