### ISSUE TITLE
Onboarding for new User PixelJonas

### ISSUE THREAD

**Issue by PixelJonas** [operate-first/support#220]
## Questionnaire

1. **Project description**:

Running small demo-envs and maybe a vault-instance for external secrets

   PROJECT DESCRIPTION:

2. **Target cluster**:

    TARGET CLUSTER: `Zero`

3. **Team name**:

    TEAM NAME: team-pixel

4. **Desired project names**:

    PROJECT NAMES: pixel-demos, pixel-vault

5. **Users needing access**:

    LIST OF USERS: jjanz at redhat dot com

6. ** Namespace Quota **

    

    QUOTA:
        pixel-demos: MEDIUM
        pixel-vault: MEDIUM

7. **GPG Key** (OPTIONAL)

      GPG KEY FINGERPRINT: 16787415FA4A18A006599425A5D655E1C8499F03
      KEYSERVER: keys.openpgp.org

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by HumairAK** [comment]
Hello @PixelJonas we've onboarded you as per the details provided. Can you verify that you can access the following namespaces: 

https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/pixel-demos
https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/pixel-vault
