### ISSUE TITLE
`kubeflow` resource quota required

### ISSUE THREAD

**Issue by tumido** [operate-first/support#222]
Same as: https://github.com/operate-first/support/issues/159 

Kubeflow (pipelines) reserves all the CPU

![image](https://user-images.githubusercontent.com/7453394/116713823-71f5e280-a9d5-11eb-986e-a83aab52eda8.png)

**Comment by tumido** [comment]
I've manually deleted finished pods:
```
oc delete pod --field-selector=status.phase==Succeeded  # drop no.1
oc delete pod --field-selector=status.phase==Failed  # drop no.2
```

![image](https://user-images.githubusercontent.com/7453394/116714650-43c4d280-a9d6-11eb-8fe9-b9494376aef5.png)


There's still few workflows pending and containers spawning. I'll delete those once they finish.

**Comment by oindrillac** [comment]
@tumido are we waiting on this pipeline to finish? http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/pipeline/#/experiments/details/97347293-a721-4484-a7a9-58de775b0404

I think this has run for too long, it should not have been running for this long. Seems like something weird.

**Comment by HumairAK** [comment]
Stale issue, we also currently don't have kubeflow deployed, if there's more to discuss still please re-open, closing.
