### ISSUE TITLE
Unable to assign issues or request for reviews.

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/support#224]
**Description**
As a contributor to Operate First, I would want access to assign myself to issues and request reviews from my peers.

**Additional context**
Need additional access to the repo : https://github.com/operate-first/operate-first.github.io

**Comment by tumido** [comment]
@aakankshaduggal it seems that you were left out from the `contributor` team in this repo. (I hope it was unintentional :stuck_out_tongue: :grin: ) I've added you there. You should have at least `triage` access to all repos in this org now.

I'll double check if there's anybody we forgot about not included in that team. If you know about anybody else, feel free to point them to me.

**Comment by tumido** [comment]
Actually, I was thinking.. I'm gonna create a new team for you folks that are interested in triage on the website repo. Just to keep things tidy...

**Comment by tumido** [comment]
So, I've created the @operate-first/contributors-web team now for the website-concerned people. LMK if there's anybody missing.

The `contributors-core` team has the same access on the website repos but it's not their main focus...

**Comment by aakankshaduggal** [comment]
Awesome. Thanks @tumido :D
