### ISSUE TITLE
[SPIKE] Evaluate Openshift GitOps instead of custom ArgoCD deployment

### ISSUE THREAD

**Issue by tumido** [operate-first/support#228]
Openshift Gitops is GA by yesterday, 2021-05-03, see the [announcement](https://www.openshift.com/blog/openshift-pipelines-and-openshift-gitops-are-now-generally-available).

Evaluate if we can start using it instead of our custom Argo CD deployment.

We need it to meet following criteria:
- [ ] Allows us to bring in kustomize plugins (ksops)
- [ ] Allows uploading and using our GPG keyring

**Comment by HumairAK** [comment]
@rbo pointed out that the following: https://issues.redhat.com/browse/GITOPS-766 

Is planned for version 1.3 and together with GitOps 1.2 will be GA

**Comment by HumairAK** [comment]
Based on the comment above, let's close this out. And create a follow up (blocked) issue for when this goes GA and we can adopt the gitops operator.

**Comment by tumido** [comment]
Updated: We're migrating secrets from ksops into vault and allowing other teams to use vault as well, therefore we don't need any custom tooling anymore in ArgoCD and we can pivot to OpenShift GitOps.
