### ISSUE TITLE
Include external experimental image streams to ODH JupyterHub

### ISSUE THREAD

**Issue by tumido** [operate-first/support#229]
**Is your feature request related to a problem? Please describe.**
We are starting to see requests coming in about bringing new image versions into our ODH JupyterHub deployment before it hits ODH. I believe that supporting this would bring us closer to the communities around projects which build upon ODH, allowing them to iterate faster on ODH compatible images.   

**Describe the solution you'd like**
1. Support document for users
2. Automation/script for image creation and upgrade https://github.com/operate-first/SRE/issues/284

**Comment by HumairAK** [comment]
Image added

**Comment by tumido** [comment]
Let's keep this one open until we have a user docs that we support this.

**Comment by HumairAK** [comment]
What would be a good place to document this in your opinion?

**Comment by tumido** [comment]
:shrug: What about a short doc in https://www.operate-first.cloud/users JupyterHub section? hosted from a doc in the `support` repo I suppose.
