### ISSUE TITLE
Jupiter spark notebook fails to download session's jar to classpath (driver, executor)

### ISSUE THREAD

**Issue by oshritf** [operate-first/support#239]
**Describe the bug and how to repreduce**
```
from pyspark import SparkConf
import os

# Instantiate a spark configuration object to receive settings
spark_conf = SparkConf()

Maven coordinates for additional packages
my_packages = 'io.xskipper:xskipper-core_2.11:1.1.1,com.ibm.stocator:stocator:1.1.1'

# Configure spark package
spark_conf.set('spark.jars.packages', my_packages)

from pyspark.sql import SparkSession
spark_cluster_url = f"spark://{os.environ['SPARK_CLUSTER']}:7077"
    
spark = SparkSession.builder \
    .master(spark_cluster_url) \
    .appName('Spark2.4.5-XSKIPPER1.0-Demo') \
    .config(conf = spark_conf) \
    .enableHiveSupport() \
    .getOrCreate()
```
Neither were downloaded to /opt/app-root/lib/python3.6/site-packages/pyspark/jars
Nor listed in spark.sparkContext.getConf().get('spark.jars')

**Expected behaviour**
Ability to extend and use additional packages from spark's notebook

**Additional context**
Is there another way to update pyspark spark-defaults.conf? specifically spark.driver.extraClassPath,  spark.executor.extraClassPath and spark.jar.packages

Creating a new image (based on the existing spark image?) with spark-defaults.conf configured with spark.jar.packages could be a workaround, details on which image to use would be helpful

**Comment by tumido** [comment]
I'm sorry @oshritf, we'll probably need to defer this to the ODH community. Operate First doesn't have that expertise.

cc @vpavlin @rimolive @nakfour @lavlas do you have any experience with this? Would you rather see this filed against one of ODH's repos for better visibility, instead of here?

**Comment by oshritf** [comment]
Modifying os.environ['PYSPARK_SUBMIT_ARGS']  to include desired packages solved it for me

os.environ['PYSPARK_SUBMIT_ARGS'] = \
 '--conf spark.cores.max=2 --conf spark.executor.instances=2 --conf spark.executor.memory=1G --conf spark.executor.cores=1 --conf spark.driver.memory=2G --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.3,io.xskipper:xskipper-core_2.11:1.1.1,com.ibm.stocator:stocator:1.1.1 pyspark-shell'

**Comment by tumido** [comment]
Thanks for sharing the solution @oshritf ! Glad you've resolved this!

/sig user-experience
/kind documentation

We probably need some documentation around this, so the next person with the same problem doesn't need to invent the wheel again. Reopening because of that.

The docs should live either in here or in ODH. Thoughts?

**Comment by HumairAK** [comment]
We could add this as part of the runbook so it goes under troubleshooting, wdyt?

**Comment by rimolive** [comment]
@tumido Why not both? After all, this is an important info to all the community

**Comment by vpavlin** [comment]
Sorry for later response... Glad you found a solution!

**Comment by tumido** [comment]
> @tumido Why not both? After all, this is an important info to all the community

@rimolive 
I don't think we should intentionally create duplicate documentation (things tend to get outdated and diverge). Either we create docs for it in ODH and make OPF link to it, or we decide that this is "environment specific" and create docs in OPF. :slightly_smiling_face: 

I'd favor the first option - extend the ODH docs with this and link to that from our runbooks.
