### ISSUE TITLE
Change JupyterHub pod "size" quota based on the actual recorded usage

### ISSUE THREAD

**Issue by tumido** [operate-first/support#240]
After https://github.com/operate-first/SRE/issues/281 happened, we'd like to adjust the sizes offered to users in JupyterHub to some reasonable amounts.
![image](https://user-images.githubusercontent.com/7453394/117983537-5a085200-b337-11eb-97cb-a2d5a12b9e8f.png)

https://github.com/operate-first/apps/blob/a67481fca8a5e76a067735deee7d1a1c9c4c170b/odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml#L58-L90

Our data science team will provide some kind of analysis on this, see here:
https://github.com/aicoe-aiops/operate-first-openshift-data/issues/26

**Comment by HumairAK** [comment]
Okay so the big issues is majority of the time it seems like the pods are sitting unused, then once in a while they'll spike in cpu usage. 

So I'm thinking we adjust the profiles so that the `requests` are way lower and aligned with average usage, and the `limits` can stay as is, to allow the pods to request up to the limit for those moments when usage goes high.

**Comment by 4n4nd** [comment]
> Okay so the big issues is majority of the time it seems like the pods are sitting unused, then once in a while they'll spike in cpu usage.
> 
> So I'm thinking we adjust the profiles so that the `requests` are way lower and aligned with average usage, and the `limits` can stay as is, to allow the pods to request up to the limit for those moments when usage goes high.

I like this idea, but we might see some OOM kills. I think we should still try it out.

**Comment by HumairAK** [comment]
> I like this idea, but we might see some OOM kills. I think we should still try it out. 

I think this will occur when _actual_ usage starts reaching capacity of the cluster I think. Right now it seems like we're way off from that (25% based on the cluster dashboard)

**Comment by HumairAK** [comment]
Atm I don't think there's active work being done here as this hasn't seen any activity and is thus stale, but if I'm wrong please re-open.

**Comment by MichaelClifford** [comment]
@Shreyanand did your recommended sizes get implemented?

**Comment by Shreyanand** [comment]
@MichaelClifford that is getting tracked in [PR 1](https://github.com/operate-first/apps/pull/1156), [PR 2](https://github.com/operate-first/apps/pull/1311).
