### ISSUE TITLE
Access for CCX team to be able to test workloads fingerprint gathering

### ISSUE THREAD

**Issue by tremes** [operate-first/support#242]
## Questionnaire

1. **Project description**:

   

 CCX (connected customer experience) team gathers data from OCP4 clusters and evaluates Insights recommendations against this data. 

2. **Target cluster**:

    

    TARGET CLUSTER: I guess the common one. 

3. **Team name**:

    

    TEAM NAME: ccx

4. **Desired project names**:

    

    PROJECT NAMES:

5. **Users needing access**:

    

    LIST OF USERS: 

6. ** Namespace Quota **

    

    QUOTA:

7. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by tumido** [comment]
Hey @tremes ! Glad to have you. From the chat I've noticed that you'd be interested in deploying something like a "latest" version of the insights operator or something? Is that correct assumption? What level of access to our clusters you'd want to get?  In technical terms: Can you please share sample cluster roles you'd like to be granted, is any security context constraint required to be granted to you?

We can give you your namespace without a question asked - where you can be your own admin. But I feel like you intention is to get access beyond your namespace to have a peek under others hand. Which is totally fine and we support you in that. I think we just need to have that defined :slightly_smiling_face:

**Comment by billburnseh** [comment]
Want to note that Radek Vokal from the insights dev org is starting discussion around bringing it to the operate first environment. Might be some opportunity for coordination!

**Comment by tremes** [comment]
@tumido Thanks. Well my original thought was to get the full kubeadmin access to be able to run the Insights Operator locally (or alternatively just work with someone and share the instructions how to do that)...at least for awhile. Second option (which is more complicated IMO) is to deploy custom insights operator deployment. I would need to be able to create a deployment in the "openshift-insights" namespace. I assume the clusters are already running the default installed Insights Operator (since they are OCP4 clusters).  The disadvantage is that the 2 instances of the IO would little bit conflict, but it shouldn't cause any critical issue to the cluster itself.

**Comment by tumido** [comment]
@billburnseh I'll check with him. This should be the ccx/insights operator dev thing so we're probably talking about the same topic.

This issue ties back to [CCXDEV-4842](https://issues.redhat.com/browse/CCXDEV-4842)

**Comment by tumido** [comment]
@billburnseh Radek confirmed those are 2 independent workstreams - this one goes the other way around than the insights dev/community platform and enables CCX to use OperateFirst as a playground or stage for the insights operator.

**Comment by tumido** [comment]
@tremes Great summary! There's some meat to this that we can work with. :slightly_smiling_face: 

Just to rearrange the thoughts here a bit:
### Option 1
Give away kubeadmin access to our clusters to your team so you can tunnel to the cluster and start an operator from your local machine against our clusters, correct?

Excuse my ignorance in this topic. How is kubeadmin access different from granting you cluster-admin cluster role?

Does it have to be `cluster-admin` or would `cluster-view` + `admin` access to certain namespaces enough?

Can you point me to any docs on the workflow so I can imagine the whole experience for you?

### Option 2
Grant you access to the `openshift-insights` namespace so you can deploy additional versions of the operator and compare/test/dev them on a live cluster, correct?

> The disadvantage is that the 2 instances of the IO would little bit conflict

How is this not the case for the option 1?

### Note
Our clusters face quite frequent issues during OpenShift upgrades. Each OCP upgrade we open about 2-4 support cases. I think we still need to keep the "vanila" stable insights operator released, in case it is used by TAMs to troubleshoot the clusters. So we should be careful not to break things if we don't necessarily have to (rule of thumb, not a dogma). :slightly_smiling_face:

**Comment by tremes** [comment]
Thanks. 
**Add Option 1.** : 

- I think there's no difference (I am not very experienced with the OpenShift permission settings, definitions, role etc. TBH)
- Our manifests are https://github.com/openshift/insights-operator/tree/master/manifests and I guess the one executing the command locally needs to access the `system:serviceaccount:openshift-insights:gather`. The steps how to run the IO locally are described in https://github.com/openshift/insights-operator#building.
- maybe the `cluster-view` + `admin` would be sufficient

**Add Option 2**:

- good point. It's kinda similar. The assumption here is that running locally will be much shorter and there won't be any archive uploads from the local run. Otherwise it's almost similar.....

**Comment by tumido** [comment]
Great stuff, thanks for the links! :slightly_smiling_face: 

I think for us it would be better to have something really deployed on the cluster, so we can really host you - all pods generate logs, metrics, events - all of it is valuable for us.

Giving you "just" the access seems like an easy way but doesn't contribute much to the platform itself.

If I'm reading those manifests correctly all you actually need is admin/edit access to the `openshift-insigths` then, no cluster admin is needed. You can use the `gather` service account in that namespace for the rest.

If you would need to further escalate the permissions for your operator, we can adjust the `insights-operator-gather` Cluster Role or deploy a secondary, similar cluster role, and bind it to the same service account - which would give your operator enough access to the cluster.

Does that sound like a good plan to you?

**Comment by tremes** [comment]
Yeah I think it sounds good. Thanks.

**Comment by tumido** [comment]
@tremes are there any other users besides you that should get access to this namespace?

**Comment by tremes** [comment]
Yes I think we can add @Sergey1011010, @rluders, @natiiix

**Comment by tumido** [comment]
@tremes can you please try accessing the namespace at:
https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/openshift-insights

please let me know if there's any issues. :slightly_smiling_face:

**Comment by tremes** [comment]
@tumido It seems to work! Thanks a lot.
