### ISSUE TITLE
Onboard odh-developer (llasmith@RH) to Zero cluster 

### ISSUE THREAD

**Issue by LaVLaS** [operate-first/support#244]
## Questionnaire

1. **Project description**:
   PROJECT DESCRIPTION: I am requesting access to the JupyterHub environment so that I can recreate any user ODH issues that may be reported by Operate First users

2. **Target cluster**:
    TARGET CLUSTER: Zero

3. **Team name**:
    TEAM NAME: odh-developer

4. **Desired project names**:
    PROJECT NAMES: odh-developer

5. **Users needing access**:
    LIST OF USERS: llasmith@redhat.com

6. ** Namespace Quota **
    QUOTA: Small

7. **GPG Key** (OPTIONAL)
    GPG KEY FINGERPRINT: 41E217886B24605316217B8F5AD1C1B1F3A28B6B
    KEYSERVER: keys.gnupg.net

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by HumairAK** [comment]
@tumido @4n4nd -- for this, should we give access to `operate-first` admin? I am inclined to just create another `group` which has access to all the odh namespaces w/ admin access and distribute that instead, and prune down the `operate-first` admin group.

**Comment by 4n4nd** [comment]
@HumairAK yeah let's create a `odh-admin` group and start with access to the `opf-jupyterhub`+`opf-jupyterhub-stage` namespaces
