### ISSUE TITLE
Cluster onboarding for Pulp+Thoth experiments

### ISSUE THREAD

**Issue by fridex** [operate-first/support#252]
## Questionnaire

1. **Project description**:

   PROJECT DESCRIPTION: Experimenting with [Pulp](https://pulpproject.org/), deploying it to operate1st environment and integrating it with [Thoth](https://thoth-station.ninja/).

2. **Target cluster**:

    TARGET CLUSTER: `Zero`

3. **Team name**:

    TEAM NAME: `thoth-pulp-experiments`

4. **Desired project names**:

    PROJECT NAMES: `thoth-pulp-experiments`

5. **Users needing access**:

    LIST OF USERS: keeping addresses private

6. ** Namespace Quota **

    QUOTA: `medium`

7. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by fridex** [comment]
Based on https://github.com/operate-first/support/issues/176#issuecomment-846969421

CC @tumido @ipanova @harshad16 @fao89 @mikedep333 @gerrod3 @dralley

**Comment by 4n4nd** [comment]
@fridex will you be making a PR for this issue or do you want the ops team to do it?

**Comment by harshad16** [comment]
I will open the pull requests.
