### ISSUE TITLE
Update Ray images and RayClusterCRD

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/support#254]
**Describe the solution you'd like**
- Update the Ray images to latest nightly wheels
- Add some packages to the `ml` images to support Dask and XGBoost

**Additional context**
I will be filing a pull request against the zero cluster to make these updates.

**Comment by 4n4nd** [comment]
@erikerlandson can this be closed now?

**Comment by erikerlandson** [comment]
yes, I'll close it, thanks!
