### ISSUE TITLE
Deploy Seldon Operator

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#259]
#### Operator request

If you want to request an operator, please provide the following:

1. **Name of the Operator**: Seldon Operator (from ODH)

2. **Operator version**:

3. **Operator scope**:
   All Namespaces

4. **Documentation and links**:
     operator part of ODH

#### Resource request

Please list all the resources you want to have deployed. Please list only the resources which can't be deployed by your project-admins. If possible, please include the resource manifest as a link to upstream definition or as an attachment file.

Requesting these resources to be deployed:

- A resource name: [links to manifests]()
- ...

### Questionnaire

1. **Team name**:
   aicoe

---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the docs [here](https://github.com/operate-first/apps/blob/master/cluster-scope/README.md).

**Comment by 4n4nd** [comment]
The operator was deployed, there were some issues with it which are documented in [this thread](https://operatefirst.slack.com/archives/C01RT0S2WKX/p1622814297181800). It is still not the latest version.

The current version is v1.2.2 and the latest is v1.7.0. This should be updated once odh releases a newer version that includes [this PR](https://github.com/opendatahub-io/odh-manifests/pull/397/files).

**Comment by pacospace** [comment]
@4n4nd where are the endpoints for Seldon? any doc? Thanks!!!

**Comment by 4n4nd** [comment]
@pacospace I am not really sure about how Seldon works. We just deployed the Operator. I can just give access for the Seldon Namespace to the Data Science group and you can figure it out?

**Comment by pacospace** [comment]
> @pacospace I am not really sure about how Seldon works. We just deployed the Operator. I can just give access for the Seldon Namespace to the Data Science group and you can figure it out?

Sure, sounds good! thanks @4n4nd

**Comment by 4n4nd** [comment]
@pacospace you along with the data-science group should now have access to the `opf-seldon` namespace.

**Comment by pacospace** [comment]
> @pacospace you along with the data-science group should now have access to the `opf-seldon` namespace.

Thanks @4n4nd I will check that!!

**Comment by MichaelClifford** [comment]
I just took a look. And it seems like having access to the operator allows us to deploy instances of seldon. Is this what we want? I would think that only the admins should have this access. Then they can deploy a seldon instance, then give the ds-group access to a shared the instance. WDYT?

**Comment by pacospace** [comment]
> I just took a look. And it seems like having access to the operator allows us to deploy instances of seldon. Is this what we want? I would think that only the admins should have this access. Then they can deploy a seldon instance, then give the ds-group access to a shared the instance. WDYT?

Shouldn't we have an aicoe pipeline for deployment of Seldon model? and in anyc ase let ArgoCD manage manifests?

**Comment by MichaelClifford** [comment]
> Shouldn't we create an aicoe pipeline for deployment of Seldon model? or in any case let ArgoCD manage manifests so we can trace what is deployed?

Maybe, but this is not for models, I don't think. I'm just talking about the service. Or does each model require its own seldon deployment?

**Comment by pacospace** [comment]
> > Shouldn't we create an aicoe pipeline for deployment of Seldon model? or in any case let ArgoCD manage manifests so we can trace what is deployed?
> 
> Maybe, but this is not for models, I don't think. I'm just talking about the service. Or does each model require its own seldon deployment?

No don't think so, it is an operator, so just waits for SeldonDeployment CRD, but if you access to that namespace we should make sure users cannot delete those.

**Comment by 4n4nd** [comment]
> I would think that only the admins should have this access.

That would be ideal, but since the admins don't really have enough cycles to take this on and maintain it, I thought the data-science group can look into this and help us with it. 
We have given access to the upstream odh group as well in case we need any help with something.

**Comment by erikerlandson** [comment]
This demo doesn't work on the MOC, because seldon server doesn't work:
https://www.operate-first.cloud/data-science/pet-image-detection/

**Comment by 4n4nd** [comment]
@erikerlandson that would be a separate demo created by @isabelizimm, maybe she can help you with it.

**Comment by erikerlandson** [comment]
@4n4nd  I think we should consider removing that image from the choices available at `https://odh.operate-first.cloud`, if it is not intended to work there.

**Comment by MichaelClifford** [comment]
We just got the seldon operator installed on opf. Instead of removing @isabelizimm demo. Let's deploy seldon and update her demo to work with it. WDYT?

**Comment by MichaelClifford** [comment]
> That would be ideal, but since the admins don't really have enough cycles to take this on and maintain it, I thought the data-science group can look into this and help us with it.
We have given access to the upstream odh group as well in case we need any help with something.

I think we've moved our conversation outside the scope of this issue. 

That sounds good @4n4nd, I think we can close this issue and we (DS folks) can  take it form here and help out with the seldon deployments.

**Comment by isabelizimm** [comment]
Yes! I can look at upgrading my demo so it works on opf. Tracking issue separately :rocket:

**Comment by HumairAK** [comment]
> That sounds good @4n4nd, I think we can close this issue and we (DS folks) can take it form here and help out with the seldon deployments.

Sounds good, thanks folks -- let us know if there's any issues that we can help with.

**Comment by 4n4nd** [comment]
> @4n4nd I think we should consider removing that image from the choices available at `https://odh.operate-first.cloud`, if it is not intended to work there.

I don't see Seldon in https://odh.operate-first.cloud/
