### ISSUE TITLE
OF Access Request

### ISSUE THREAD

**Issue by dystewart** [operate-first/support#261]
## Questionnaire

1. **Project description**:

   

   PROJECT DESCRIPTION: Investigate and gain familiarity with the infrastructure. 

2. **Target cluster**:

    

    TARGET CLUSTER: Zero

3. **Team name**:

    

    TEAM NAME: redhat-cto-team

4. **Desired project names**:

    

    PROJECT NAMES: redhat-cto-ns

5. **Users needing access**:

    

    LIST OF USERS: Dylan Stewart, Tyler Sheehan, Sean Waite, Heidi Dempsey, Fabrizio D'Angelo

6. ** Namespace Quota **

    

    QUOTA: X-Small

7. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by HumairAK** [comment]
Hello, I onboarded the users as outlined above, with the namespace created. I used each users' respective redhat gmail account as the login creds. Let me know if I should instead use a different email for any particular user. 

Let us know if there are any issues accessing the namespace! https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/redhat-cto-ns
