### ISSUE TITLE
Curator to Zero cluster

### ISSUE THREAD

**Issue by tumido** [operate-first/support#265]
## Questionnaire

1. **Project description**:

   

   PROJECT DESCRIPTION: Curator

2. **Target cluster**:

    

    TARGET CLUSTER: Zero

3. **Team name**:

    

    TEAM NAME: curator

4. **Desired project names**:

    

    PROJECT NAMES: ???

5. **Users needing access**:

    

    LIST OF USERS: @gagansk @skanthed

6. ** Namespace Quota **

    

    QUOTA: ???

7. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

Related to: https://github.com/operate-first/curator/issues/29

**Comment by tumido** [comment]
@gagansk @skanthed

we'll provision Koku operator to `koku-metrics-operator` namespace and grant you access to it.

If you need to deploy any additional workloads on zero you'd need another namespace (`koku-metrics-operator` should host the operator only, if possible). Do you want an additional namespace? How should we name it?

**Comment by skanthed** [comment]
For questions above - 

5. You can add one more user @matankb to the list. 

6.  If we can operator storage from 50Gi-100Gi. It would be great. All the reports will be saved in operator storage. If the number of reports reaches the limit and it doesn't find enough space to save all the reports. It will stop generating reports and then we need to delete it manually. 

As of now, if we can get an additional namespace as 'curator-engine' that would be great.

**Comment by HumairAK** [comment]
@skanthed added requested additions from above in https://github.com/operate-first/apps/pull/739

As for the storage requests, currently the operator namespace that @tumido added has no restrictions on storage (or cpu/memory) for that matter. Though we should probably add one in the future, for now we can monitor it's consumption and suggest a reasonable quota later on.

**Comment by HumairAK** [comment]
@skanthed the pr was merged and should be live, can you verify the changes? and if there's anything else that will be needed?
