### ISSUE TITLE
Provide access to Eclipse Adoptium open source project

### ISSUE THREAD

**Issue by tellison** [operate-first/support#268]
## Questionnaire

1. **Project description**:

Eclipse Adoptium builds, tests, and distributes Java runtimes. Adoptium is the new name for the AdoptOpenJDK project, an established project with multiple enterprise participants contributing, and many millions of users.

The project runs an API (api.adoptopenjdk.net) that serves metadata and binaries to end users, and powers our own website. The API is powered by Quarkus and is a vital part of the project infrastructure. Last month is serviced 17 million API requests.

2. **Target cluster**:

The preferred target cluster is "Zero".

3. **Team name**:

Preferred team name is "adoptium"

4. **Desired project names**:

    

No further project names required at this point.

5. **Users needing access**:

    

Will be provided out of band of this issue.

6. ** Namespace Quota **

    

Requires the LARGE quota.

The app is currently running with 14Gb memory, 10Gb storage.

7. **GPG Key** (OPTIONAL)

    

Requested information will follow.

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by tumido** [comment]
This should be closed via https://github.com/operate-first/apps/pull/752 

cc @Gregory-Pereira @HumairAK can you verify?

**Comment by HumairAK** [comment]
Yes namespace can be found here: https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/adoptium-project -- let us know if there are any issues. Thanks!
