### ISSUE TITLE
request to get access of a zero cluster

### ISSUE THREAD

**Issue by DanNiESh** [operate-first/support#272]
## Questionnaire

1. **Project description**:

   

   PROJECT DESCRIPTION: Our project permits multiple tenants to flexibly allocate baremetal machines from a pool of available hardware, create networks, attach baremetal nodes and networks, and to optionally provision an operating system on those systems through the use of an associated provisioning service.

2. **Target cluster**:

    

    TARGET CLUSTER: zero

3. **Team name**:

    

    TEAM NAME: esi-project

4. **Desired project names**:

    

    PROJECT NAMES:

5. **Users needing access**:

    

    LIST OF USERS: sdanni@redhat.com, tzumainn@redhat.com, 
lmcgann@redhat.com, ebrock@redhat.com, lars@redhat.com, naved001@bu.edu

6. ** Namespace Quota **

    

    QUOTA: Small

7. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by 4n4nd** [comment]
@DanNiESh could you please tell me what specific resources you would need access to? If you need a namespace, what should the namespace name be?

**Comment by tumido** [comment]
Hey @DanNiESh we currently manage shared OpenShift instances only. We can provide you with a namespace or more namespaces, but we can't allocate bare metal to you. Maybe Open Infra Labs project can help us with that. :slightly_smiling_face: 

cc @billburnseh @larsks @durandom

**Comment by DanNiESh** [comment]
> Hey @DanNiESh we currently manage shared OpenShift instances only. We can provide you with a namespace or more namespaces within OCP, but we can't allocate bare metal to you. Maybe Open Infra Labs project can help us with that. 
> 
> cc @billburnseh @larsks @durandom

Hi @tumido, does a project without resources show up anywhere as existing? If so, just a namespace is fine for now.

**Comment by 4n4nd** [comment]
> > Hey @DanNiESh we currently manage shared OpenShift instances only. We can provide you with a namespace or more namespaces within OCP, but we can't allocate bare metal to you. Maybe Open Infra Labs project can help us with that.
> > cc @billburnseh @larsks @durandom
> 
> Hi @tumido, does a project without resources show up anywhere as existing? If so, just a namespace is fine for now.

We could create a namespace/project in the zero cluster with a [x-small resource quota](https://github.com/operate-first/apps/blob/master/cluster-scope/components/resourcequotas/x-small/resourcequotas.yaml). What do you want the namespace name to be?

**Comment by DanNiESh** [comment]
> > > Hey @DanNiESh we currently manage shared OpenShift instances only. We can provide you with a namespace or more namespaces within OCP, but we can't allocate bare metal to you. Maybe Open Infra Labs project can help us with that.
> > > cc @billburnseh @larsks @durandom
> > 
> > 
> > Hi @tumido, does a project without resources show up anywhere as existing? If so, just a namespace is fine for now.
> 
> We could create a namespace/project in the zero cluster with a [x-small resource quota](https://github.com/operate-first/apps/blob/master/cluster-scope/components/resourcequotas/x-small/resourcequotas.yaml). What do you want the namespace name to be?

I want the namespace to be esi-operate-first-project. Actually, we just want a namespace without resources for now. Does a namespace without any resources show as existing in Cluster Zero?  Thanks!

**Comment by 4n4nd** [comment]
This would just be a limit set to the resources. You can choose to not use any of it. 
We can also try to change the resources to `0` using a custom resource quota later.

**Comment by DanNiESh** [comment]
> This would just be a limit set to the resources. You can choose to not use any of it.
> We can also try to change the resources to `0` using a custom resource quota later.

That's fine!
