### ISSUE TITLE
Augur instance set up for sandiego

### ISSUE THREAD

**Issue by cdolfi** [operate-first/support#274]
**Describe the solution you'd like**
The OSPO team (@jberkus and @jasonbrooks) is working on setting up an Augur instance to be accessed for Project Sandeigo on the operate first environment. The postgres DB will need to be able to handle 500+ GB of data. @oindrillac mentioned that @hemajv may have some insight on this process. I would like to set up communication between the two parties to help with the effort. 

**Describe alternatives you've considered**
The OSPO team has considered setting up the instance on AWS 

**Additional context**
https://oss-augur.readthedocs.io/en/master/development-guide/installation.html

**Comment by hemajv** [comment]
@cdolfi We can definitely look into setting it up on operate first as this would also be beneficial for us (for fetching github related data for our team), however @HumairAK @4n4nd may have to look into the amount of resources required by the Augur deployment and if the cluster can accommodate it for Augur
cc @goern @durandom

**Comment by durandom** [comment]
sure, please create the instance here. 
Is there a containerized version of this?

**Comment by jasonbrooks** [comment]
We've been running it from a VM, but we could get it running on openshift. How can I get access to the cluster?

**Comment by 4n4nd** [comment]
@jasonbrooks could you please create an onboarding issue ([here](https://github.com/operate-first/support/issues/new?assignees=&labels=onboarding&template=onboarding_to_cluster.md&title=)) and specify the namespace name and resources that would be required for this.

**Comment by jasonbrooks** [comment]
We will create this onboarding issue. We have to get augur running in a container, so for now, we're installing it in a blade in our datacenter.

**Comment by jberkus** [comment]
It's running, what it's not doing is populating the database, which I'm still troubleshooting.

**Comment by jberkus** [comment]
this was taken care of some months ago

/close
