### ISSUE TITLE
JumpStart Library

### ISSUE THREAD

**Issue by guimou** [operate-first/support#275]
## Questionnaire

1. **Project description**:

   The Jumpstart Library is an initiative from the Red Hat Data Services business unit to provide data engineers and data scientists with a set of repeatable patterns that they can implement in their data pipelines.
   Through different real-life "plausible" scenarios we are illustrating different data pipelines. For each of those scenario we provide:

-  Full Source code for the different elements implemented (container images, applications, configuration files,...),
-  Full code for deployment into OpenShift environment (YAML files),
- Complete instructions to deploy the scenarios into an OpenShift cluster, either manually or automaically (Ansible scritps, ArgoCD pipelines)
- Packaged workshops around the scenatios to learn how to deploy the components (Bookbag)
- Videos, tutorials...

  On top of those scenarios we provide full code and instructions to easily deploy/reuse the patterns found in them. For example:

- Aggregate data from Kafka and save to an S3 bucket,
- Send a bucket notification from Ceph to Kafka,
- Deploy Trino to cross-query PostgreSQL and S3,
- ...

Reference: [Jumpstart Library Repository](https://github.com/red-hat-data-services/jumpstart-library)

We are now looking for a place to host the Developement and Production environments for those different demo scenarios.
At the moment two scenarios are ready to be deployed: Automated XRay Diagnosis, and Smart City/Green City.

For both those scenarios, if we can have access to "external" resources like S3 bucket from a Ceph Cluster, an Open Data Hub environment, or even a Kafka cluster, we won't have to deploy all those tools meaning the resource consumption can be minimal, in the range of 4-8 CPUs/5-10GB RAM per namespace (again, 4 namespaces required at the moment Dev/Prod for 2 scenarios).

2. **Target cluster**:

    TARGET CLUSTER: Zero cluster

3. **Team name**:

    TEAM NAME: jumpstart-library

4. **Desired project names**:

    PROJECT NAMES:

- jumpstart-xray-dev
- jumpstart-xray-prod
- smartcity-xray-dev
- smartcity-xray-prod

5. **Users needing access**:

    LIST OF USERS:

- gmoutier@redhat.com
- karan@redhat.com
- kbader@redhat.com

6. ** Namespace Quota **

    QUOTA: Large for each namespace, although not all the memory would be needed.

7. **GPG Key** (OPTIONAL)

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by 4n4nd** [comment]
@guimou we can give you a custom quota for the resources if you could just tell us how much cpu and memory you would need.

**Comment by guimou** [comment]
Hi!
Sorry, it took some time to gather the right data and see where we could shrink the ressources. I will put for each environments all the requests and limits that the pods are runnng with, along with what is really consumed. Because a DB pod for example may have a request for 256MB RAM, a limit at 1GB, but in real will consume 300MB for the specific workload we are running. Same for CPU.

### For smartcity (each of the dev and prod environment):
Requests:
- CPU: 5
- RAM: 20GB
Limits:
- CPU: 20
- RAM: 50GB
Really consumed:
- CPU: 1.5 - 2
- RAM: 12GB

### For xray (each of the dev and prod environment):
Requests:
- CPU: 5
- RAM: 5GB
Limits:
- CPU: 10
- RAM: 15GB
Really consumed:
- CPU: 2
- RAM: 8GB

Does that make sense? Unfortunately there are not so many things we have control on to scale down requests and limits specifically as it's handled by operators. But we can try further if needed.

**Comment by guimou** [comment]
@Gregory-Pereira @4n4nd 
Hi! Did not have time to do a follow-up, but where are we with this? Do you need further info?

**Comment by 4n4nd** [comment]
@guimou the issue is that we are currently capped on Compute resources and we are expecting new hardware soon.

**Comment by guimou** [comment]
Ah, ok. Thanks for the feedback.
