### ISSUE TITLE
Jupyterhub Spawner UI has some blank images in the image list

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/support#276]
**Describe the bug**
There are 3 images in the image selection UI which do not have a name

**To Reproduce**
1. Go to https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/hub/spawn

**Expected behaviour**
All images have a name/description

**Screenshots**
![Screenshot from 2021-06-21 10-04-11](https://user-images.githubusercontent.com/22333506/122776404-13ccd980-d279-11eb-93ba-5e7e5f56cd41.png)

**Additional context**
This might be the result of the new UI update in odh v1.1.0 ([PR](https://github.com/operate-first/apps/pull/773))

**Comment by tumido** [comment]
Maps to following ImageStreams:
- s2i-spark-scipy-notebook:3.6
- s2i-spark-minimal-notebook:py36-spark2.4.5-hadoop2.7.3
- s2i-pytorch-py38-notebook:latest

**Comment by 4n4nd** [comment]
The manifests for these images are in the [upstream odh repo](https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images/overlays/additional), seems like they are missing the `opendatahub.io/notebook-image-name` annotation.

**Comment by 4n4nd** [comment]
Upstream issue: https://issues.redhat.com/browse/RHODS-1014
