### ISSUE TITLE
Access to a cluster for the Elyra AIDevSecOps Tutorial

### ISSUE THREAD

**Issue by preska** [operate-first/support#279]
## Questionnaire

1. **Project description**:

   

   PROJECT DESCRIPTION: I'd like a cluster to run this project https://github.com/AICoE/elyra-aidevsecops-tutorial

2. **Target cluster**:

    

    TARGET CLUSTER: Infra - Cluster for management via ACM and ArgoCD

3. **Team name**:

    

    TEAM NAME: chi-rhug

4. **Desired project names**:

    

    PROJECT NAMES:

5. **Users needing access**:

    

    LIST OF USERS: presshar@redhat.com

6. ** Namespace Quota **

    

    QUOTA: Medium

7. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

If you don't want to wait for the maintainers to notice this issue, you can make the changes yourself by submitting a pull request against the configuration repository. Please follow the [docs/onboarding_to_cluster.md][2] guide.

[2]:https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md

**Comment by tumido** [comment]
@preska I'll be onboarding you to the `zero` cluster since that is our workload cluster. Don't worry, you'll still have access to ArgoCD if you need to.

**Comment by preska** [comment]
Hi, will I be receiving the credentials through here?

**Comment by HumairAK** [comment]
@preska you can log in to your namespace using your gmail login for `presshar [at] redhat [dot] com`, your namespace is located [here](https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/chi-rhug)
