### ISSUE TITLE
Ceph - cannot retrieve file

### ISSUE THREAD

**Issue by xtuchyna** [operate-first/support#284]
**Describe the bug**
When trying to retrieve a file, timeout error occurs.

**To Reproduce**
1. I am using following profile (`.aws/credentials`):
```
[profile zero]
s3 =
    endpoint_url = https://s3-openshift-storage.apps.zero.massopen.cloud/                            
```
access key and key id are used from `ceph` secret available on zero cluster in `thoth-test-core` namespace (https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/thoth-test-core/secrets/ceph)
2. try
```
aws s3 --profile zero cp  s3://thoth/data/kebechet-update-manager/overall_kebechet_update_manager_2021-06-21.json .
```
3. Wait and see that nothing happens

**Expected behaviour**
File is small, should be downloaded in a second.

/kind bug

**Comment by 4n4nd** [comment]
I was able to replicate this issue. Seems like this is an issue in other `nooba` buckets as well. I did not see this issue in `ceph-rgw` type buckets.

**Comment by HumairAK** [comment]
Looks like we've been getting some nooba alerts the past couple of days: https://github.com/operate-first/alerts/issues?q=is%3Aissue+is%3Aclosed+noobaa

**Comment by tumido** [comment]
Incident opened at: https://github.com/operate-first/SRE/issues/347

**Comment by xtuchyna** [comment]
Hello @tumido, how's this issue going on so far?

**Comment by tumido** [comment]
Hey @xtuchyna support case is still pending, RH support is working on it. Sadly we don't have many answers yet. :disappointed:
