### ISSUE TITLE
User support: S3 Storage request - aicoe-kaggle

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#287]
### Questionnaire

1. **User details**:

mcliffor

This will be a shared storage location for datasets and ML models used by the [aicoe-kaggle](https://github.com/aicoe-kaggle) org as they develop with jupyter on the MOC. This should be a private bucket that only members of that org have access to. 

2. **Desired bucket name**:

aicoe-kaggle

3. **Maximal bucket size**:
   500 Gb

4. **Maximal bucket object count**:
   Planned maximal count of objects in your bucket. Default quota is 10000.

5. **Your GPG key or contact**:
  
email or gchat or slack

---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the [docs/claiming_object_store.md](https://github.com/operate-first/support/blob/main/docs/claiming_object_store.md) guide.

**Comment by HumairAK** [comment]
@MichaelClifford -- how urgent is this? We're currently trying to resolve an issue with provisioning nooba buckets with support https://github.com/operate-first/SRE/issues/347 

We don't have an eta yet, but hope to know more in the coming days.

**Comment by MichaelClifford** [comment]
any update here? @HumairAK

**Comment by Gregory-Pereira** [comment]
Sorry not yet, I can try to get to it today.

**Comment by MichaelClifford** [comment]
Hi @Gregory-Pereira any updates on this?

**Comment by MichaelClifford** [comment]
Hi @Gregory-Pereira any updates on this?

**Comment by MichaelClifford** [comment]
This may be a good use case for using one of the MOC openstack buckets. So I think we can probably close this issue now.
