### ISSUE TITLE
rekor as an operate first service

### ISSUE THREAD

**Issue by lukehinds** [operate-first/support#29]
hello, [project rekor](https://github.com/projectrekor/rekor) is interested in becoming an operate first service to allow argocd deployments to MOG / GKE cluster. This issue will act as a placeholder and means to track / reference. 

We are working on an k8s operator and plan to explore monitoring integration. 

rekor is a golang based project, it provides a web front end (rest API) and has a backend using the project google/trillian. Trillian is already supported to run in a k8s cluster and also has prometheus monitoring files available.

**Comment by tumido** [comment]
cc @durandom

**Comment by wattsteve** [comment]
Is the intent here to allow the Rekor projects CD to be able to deploy to either the Massachusetts Open Cloud (MOC) or GKE? Is "Operate First" a Red Hat internal initiative or a community initiative?

**Comment by durandom** [comment]
First step would be to deploy a Rekor service to the MOC cluster via our tooling (argocd, etc) and then deploy to GKE either via the same tooling or another instance of that tooling, re-using the procedures.

This version of Operate First is the community part, concerned with creating an open source equivalent for operations.

**Comment by durandom** [comment]
@lukehinds can you follow https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/blob/master/docs/about-the-cluster.md to get access to the cluster? @larsks will enable your account.

@HumairAK can then point you to documentation on how to deploy via our argocd

**Comment by HumairAK** [comment]
Hey guys, FYI you guys should be able to go ahead and make namespaces and deploy on the MOC cluster right now w/o needing to be added [here](https://console-openshift-console.apps.cnv.massopen.cloud/k8s/cluster/projects).

If this is an operator then it should go [here](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/tree/master/manifests/operators) (We keep all operators and cluster resources in this repository).

Everything else goes [here](https://github.com/operate-first/argocd-apps). We don't have docs for a formal onboarding process just yet, but I've added the folders for `rekor` to put their argocd applications in. You'll need some basic understanding of [kustomize](https://kustomize.io/) and can follow the docs [here](https://github.com/operate-first/argocd-apps/blob/main/docs/add_application.md) to figure out where to put your argocd applications. I'll need to create the argocd projects for your team and I'll request an openshift-group on moc for your team that will be able to access the argocd project via console.

We're in the process of adding more docs to ease the process and understanding, if you have questions/feedback/suggestions please let us know.

Right now we have environments for `crc`, `quicklab`, `moc`, please make an issue for any other environments/clusters you'd like us to support here.

**Comment by HumairAK** [comment]
I've created an issue [here](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/61) for an openshift group for `rekor`, please add the people that would need access to the argocd `rekor` project there.

**Comment by HumairAK** [comment]
Rekor argocd project has been setup, and the appropriate users have been given access to the argocd instance. Login [here](https://argocd-server-argocd.apps.cnv.massopen.cloud/applications). 

You can create argocd applications via the UI. But note that the ArgoCD Application resource will not be version controller if you do it this way. 

If you would like your argocd manifests backed up on vcs, then you can submit a pr [here](https://github.com/operate-first/argocd-apps). Docs explaining the structure and which directory to add the files can be found [here](https://github.com/operate-first/argocd-apps/blob/main/docs/add_application.md). Let us know if you have any questions!

**Comment by durandom** [comment]
@HumairAK is the process in your last comment documented anywhere? If not, please do :)

**Comment by HumairAK** [comment]
@durandom  -- yep! I've linked to the repo & docs on how they may add their applications on vcs in the comment above.

**Comment by lukehinds** [comment]
hey, sorry for late reply, seems like the service is offline (you may already be aware):

![image](https://user-images.githubusercontent.com/7058938/103639903-04660800-4f47-11eb-9e0c-03c33631fa73.png)

**Comment by tumido** [comment]
Hi @lukehinds, I confirm the cluster is currently down. :frowning_face: @HumairAK and @larsks are trying to get hold onto people who can help us get it back online. Unfortunately most of them are either still on Christmas vacation or just came back. It should be up in few days at most.

**Comment by lukehinds** [comment]
any luck / progress at all guys?

**Comment by tumido** [comment]
yes @lukehinds, the cluster should be up again. Can you access it?
https://console-openshift-console.apps.cnv.massopen.cloud/

We've also very recently tried to switch over to using declarative namespace and user management. We're still putting together the docs, but in general, please open a ticket like these https://github.com/open-infrastructure-labs/moc-cnv-sandbox/issues/8 https://github.com/open-infrastructure-labs/moc-cnv-sandbox/issues/7 if you'd like a namespace an a user group to be created for you in OpenShift. Just shoot us the MOC openshift usernames and namespace names.. :slightly_smiling_face: 

Or, you can open a PR yourself against this repo:  https://github.com/operate-first/apps/tree/master/namespaces/overlays/moc and encrypt the group membership using ksops.

**Comment by goern** [comment]
see also https://github.com/thoth-station/core/issues/262
