### ISSUE TITLE
Superset/Trino not accessible

### ISSUE THREAD

**Issue by hemajv** [operate-first/support#297]
**Describe the bug**
Trino after being recently deployed is not accessible. Superset also does not seem to be running.

**To Reproduce**
1. Go to https://trino-route-opf-trino.apps.zero.massopen.cloud/
2. Go to http://superset-opf-superset.apps.zero.massopen.cloud/

**Expected behaviour**
Trino/Superset login landing page

**Screenshots**

![Screenshot from 2021-07-07 10-56-15](https://user-images.githubusercontent.com/7343099/124782159-0159cd80-df12-11eb-8239-92cc39e2136a.png)

**Comment by hemajv** [comment]
cc @4n4nd @rimolive

**Comment by 4n4nd** [comment]
related https://github.com/opendatahub-io/odh-manifests/pull/454

**Comment by rimolive** [comment]
Can this issue be closed? The systems mentioned in this issue are already available.
