### ISSUE TITLE
NEW PROJECT: Decision-as-a-Service

### ISSUE THREAD

**Issue by robpblake** [operate-first/support#300]
### Target cluster

Zero

### Team name

baaas

### Desired project names

baaas-dfm, baaas-dfs, baaas-dmn-jit, baaas-trusty-ai, baaas-modeler

### Project description

Decision-as-a-Service (DaaS) is the first effort from the Business Automation group at Red Hat to provide managed services to our customers. We envision it will become part of a larger portfolio of Business Automation as a Service (BAaaS) 

Building on top of the Kogito project, DaaS provides a simple API to allow customers to deploy Decisions modeled in Decision Model and Notation (DMN). As a managed service, DaaS removes the operational complexity for our customers, allowing them to focus on integration with their Decision logic.

### Users needing access

Please contact me for the list of email addresses.

### Namespace Quota

Custom

### Custom quota

Our application is designed to run in multiple namespaces. Therefore could you use the following sizes for each namespace:

- baaas-dfm: small
- baaas-dfs: small
- baaas-trusty-ai : small
- baaas-dmn-jit: x-small
- baaas-modeler: x-small

**Comment by tumido** [comment]
Hey @robpblake unfortunately we might need to hold your onboarding request for a bit. In last week we had too many teams onboarding the clusters and since our deployment runs on bare metal, we're struggling to scale the cluste. We should have new HW incoming in a week or so, we'll keep you updated.

**Comment by robpblake** [comment]
@tumido OK thanks for the heads-up. 

From your perspective, is there any of the onboarding we can complete before the new HW arrives, or do we need to wait?

**Comment by tumido** [comment]
@robpblake there's not much you can do. I'll prepare a PR in the meantime, but we have to wait for the HW before merging it anyways.

**Comment by robpblake** [comment]
@mariofusco : FYI, this is the onboarding ticket for DaaS into operate-first.cloud

**Comment by mimotej** [comment]
Hi, sorry for missing this issue. If you still want to onboard your project could you please provide us with GitHub usernames of users who need access?
