### ISSUE TITLE
NEW PROJECT: microservices

### ISSUE THREAD

**Issue by MaxLanLiu** [operate-first/support#302]
### Target cluster

Rick

### Team name

grok-micro

### Desired project names

grok-micro

### Project description

Our project is about deploying and testing several microservices benchmark like BookInfo and DeathStarBench. We plan to test things like version updates and various workloads. Results from this project will bring better understanding of microservices and better research projects.

### Users needing access

I still need to finalize the list and will reach out to a team member soon.

### Namespace Quota

Small

**Comment by harshad16** [comment]
We are currently capped on hardware compute resources. Onboarding requests are currently put on hold. We are expecting new hardware soon, until then your onboard request will remain in a pending state.

we will get back to you soon.

**Comment by mimotej** [comment]
Hi, sorry for missing this issue. If you still want to onboard your project could you please provide us with GitHub usernames of users who need access?
