### ISSUE TITLE
Pytorch-jobs Operator on Zero Cluster? 

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#303]
Does the the zero cluster have [Pytorch-jobs](https://github.com/kubeflow/pytorch-operator) included as part of its Kubeflow deployment. If not, could it be added? 

cc: @pacospace @TreeinRandomForest @erikerlandson

**Comment by 4n4nd** [comment]
@MichaelClifford I couldn't find the instructions to install this operator in the [kubeflow components page](https://www.kubeflow.org/docs/components/).

**Comment by 4n4nd** [comment]
But I do see some manifests and overlays [in their repo](https://github.com/kubeflow/pytorch-operator/tree/master/manifests/overlays) that we could use

**Comment by pacospace** [comment]
cc @nakfour

**Comment by 4n4nd** [comment]
We are on v4.7.13

**Comment by nakfour** [comment]
KF 1.3 on OCP v4.7 has issues, but not specific to pytorch operator. To install it, use ODH operator and customize this example [kfdef](https://github.com/kubeflow/manifests/blob/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml), You most like will only need istio, cert-manager, openshift-scc and pytorch operator.

**Comment by TreeinRandomForest** [comment]
@4n4nd would it be possible to do what @nakfour suggested?

**Comment by erikerlandson** [comment]
Somewhat speculative, but would be interesting to try adding torch to the ray images and see if we can do pytorch using ray instead of a separate torch op

**Comment by MichaelClifford** [comment]
@4n4nd would it be possible to update the current `apps/kubeflow-components/base/kfdef.yaml` with the kfdef @nakfour linked above? Or possibly just add the relevent lines for tf-jobs and py-torch jobs?

https://github.com/kubeflow/manifests/blob/42a19c0825d23149c0edb67757b04a635d6a26f0/distributions/kfdef/kfctl_openshift_v1.3.0.yaml#L55-L64

**Comment by MichaelClifford** [comment]
@erikerlandson any luck on using the default torch package and using ray to distribute the computation?

**Comment by erikerlandson** [comment]
@MichaelClifford  I haven't personally used it, but I know of a couple people from the IBM Research group that used the ray horovod stuff successfully.

**Comment by MichaelClifford** [comment]
> @MichaelClifford I couldn't find the instructions to install this operator in the [kubeflow components page](https://www.kubeflow.org/docs/components/).

@4n4nd  the training operators can be found here: https://www.kubeflow.org/docs/components/training/

**Comment by 4n4nd** [comment]
@MichaelClifford @TreeinRandomForest the issue with that is we don't have a functional Istio deployment in our cluster. Since that is a dependency, we will need to figure that out first. 
@HumairAK @tumido do you folks have any suggestions?

**Comment by MichaelClifford** [comment]
What about this? http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/?ns=kf-demo 

isn't it being used to run kfpiplines currently?

**Comment by MichaelClifford** [comment]
@4n4nd can this istio be used? 
 http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/?ns=kf-demo ?
