### ISSUE TITLE
Create temporary augur db as an openshift external service 

### ISSUE THREAD

**Issue by cdolfi** [operate-first/support#306]
**Description**
The OSPO team has set up a temporary Augur instance to be able to use for EDA/initial work as a long term solution is being worked on(https://github.com/operate-first/support/issues/274).  The data source is available from random cloud instances on GCE, but somehow you can't connect to it from a Notebook instance running in MOC/OF. The solution identified by @jberkus is for someone with admin right to create the database as an openshift external service. 

**Additional context**
https://docs.openshift.com/container-platform/3.5/dev_guide/integrating_external_services.html

**Comment by jberkus** [comment]
Here's the service we need available:

* augur.osci.io
* port 6432
* protocol: postgresql

**Comment by tumido** [comment]
@HumairAK @larsks @4n4nd  any idea why it's not possible to connect to external service from a JH notebook? Like, sure, we can define external service resource, but I thought JH pods can access resources outside of the cluster, so I wonder why it's no the case here.

PR for external service here: https://github.com/operate-first/apps/pull/860

**Comment by 4n4nd** [comment]
@tumido https://github.com/operate-first/support/issues/309 this issue might have more information

**Comment by 4n4nd** [comment]
this does not seem to be a DNS issue so the external Service did not work. I suspect this is the same issue as #309 let's continue the discussion in that thread.

**Comment by 4n4nd** [comment]
This issue is being tracked at https://github.com/operate-first/support/issues/309. Closing this one.
