### ISSUE TITLE
NEW PROJECT: Project Meteor

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#310]
### Target cluster

Zero

### Team name

ai-coe

### Desired project names

project-meteor

### Project description

https://github.com/AICoE/meteor

### Users needing access

mcliffor

### Namespace Quota

Medium

**Comment by HumairAK** [comment]
This was completed by: https://github.com/operate-first/apps/pull/844
Namespace here: https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/projects/aicoe-meteor

**Comment by MichaelClifford** [comment]
Thanks @HumairAK
