### ISSUE TITLE
Network latency issues in MOC/Zero cluster

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/support#311]
There have been reports of access to user applications (like Jupyterhub) being slow/lagging.
Other users have also reported connection issues between in cluster services (`sdap`)

**Comment by 4n4nd** [comment]
We asked the `network-observability` team in openshift if there were any metrics that we could look at to get more insight with this issue, they suggested some metrics `haproxy_server_*`. Slack thread:  https://coreos.slack.com/archives/C01DMAD88JF/p1626289311159700

**Comment by 4n4nd** [comment]
cc @HumairAK

**Comment by tloubrieu-jpl** [comment]
Hello, 

In the sdap namespace on operate first there are a lot of intermittent network issues like reported in this log message:
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'172.30.18.177:9042': OSError(None, "Tried connecting to [('172.30.18.177', 9042)]. Last error: timed out")})

This service is up and sometime accessible but very often not accessible as shown in this log.

Is there an estimated resolution or at least analysis time ?

Thanks

**Comment by 4n4nd** [comment]
@larsks suggested pinging a local pod to check for packet loss.
Tried pinging a pod on `os-wrk-1`([pod](https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-jupyterhub-stage/pods/jupyterhub-1-hzwbt)) from debug pods on different nodes.

Results:
```
os-wrk-0:
--- 10.130.5.159 ping statistics ---
130 packets transmitted, 122 received, 6.15385% packet loss, time 131976ms
rtt min/avg/max/mdev = 0.137/0.242/2.651/0.244 ms

os-sto-0:
--- 10.130.5.159 ping statistics ---
115 packets transmitted, 108 received, 6.08696% packet loss, time 116341ms
rtt min/avg/max/mdev = 0.122/29.554/2054.086/220.163 ms, pipe 3
```

We can see some consistent packet loss

**Comment by tloubrieu-jpl** [comment]
Hi @4n4nd, does that mean somthing should be done ? Thanks

**Comment by HumairAK** [comment]
Stale issue, closing -- please re-open if needed.
