### ISSUE TITLE
User guide for Trino+Superset

### ISSUE THREAD

**Issue by hemajv** [operate-first/support#314]
Include documentation/guide on using Trino and Superset

Trino: https://trino-route-opf-trino.apps.zero.massopen.cloud/
Superset: http://superset-opf-superset.apps.zero.massopen.cloud/
CluodBeaver: http://cloudbeaver-opf-trino.apps.zero.massopen.cloud/

**Comment by hemajv** [comment]
Created an initial guide here: https://docs.google.com/document/d/1m8wBr3s4763kIlU6S3HMunkEQI_e2586HcmvENHsEss/edit?usp=sharing

**Comment by hemajv** [comment]
Short demo walk through also available here: https://drive.google.com/file/d/1SM0wpkdxvSC3J-LJ2d0HJN1ZysgCJ_C1/view?usp=sharing

**Comment by pacospace** [comment]
Link to CloudBeaver is not available @hemajv :/

**Comment by hemajv** [comment]
@pacospace there was a PVC issue which is now resolved, it should be accessible again: http://cloudbeaver-opf-trino.apps.zero.massopen.cloud/

**Comment by pacospace** [comment]
> @pacospace there was a PVC issue which is now resolved, it should be accessible again: http://cloudbeaver-opf-trino.apps.zero.massopen.cloud/

Thanks a lot @hemajv!! 💯

**Comment by pacospace** [comment]
cc @xtuchyna
