### ISSUE TITLE
ODH JupyterHub injecting Kafka SSL certs

### ISSUE THREAD

**Issue by Gkrumbach07** [operate-first/support#315]
**Description**
I am trying to consume and produce messages on kafka inside a jupyter notebook which is hosted on Operate First's deployment of ODH JupyterHub. In other instances where I used kafka in MOC Zero, I was able to inject the SSL certs as OpenShift secrets which were mounted as a volume in the container. Is this something I can do in the JupyterHub instance? Would I need to create another Kafka User profile?

**Additional context**
Previously I was able to use a Kafka broker that did not use SSL authentication.

@vpavlin

**Comment by 4n4nd** [comment]
@Gkrumbach07 let's create a public kafka user with limited privileges
