### ISSUE TITLE
[TASK] Create "Namespace delete" issue template and docs

### ISSUE THREAD

**Issue by tumido** [operate-first/support#319]
**User story**
We don't have any docs, issue templates or automation for deleting a namespace.

**Additional context**
Zero cleanup initiated by @erikerlandson made us aware that we have no formal procedure for this.

**Acceptance Criteria**
- [ ] There's an issue template
- [ ] There's `opfcli` command
- [ ] There's documentation around this (ADR?)

**Comment by erikerlandson** [comment]
reference PR removing a namespace:  https://github.com/operate-first/apps/pull/857
