### ISSUE TITLE
Pulp deployment requires more resources

### ISSUE THREAD

**Issue by fridex** [operate-first/support#321]
**Resource request**

Namespace `thoth-pulp-experiments` is low on resources - we cannot bring some pods up.

![Screenshot_2021-07-23_09-21-06](https://user-images.githubusercontent.com/880687/126749480-3da83898-9be0-4ca4-83ea-ff301fe403d1.png)

![Screenshot_2021-07-23_09-20-05](https://user-images.githubusercontent.com/880687/126749368-2266f854-32be-442e-a7da-5bc57bd042d8.png)

Please increase memory allocated for `thoth-pulp-experiments` namespace.

**Comment by tumido** [comment]
FTR: Double the memory quota: https://github.com/operate-first/apps/pull/859
