### ISSUE TITLE
Request : Access to Superset

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/support#331]
As a Data Scientist working on https://github.com/aicoe-aiops/ocp-ci-analysis/issues/78, I need access to Superset and cloudbeaver.

username - aduggal
email - aduggal@redhat.com

cc- @hemajv @HumairAK

**Comment by hemajv** [comment]
Manually created user account for CloudBeaver (granted `user` role) and Superset (granted `alpha` role).
Creds shared with @aakankshaduggal

**Comment by aakankshaduggal** [comment]
Thank you @hemajv :heart:
