### ISSUE TITLE
Request : Access to Superset and Cloudbeaver

### ISSUE THREAD

**Issue by amsaparov** [operate-first/support#332]
As a Data Scientist working on aicoe-aiops/ocp-ci-analysis#78, I need access to Superset and cloudbeaver.

username - asaparov
email - asaparov@redhat.com

cc- @hemajv @HumairAK

**Comment by hemajv** [comment]
Manually created user account for both CloudBeaver (granted `user` role) and Superset (granted `alpha` role).
