### ISSUE TITLE
Manage DNS declarativelly

### ISSUE THREAD

**Issue by tumido** [operate-first/support#334]
### Requested actions
Changing DNS is one of the last remaining tasks we do manually when provisioning new clusters and/or cnaming routes (like argocd.operate-first.cloud etc.) Switchboard (or any similar thing) can help us with that.

#### Operator request

If you want to request an operator, please provide the following:

1. **Name of the Operator**: switchboard
2. **Operator version**:  I don't care
3. **Operator scope**: I don't care
4. **Documentation and links**:  https://github.com/borchero/switchboard

#### Additional context
https://github.com/operate-first/SRE/issues/359#issuecomment-893470852

**Comment by tumido** [comment]
Btw as @durandom mentioned, Switchboard looks a bit unmaintained.

I've found https://github.com/replicatedhq/kubeflare which works with cloudflare only so it's not useful either.

If anybody has any sugestion for declarative DNS, bring it on! It doesn't have to be a kubernetes manifest, but it really needs to be able to be automated via CI.

**Comment by durandom** [comment]
Does Terraform or https://crossplane.io/ support our DNS? What's our DNS based on anyway?

**Comment by tumido** [comment]
Terraform does support Google Cloud DNS via
 https://registry.terraform.io/modules/terraform-google-modules/cloud-dns/google/latest

While crossplane looks neat it seems it currently doesn't have any support for DNS Zones in Google. Based on their docs they support Google Compute Engine VPC Network only, which is not useful for our usecase.

https://crossplane.io/docs/v0.4/api/crossplaneio/stack-gcp/compute-gcp-crossplane-io-v1alpha3.html#Network

I'll experiment with the Terraform a bit to see what can be done there. 

I know we can automate Terraform via GitHub Actions (for the beginning).

https://learn.hashicorp.com/tutorials/terraform/github-actions
