### ISSUE TITLE
Please install openshift-pipelines operator

### ISSUE THREAD

**Issue by rbo** [operate-first/support#340]

**Comment by HumairAK** [comment]
To do this declaratively add the subscription to the rick cluster here: https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/emea/rick/kustomization.yaml 

e.g. for the zero cluster we have: 
https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/zero/kustomization.yaml#L123


I think that should be sufficient. Then argocd will deploy it, or...it would if infra was up :)  -- for now you can manually kustomize/build deploy it.

**Comment by tumido** [comment]
Did any of the manual deployments happened or not at all? looking at the cluster we did no manual changes, correct?

Let's do it properly then. :slightly_smiling_face: 

@mimotej would you like to give it a try?

**Comment by rbo** [comment]
> Did any of the manual deployments happened or not at all? looking at the cluster we did no manual changes, correct?
Only manual deployment after cluster installation was the OCS/ODF installation & configuration.
