### ISSUE TITLE
Quota resource overview about entire cluster

### ISSUE THREAD

**Issue by rbo** [operate-first/support#342]
**Description**

Do we have an overview of the available resources and quota of a cluster? 

For example User onboarding at Rick cluster, how do we check If we have enough space left? 

**Additional context**

**Comment by HumairAK** [comment]
We have resource overview metrics here: https://grafana.operate-first.cloud/dashboards/f/XhHHmTT7z/cluster-management 

If these are insufficient we should make explicit issues requesting what additional dashboards/info we need.
