### ISSUE TITLE
NEW PROJECT: examples-openshift-pub on rick

### ISSUE THREAD

**Issue by rbo** [operate-first/support#343]
### Target cluster

Morty

### Team name

examples-openshift-pub

### Desired project names

examples-openshift-pub

### Project description

EMEA Deployment of https://examples.openshift.pub 

### Users needing access

rbo

### Namespace Quota

Medium

### Your GPG key or contact

https://keys.openpgp.org/search?q=rbohne@redhat.com

**Comment by tumido** [comment]
Let's attempt this via hitchhikers guide. cc @mimotej

**Comment by rbo** [comment]
pr merged
