### ISSUE TITLE
Issue Template "Onboard to Continuous Deployment" - broken link

### ISSUE THREAD

**Issue by rbo** [operate-first/support#345]
**Describe the bug**

The issue template  "Onboard to Continuous Deployment " has a broken link: 
Broken: https://github.com/operate-first/apps/tree/master/cluster-scope/base/groups
Should be: https://github.com/operate-first/apps/tree/master/cluster-scope/base/user.openshift.io/groups ? 

https://github.com/operate-first/support/blob/main/.github/ISSUE_TEMPLATE/onboarding_argocd.md#creating-a-new-project

**Comment by HumairAK** [comment]
yes it should, good call! mind submitting a pr?

**Comment by rbo** [comment]
> yes it should, good call! mind submitting a pr?

Unfortunately I don't have time next weeks :-(

**Comment by tumido** [comment]
Fixed by https://github.com/operate-first/support/pull/325
