### ISSUE TITLE
NEW PROJECT: Synapse server

### ISSUE THREAD

**Issue by vrutkovs** [operate-first/support#347]
### Target cluster

Smaug

### Team name

matrix-synapse

### Desired project names

matrix-synapse, matrix-element, matrix-postgresql, matrix-slack-bridge, 

### Project description

This project sets up [Matrix](https://matrix.org) chat server. The chat rooms could connect to other servers, making it a federated solution. Matrix also has a concept of bridges, which allows it emulate users from other chat solutions, i.e. Slack, Discord, IRC etc.

It uses PostgresQL database to store messages. Slack bridge is also deployed, so that various OKD-related Slack channels could be bridged on single server.
Matrix uses several OIDC providers for authentication, at this point we'll probably use Github for authentication. All components would be deployed using ArgoCD using Helm charts (upstream Synapse/Bitnami's Postgresql) and several kustomized components (Sealed Secrets and Slack bridge deployment)

See https://github.com/vrutkovs/synapse-operatefirst

### Users needing access

vrutkovs@redhat.com

### Namespace Quota

Small

### Your GPG key or contact

`DB861D01D4D1138A993ADC1A3D54B6723B20C69F` on keys.gnupg.net

**Comment by vrutkovs** [comment]
/cc @durandom

This is not urgent, but would be lovely to have

**Comment by durandom** [comment]
This is great, it's the first contact into the OKD community.
Once the Smaug https://github.com/operate-first/SRE/issues/359 cluster is up we can start onboarding.

@vrutkovs you also should consider using our ArgoCD for deploying your workloads

**Comment by durandom** [comment]
@vrutkovs I think you want to start with creating a PR to onboard a new project: https://github.com/operate-first/hitchhikers-guide/blob/main/pages/onboarding_project.ipynb

@HumairAK can point you to docs how to get your project into argocd

**Comment by HumairAK** [comment]
Yep as @durandom said, the onboarding notebook will help you get set up with a ocp group/namespace etc. Once done you can get onboarded to argocd by following these docs [here](https://github.com/operate-first/support/blob/main/docs/onboarding_to_argocd.md), the links here somewhat outdated, I just sent in a PR to update this doc [here](https://github.com/operate-first/support/pull/432), which should be in soon.

**Comment by HumairAK** [comment]
Just fyi if there's still interest on this please remove the stale as per the command above. Also the docs mentioned above have been once again updated/moved, and the process to onboard has been made slightly easier: https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html

**Comment by vrutkovs** [comment]
/remove-lifecycle stale

This is still planned, but deferred due to a lack of time :/

**Comment by HumairAK** [comment]
No problem! Know the feeling :)
