### ISSUE TITLE
create content TLS route for the pulp-content

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#353]
**Is your feature request related to a problem? Please describe.**
It would be great to have a TLS route created for the `pulp-content`. This would the serve endpoint for serving the pulp content for installing the packages served from the pulp instance on the operate-first.

**Describe the solution you'd like**
create a TLS Route: `pulp-content.operate-first.cloud`
configure against: `pulp-content-thoth-pulp-experiments.apps.zero.massopen.cloud`
This has to be configured for the pulp instance of the operate-first. 

**Describe alternatives you've considered**
None

**Additional context**
This has to be set up from the google cloud.

**Comment by harshad16** [comment]
cc: @fridex @tumido

**Comment by tumido** [comment]
`pulp-content.operate-first.cloud` is CNAMEd to the Zero cluster app router. You can define your namespaced route on your own. :slightly_smiling_face:

**Comment by fridex** [comment]
> `pulp-content.operate-first.cloud` is CNAMEd to the Zero cluster app router. You can define your namespaced route on your own.

Thanks, created a route in `thoth-pulp-experiments` namespace. Could it be also secured using TLS?

**Comment by harshad16** [comment]
Here is the TLS set route: https://pulp-content.operate-first.cloud

**Comment by harshad16** [comment]
thanks everyone.
