### ISSUE TITLE
[TASK] Cleanup obsolete group memberships after Keycloak migration

### ISSUE THREAD

**Issue by tumido** [operate-first/support#357]
After users are migrated to Operate First SSO, we should clean up existing Groups and remove members no longer active in community.

- [ ] remove `ipolonsk` https://github.com/operate-first/apps/pull/842#discussion_r669958990
- [ ] remove `martinpovolny` https://github.com/operate-first/apps/pull/842#discussion_r669958457 https://github.com/operate-first/apps/pull/842#discussion_r691335959
- [ ] remove `sankbad` https://github.com/operate-first/apps/pull/842#discussion_r669958457

**Comment by HumairAK** [comment]
all pr's look merged, marking as closed.
