### ISSUE TITLE
Add Fabricio to thoth-pulp-experiments namespace

### ISSUE THREAD

**Issue by fridex** [operate-first/support#359]
Could you please please add @fao89 (kerberos: faguiard) to the `thoth-pulp-experiments` namespace with edit permissions?

Thanks in advance.

**Comment by fao89** [comment]
@fridex I believe this is not needed anymore, I found the issue, and it seems to be working now, please test it:
https://pulp.operate-first.cloud/pypi/test/simple/

**Comment by fao89** [comment]
Actually, I found another error, pulp-operator keeps reconciling with this error:

```
TASK [pulp-api : pulp-file-storage persistent volume claim] ********************\r
\u001b[1;30mtask path: /opt/ansible/roles/pulp-api/tasks/main.yml:21\u001b[0m
\u001b[0;31mfailed: [localhost] (item=pulp-file-storage) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"error\": 403, \"item\": \"pulp-file-storage\", \"msg\": \"Failed to patch object: b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"persistentvolumeclaims \\\\\\\\\\\"example-pulp-file-storage\\\\\\\\\\\" is forbidden: exceeded quota: thoth-pulp-experiments-custom, requested: requests.storage=50Gi, used: requests.storage=59Gi, limited: requests.storage=60Gi\\\",\\\"reason\\\":\\\"Forbidden\\\",\\\"details\\\":{\\\"name\\\":\\\"example-pulp-file-storage\\\",\\\"kind\\\":\\\"persistentvolumeclaims\\\"},\\\"code\\\":403}\\\
'\", \"reason\": \"Forbidden\", \"status\": 403}
```

**Comment by fridex** [comment]
> @fridex I believe this is not needed anymore

Given your pulp expertise, it might be good to have you available in the namespace.

> Actually, I found another error, pulp-operator keeps reconciling with this error:
> 
> ```
> TASK [pulp-api : pulp-file-storage persistent volume claim] ********************\r
> \u001b[1;30mtask path: /opt/ansible/roles/pulp-api/tasks/main.yml:21\u001b[0m
> \u001b[0;31mfailed: [localhost] (item=pulp-file-storage) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"error\": 403, \"item\": \"pulp-file-storage\", \"msg\": \"Failed to patch object: b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"persistentvolumeclaims \\\\\\\\\\\"example-pulp-file-storage\\\\\\\\\\\" is forbidden: exceeded quota: thoth-pulp-experiments-custom, requested: requests.storage=50Gi, used: requests.storage=59Gi, limited: requests.storage=60Gi\\\",\\\"reason\\\":\\\"Forbidden\\\",\\\"details\\\":{\\\"name\\\":\\\"example-pulp-file-storage\\\",\\\"kind\\\":\\\"persistentvolumeclaims\\\"},\\\"code\\\":403}\\\
> '\", \"reason\": \"Forbidden\", \"status\": 403}
> ```

Related: https://github.com/operate-first/support/issues/362#issue-977698424 Thanks for spotting this 👍🏻

**Comment by harshad16** [comment]
seems like this was already fixed with this inclusion: https://github.com/operate-first/apps/blob/b0eb7e7939887b97b033b4abeef5cb60359c6d56/cluster-scope/base/user.openshift.io/groups/pulp/group.yaml#L7
thanks, everyone.
