### ISSUE TITLE
Access Request: Cloudbeaver

### ISSUE THREAD

**Issue by chauhankaranraj** [operate-first/support#360]
As a data scientist working on aicoe-aiops/ocp-ci-analysis#78 and aicoe-aiops/ocp-ci-analysis#344, I need access to cloudbeaver

Username: kachauha
Email id: kachauha at redhat dot com

/cc @hemajv @HumairAK

**Comment by HumairAK** [comment]
this looks like it might be stale @chauhankaranraj is there any access needed still? let us know, otherwise please close this issue if it's resolved -- thanks!
