### ISSUE TITLE
Hook up Hue with Trino to replace cloudbeaver

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#361]
Currently cloudbeaver does not have oauth enabled, and the plan is to only add it to [their enterprise version](https://github.com/dbeaver/cloudbeaver/issues/443). AFAIK hue accomplishes pretty much the same thing, and is also an ODH offering with [oidc](https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L772) support. So let's try `hue` out. 

Acceptance criteria: 

- [ ] 1. Confirm hue meets the needs currently met by cloudbeaver
- [ ] 2. Hook up trino to hue and confirm a successful connection (instructions [here]() https://docs.gethue.com/administrator/configuration/connectors/). Note that "presto" is the old name for "trino". 
- [ ] 3. Confer with @hemajv that hue deployment fulfills the requirement and is functioning 
- [ ] 4. Add oauth / oidc connectivity to dex (ini config values [here](https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L772) )

**Comment by HumairAK** [comment]
@hemajv can you provide the list of features that need to be supported by hue that cloudbeaver provides, so @suppathak knows what to look for.

**Comment by durandom** [comment]
@HumairAK please consult with @rimolive and the ODH community if that's a recommended approach.

**Comment by HumairAK** [comment]
@rimolive WDYT? We basically would like to stop relying on cloudbeaver/dbeaver if we can instead use Hue.

**Comment by rimolive** [comment]
I believe it's doable since Presto/Trino connector in Hue also uses PyHive, but make sure to enable user impersonation in the connector.

https://docs.gethue.com/administrator/configuration/connectors/#trino
