### ISSUE TITLE
Increase thoth-pulp-experiments-custom persistent volume quota

### ISSUE THREAD

**Issue by fridex** [operate-first/support#362]
### Requested actions

Please increase `thoth-pulp-experiments-custom` quota in thoth-pulp-experiments namespace. See https://github.com/operate-first/support/issues/359#issuecomment-904159934 as a reference.

### Questionnaire

1. **Team name**: Thoth

**Comment by HumairAK** [comment]
@fridex what quota do you need updated? You can also put in a pr updating the file here: https://github.com/operate-first/apps/blob/master/cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml with the preferred resource quotas.

**Comment by fridex** [comment]
@HumairAK thanks, updated in https://github.com/operate-first/apps/pull/924
