### ISSUE TITLE
Support for multiple buckets in Trino and access permissions

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#364]
**Is your feature request related to a problem? Please describe.**
Right now we can only configure one bucket to trino, and we have no ways of controlling access to it.

**Describe the solution you'd like**
We would like to be able to support multiple buckets in trino, and follow this up with onboarding for "adding your bucket", and controlling who can query these buckets, the more granular we can set the permissions the better. 

We need this for the OS-Climate cluster as well as Zero cluster.

**Comment by erikerlandson** [comment]
trino examples in python
https://gitlab.cee.redhat.com/data-hub/dh-code-samples/-/tree/master/trino
