### ISSUE TITLE
[TASK] [Hue] Add documentation for accessing MOC Hue

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/support#37]
**User story**
Need documentation on how to access the [MOC Hue](https://hue-opf-datacatalog.apps.cnv.massopen.cloud) environment.

**Additional context**
This documentation should include generic credentials that can be used to access Hue.

**Comment by HumairAK** [comment]
can we have the docs added [here](https://github.com/operate-first/apps/tree/master/docs/odh) thanks.

**Comment by durandom** [comment]
@4n4nd let's just put the user/pw on the website in the 3rd column of that [table](https://www.operate-first.cloud/users/odh-moc-support/#component-status)

**Comment by 4n4nd** [comment]
let's keep this issue open, since we still need the docs

**Comment by HumairAK** [comment]
Woops I think my "related" comment must have caused sesheta to close it. That was unintentional :joy:

**Comment by 4n4nd** [comment]
I think github closes any issue that you link with a PR using the UI
