### ISSUE TITLE
Requesting resources for Fybrik (previously Mesh for Data)

### ISSUE THREAD

**Issue by eletonia** [operate-first/support#370]
### Requested actions

We would like cluster-scoped resources necessary for [Fybrik](https://fybrik.io/v0.4/) deployed on the MOC Zero cluster.
We reduced our RBAC requirements and generated the raw rendered yaml files that we would like deployed here:
https://github.com/fybrik/fybrik/tree/master/samples/operate-first

Please ignore the fybrik-crd.yaml and fybrik.yaml files. The cluster-scoped resources we would like deployed are organized by `kind` into directories.

For the non-cluster scoped resources, we need a `fybrik-system` namespace, `fybrik` user group, and `fybrik` ArgoCD project. Please let us know once these are created. 

@roee88 @ronenkat @durandom 

### Questionnaire

1. **Team name**:       Fybrik

**Comment by durandom** [comment]
@mimotej @Gregory-Pereira @4n4nd can you guide @eletonia to similar PRs for this - or documentation?

**Comment by 4n4nd** [comment]
@eletonia 
1. All our cluster-scoped resources should go [here](https://github.com/operate-first/apps/tree/master/cluster-scope/base), they are organized as `apiVersion/kind/...`.
2. For namespaces and groups, we have a [cli tool](https://github.com/operate-first/opfcli#usage) that you can use to create the necessary manifests ([an example PR](https://github.com/operate-first/apps/pull/818)).
3. For the argocd app, you can create the `AppProject` [here](https://github.com/operate-first/argocd-apps/tree/main/projects) and the argocd app in your desired environment [available here](https://github.com/operate-first/argocd-apps/tree/main/envs).

Could you please create PRs for the above mentioned changes? Please let us know if you need any help with them.

Also, just a heads up that we are currently moving clusters from `moc/zero` to `moc/smaug` so the PRs might take a few days to be applied.

cc @HumairAK can add any other instructions that I missed

**Comment by eletonia** [comment]
@4n4nd I tried to create an application on [ArgoCD](https://argocd.operate-first.cloud/applications) using this YAML:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fybrik
spec:
  destination:
    name: smaug
    namespace: fybrik
  source:
    path: charts/fybrik
    repoURL: 'https://github.com/fybrik/fybrik'
    targetRevision: HEAD
  project: fybrik
```
But I'm getting this permission denied error even though I'm logged in through GitHub:
![Screen Shot 2021-09-23 at 12 51 24 PM](https://user-images.githubusercontent.com/6710338/134551886-595e9e1d-e13a-49a0-a8f6-dc2ff38c9039.png)

Also, I don't see `Fybrik` as one of the ArgoCD projects.. am I missing something?

**Comment by eletonia** [comment]
@durandom Yes I'm able to login with the `operate-first` SSO option now since [this PR](https://github.com/operate-first/apps/pull/1217) was merged

However, I'm still seeing this `permission denied` error when trying to make a new app as I mentioned above.
![Screen Shot 2021-10-21 at 2 50 28 PM](https://user-images.githubusercontent.com/6710338/138339005-037ea597-c034-4ae3-9645-a344351b4670.png)
