### ISSUE TITLE
deploy OpenShift into POD

### ISSUE THREAD

**Issue by durandom** [operate-first/support#375]
POD - Penguin on Demand https://pod.penguincomputing.com/ 

- [ ] bootstrap a cluster
- [ ] get cluster under ArgoCD / ACM control
- [ ] deploy JH

might re-use some of the Hetzner docs: https://github.com/operate-first/hetzner-baremetal-openshift

this is a placeholder issue. Folks from SLAC, RH and POD will cc on this issue to get started.

**Comment by durandom** [comment]
@aiyagari can you help deploying to POD?

@slac-omarq @ryancoffee we need specs for the cluster from you

**Comment by ryancoffee** [comment]
Just tried logging into the server and it is down, from memory, 750 GB sys mem, 2 TB NVME for storage, 20 quad cores, V100 (lower memory version), P40, P4, and is host to a GraphCore M-2000 (4 IPUs, working on upgrading to 16 IPUs but that is months out.)
