### ISSUE TITLE
rick: no internal registry configured -> build break

### ISSUE THREAD

**Issue by goern** [operate-first/support#377]
**Describe the bug**
Error starting build: an image stream cannot be used as build output because the integrated container image registry is not configured

**To Reproduce**
1. Go to https://console-openshift-console.apps.rick.emea.operate-first.cloud/k8s/ns/thoth-website-prod/builds/thoth-station-website-1/events

**Expected behaviour**
Builds succeed, image is delivered to an ImageStreamTag on the internal registry of rick.

**Screenshots**
n/a

**Additional context**
n/a

/kind bug
/priority important-soon
/area user

**Comment by goern** [comment]
Related-To: https://github.com/operate-first/support/issues/376

**Comment by rbo** [comment]
Image registry was forgotten at https://github.com/operate-first/hetzner-baremetal-openshift/issues/12   :-( 

Another topic for the cluster onboarding checklist... 

/cc @tumido

**Comment by goern** [comment]
@rbo could you deploy it now?

**Comment by goern** [comment]
https://docs.openshift.com/container-platform/4.8/registry/configuring_registry_storage/configuring-registry-storage-baremetal.html

@tumido @Gregory-Pereira could one of you take this?

/priority critical-urgent
/remove-priority important-soon
