### ISSUE TITLE
[TASK] install a new `registry-secret` for os-climate

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/support#378]
**User story**
as an os-climate admin, I need to enable aicoe-ci image builds pushed to the quay.io os-climate org

I have downloaded the kubernetes secret from the robot account, let me know how I should get that to you.

reference:
https://www.operate-first.cloud/blueprints/continuous-delivery/docs/setup_cd_pipeline.md#configuring-build-requirements

**Comment by harshad16** [comment]
send them to me via email. 
i will set them in the service.

**Comment by pacospace** [comment]
Related-To: https://github.com/AICoE/aicoe-ci/issues/137

**Comment by harshad16** [comment]
Please use the secret-name as `os-climate-pusher-secret` in your .aicoe-ci.yaml

**Comment by erikerlandson** [comment]
Awesome, thanks!

**Comment by erikerlandson** [comment]
this new push secret is working so I will close this issue
