### ISSUE TITLE
NEW PROJECT: access logs for investigation regarding machine learning

### ISSUE THREAD

**Issue by yrobla** [operate-first/support#379]
### Requested actions

I am Yolanda from Red Hat. I need to get access to logs, in order to work on a machine learning project as part of an university degree. I am interested in getting logs from insights, in order to work on a model for error prediction.

### Questionnaire

1. **Team name**:
Yolanda Robla <yroblamo@redhat.com>

**Comment by durandom** [comment]
@4n4nd can you point @yrobla to the documentation to get access to the loki logs?
