### ISSUE TITLE
Prow: pods cant write log

### ISSUE THREAD

**Issue by goern** [operate-first/support#380]
**Describe the bug**
All of the Pods created for Prow jobs fail with a very similar error message: `{"component":"initupload","error":"failed to upload to blob storage: failed to upload to blob storage: encountered errors during upload: [writer close error: blob (key \"prow-logs/logs/periodic-close-rotten/latest-build.txt\") (code=Unknown): RequestError: send request failed\ncaused by: Put \"http://rgw-openshift-storage.apps.zero.massopen.cloud/ci-prow-artifacts--a96a53d7-728c-4ebb-bfc4-2f9e4dc68070/prow-logs/logs/periodic-close-rotten/latest-build.txt\": dial tcp 192.12.185.104:80: connect: connection refused]","file":"prow/cmd/initupload/main.go:45","func":"main.main","level":"fatal","msg":"Failed to initialize job","severity":"fatal","time":"2021-09-08T05:23:34Z"}`

**To Reproduce**
1. Go to https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-ci-prow/pods/d423a905-1064-11ec-a780-0a580a8304f2/logs?container=initupload
2. look at initupload container logs

**Expected behaviour**
no failure.

**Additional context**
n/a

/kind bug
/priority critical-urgent
/assign @harshad16 
/assign @Gregory-Pereira 
/assign @HumairAK 
/assign @anishasthana

**Comment by harshad16** [comment]
```
curl -I http://rgw-openshift-storage.apps.zero.massopen.cloud                                                                        
curl: (7) Failed to connect to rgw-openshift-storage.apps.zero.massopen.cloud port 80: Connection refused
```

zero cluster seems not to be functioning :(

**Comment by harshad16** [comment]
This issue is fixed by using the ceph from rick cluster.
