### ISSUE TITLE
Onboard Koku Cluster

### ISSUE THREAD

**Issue by durandom** [operate-first/support#381]
@chargio maintains a long-running cluster in AWS:

https://console-openshift-console.apps.costdemo.openshift.mbulab.xyz/

We would like to 

- [ ] adopt the cluster to our ACM instance
- [ ] manage cluster upgrades
- [ ] deploy real or play workloads to the cluster via ArgoCD

Benefits for our community:
- adds additional compute capacity for the Operate First community cloud
- adds a long running AWS cluster

Benefits for Koku / CostManagement:
- real workloads on cluster
- less maintenance 

cc @kholdaway

**Comment by durandom** [comment]
@HumairAK can you comment on what is needed to adopt a cluster? Right now the cluster has oauth for GH configured.

@mimotej please document this process in the hitchhiker guide

**Comment by chargio** [comment]
Please send me the Github handles you want to add as cluster-admin, and I will do it (it will take me a few minutes only)

**Comment by chargio** [comment]
Are you still interested in this issue?

**Comment by HumairAK** [comment]
/remove-lifecycle stale

@chargio we now allow users to create their own managed cluster sets in our acm instance: https://www.operate-first.cloud/apps/content/acm/adding_users_to_acm.html

This way users can onboard their cluster to the operate-cluster fleet. ArgoCD will be auto configured to be able to deploy to this cluster. And you can be onboarded to ArgoCD via: https://www.operate-first.cloud/apps/content/argocd-gitops/onboarding_to_argocd.html 

LMK if you have any questions. We can also tie this cluster to our keycloak instance, and delegate auth via keycloak. 

If you would also like to manage your cluster via gitops through the operate first org (i.e. store your cluster manifests in this git org, and have argocd depoy them, perform cluster upgrades via prs, etc.), let us know! We don't have exact docs on this yet, but if there's interest we can guide you through it.
