### ISSUE TITLE
[TASK] Deploy VolSync (previously known as Scribe) to sync/backup PVCs

### ISSUE THREAD

**Issue by tumido** [operate-first/support#386]
**User story**
Offer users a way to distribute their PVC content across Operate First clusters

**Additional context**
https://volsync.readthedocs.io/en/latest/index.html
https://github.com/backube/volsync

**Acceptance Criteria**
- [ ] 

**Linked epics / issues**

**Comment by screeley44** [comment]
@tumido - John Strunk is the creator and my team worked very closely on this project with him and would be able to assist when needed, just let me know and I can pull in John or other resources to assist

**Comment by screeley44** [comment]
@tumido - would this be a part of the "managed services" offered? volsync is also going to be in tech preview for RHACM 2.4, just fyi

**Comment by screeley44** [comment]
Also, VolSync currently only handles file and block pvc's, might want to think about how to handle object/bucket data as well (NooBaa, rclone, ???)

**Comment by HumairAK** [comment]
@screeley44 

@tumido is no longer direclty involved with operate-first operations :cry: 
Regardless -- we'll be meeting with acm/volsync folks this Monday to get more insight/collaboration into it. I'll extend you an invite as well!

**Comment by HumairAK** [comment]
@screeley44 in our last acm meeting I believe you mentioned someone you had in mind that can help out with this (unless I misheard), let us know if that's still the case! From what I understand, this will mostly consist of just installing the policy manifest onto the smaug cluster. 

@larsks (fyi)

**Comment by HumairAK** [comment]
Volsync was deployed on smaug.
