### ISSUE TITLE
[TASK] Consolidate onboarding docs and ADRs to be up to date

### ISSUE THREAD

**Issue by tumido** [operate-first/support#39]
**User story**
User should be able to follow a single doc to fully onboard to MOC via ArgoCD.

**Additional context**
Including:
- user management
- secrets management
- namespace management
- application deployment to target MOC cluster of choince

**Acceptance Criteria**
- [ ] A single doc with such checklist is present
- [ ] ADRs are up to date with the implementation

**Comment by HumairAK** [comment]
Just laying down some preliminary thoughts. So the primary use case for this doc: 

- The first link we send to anyone requesting MOC access

I would like to be able to send this Doc to a person if they ask the following questions: 

**Onboarding MOC**
- How do I get access to MOC?
- I have an account on MOC, how do I create a namespace? 
- My team has a namespace, how do _I_ get access to this namespace? 

**Onboarding ArgoCD**
- How can I or my team get access to ArgoCD to use to deploy our apps? (bonus: why should the team use ArgoCD, we need to promote this)
- How can I use ArgoCD / Kustomize for secret management via GitOps? 
- Where can I get support/help?

Every explanation should also have pre-requisites if required (e.g. kustomize installed, etc.). The doc can (and should) link to other docs that have detailed explanations.

We could create an ISSUE onboarding template, that gives teams a form to fill out like "Team name, users, project name (for argocd), etc."

**Comment by HumairAK** [comment]
I think we've checked all boxes, final step would probably be to add these to the operate first website, then we can close the ticket. Thoughts?

**Comment by tumido** [comment]
Yes. We have some future docs tasks pending as well, but for the onboarding part of it, we should be fine. :slightly_smiling_face:

**Comment by HumairAK** [comment]
I think remaining items before closing this ticket:
- [Onboarding script merge](https://github.com/operate-first/apps/pull/121)
- Add onboarding docs to operate-first website

**Comment by tumido** [comment]
I think this is done now. Closing

https://www.operate-first.cloud/users/support/docs/onboarding_to_cluster.md
