### ISSUE TITLE
Demo cluster required for OSS session on AI4CI

### ISSUE THREAD

**Issue by oindrillac** [operate-first/support#392]
We would need a demo cluster to be provisioned for our demo at [OSS on AI4CI](https://sched.co/lBwp) which needs to be active until Sep 30.

**Users Needed:**
1-2

**Components Needed:**
- JupyterHub with Elyra  with profile `Extra Large - Memory intensive`
- Kubeflow Pipelines
- Trino
- Cloudbeaver
- SuperSet
- Cluster with Seldon Operator deployed

cc:  @aakankshaduggal @MichaelClifford @HumairAK @durandom

**Comment by HumairAK** [comment]
quick approximation on resources needed, donnu about kfpipelines and seldon

JupyterHub with Elyra - 2 core, 2gb mem, 1gb storage
JH Extra Large Pod x2 - 8 cores, 100 gb mem, 40gb storage (?) 
Kubeflow Pipelines - no clue @4n4nd got any ideas? 
Trino - 20 cores, 80gb mem, 20gb storage (taken from zero's specs, we could maybe lower this a little here depending on data size/query size)
Cloudbeaver - 1 core, 2gb mem, 2gb storage
SuperSet - 4 core, 4gb mem, 1gb storage
Cluster with Seldon Operator deployed - no clue

**Comment by HumairAK** [comment]
trino / JH pods are the big resource hogs, could maybe reduce trino down to 8cores/40gb mem and see where that lands us if we need to

**Comment by oindrillac** [comment]
We also need an S3 storage, forgot to add that. Perhaps we can use the one on rick which @4n4nd set up for us?

**Comment by 4n4nd** [comment]
> We also need an S3 storage, forgot to add that. Perhaps we can use the one on rick which @4n4nd set up for us?

yeah the bucket on Rick should be fine for that.

**Comment by 4n4nd** [comment]
> Kubeflow Pipelines - no clue @4n4nd got any ideas?

I am not sure, I think this is configured by the user for each pipeline run

**Comment by harshad16** [comment]
As you pointed out, the pipeline resources are indeed set by users.
on account of the deployment of kubeflow pipeline itself, i think it requires 2 cpu and more than 4 gb of memory.
more details: https://github.com/kubeflow/pipelines/search?p=6&q=cpu

**Comment by durandom** [comment]
@tumido can you try to guess what such a cluster in AWS would cost us? Ping @codificat to get numbers if needed.
@HumairAK what are the odds that either smaug is available by then? 
@HumairAK @tumido can we use or upgrade rick for that?

**Comment by HumairAK** [comment]
we are spinning up a cluster on aws already, expected to have all the tools mentioned above provisioned by eod

**Comment by HumairAK** [comment]
JupyterHub: https://jupyterhub-opf-jupyterhub.apps.ai4ci.aws.operate-first.cloud/
Superset: https://superset-secure-opf-superset.apps.ai4ci.aws.operate-first.cloud
Trino: https://trino-secure-opf-trino.apps.ai4ci.aws.operate-first.cloud
Cloudbeaver: https://cloudbeaver-opf-trino.apps.ai4ci.aws.operate-first.cloud
ML Pipelines: http://ml-pipeline-ui-kubeflow.apps.ai4ci.aws.operate-first.cloud
Cluster: https://console-openshift-console.apps.ai4ci.aws.operate-first.cloud
Credentials: https://console-openshift-console.apps.ai4ci.aws.operate-first.cloud/k8s/ns/creds/secrets/credentials

**Comment by aakankshaduggal** [comment]
Thank you @HumairAK 
I was able to access them :smile:

**Comment by HumairAK** [comment]
This was resolved, please re-open if there's anything left.
