### ISSUE TITLE
Missing option for requesting GPU's through spawner UI in OS-Climate cluster

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#393]
We are looking to test out use of the GPU on the os-climate cluster, but the jupyterhub launcher is missing the "number of GPU's" option (see below image). What needs to happen to 1) have this option added back to the UI. 2) or is there another method by which we can request a GPU node for our JH instance?

![image](https://user-images.githubusercontent.com/4494906/134025464-59911285-2034-467f-8d11-839567dc8913.png)

**Comment by tumido** [comment]
cc @vpavlin @LaVlaS @anishasthana what do we need to do to get those options to appear?

**Comment by MichaelClifford** [comment]
This has been done by @erikerlandson

**Comment by MichaelClifford** [comment]
https://github.com/operate-first/apps/pull/1034
