### ISSUE TITLE
Install kafka on rick cluster

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#394]
**Is your feature request related to a problem? Please describe.**
Project thoth components use kafka service, it would be great if we can install kafka on rick cluster.
kafka is shipped with odh, we can leverage that 

Lets install a small kafka, to not overload the cluster.
we can have :
2 replica of kafka
3 replica of zookeeper

this should fit in the larger type resource quota.

**Describe the solution you'd like**
install via odh

**Comment by harshad16** [comment]
related-to: https://github.com/thoth-station/thoth-application/issues/1769

**Comment by tumido** [comment]
Resolved via https://github.com/operate-first/apps/pull/1033 and https://github.com/operate-first/apps/pull/1052
