### ISSUE TITLE
Thoughts on provisioning an AWS monitoring cluster for our monitoring stack? 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#398]
With the zero cluster down, and smaug currently lacking storage, we do not have any monitoring in place. This I think begs a very critical question -- should the monitoring stack be on the same cluster as where we run our user workloads? We are currently in the blind, with no proper visualizations/metrics/etc as we had this originally running on zero. All the effort towards aggregating metrics onto a singular thanos and then visualizing in grafana as a one place go to solution for monitoring/visualizations has been blocked for quite some time as well. 

In principal I think it's just better design to have monitoring be separated from other workloads and run in a more stable environment. I don't think the monitoring cluster would require very many resources, we can keep the storage outside aws for thanos to write to. 

WDYT?

**Comment by 4n4nd** [comment]
I think this is a great idea :+1:

**Comment by HumairAK** [comment]
@tumido @4n4nd @durandom

**Comment by durandom** [comment]
what about the previous/current infra cluster?

**Comment by HumairAK** [comment]
The one downside is `infra` is another cluster that will be monitored by the monitoring stack with other workloads, which could potentially affect stability of the cluster. 

So if we have monitoring on infra and infra goes down: 
- we lose monitoring
- we lose infra 

So we won't have alerting and can't use monitoring to diagnose issues with infra. 

If we have monitoring standalone, then we have monitoring if infra goes down. Of course the monitoring cluster _could_ also go down, but in this case we're just losing monitoring, and no actual services, so we theoretically have time to resolve this incident.


That being said, our claim is infra should be extremely stable, so I don't have much issue with putting it there, though separate cluster is ideal imo.

**Comment by durandom** [comment]
as the long term storage for logs and metrics should be in NERC, I would keep it local to this datacenter
let's revisit deploying it to a cloud provider once we run into troubles

**Comment by HumairAK** [comment]
The data store does not need to be aws s3 and can be located anywhere, fyi @4n4nd

**Comment by 4n4nd** [comment]
> The data store does not need to be aws s3 and can be located anywhere, fyi @4n4nd

I remember @codificat mentioning something about that increasing data transfer costs, so that might not be the best idea

**Comment by codificat** [comment]
> > The data store does not need to be aws s3 and can be located anywhere, fyi @4n4nd
> 
> I remember @codificat mentioning something about that increasing data transfer costs, so that might not be the best idea

About AWS data transfers: AWS charges for outgoing traffic. Other costs aside, basically you can get as much data into it as you want, but then you pay when/if you send it out (or when you transfer across regions/AZs). S3 details: https://aws.amazon.com/s3/pricing/   inbound is $0, outbound after 1GB/month is 0.09$ per GB.

EC2 and other services have a similar scheme, e.g. https://aws.amazon.com/ec2/pricing/on-demand/#Data_Transfer
