### ISSUE TITLE
Enable OpenTelemetry Tracing in CRI-O, Etcd, Kube APIServer

### ISSUE THREAD

**Issue by sallyom** [operate-first/support#401]
**Is your feature request related to a problem? Please describe.**
As of kube-1.22 and etcd 3.5, exporting OpenTelemetry trace data is experimental
* Etcd: https://etcd.io/docs/v3.5/op-guide/monitoring/#distributed-tracing
* APIServer: https://kubernetes.io/blog/2021/09/03/api-server-tracing/ 

And CRI-O also has opentelemetry tracing support:
* https://github.com/cri-o/cri-o/pull/4883

**Describe the solution you'd like**
Enabling tracing in CRI-O, APIServer and Etcd will benefit the K8s and OpenTelemetry communities:
* Document and automate the enabling of OpenTelemetry tracing in etcd and APIServer.
* Calculate performance overhead of exporting OpenTelemetry traces.
* Document the collection and visualization of trace data with various tracing backends. OpenTelemetry Collector and Jaeger are available through OperatorHub.
* Demonstrate how tracing can improve the performance and debugging of K8s, weighed against the performance overhead of exporting traces.
* Investigate how instrumented applications running on K8s interact with the instrumented core components (etcd, apiserver)? 

Enabling tracing will provide valuable data for research:
* Would like to deploy varied workflows & collect traces from the platform as well as the applications running on it.
* Does the tracing instrumentation make sense for K8s architecture? For what use-cases? 

**Describe alternatives you've considered**
Setup to enable tracing in a pseudo environment (kubeam single node): https://github.com/sallyom/otel-kubeadm

**Additional context**
Etcd, APIServer, and CRI-O tracing is experimental upstream, not enabled by default. In order to enable in Operate First I will be investigating what, if any, modifications to OpenShift operators are required. Kubelet tracing may be added in a follow-up issue, instrumentation is in progress upstream.

@durandom

**Comment by durandom** [comment]
@sallyom are you looking for ways to enable this in Etcd in our environment? We define cluster-scope configuration in https://github.com/operate-first/apps/tree/master/cluster-scope 
Is this something we would have to do at boot time? I have no idea on how to pass cli arguments :/

@HumairAK @tumido

**Comment by tumido** [comment]
@sallyom ok, how do we know then the opentelemetry tracing PR is deployed?

>  can we deploy a cluster with a latest-from-main-branch CRI-O?

I'm not sure. We've never done that, if you can help us customizing OCP install we can try doing it. Can such modification survive OCP upgrades/cluster scaling?

@larsks do you have any thoughts/knowledge how to do these things?

**Comment by sallyom** [comment]
@tumido I missed that! sorry. Can you tell me what version of OCP is running? Do you run w/ latest stable release? So, 4.9? 

Enabling tracing in CRI-O requires a drop-in file on the host, that _might_ survive upgrade, I'll check on that. This will be easiest to start with, not sure how much benefit we'll get, but we'll be able to get some information about the overhead of tracing, so that will be good.

**Comment by 4n4nd** [comment]
@sallyom all our clusters run OCP v4.8.x, I am not sure if 4.9 is out yet

**Comment by sallyom** [comment]
@4n4nd CRI-O instrumentation hasn't landed in any release (will in 1.23 AFAICT) also, there isn't a clean way to enable tracing feature gate in K8s/apiserver and/or etcd in OCP. I'll keep this issue updated with any relevant info.

**Comment by sallyom** [comment]
moving discussion over to the Kspan issue, until there's news with enabling tracing in OpenShift: https://github.com/operate-first/support/issues/491

**Comment by durandom** [comment]
/remove-lifecycle rotten

@sallyom are you still planning to work on this?

**Comment by durandom** [comment]
/remove-lifecycle stale

@sallyom has there been any progress on this? should we close it or do you still plan to get tracing enabled?
