### ISSUE TITLE
deploy OpenStack

### ISSUE THREAD

**Issue by durandom** [operate-first/support#403]
With the zero cluster decommissioned, we might consider deploying an experimental OpenStack cluster to that hardware.
The process should follow a GitOps approach as much as possible.

https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/docs/hardware.md

@larsks if you don't have any strong objections, would you work with @EmilienM to give him access to the hardware?

**Comment by msdisme** [comment]
If we plan to do this it would be good to base the work on the installation that RH consulting helped craft for the NERC.   I'll get a link to the git repository for that.
