### ISSUE TITLE
NEW PROJECT: Tremor.rs

### ISSUE THREAD

**Issue by GaryPWhite** [operate-first/support#406]
### Target cluster

Infra

### Team name

tremor-sample

### Desired project names

tremor-sample-ns

### Project description

Sample k8s application using Tremor to process logging and export to Kafka 

(as Loki becomes available in the mid-to-long term, we may use this namespace to have applications exporting to both)

for more details and background conversation, consult myself or @durandom 

### Users needing access

I do not have a username yet, but myself and I'm happy to do what I need to to do provide!

### Namespace Quota

Small

**Comment by tumido** [comment]
Hey @GaryPWhite do you have any specific reason to request `Infra` cluster? Or would any cluster would do? We're currently managing 2 Kafka deployments - one on Smaug and one on the Rick cluster.

**Comment by durandom** [comment]
I suggest to create a sample application with tremor.rs running as a sidecar which then connects via an offramp to loki or kafka. @4n4nd 

I.e. we would need a namespace and a team? for the tremor folks
@4n4nd do we have creating a PR for that documented in the hitchhikers guide?

**Comment by GaryPWhite** [comment]
@tumido the dropdown only had infra cluster I believe. I have no preference in particular.

Also, +1 to @durandom 's comment!

**Comment by 4n4nd** [comment]
@GaryPWhite if you can could you try and follow the [project onboarding notebook](https://github.com/operate-first/hitchhikers-guide/blob/main/pages/onboarding_project.ipynb) we have in our hitchhiker's guide repo? We just updated that documentation and would really appreciate feedback for it.

The [operate first toolbox](https://github.com/operate-first/toolbox#tools-included) image should have all the tools that you would need for it.

**Comment by durandom** [comment]
@GaryPWhite in terms of a sample workload, I would go with any "hello world" that you already have.
Then work with the community to get it deployed via https://www.operate-first.cloud/apps/content/argocd-gitops/README.html 
And then setup the tremor "pipelines" to get the data into https://www.operate-first.cloud/apps/content/observatorium/README.html 
That would span a typical cloud infra setup :)

**Comment by mimotej** [comment]
/remove-lifecycle rotten

@GaryPWhite Hi checking in, is this still relevant or can this issue be closed?

**Comment by GaryPWhite** [comment]
I think so. Sorry for the long delay :)
