### ISSUE TITLE
Fybrik as an Operate First Service

### ISSUE THREAD

**Issue by eletonia** [operate-first/support#41]
We would like to install [Fybrik](https://fybrik.io/v0.4/) on the Operate First cluster that we have received access to. Currently, we install Fybrik components with Helm Charts. @ronenkat @roee88 @hunchback

Is there a specific process for installing applications on the MOC CNV cluster? 
@durandom mentioned using Argo-CD

Please point us to the onboarding documentation when it is ready @tumido @HumairAK

**Comment by HumairAK** [comment]
Hello @eletonia , as you already know we're right in the middle of getting all the onboarding docs out, in the mean time we'll get your team's argocd project set up. I'll update here when everything is ready.

**Comment by tumido** [comment]
@eletonia @ronenkat @roee88 @hunchback

Update for you:

As of today you have:
- an user group `mesh-for-data` available to you (definition [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/groups/mesh-for-data.enc.yaml))
- a namespace `mesh-for-data` available as well (definition [here](https://github.com/operate-first/apps/blob/master/cluster-scope/base/namespaces/mesh-for-data/namespace.yaml))

Pending changes:
@HumairAK's recent PR https://github.com/operate-first/continuous-deployment/pull/94 makes the `mesh-for-data` as well as all the future namespaces created with the `m4d-` prefix [managed by ArgoCD](https://github.com/operate-first/continuous-deployment/pull/94/files#diff-6eb1ce7ceb0b9689648812d8651cee2c4d473a683989fe3c55cb8d6c63f5ac68R7-R10) and belonging to a project owned by your user group. ("Managed by ArgoCD" in a sense that ArgoCD can deploy to those namespaces. You can do manual changes if you need to)

That means, you can request as many namespaces as you want and as long as the namespace name is prefixed by the `m4d-` it can be managed by ArgoCD and you can deploy to it via ArgoCD. Newly you can request new namespaces using an issue template "Onboarding to a cluster" [in the operate-first/support repository](https://github.com/operate-first/support/issues/new/choose) or follow [the docs](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md) by yourself.

The user group created for you is encrypted by our GPG key currently. If you want, you can point us to your GPG key and we can add it to the keyring, so you will be able to manage the usergroup by yourself. More detail on that can be found [in here](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md#adding-users)

**Comment by HumairAK** [comment]
Hello, the argocd `mesh-for-data` project has been created, you can directly create apps on argocd that belong to the project `mesh-for-data`, but we recommend submitting a pr to [this repo](https://github.com/operate-first/argocd-apps) to have your argocd application stored in git. You can follow the docs [here](https://github.com/operate-first/argocd-apps) to see where to add your application manifest depending on your use case.

**Comment by eletonia** [comment]
Hi @tumido @HumairAK 
I tried to create an application in Argo CD with the following inputs in the Argo CD UI:
```apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-for-data
spec:
  destination:
    name: ''
    namespace: mesh-for-data
    server: 'https://api.cnv.massopen.cloud'
  source:
    path: mesh-for-data
    repoURL: 'https://github.com/IBM/the-mesh-for-data'
    targetRevision: HEAD
  project: mesh-for-data
  ```
However, I'm getting this error:
```
Unable to create application: permission denied: applications, create, mesh-for-data/mesh-for-data, sub: CiQ1M2FiOGNlYy03ZGM1LTQ5MzItOGRhYy00YWY2NGFlNmY4ZWQSCW9wZW5zaGlmdA, iat: 2021-01-21T21:21:59Z
```
Do I have the correct cluster name?

**Comment by HumairAK** [comment]
@eletonia  can you make the following changes: 
- Change the `spec.destination.server` to: https://kubernetes.default.svc, this should show up in the dropdown.
- Change the `spec.source.path` to the location where your charts are, from looking at your repo _I think_ you are looking for `charts/m4d` as that's where a `chart.yaml` lives.

**Comment by eletonia** [comment]
I changed those fields:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-for-data
spec:
  destination:
    name: ''
    namespace: mesh-for-data
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/m4d
    repoURL: 'https://github.com/IBM/the-mesh-for-data'
    targetRevision: HEAD
  project: mesh-for-data
  ```
but I'm still getting the same error:
```
Unable to create application: permission denied: applications, create, mesh-for-data/mesh-for-data, sub: CiQ1M2FiOGNlYy03ZGM1LTQ5MzItOGRhYy00YWY2NGFlNmY4ZWQSCW9wZW5zaGlmdA, iat: 2021-01-21T21:21:59Z
```
The [ArgoCD documentation](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/) mentions this:
> When creating an application from a Helm repository, the chart attribute must be specified instead of the path attribute within spec.source.

So I tried changing `spec.source.path` to `spec.source.chart` but that didn't work either

>

**Comment by HumairAK** [comment]
Hrmm I created a new user that's only in the `mesh-for-data` ocp group, and I was able to create the application in the `mesh-for-data` project using the same spec you provided: 
```
project: mesh-for-data
source:
  repoURL: 'https://github.com/IBM/the-mesh-for-data'
  path: charts/m4d
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: mesh-for-data
```
Can you click the user icon on the left in the ArgoCD console and tell us what you see? 

![image](https://user-images.githubusercontent.com/10904967/106403114-eb902b80-63fa-11eb-800b-ad8f736b19a3.png)


Can you also try leaving out the `spec.destination.name`? Other than this, I'm not sure what the issue is, could we schedule a call to figure this out?

**Comment by eletonia** [comment]
I clicked on the user icon and it showed an empty username and no groups
I just tried logging out of Argo CD and logged back in with OpenShift and I was able to create the application! Thanks!


![Screen Shot 2021-01-31 at 7 52 28 PM](https://user-images.githubusercontent.com/6710338/106403701-f8624e80-63fd-11eb-86c1-4397b2f9555d.png)

**Comment by HumairAK** [comment]
Great to hear!

**Comment by eletonia** [comment]
The sync keeps failing for this [ArgoCD project](https://argocd-server-argocd.apps.cnv.massopen.cloud/applications/mesh-for-data) that I created. I know you mentioned that cluster-level resources would produce warnings but would it cause the other resources which are namespace scoped to not be deployed to the cluster? 

I don't see the services or deployments that were supposed to be created in the `m4d-system` namespace
```
$ oc get svc -n m4d-system
No resources found in m4d-system namespace.
$ oc get deployment -n m4d-system
No resources found in m4d-system namespace.
```

**Comment by HumairAK** [comment]
@eletonia yeah I noticed this in your app as well. This may have been an oversight on our part, as before we limited cluster resources at the cluster level (in this method only warnings produced) but now we limit it at a project level (here the behavior is different, in that the app will not deploy in it's entirety), I'll be looking into this to see if we can get cluster-resources ignored and report back.

**Comment by HumairAK** [comment]
Update: So I've tried digging around and haven't found a clear way around this. According to [this issue](https://github.com/argoproj/argo-cd/issues/2969) this seems like it's intended. I've also reached out on slack, though I don't expect to get very many responses about this.

For now you can try synchronizing only the out-of-sync resources. To do this, click sync at the top > click "out of sync" shown in blue > then click "synchronize", this will deploy those resources that _can_ be deployed. 

![image](https://user-images.githubusercontent.com/10904967/106529190-168c8500-64b8-11eb-9b01-560b5a88ad5f.png)

This _should_ get the non cluster-level resources deployed. But you will not be able to turn on autosync (without errors), or sync the "whole" app (i.e. all resources). 

If you guys can use helm values or similar, to give the option to exclude these resources, then you could use [argocd parameters](https://argoproj.github.io/argo-cd/user-guide/helm/#helm-parameters) to tune your deployment further. This is another option.

**Comment by eletonia** [comment]
Thanks @HumairAK ! I was able to deploy the non-cluster level resources by synchronizing only the out-of-sync resources. 

To deploy cluster-level resources, you mentioned we can create an upstream link to our kustomization file from [this repo location](https://github.com/operate-first/apps/tree/master/cluster-scope/base) correct? How do we do this?

**Comment by HumairAK** [comment]
> To deploy cluster-level resources, you mentioned we can create an upstream link to our kustomization file from this repo location correct? How do we do this? 

I think we ended up deciding we are going to disallow remote links in kustomizations, instead we store the copy of the resource there, since the resource pointed to a remote link can be updated to be anything and thus take over the cluster. @tumido can you confirm.

@eletonia the doc [here](https://github.com/operate-first/apps/tree/master/cluster-scope) explains the structure of the `cluster-scope` folder, and how to add a new resource. But you can also make an issue using this [template here](https://github.com/operate-first/support/issues/new/choose) and we can set up the cluster resources for you if you can provide us the links to them.

**Comment by tumido** [comment]
Yes, that is correct. When it comes to cluster scoped resources, I think referencing remote repositories is a security concern to us precisely for the reasons Humair described. I also don't expect the cluster wide resources to change every week, so this should be one-off addition anyways. (However changes are totally possible later on, I just don't expect them to be that frequent as changes to application manifests.)

> @eletonia the doc here explains the structure of the cluster-scope folder, and how to add a new resource. But you can also make an issue using this template here and we can set up the cluster resources for you if you can provide us the links to them.

:+1:

**Comment by eletonia** [comment]
> Hello @eletonia , as you already know we're right in the middle of getting all the onboarding docs out, in the mean time we'll get your team's argocd project set up. Helm should be fine (though we encourage the use of Kustomize)
> 
> Our ArgoCD instance is [here](https://argocd-server-argocd.apps.cnv.massopen.cloud/applications) you won't be able to see anything just yet, as your team's group hasn't been assigned an argocd project.
> 
> Once set up you can use ArgoCD to auto deploy everything in your git repo, and keep your namespace in sync with what's in git.
> 
> I'll update here when everything is ready.

Hi @tumido @HumairAK 
Is there a new ArgoCD instance for the new MOC Zero cluster?

**Comment by tumido** [comment]
Hey @eletonia, yes!

ArgoCD was migrated to Infra cluster to offer more stable and multicluster environment. This ArgoCD is the same as the one before on CNV, however it now manages 3 different clusters, including Zero cluster. It can be accessed via:

https://argocd.operate-first.cloud/

**Comment by eletonia** [comment]
Thanks @tumido 
I tried to create an ArgoCD application in the new ArgoCD instance with this spec:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-for-data
spec:
  destination:
    name: ''
    namespace: mesh-for-data
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/m4d
    repoURL: 'https://github.com/IBM/the-mesh-for-data'
    targetRevision: HEAD
  project: mesh-for-data
  ```
  But I am getting this error:
  `Unable to create application: application spec is invalid: InvalidSpecError: application destination {https://kubernetes.default.svc mesh-for-data} is not permitted in project 'mesh-for-data'` 
  
  Is there another Cluster URL I should provide?

**Comment by tumido** [comment]
Hey @eletonia! Yup, that's precisely it. The manifest should specify the name instead:

```diff
 apiVersion: argoproj.io/v1alpha1
 kind: Application
 metadata:
   name: mesh-for-data
 spec:
   destination:
+    name: zero
     namespace: mesh-for-data
-    server: 'https://kubernetes.default.svc'
   source:
     path: charts/m4d
     repoURL: 'https://github.com/IBM/the-mesh-for-data'
     targetRevision: HEAD
   project: mesh-for-data
```

**Comment by eletonia** [comment]
> @eletonia @ronenkat @roee88 @hunchback
> 
> Update for you:
> 
> As of today you have:
> 
> * an user group `mesh-for-data` available to you (definition [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/groups/mesh-for-data.enc.yaml))
> * a namespace `mesh-for-data` available as well (definition [here](https://github.com/operate-first/apps/blob/master/cluster-scope/base/namespaces/mesh-for-data/namespace.yaml))
> 
> Pending changes:
> @HumairAK's recent PR [operate-first/continuous-deployment#94](https://github.com/operate-first/continuous-deployment/pull/94) makes the `mesh-for-data` as well as all the future namespaces created with the `m4d-` prefix [managed by ArgoCD](https://github.com/operate-first/continuous-deployment/pull/94/files#diff-6eb1ce7ceb0b9689648812d8651cee2c4d473a683989fe3c55cb8d6c63f5ac68R7-R10) and belonging to a project owned by your user group. ("Managed by ArgoCD" in a sense that ArgoCD can deploy to those namespaces. You can do manual changes if you need to)
> 
> That means, you can request as many namespaces as you want and as long as the namespace name is prefixed by the `m4d-` it can be managed by ArgoCD and you can deploy to it via ArgoCD. Newly you can request new namespaces using an issue template "Onboarding to a cluster" [in the operate-first/support repository](https://github.com/operate-first/support/issues/new/choose) or follow [the docs](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md) by yourself.
> 
> The user group created for you is encrypted by our GPG key currently. If you want, you can point us to your GPG key and we can add it to the keyring, so you will be able to manage the usergroup by yourself. More detail on that can be found [in here](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md#adding-users)

Hi @tumido 
We renamed Mesh for Data to Fybrik so can you create the following with the Fybrik name?

- `fybrik-system` namespace
- `fybrik` user group
- `fybrik` ArgoCD project

You can delete everything on the cluster with `mesh-for-data`
Thanks in advance!

**Comment by durandom** [comment]
/lifecycle stale

@roytman can we close this and/or is there another issue to follow the current state of fybrik on operate first?
IIRC you installed components on the os-climate clusters, correct?

**Comment by roytman** [comment]
Hi, I don't have permissions to close it

**Comment by durandom** [comment]
you can always ask the bot to close it, I think via `/close` 
/remove-lifecycle stale

But I'd like to close with a pointer for people to find out about the current state of fybrik on operate first
