### ISSUE TITLE
NEW PROJECT: sre-research

### ISSUE THREAD

**Issue by margarethaley** [operate-first/support#410]
### Team name

sre-research

### Desired project names

opf-sandbox

### Project description

As an SRE beginner / novice, I'd like to get access to a cluster in order to learn more about SRE practices and the operations side of things.

### Users needing access

mhaley@redhat.com

### Namespace Quota

X-Small

### Custom quota

I selected the smallest option because I'm not sure of the resource requirements - right now, I'm just looking to get access to the cluster!

**Comment by margarethaley** [comment]
Just wanted to note that I believe the target cluster would be Smaug, but I did not see that as an option so I left it blank :)

**Comment by HumairAK** [comment]
Hrmm missed this, if this is still needed you can follow instructions here: https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html

**Comment by margarethaley** [comment]
@HumairAK I dont think it's needed anymore - sorry about that, I'll close it out!
