### ISSUE TITLE
Add group/team OCTO-USHIFT-DEV to Infra Cluster and RHACM access

### ISSUE THREAD

**Issue by screeley44** [operate-first/support#414]
### Target cluster

Infra

### Team name

octo-ushift-dev

### Desired project names

ushift-dev

### Project description

We need access to the Infra cluster for RHACM support as we develop microshift for the demo and bring it under ACM mgmt.

### Users needing access

https://github.com/operate-first/apps/pull/1084 - group/team **octo-ushift-dev**

### Namespace Quota

Medium

### Your GPG key or contact

GPG Key:
   passphrase: octo2022demo
   details:
         rsa
         screeley@redhat.com
gpg: key 19A86C5A780C6557 marked as ultimately trusted
gpg: directory '/home/screeley/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/home/screeley/.gnupg/openpgp-revocs.d/B633C95F616EBBEC5F6D78D719A86C5A780C6557.rev'
public and secret key created and signed.

pub   rsa4096 2021-09-16 [SC] [expires: 2022-09-16]
      B633C95F616EBBEC5F6D78D719A86C5A780C6557
uid                      Scott Creeley (OCTO-Platforms-Operate-First) <screeley@redhat.com>
sub   rsa4096 2021-09-16 [E] [expires: 2022-09-16]

**Comment by durandom** [comment]
@tumido @HumairAK to unblock https://github.com/AICoE/summit-2021-octo-keynote/issues/5 can you grant access to our ACM. They "just" want to adopt a uShift cluster that's deployed on rick

**Comment by tumido** [comment]
I think we should try what Tim from ACM suggested - to create a new managed cluster set and see if ushift team can add clusters in there... @HumairAK can you take a look into it?

**Comment by HumairAK** [comment]
yeah I'll investigate this today

**Comment by HumairAK** [comment]
Okay so I created a new `managedclusterset` called `octo-ushift-dev`, and gave admin access to everyone in ocp group `octo-ushift-dev`. Which is everyone here: https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/group.yaml. 

In my testing, this allowed me the ability to create the cluster within this cluster set, however I didn't actually go ahead and create/import one. So I'll leave that for you guys to try, and give us feedback there :) 

Further, I have a PR pending which would auto enable all clusters imported in this cluster set to our ArgoCD instance: https://github.com/operate-first/apps/pull/1211/files

Also additional docs on how future teams can enable themselves to do the same.
