### ISSUE TITLE
Request that OS-Climate ODH host a datasette instance

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#418]
Please see https://github.com/os-climate/os_c_data_commons/issues/79 for full details. 

In short. We would like to host an instance of [Datasette](https://github.com/os-climate/os_c_data_commons/issues/79) on the os-climate cluster. What would be the best approach to make this happen?

**Comment by 4n4nd** [comment]
cc @erikerlandson @HumairAK

**Comment by MichaelTiemannOSC** [comment]
Actually, datasette is installed via pip install.  And it's not thrilled about trying to connect jupyter-server 1.6.4 with anyio 3.3.3.  There's a bit of a dance I can do manually to downgrade enough things to be compatible.  But where should I actually file this as an issue?

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-server 1.6.4 requires anyio<3,>=2.0.2, but you have anyio 3.3.3 which is incompatible.
```

**Comment by erikerlandson** [comment]
https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/wri-pp/pods/wri-pp-demo-git-54794f4cc4-s6wq2/logs

**Comment by MichaelTiemannOSC** [comment]
I'm lacking key skills in the container area.  From the openshift terminal I'm able to see that datasette is happy to run (for example datasette --get, as documented here: https://docs.datasette.io/en/stable/getting_started.html#datasette-get)

However, I don't know how to upload a database file to the openshift environment and I don't know why the route I get (which is just an http: not https: route) doesn't reach the application and bring up a webserver that says hello.
