### ISSUE TITLE
Default Elyra notebook image has README and requirements.txt as directories, not files

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [operate-first/support#422]
**Description**
When I create a fresh Elyra notebook image I see that README and requirements.txt are directories:

```[1000640000@jupyterhub-nb-michaeltiemannosc app-root]$ pwd; ls -l README/ requirements.txt/
/opt/app-root
README/:
total 12
-rwxrwxr-x. 1 builder root 11321 Feb 25  2021 README.md

requirements.txt/:
total 4
-rw-rw-r--. 1 builder root 81 Apr 22 20:20 requirements.txt
```

I suspect that these directories should be replaced in the manifest by the files they contain.

**Additional context**
This also appears to affect other notebook configurations, such as Minimal.

**Comment by MichaelTiemannOSC** [comment]
/remove-lifecycle stale

@MichaelClifford can you comment on this?

**Comment by MichaelClifford** [comment]
This appears to be an artifact of the underlying image build process. @harshad16 is this the expected behavior for this files?

**Comment by harshad16** [comment]
/remove-lifecycle stale
This issue somehow missed out of my list.

This is not expected behavior, we didn't notice this.
I will investigate.

**Comment by harshad16** [comment]
I can confirm that it is an issue. 
Will work on fixing this issue.
thank you for the issue.

/lifecycle active

**Comment by harshad16** [comment]
After the investigation, we have found the reason for their existence.

During the image builds, the python packages are installed via the source method.
Two of the packages have data_files stated in their install method, so the REAME and requirements.txt directory are formed in build time as a part of these package installations.

README via python-string-utils : https://github.com/daveoncode/python-string-utils/blob/v1.0.0/setup.py#L26
requirement.txt via openshift: https://github.com/openshift/openshift-restclient-python/blob/d2576725b48a3db864652e6e57b6dfc794d42e32/setup.py#L52

This behavior would exist, till the upstream package change such behavior.
I couldn't think of an easy-fast solution, we would have to write steps to remove them after builds.
if this feels like a critical issue, please let us know so we can include steps to remove such parts.

if this is not a critical issue, feel free to close the issue.

**Comment by schwesig** [comment]
@harshad16 @MichaelTiemannOSC
is this still a problem/ needs to be fixed?

**Comment by schwesig** [comment]
> I can confirm that it is an issue.
> Will work on fixing this issue.
> thank you for the issue.

/triage accpeted

**Comment by harshad16** [comment]
@schwesig please take a look at my comment
the issue described is an upstream flow that would occur in any build irrespective of our image or not if the application is using package open shift.
IMHO this is something we can explicitly remove in built if needed, however, I feel it would be just an extra step.
If anyone can confirm, that we need to invest time in this. Please provide an acknowledgment.

**Comment by schwesig** [comment]
@harshad16 That is why I added/ pinged @MichaelTiemannOSC in this comment again.
I will leave this stale by now.
We will see if it becomes urgent again and Michael has an opinion/ update.

**Comment by MichaelTiemannOSC** [comment]
I'm not an expert in these regards, but I wonder whether the data_files directives in these two cases are not merely making the mess that needs to be cleaned up.  I understand that talking with the python stringutils people might take a while, but do the openshift people really need to push requirements.txt down a level to make things work?

Anyway, I reported what I saw as awkward, and admit that I don't understand all the corner cases that might make the status quo the elegant solution.

**Comment by goern** [comment]
circling back through the root causes its seems that

1. v1.0.0 of python-string-utils is still buggy
2. v0.13.1 of openshift-restclient-python fixed the `data_files` problem

I'd consider this an 'wait for upstream' and close this issue

@harshad16 @MichaelTiemannOSC wdyt?

**Comment by harshad16** [comment]
yes, i would say so

**Comment by MichaelTiemannOSC** [comment]
I'll go along.  Shame that python-string-utils folks haven't addressed, but I don't know how it is we are falling afoul of their assumptions, so I don't know what to file as an issue.
