### ISSUE TITLE
Deploy curator on Smaug

### ISSUE THREAD

**Issue by skanthed** [operate-first/support#424]
### Description 

**Project Curator** 

The goal of the curator is to record all the resource consumption using [koku-metrics-operator](https://github.com/project-koku/koku-metrics-operator) made by applications running on the OpenShift instances and provides users the ability to query the infrastructure utilization based on the time period and namespaces using API functionality.  

> For detailed documentation - https://curator-doc.readthedocs.io/en/latest/about.html
Github repository - https://github.com/operate-first/curator

To deploy v2.0 on Smaug we need - 

- Koku-metrics-operator 
- 	Postgres database
- 	Some cluster lever roles and permission to deploy API (API is built using kubebuilder) - https://curator-doc.readthedocs.io/en/latest/api.html

> We are still working on documentation. Feel free to ask any queries related to that.

**Comment by HumairAK** [comment]
@skanthed if this is still ongoing, can you remove the lifecycle, otherwise you may leave it as is.
