### ISSUE TITLE
Failure to run ansible-playbook to setup PersistentVolumes

### ISSUE THREAD

**Issue by suppathak** [operate-first/support#434]
Describe the bug
Failure to run ansible-playbook

To Reproduce
Following through the instructions for setting up PersistentVolumes given in this [link](https://github.com/operate-first/apps/tree/master/scripts/setup_pvs). After loggin as a cluster admin. I successfully installed ansible.posix , community.kubernetes and openshift. I then updated the quicklab host in env.yaml file and ran ansible-playbook playbook.yaml file. The error is shown in the screenshots.

**Screenshots**

![Screenshot from 2021-10-21 10-01-20](https://user-images.githubusercontent.com/30439457/138324601-9b6c20bf-2f37-4261-a00d-900d302d951c.png)

**Comment by tumido** [comment]
Interesting.. it seems despite you've installed the `community.kubernetes` ansible collection, it's unable to find it. You can try deleting the `~/.ansible/` folder and retry downloading the collections.. No idea what went wrong there.. you may need to look up Ansible docs on this...
