### ISSUE TITLE
NEW PROJECT: varangian-test

### ISSUE THREAD

**Issue by KPostOffice** [operate-first/support#439]
### Target cluster

Smaug

### Team name

varangian

### Desired project names

varangian-test

### Project description

Varangian is an augmented static analyzer based on infer. The goal is to reduce the number of false positives reported to users by using a model trained on historical repository data. This improvement should reduce developer fatigue and increase engagement.

### Users needing access

saurabh.s.pujar@gmail.com, BurnLewis@gmail.com, sahilsuneja@gmail.com, kpostlet@redhat.com

### Namespace Quota

Small

**Comment by HumairAK** [comment]
Hello, just notice that is still ongoing, this can be self provisioned by following the instructions here: 

https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html 
Jupyterhub access here: https://www.operate-first.cloud/apps/content/odh/jupyterhub/access_jupyterhub.html 

Let us know if there are any issues as we are continuously trying to improve the docs. Thanks.

**Comment by HumairAK** [comment]
Project onboarded via: https://github.com/operate-first/apps/pull/1559 

Access namespace here: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects/varangian-test
