### ISSUE TITLE
Expose cluster logs 

### ISSUE THREAD

**Issue by eranra** [operate-first/support#44]
**Is your feature request related to a problem? Please describe.**
Logs need to be exposed from OCP cluster in order to execersise Decorus anomaly detection algorithm

**Describe the solution you'd like**
(1) Deploy cluster Logging Operator (CLO) and expose ElasticSearch end-point and Kibana so that it can be consumed by exteral tools such as Decorus 
https://docs.openshift.com/container-platform/4.3/logging/cluster-logging-deploying.html
(2) Also:: integration with Observatorium/Loki will be next phase once the client side instructions for Observatorium mature

**Describe alternatives you've considered**
Wait for Observatorium/Loki instructions and deploy (this might take time, and we do not want to delay process of execersising Decorus anomaly detection algorithm)

**Additional context**
CLO has deployment instruction using UI and/or CLI - It is an operator, so need to change cluster configuration and/or install that operator to the cluster

@tumido @HumairAK @durandom @drbwa

**Comment by durandom** [comment]
Let's try to get 1) going. @tumido @HumairAK can you point @eranra to a similar PR or yaml code that deploys an operator?
Looking at https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-deploying.html it looks similar to our initial ODH approach - or ist there anything in there that would not be supported via our approach in https://github.com/operate-first/blueprint/blob/main/docs/adr/0009-cluster-resources.md

**Comment by drbwa** [comment]
In addition to ElasticSearch, is it possible to get the raw logs streamed into a Kafka cluster?

**Comment by durandom** [comment]
Since we also have [kafka](https://github.com/operate-first/apps/tree/master/odh/base/kafka) that should be possible. 
PR's welcome 😄 the current team is super busy with establishing processes to deploy and manage new workloads.

But PR reviews and guidance would be a win-win situation, since it also helps validating the processes

**Comment by eranra** [comment]
@drbwa Doable, we need to follow instructions here::  https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-external.html#cluster-logging-collector-lo[…]afka_cluster-logging-external

**Comment by tumido** [comment]
FTR, an example PR against the cluster scoped resources: https://github.com/operate-first/apps/pull/131

Just put the resources within the [`cluster-scope/base`](https://github.com/operate-first/apps/tree/master/cluster-scope/base) folder and reference the resources in the [`cluster-scope/base/overlays/moc/kustomization.yaml`](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/kustomization.yaml) file.

**Comment by eranra** [comment]
@tumido I can try to do that, but I am not such an expert in OCP ... what I know to do is deploy using CLI and/or UI ... so how can I know what are the resources that need to be deployed ... 

**@tumido any chance to deploy manually (UI or CLI) on the cluster and look on the changes and use that to harden them into this git repo ???**

**Comment by tumido** [comment]
When it comes to deploying any namespace scoped resources to a namespace you are admin of, you can do that manually just fine. On the otherhand we don't want people touching the cluster scoped resources on a live cluster. So the only way currently to get the cluster scoped resources in, is via the apps repo. If it helps, you can tell us what cluster scoped resources you want to deploy and we'll take care of it.

**Comment by durandom** [comment]
> **@tumido any chance to deploy manually (UI or CLI) on the cluster and look on the changes and use that to harden them into this git repo ???**

You can try out stuff manually in a namespace *without* cluster-admin. But adding cluster wide resources is only possible via argo-cd
You can also replicate the setup easily in [quicklab](https://www.operate-first.cloud/operators/continuous-deployment/docs/downstream/quicklab.md) (RH internal) or [CRC](https://www.operate-first.cloud/operators/continuous-deployment/docs/downstream/crc.md)

**Comment by tumido** [comment]
What can help you with the overall onboarding:
- Understanding [Kustomize](https://kustomize.io/) which we use to structure/generate and compose our manifests with.
- The cluster resources [ADR 0009](https://github.com/operate-first/blueprint/blob/main/docs/adr/0009-cluster-resources.md) which explains the reasons for the specific repo layout.
 
If there are any issues with any of it, just either comment in here, open new issues anywhere you see fit or shoot me a message. :slightly_smiling_face:

**Comment by eranra** [comment]
Hi @tumido I used your PR as refrence (and looked also on other resources in the `apps` repo) 

I created pr:: https://github.com/operate-first/apps/pull/153/ 
If you can review?  also, can I check this somehow on local/other OCP cluster .... so that I will know that this works???

@HumairAK @durandom @drbwa

**Comment by eranra** [comment]
REF: https://github.com/operate-first/apps/issues/154

**Comment by eranra** [comment]
Open debug issue REF: https://github.com/operate-first/apps/issues/154

**Comment by eranra** [comment]
Waiting for access credentials (RBAC) Based on PR https://github.com/operate-first/apps/issues/171

**Comment by HumairAK** [comment]
I think we can consider this issue complete. 1) Has been completed. And discussions for 2) seem to have been moved to different threads, see: https://github.com/operate-first/apps/issues/232 . 

Feel free to re-open if there's more purpose for this thread. Thanks!
