### ISSUE TITLE
https://www.operate-first.cloud/users/support#moc-environment still points to zero cluster

### ISSUE THREAD

**Issue by billburnseh** [operate-first/support#443]
**Describe the bug**
Page is out of date, MOC clusters needs to be updated to Smaug with the proper link.

**To Reproduce**
1. Go to '...'https://www.operate-first.cloud/users/support#moc-environment
2. Click on '.MOC environment zero
3. See error

**Expected behaviour**
Just needs to be updated.

**Comment by HumairAK** [comment]
The support page in general was updated and moved to: https://www.operate-first.cloud/community-handbook/support/README.md -- closing.
