### ISSUE TITLE
Add Superset user access 

### ISSUE THREAD

**Issue by leihchen** [operate-first/support#450]
Could someone help me add the curator team members (@skanthed @gagansk ) to superset on Smaug. I would like get dashboards, charts access for the team.

**Comment by HumairAK** [comment]
can you follow the instructions here and make a pr? https://github.com/operate-first/apps/blob/master/docs/odh/superset/add_superset_users.md

**Comment by leihchen** [comment]
Created: https://github.com/operate-first/apps/pull/1263

**Comment by HumairAK** [comment]
@leihchen was this issue resolved? if so please close. Thanks!
