### ISSUE TITLE
Pods are failing due to unavailability of pvc bound

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#456]
**Describe the bug**
The **pulp** project was recently migrated from the experiment namespace to the official `opf-pulp` namespace.
The argocd application deployed the operator and the instance.

However, the instance is having a hard time bringing up the pods due to the following error:
`0/29 nodes are available: 29 pod has unbound immediate PersistentVolumeClaims.`

further investigation shows that one of the PVC is still in a pending state.
https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-pulp/persistentvolumeclaims/pulp-file-storage
![pulp-pvc](https://user-images.githubusercontent.com/14028058/140529085-349e0c07-d0dc-41d7-8f83-21532d7b5788.png)

**Comment by harshad16** [comment]
affiliated with this larger topic: https://github.com/operate-first/support/issues/176

**Comment by HumairAK** [comment]
Pasting slack conversation for context: 

> **Harshad wrote:**
> maybe it is due to the pvc storage
> can storage class <https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/storageclasses/ocs-external-storagecluster-ceph-rbd|ocs-external-storagecluster-ceph-rbd> handle 50gi request ?
> 
> **Humair Khan wrote:**
> larsks ^
> 
> **Humair Khan wrote:**
> this is the pvc: <https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-pulp/persistentvolumeclaims/pulp-file-storage>
> 
> **larsks wrote:**
> Humair Khan There shouldn't be any limits on volume size other than the total available space (20TB). I can take a closer look at this after my 11am meeting.
> 
> **Humair Khan wrote:**
> thank you!
> 
> **larsks wrote:**
> Humair Khan Maybe it's a quota issue; if I try to create a 50Gi volume I get: `Error from server (Forbidden): error when creating "pvc.yaml": persistentvolumeclaims "example" is forbidden: exceeded quota: opf-pulp-custom, requested: requests.storage=50Gi, used: requests.storage=59Gi, limited: requests.storage=96Gi`
> 
> **Humair Khan wrote:**
> I think that's because the `pulp-file-storage` pvc is already using 50g, and the ns only allows for 100g
> 
> **Humair Khan wrote:**
> and in total 59g are being used
> 
> **Humair Khan wrote:**
> I can turn off autosync and increase the quota if you want to experiment in this ns
> 
> **Humair Khan wrote:**
> try now
> 
> **Humair Khan wrote:**
> hrmm I created one just fine
> 
> **Humair Khan wrote:**
> using `ocs-external-storagecluster-ceph-rbd`
> 
> **Humair Khan wrote:**
> <https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-pulp/persistentvolumeclaims/testtest>
> 
> **Humair Khan wrote:**
> 50g
> 
> **Humair Khan wrote:**
> Harshad have you tried recreating this pvc?
> 
> **larsks wrote:**
> Humair Khan so upping the quota fixed it, or you were able to create one before adjusting the quota?
> 
> **Humair Khan wrote:**
> no but, I think that was a separate issue
> 
> **Humair Khan wrote:**
> after upping the quota the pvc in question still hasn't bounded
> 
> **Humair Khan wrote:**
> but I can create a new pvc of 50g just fine
> 
> **Humair Khan wrote:**
> I think it has to do with the access mode
> 
> **Humair Khan wrote:**
> they're trying to do `ReadWriteMany`  with `filesystem` volume mode
> 
> **Humair Khan wrote:**
> if you do `ReadWriteMany` then the volumeMode needs to be `Block` Harshad
> 
> **larsks wrote:**
> Oh, good catch. That's totally it.
> 
> **larsks wrote:**
> I'm unsure if a block-mode rwx volume is useful (I mean, I can't see how that would work without some sort of distributed filesystem on top of it).
> 
> **larsks wrote:**
> We may be functionally restricted to rwo volumes with the current configuration.
> 
> **Harshad wrote:**
> sorry was afk
> so teh solution is to change the filesystem to `readwritemany` ?
> 
> **Harshad wrote:**
> oh the volumeMode block doesnt help the pods,
> the pvc gets bounded however , pod starts throwing the volumemount issue
> ```Unable to attach or mount volumes: unmounted volumes=[file-storage], unattached volumes=[file-storage kube-api-access-x5tbx pulp-server pulp-db-fields-encryption]: volume file-storage has volumeMode Block, but is specified in volumeMounts```
> 
> **Humair Khan wrote:**
> this is hitting the limits of my understanding of storage in ocp, but my guess is that because you are mounting within the pod directory, you _need_ pvc's with mode `filesystem` , but the ceph storage class does not support `filesystem` + `RWX` access mode
> 
> **Humair Khan wrote:**
> larsks does that sound right?
> 
> **larsks wrote:**
> Humair Khan that's correct. The only way to get filesystem + rwx would be with something like cephfs/nfs/etc that supports mounting a filesystem on multiple hosts.
> 
> **Humair Khan wrote:**
> seems like one thing you guys could try is to do `ReadWriteOnce`  but schedule all the pods mounting this pvc on the same node
> 
> **Humair Khan wrote:**
> <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes>
> 
> **Harshad wrote:**
> thanks for the knowledge share, i also not aware which all storage has support the fs, amoung the thre storage classes we have in smaug
> moc-nfs-csi
> ocs-external-storagecluster-ceph-rbd
> <http://openshift-storage.noobaa.io|openshift-storage.noobaa.io>
> 
> is it just the moc-nfs-csi, supporting rwx+fs ?
> 
> **Humair Khan wrote:**
> not sure, but afaik `moc-nfs-csi`  will be phased out in the future as it's not adequately maintained
> 
> **Harshad wrote:**
> the pvc getting from the operator, and changing the pvc to readwriteonce is not an option as multiple component would be attach to the pvc and try to read write
> 
> **Humair Khan wrote:**
> &gt;  the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.
> 
> **Harshad wrote:**
> oh i didnt know that , i will try it out then
> 
> **larsks wrote:**
> We're planning on turning off the NFS server towards the end of the year. If your application supports object buckets instead of pvs that's a better solution to multi-node access.
> 
> **Harshad wrote:**
> ack, this an upstream project , whose instance we would like to run on the operate-first , i wil check with there team on the reuiqrements, based on this
>

**Comment by HumairAK** [comment]
Let's get a doc that explains that we don't support RWX + ceph via ocs, and offer alternatives (either RWO+same node, or use buckets instead for multi node access)

**Comment by harshad16** [comment]
The pr https://github.com/operate-first/apps/pull/1325 fix this issue.
keep this issue still open for more better solution
