### ISSUE TITLE
OpenShift service health monitoring

### ISSUE THREAD

**Issue by billburnseh** [operate-first/support#462]
**Is your feature request related to a problem? Please describe.**
NERC needs to monitor the health of the environment.

**Describe the solution you'd like**
Fully configured and operation monitoring and metrics dashboard across the suite of critical services.

**Describe alternatives you've considered**
See below

**Additional context**
Original description
We need a set of services to collect metrics on the basic utilization of systems (cpu load, memory, network, disk I/O), basic OpenStack services health, and alert (to Slack and/or PagerDuty) on customized thresholds.  We chose to deploy  RH Service Telemetry Framework but have been met with a number of issues that resulted in tickets and bug-fixes. We still don’t have a fully functional deployment that doesn’t result in regularly restarting containers which are failing due to a collectd memory leak.  Goal: Fully configured and operation monitoring and metrics dashboard across the suite of critical services.

Suggested action
1 . Get current status from NERC and STF on ongoing efforts. Make final determination on the need for technologies like STF or Observatorium as part of the solution.
2. Evaluate what is currently used in the community cloud at the MOC against the needs of NERC to determine a course of action to meet the requirements..

**Comment by hpdempsey** [comment]
Context above applies to OpenShift for this ticket (NERC wants to use the same type of health monitoring for both OpenStack and OpenShift clusters, so the context quote is repeated).  The first task is to collect and if necessary supplment/update the OpenShift documentation about how admins currently monitor OpenShift up/down status, network status, and other important metrics that the OperateFirst existing admins consider important health indicators.  It is understood that this is not STF.  NERC will compare the two approaches, and give feedback on what they need to integrate.
