### ISSUE TITLE
Centralized logging

### ISSUE THREAD

**Issue by billburnseh** [operate-first/support#463]
**Is your feature request related to a problem? Please describe.**
NERC requires a centralized log to manage their large deployment

**Describe the solution you'd like**
Ideally a common solution that meets NERC's needs as well as the needs from telemetry
and AIOPs efforts.

**Describe alternatives you've considered**
Part of this issue is vet various alternatives to choose the best.

**Additional context**
Original description
Given the size the NERC deployment  is expected to grow to, we will likely need an independent ELK stack for various logs.  We have not started this yet.  Goal: Design and deploy Elasticsearch engine and configure Kibana with meaningful dashboards.

Suggested action
This is a large project, and also overlaps with the centralized logging needed in Operate First for AIOps and Telemetry sharing.  We will probably tackle this one when we have better capability to store Operate First logs in NESE with proper policy in place.  We will create an issue to track this in Operate First.

**Comment by 4n4nd** [comment]
@billburnseh we recently set up an instance of Loki on Smaug to which we are pushing cluster logs. Instead of setting up a whole new instance of ES and Kibana, maybe this Loki and Grafana setup could be used?
