### ISSUE TITLE
Cannot install dependencies in Elyra notebook

### ISSUE THREAD

**Issue by xtuchyna** [operate-first/support#466]
**Describe the bug**
After hitting the Install button (in `Manage dependencies` window), it first logs
```
Contacting thoth for advise... please be patient!
```
but after a while an error comes out
```
Manage Dependencies

Thoth resolution engine failed... pipenv will be used to lock dependencies!
```
After that, the `Manage dependencies` window when re-visited, shows that the dependencies are installed.

However, when trying to use any of them, a module is not found.
```
import pandas as pd

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-5a9f707586ee> in <module>
----> 1 import pandas as pd
      2 series = pd.Series([len(x) for x in source_code_sequences])

ModuleNotFoundError: No module named 'pandas'
```

**To Reproduce**
1. Go to https://www.operate-first.cloud/hitchhikers-guide/apps/docs/odh/jupyterhub/access_jupyterhub.md
2. Access jupyterhub on smaug by clicking on the reference link
3. Create new python notebook
4. Add `pandas` dependency by clicking on `Manage dependencies` and writing 'pandas' in the text box.
5. Click on the + sign
6. See `Contacting thoth for advise... please be patient!`
7. After a while, the process either does not finish or shows `Thoth resolution engine failed` error
8. Click on the `Manage dependencies` again, and see there is a green check next to the pandas, indicating it should be installed
9. try to `import pandas`, and see the module not found error

**Expected behaviour**
Module to be installed and ready to use

**Screenshots**
![image](https://user-images.githubusercontent.com/46632404/140800933-fb300a49-6517-4273-9ec8-6d4d2d24a6a3.png)

**Comment by pacospace** [comment]
@HumairAK have you tried with new images? I assume this was still quite old version! also can you try with %horus magic commands instead of the UI to lock dependencies?
