### ISSUE TITLE
Find a service that can be target candidate for VPA

### ISSUE THREAD

**Issue by apoorvam** [operate-first/support#467]
**Description**
For enabling the Vertical Pod Autoscaler(VPA) operator, we want to find a service that can be used as a target candidate in Operate-First environment.

**Additional context**
VPA: https://docs.openshift.com/container-platform/4.9/nodes/pods/nodes-pods-vertical-autoscaler.html 

Pods in the target namespace should be mapped to a deployment or similar parent object

cc: @HumairAK @4n4nd

**Comment by tumido** [comment]
I'm thinking about:
- `acme-operator`
- `aicoe-meteor`, only `*-jupyterbook` deployments
- `opf-slack-first`

**Comment by apoorvam** [comment]
`Trino` was chosen as the candidate for VPA and enabled VPA for same in both staging and prod of Smaug cluster. Resources: https://github.com/operate-first/apps/tree/master/kfdefs/overlays/moc/smaug/opf-trino/vpa 

> VerticalPodAutoscaler can be targeted at controller implementing scale subresource (the pod set is retrieved from the controller's ScaleStatus) or some well known controllers (e.g. for DaemonSet the pod set is read from the controller's spec)

Based on this, VPA could be suitable for JH/notebook applications as well.
