### ISSUE TITLE
quota page can not be found

### ISSUE THREAD

**Issue by goern** [operate-first/support#468]
**Describe the bug**
404 on https://github.com/operate-first/support/blob/main/docs/quotas.md which is referred from the new project issue template

**To Reproduce**
1. Go to https://github.com/operate-first/support/issues/new?assignees=first-operator&labels=kind%2Fonboarding%2Carea%2Fcluster&template=onboarding_to_cluster.yaml&title=NEW+PROJECT%3A+%3Cname%3E
2. Click on link in "Namespace Quota" section

**Expected behaviour**
200

**Screenshots**
n/a

**Additional context**
n/a

**Comment by HumairAK** [comment]
good catch!
