### ISSUE TITLE
NEW PROJECT: b4mad-ipfs

### ISSUE THREAD

**Issue by goern** [operate-first/support#469]
### Target cluster

Rick

### Team name

b4mad

### Desired project names

b4mad-ipfs

### Project description

This is an experimental deployment of IPFS, the goal is to document operational procedures for an Kubernetes/OpenShift based IPFS deployment

### Users needing access

@goern 

### Namespace Quota

Medium

### Your GPG key or contact

34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34

**Comment by HumairAK** [comment]
Rick cluster is capped on resources, some comments about adding new nodes: https://github.com/operate-first/support/issues/419#issuecomment-954845288
