### ISSUE TITLE
PROJECT: b4mad-ipfs

### ISSUE THREAD

**Issue by goern** [operate-first/support#470]
### Select all that apply

- [ ] Create a new ArgoCD project for existing team
- [ ] Enlist an application to be deployed automatically via ArgoCD
- [ ] Add a new user to an ArgoCD Project

### Team name

b4mad

### Target cluster

Rick

### Managed namespaces

b4mad-ipfs

### Team name or your Argo CD project

b4mad-ipfs

### Application source git repository

https://github.com/b4mad/op1st-ipfs.git

### Path to manifests within the repository

overlays/op1st-rick

### Target cluster

Rick

### Target namespace for the application

b4mad-ipfs

### Team name

b4mad

### ArgoCD Project

b4mad-ipfs

**Comment by goern** [comment]
ping

**Comment by HumairAK** [comment]
If this is still needed, instructions for onboarding project can be found here: https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html
