### ISSUE TITLE
PROJECT: Thoth

### ISSUE THREAD

**Issue by mayaCostantini** [operate-first/support#474]
### Select all that apply

- [ ] Create a new ArgoCD project for existing team
- [ ] Enlist an application to be deployed automatically via ArgoCD
- [x] Add a new user to an ArgoCD Project

### User name

mcostant

### Team name

aicoe-thoth-devops

### ArgoCD Project

Thoth-station

**Comment by HumairAK** [comment]
For access to the thoth argocd projects you can add your github username here: https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/thoth/group.yaml and that should be sufficient. 

fyi @harshad16

**Comment by mayaCostantini** [comment]
Thanks @HumairAK !
