### ISSUE TITLE
NEW PROJECT: smartoffice

### ISSUE THREAD

**Issue by joschro** [operate-first/support#477]
### Target cluster

Rick

### Team name

rh-dus

### Desired project names

smartoffice

### Project description

The purpose of this project is to demonstrate how to develop and run cloud native applications in a production OpenShift environment. Our goal is to use modern approaches (gitops, serverless) for those applications.

Examples include, but are not limited, to:

- app for managing parking lots
- office chatbot
- automated busy light (automated meeting room allocation), based on activity

### Users needing access

koep,joschro,DanielFroehlich

### Namespace Quota

Medium

**Comment by HumairAK** [comment]
Rick cluster is currently capped on resources, does it have to be `rick` ? Can it be `smaug` ? @durandom

**Comment by joschro** [comment]
Rick was chosen randomly - no issue with smaug from my side

**Comment by durandom** [comment]
@rbo dont we already have an solution-architects group for `team name`?
@4n4nd can you point to documentation to create the required PR for onboarding?

**Comment by 4n4nd** [comment]
@joschro we have a notebook available [here](https://github.com/operate-first/hitchhikers-guide/blob/main/pages/onboarding_project.ipynb) that you could use to onboard yourself to the smaug cluster. Let me know if you see any issues, we would love to get feedback for our docs.

**Comment by rbo** [comment]
> @rbo dont we already have an solution-architects group for `team name`? 

We have a `sa-dach` group: https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/sa-dach/group.yaml

**Comment by joschro** [comment]
@rbo would you be available to guide Christian, Daniel and myself through the process and explain what meaning the group sa-dach has in this context?

**Comment by rbo** [comment]
@joschro yes. Currently, we set up a new cluster in EMEA (Morty) if this cluster is available I will create a PR with everything for your smart office project.

**Comment by rbo** [comment]
@joschro @DanielFroehlich @koep please try you access to morty cluster: https://console-openshift-console.apps.morty.emea.operate-first.cloud/

**Comment by rbo** [comment]
@joschro @DanielFroehlich @koep I will close the issue, if something doesn't work feel free to ping me, reopen the issuer and/or create a new one.

**Comment by koep** [comment]
Works for me, thanks a lot @rbo
