### ISSUE TITLE
[TASK] add `erikerlandson` to OWNERS for OSC overlays

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/support#479]
**User story**
As an os-climate cluster administrator, I need the ability to make cluster configuration changes (e.g. trino config changes) to certain files, in iteration loops.

**Additional context**

**Acceptance Criteria**
- [ ] user `erikerlandson` can review and merge his own pull requests for os-climate overlays 

**Linked epics / issues**

**Comment by HumairAK** [comment]
I think we can just add an OWNERS file in these overlays and add @erikerlandson as an appprover, so he may merge via /approve. Not a 100% sure as I have not tested this yet. So need to investigate.

Let's also add @redmikhail to the cluster osc overlays so he can also be auto added as

**Comment by HumairAK** [comment]
@erikerlandson let's add them first to resolve this warning, pr to do this is here: https://github.com/operate-first/common/pull/47
