### ISSUE TITLE
[TASK] Create user docs for S3/Ceph/Rook usage

### ISSUE THREAD

**Issue by tumido** [operate-first/support#48]
**User story**
Users wants to provision s3 buckets. We need to advise them to use rook.

**Additional context**
n/a

**Acceptance Criteria**
- [ ] There's a single doc which can be used for the whole bucket request thing.
- [ ] Maybe another issue template?
 
**Linked epics / issues**

**Comment by goern** [comment]
Its a little bit odd that rook is forcing us to use a bucket-name prefix, so https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod/config.yaml#L5 is required.

Can we do something about that?

/sig documentation
/sig user-experience
/open

**Comment by tumido** [comment]
@goern yes, you can specify the bucket name directly. You just need to make sure this name is unique within the cluster (because the Rook operator operates on a cluster scope and bucket names has to be unique in ceph instance)

Please read this doc:
https://rook.io/docs/rook/v1.5/ceph-object-bucket-claim.html#sample

In our support docs, we advise users to use the `generateBucketName` property, because it ensures the uniqueness within the cluster automatically during provisioning and the bucket name is then available as a `ConfigMap` value.

If this behavior is not comfortable to you, you can use the `bucketName` property directly, just be advise the provisioning may fail, if there's already a bucket with the same name.

**Comment by martinpovolny** [comment]
@tumido , @goern : This issue is about claiming S3 buckets as part of an app deployment (via ArgoCD), correct?

Is there a way to claim a bucket for a data scientist (for example one working with the JH instance on MOC)?

Or is the supposed workflow for such case to:

1. do the onboarning https://www.operate-first.cloud/users/support/docs/onboarding_to_cluster.md
1. create an ArgoCD app   https://www.operate-first.cloud/users/argocd-apps/docs/add_application.md
1. have the S3 bucket provisioned via the app: https://www.operate-first.cloud/users/support/docs/claiming_object_store.md

Is that so? Or am I missing something?

Thanks!

**Comment by tumido** [comment]
We currently don't have an "end user" support for this in place. We have the doc in here:

> 3. have the S3 bucket provisioned via the app: https://www.operate-first.cloud/users/support/docs/claiming_object_store.md

Mainly targeting application and project owners who can claim the resource into their Openshift namespace. We should have an easier way to do that for the end users...

It make sense to me to have a separate application for user storage, maybe alongside the jupyterhub user profiles? Honestly I think it should be aligned with https://github.com/operate-first/apps/issues/100 so the JH user profiles and bucket claims for JH/ODH users are not scattered all over the cluster.

I'd be glad if it can all live inside one namespace managed by operate-first ArgoCD project. Like.. what if we create a `user-data` application in apps repo for this and we can then have a support script and an user facing issue template that would create the bucket?

WDYT @HumairAK @4n4nd ?

**Comment by HumairAK** [comment]
> I'd be glad if it can all live inside one namespace managed by operate-first ArgoCD project. Like.. what if we create a user-data application in apps repo for this and we can then have a support script and an user facing issue template that would create the bucket? 

I'm fine with this. But OBC's are something namespace admin's can deploy themselves, so it seems we would end up having OBC's that we manage + OBC's scattered around different namespaces. Is our stance then: 
- if you don't want to think about it, we'll do it for you --> in which case we put it in a namespace/repo we're managing
- if you know what to do and have the requisite knowledge --> you can deploy it yourself

**Comment by tumido** [comment]
Precisely that. If it's an end user - data science person or what not, let's do it ourselves - and in that case keep it in a single app, so we keep things tidy, and if they want to do it themselves they probably already have a namespace.

**Comment by HumairAK** [comment]
So the action items I'm seeing are: 
- a nice easy issue template for users to fill out
- an "app" in the apps repo that manages OBCs for the moc environment (possibly other environments??)

**Comment by tumido** [comment]
I think this should also include guidance onto how to set up: https://github.com/operate-first/support/issues/53 (policy and external routes)

I might need to look into that a bit more.

**Comment by HumairAK** [comment]
Docs for ocs here: https://github.com/operate-first/apps/tree/master/docs/ocs
