### ISSUE TITLE
Login grafana.operate-first.cloud with oAuth operate-first leads to Server Error 500

### ISSUE THREAD

**Issue by schwesig** [operate-first/support#480]
**Describe the bug**
Login to grafana.operate-first.cloud leads to an Server Error, 500.
This happened when using OAuth with operate-first.
The error was not reproducible for some users @larsks @dystewart.
Assumption: this error only happens for users not yaml defined and/or with no group registration in grafana-oauth.yaml. [^1]

**To Reproduce**
1. Go to https://grafana.operate-first.cloud/login
2. Click on 'Sign in with OAuth'
3. Click on 'operate-first'
4. See error 1. webpage response, 2. server log

webpage response, Server Error
```
Grafana / Server Error
Sadly something went wrong
login.OAuthLogin(missing saved state)

Check the Grafana server logs for the detailed error message.
```

server log, status=500

```Apache Log
t=2021-11-23T11:18:56+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
t=2021-11-23T11:19:02+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
t=2021-11-23T12:18:35+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="invalid role"
t=2021-11-23T12:18:35+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=84.175.167.82 time_ms=25 size=1751 referer=
```

**Expected behaviour**

~~- [ ] For registered/role configured users/role, no error at all (this seems to be working).~~ 
- [ ] For unknown users a more user friendly message and internally a controlled exit.
- [ ] for unknown users --> nice2have: link to "how to register/PR yaml config"

**Screenshots**

![ksnip_20211123-173649](https://user-images.githubusercontent.com/89909507/143140152-2323e455-f644-464c-accd-239ea75a8121.png)

![ksnip_20211123-173837](https://user-images.githubusercontent.com/89909507/143140382-a1276e6f-efb4-4996-b508-8724eef4ef9d.png)

![ksnip_20211123-173938](https://user-images.githubusercontent.com/89909507/143140308-018f431c-c1ed-41e4-b881-b4b8848ea2c1.png)

**Additional context**
...

[^1]: https://github.com/operate-first/apps/blob/806adf2599fe0180237503573c32b894529afdca/grafana/overlays/moc/smaug/grafana-oauth.yaml#L29-L38

**Comment by HumairAK** [comment]
To add to this -- we have a simple doc on how to resolve this: https://www.operate-first.cloud/hitchhikers-guide/apps/docs/grafana/map_groups_to_roles.md

**Comment by larsks** [comment]
> we have a simple doc on how to resolve this

That only resolves half the problem; the fact that this is failing with a 500 status error, rather than presenting some sort of "authentication failed" message, is a user experience issue for which we don't currently have a resolution.

**Comment by HumairAK** [comment]
Yeah definitely. Grafana would need to offer a way to do this, otherwise this would be an upstream issue I imagine.

**Comment by schwesig** [comment]
@HumairAK thanks
