### ISSUE TITLE
Add msdisme to operate-first

### ISSUE THREAD

**Issue by msdisme** [operate-first/support#482]
**I would like to be added to the organization so that it is easier for issues and such to be assigned to me. **

**We looked for how to do this (@quaid  is not an admin) and figured asking was easiest..*

**Comment by HumairAK** [comment]
Docs here: https://github.com/operate-first/common/blob/main/docs/add_gh_member_and_access.md#become-a-github-member 

Still need to be added to the website. 

Out of curiosity, where did you look first? I'd like to make finding this easier.

**Comment by msdisme** [comment]
I looked under [I am an Open Source Develoepr](https://www.operate-first.cloud/hitchhikers-guide/apps/docs/about/intro.md), briefly at the top level of https://github.com/operate-first, and I think @quaid may have looked in blueprints.

**Comment by quaid** [comment]
I also looked in the Community Handbook, because I thought it might have been linked to from there.

**Comment by HumairAK** [comment]
Okay so, I think as part of the design discussed [here](https://github.com/operate-first/SRE/issues/424), that section will be a generalized "Community Handbook" section, [this intro](https://www.operate-first.cloud/hitchhikers-guide/apps/docs/about/intro.md) should probably be in the Community repo (I don't think it requires interaction with `apps` repo, nor is it gitops related).
But should link to the the how-to docs (linked above) found in the GitOps section. For example something like: 

![image](https://user-images.githubusercontent.com/10904967/143257153-875cf9b0-cddc-45b7-9e1f-76f3bcac762b.png)

WDYT? Would that be better?

**Comment by quaid** [comment]
Original issue of adding Michael to the org was resolved, and we're working on the issues discussed here in new working groups, so closing this issue as completed.
