### ISSUE TITLE
Add member (@suppathak) to data-science group on smaug clusters

### ISSUE THREAD

**Issue by suppathak** [operate-first/support#483]
Add @suppathak to data-science group on smaug clusters.

**Comment by HumairAK** [comment]
Instructions [here](https://github.com/operate-first/apps/blob/master/docs/cluster-scope/add_user_to_group.md) can you make a pr @suppathak ?

**Comment by suppathak** [comment]
> Instructions [here](https://github.com/operate-first/apps/blob/master/docs/cluster-scope/add_user_to_group.md) can you make a pr @suppathak ?

Here is the link to the PR: https://github.com/operate-first/apps/pull/1380
