### ISSUE TITLE
Access to apps' data

### ISSUE THREAD

**Issue by Leeron-Luzzatto** [operate-first/support#485]
Hi,

I'm working on a collaborate project between the Technion and Red Hat (under Ilya Kolchinsky, ikolchin@redhat.com).
For the project, I need your apps' data (storage & CPU usage, Prometheus).

Please help.

Thanks in advance,

Leeron Luzzatto.

**Comment by 4n4nd** [comment]
@Leeron-Luzzatto hey we have docs [here](https://www.operate-first.cloud/hitchhikers-guide/apps/docs/observatorium/thanos/request_thanos_access.md) that you can use to request access to our prometheus metrics. Can you follow these make PRs?

**Comment by Leeron-Luzzatto** [comment]
The link you sent is broken, can you please send a new one?
