### ISSUE TITLE
Install kyverno in operate-first for tekton chains image verification

### ISSUE THREAD

**Issue by screeley44** [operate-first/support#488]
It looks like now the last piece to set up is the image verification? If so I think we could use Kyverno

https://cloud.redhat.com/blog/software-supply-chain-security-on-openshift-with-kyverno-and-cosign

related to: https://github.com/operate-first/support/issues/438 

https://kyverno.io/docs/installation/

**Comment by screeley44** [comment]
@harshad16 @HumairAK

**Comment by screeley44** [comment]
https://raw.githubusercontent.com/kyverno/kyverno/release-1.5/definitions/release/install.yaml

**Comment by HumairAK** [comment]
> **Scott Creeley wrote:**
> Humair Khan Harshad - I created the following issue and start of a PR for kyverno (image verification after signing) namespace, rbac, etc...
> <https://github.com/operate-first/support/issues/488>
> <https://github.com/operate-first/apps/pull/1404>
> 
> no idea if I did this correct?
> 
> **Humair Khan wrote:**
> hey Scott Creeley nice, I think this looks good, everything seems in its right place except maybe the configmap, though I'll need to take a deeper look -- might not get to it today, but can take a look tomorrow morning/early afternoonish
> 
> **Humair Khan wrote:**
> Harshad Anand Sanmukhani if you are around ^
> 
> **Scott Creeley wrote:**
> thanks Humair Khan - let me know how I can help
> 
> **Humair Khan wrote:**
> I see you asked about SA/deployments/crd's etc.,
> 
> so the CRD's will also go in the cluster-scope directory, if you search for the apiextensions api group,
> 
> but SA/Deployment/Configmaps, basically anything you can typically deploy as a project admin, they will go in a separate directory in the root of `apps` repo, these will be deployed as a separate ArgoCD application
> 
> **Humair Khan wrote:**
> for example we deploy this operator manually as welll: <https://github.com/operate-first/apps/tree/master/odh-operator>
> 
> all the cluster resources for it are in the `cluster-scope` directory, but you can see that we put the deployment/SA/etc. in the `base` then pull it down to the `overlays/moc/smaug` folder
> 
> **Humair Khan wrote:**
> any thing cluster specific will go in the `overlays`
> 
> **Humair Khan wrote:**
> so probably the configmaps in this case (unless they are also super generic I suppose :man-shrugging: )
> 
> **Humair Khan wrote:**
> then you need an argocd app to deploy this path, add this application declaratively here, you can see the other manifests there for an idea of how to populate it, I think it's relatively self explanatory, but we also have some <https://www.operate-first.cloud/apps/content/argocd-gitops/add_application.html|docs> here for it.
> <https://github.com/operate-first/apps/tree/master/argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first>
> 
> **Humair Khan wrote:**
> _really need to document this_
> 

_Transcript of Slack thread: https://operatefirst.slack.com/archives/C01RMPVUUK1/p1638478085167200?thread_ts=1638478085.167200&cid=C01RMPVUUK1_

**Comment by screeley44** [comment]
App Root PR  https://github.com/operate-first/apps/pull/1427

**Comment by larsks** [comment]
I'm concerned that Kyverno is a really big hammer if the only immediate need is for signed image verification. It looks as if another project already exists [for this particular purpose](https://github.com/sse-secure-systems/connaisseur), and I wonder if that wouldn't be a better alternative at the moment.

**Comment by cooktheryan** [comment]
https://github.com/operate-first/continuous-delivery/pull/28

**Comment by codificat** [comment]
/close
as we are going with `cosigned` instead, see https://github.com/operate-first/apps/pull/1560
