### ISSUE TITLE
NEW PROJECT: <name>

### ISSUE THREAD

**Issue by PixelJonas** [operate-first/support#489]
### Target cluster

Rick

### Team name

team-pixel

### Desired project names

pixel-secrets

### Project description

HashiCorp Vault instance to be an endpoint for ArgoCD Vault Plugin

### Users needing access

pixeljonas

### Namespace Quota

Small

### Your GPG key or contact

`99162C16B48AD5796CF5423C2220DF90AC76156B` available at keys.openpgp.org

**Comment by HumairAK** [comment]
Hello!

> HashiCorp Vault instance to be an endpoint for ArgoCD Vault Plugin 

Could we get a bit more info about this project? Which ArgoCD instance is this? 

Also any particular reason you've picked `rick` cluster? This cluster is unfortunately capped on resources atm. We generally direct most userworkloads to `smaug` unless otherwise requested.

**Comment by PixelJonas** [comment]
I'm currently working together with @rbo to create documentation for the german solution architects.

I'm planning to have an external Vaul running on `rick` to be used for my private argocd instance as a store for secrets

**Comment by PixelJonas** [comment]
is there any update on this?

**Comment by HumairAK** [comment]
Hey sorry -- so I took a look at rick's resources, and there's  ~1-2 free cores, I suppose that could accommodate the `small` quota, I think we can also make some room in it as I see some services deployed we no longer need. As it's eod right now, we can continue with onboarding this upcoming Monday, I'll follow up then.

**Comment by HumairAK** [comment]
Had some various outages today so did not have time to get to it. Will send a pr in the coming days.

**Comment by durandom** [comment]
@HumairAK do you have a recent PR that can act as an example for adding project/group and namespace?

@Gregory-Pereira didn't we have bots to automate that?

**Comment by HumairAK** [comment]
This should offer detailed instructions: https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html 

Follow the links mentioned there, if you do not know about notebooks or how to use the operate-first JH instance to onboard read [here](https://www.operate-first.cloud/apps/content/notebooks/README.html). Let us know if there are any issues!

**Comment by PixelJonas** [comment]
I followed the notebook creating:
https://github.com/operate-first/apps/pull/1585

**Comment by HumairAK** [comment]
Great, I see namespace was created. Can this be closed now?
