### ISSUE TITLE
smaug cluster object storage is down / prow is down

### ISSUE THREAD

**Issue by codificat** [operate-first/support#490]
**Describe the bug**

Prow is not working, and while investigating why, it seems to be that ceph/object storage is causing the issue.

**To Reproduce**
1. Go to the opf-ci-prow namespace in smaug
2. check the pods that are there
3. One example is tide: `oc logs tide-78656ccf44-pb96z`
4. See error:

```
{"component":"tide","error":"error initializing history client from \"s3://ci-prow/tide/tide-history.json\": open: blob (key \"tide/tide-history.json\") (code=Unknown): SerializationError: failed to unmarshal error message\n\tstatus code: 504, request id: , host id: \ncaused by: UnmarshalError: failed to unmarshal error message\n\t00000000  3c 68 74 6d 6c 3e 3c 62  6f 64 79 3e 3c 68 31 3e  |\u003chtml\u003e\u003cbody\u003e\u003ch1\u003e|\n00000010  35 30 34 20 47 61 74 65  77 61 79 20 54 69 6d 65  |504 Gateway Time|\n00000020  2d 6f 75 74 3c 2f 68 31  3e 0a 54 68 65 20 73 65  |-out\u003c/h1\u003e.The se|\n00000030  72 76 65 72 20 64 69 64  6e 27 74 20 72 65 73 70  |rver didn't resp|\n00000040  6f 6e 64 20 69 6e 20 74  69 6d 65 2e 0a 3c 2f 62  |ond in time..\u003c/b|\n00000050  6f 64 79 3e 3c 2f 68 74  6d 6c 3e 0a              |ody\u003e\u003c/html\u003e.|\n\ncaused by: expected element type \u003cError\u003e but have \u003chtml\u003e","file":"prow/cmd/tide/main.go:159","func":"main.main","level":"fatal","msg":"Error creating Tide controller.","severity":"fatal","time":"2021-12-03T14:35:20Z"}
```

**Additional context**

There is an ongoing issue with the cluster worker nodes, https://github.com/operate-first/SRE/issues/430

I am not sure how/if this is related

**Comment by larsks** [comment]
I have opened support case https://access.redhat.com/support/cases/#/case/03095663 for this issue.

**Comment by codificat** [comment]
I believe that the issue with the storage is resolved now, 
/assign @larsks 
to confirm / provide details / close as appropriate.
Thanks

**Comment by larsks** [comment]
I confirm that storage is back up. We were generally tracking this in https://github.com/operate-first/SRE/issues/430.
