### ISSUE TITLE
Deploy KSpan & Jaeger

### ISSUE THREAD

**Issue by sallyom** [operate-first/support#491]
KSpan generates OpenTelemetry spans from Kubernetes Events: https://github.com/weaveworks-experiments/kspan 
Unlike https://github.com/operate-first/support/issues/401  KSpan does not require K8s flags or feature-gates to be enabled. It will be beneficial for SREs, developers to have correlated events visualized with Jaeger. 

TODO: Automate KSpan deployment

/cc @4n4nd

**Comment by sallyom** [comment]
@pavolloffay

**Comment by pavolloffay** [comment]
This is related to https://github.com/open-telemetry/opentelemetry-operator/issues/565. We are looking for the best place for kspan. It might be added as OTEL collector receiver component in the future. However, it will not change any functionality, only how it is deployed.

**Comment by sallyom** [comment]
Also, this is related to https://github.com/operate-first/support/issues/401 but this can be completed without OKD modifications

**Comment by sallyom** [comment]
Update:
**jaeger:** 
* Red Hat distributed tracing platform appears to be the same as Jaeger Community Operator and both are available from OperatorHub
* as **cluster-admin** I've installed the RH distributed tracing platform operator in a test cluster
    * this creates a controller that watches `Jaeger` CustomResources in configured namespaces (i've added the watch for all namespaces). 
    * when a `Jaeger` is created in any namespace, this triggers creation of jaeger services, pods, secrets, configmaps, and jaeger UI route in the same namespace as the Jaeger CR.
* as a **regular user** I can then create a project, and in that project I can create a `Jaeger` CustomResource, then I get my very own Jaeger pod/route and agent/collector/query services and various jaeger secrets,configmaps - and I can access that route.

**kspan**
* elevated privileges/rbac will be required with KSpan, because it watches cluster events, and regular users can only watch events in their own projects. I'm looking into whether KSpan can be configured to emit from only configured namespaces.

**summary - this I'll confirm over next few days**
* It will be beneficial to have this RH distributed tracing operator running in Op1st clusters. Once running, any **regular user** can bring their OpenTelemetry-instrumented applications and get access to a Jaeger UI by creating a Jaeger instance in  the user's namespace. Any OTLP-instrumented application can export traces to Jaeger (or to OpenTelemetry-Collector -> Jaeger).

**Comment by sallyom** [comment]
let's pick this up again - i let it slip due to other work
@4n4nd is there a process for installing the community Jaeger operator from the hub?
I'll work on getting a deployment in the apps repository for KSpan

**Comment by sallyom** [comment]
Here is a jaeger CR - when you create this in any namespace, some jaeger resources should be created:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: testjaeger
```

**Comment by sallyom** [comment]
https://github.com/operate-first/apps/pull/1933
https://github.com/operate-first/apps/pull/1932

**Comment by mimotej** [comment]
/remove-lifecycle stale

@sallyom Hi, is this resolved or is there still something that needs to be done?
