### ISSUE TITLE
How do you find what the cluster links are?

### ISSUE THREAD

**Issue by anishasthana** [operate-first/support#498]
I struggled to find out where the clusters are linked. I may have missed an obvious option, but here's the path I ended up taking.

1. https://www.operate-first.cloud/
2. https://www.operate-first.cloud/hitchhikers-guide/support/README.md (Link was broken), so go back to homepage
3. Click on SRE learners, go to https://www.operate-first.cloud/sre-learners
4. community handbook
5. https://www.operate-first.cloud/community-handbook/main/README.md, then support
6. I then clicked on gitops, ended up at https://www.operate-first.cloud/apps/content/README.html
7. Gave up, asked Humair directly.

**Comment by bryanmontalvan** [comment]
Hey @anishasthana did you have anything specifically in mind? 

I think adding an quick introduction and description of the clusters in the `Support` page would suffice. Made a quick mockup
<img src="https://user-images.githubusercontent.com/68972382/152433889-2fb5de5f-2cc9-4091-a9c8-e02ca6c25447.png" width="600"/>

Let me know what you think, and @HumairAK should Balrog be added? Bit confused on where balrog fits into environments picture

**Comment by anishasthana** [comment]
Yeah honestly this  looks pretty good. Could you also add links on each line to the openshift-console

**Comment by anishasthana** [comment]
Oooh nice, that works too!

**Comment by HumairAK** [comment]
cluster links are now one of the first pieces of information displayed for the operate first community cloud page: https://www.operate-first.cloud/community-cloud, hopefully this is sufficient :)
