### ISSUE TITLE
NEW PROJECT: Fedora Project Dev/Test

### ISSUE THREAD

**Issue by mattdm** [operate-first/support#500]
### Team name

fedora

### Desired project names

fedora

### Project description

The Fedora Project has a [production OpenShift cluster](https://os.fedoraproject.org/) but the [process for getting an application into that environment](https://docs.fedoraproject.org/en-US/infra/developer_guide/openshift/) has a high barrier to entry.

That process in geared around our production infrastructure and the team which runs that. This is good for folks where that is their focus. But it'd be nice for community members — a programmer on the desktop team, say, or a Project Leader with a prototype idea  — to be able to develop, test, stage, and deploy in an easy manner. We need a environment in which any Fedora Project member can easily develop and test small projects.

And if a project gets to the point where it's ready to move to production, we need a way easily generate from that what the Fedora Infrastructure team needs to deploy to the production cluster.

### Users needing access

mattdm

To start, just me. I'd eventually like to make this available to any Fedora Project member. 

### Namespace Quota

Small

### Custom quota

I think we can start with small, but of course if it's successful will need to scale up.

### Your GPG key or contact

8F721E6E74CF369AF44355EF688E1340A7D25EB6 available from https://keybase.io/mattdm

**Comment by mattdm** [comment]
@durandom tag!

**Comment by 4n4nd** [comment]
@mattdm 
> the process for getting an application into that environment has a high barrier to entry.

Instead of creating a namespace for your workloads to one of the operate first clusters, we could just onboard your existing cluster to the operate first fleet. 
Onboarding your cluster to operate first would mean: 
1. You could use the operate first login, which uses github accounts for management. You can see the list of openshift groups and users we have [here](https://github.com/operate-first/apps/tree/master/cluster-scope/base/user.openshift.io/groups)
2. Use the operate first [ArgoCD instance](https://argocd.operate-first.cloud/) for gitops on your cluster 
3. Manage all your cluster-scoped resources using gitops with [this directory](https://github.com/operate-first/apps/tree/master/cluster-scope) as the source

**Comment by 4n4nd** [comment]
I might have misunderstood this. If you just want a project, we have a guide available [here](https://github.com/operate-first/hitchhikers-guide/blob/main/pages/onboarding_project.ipynb) that you could use. All tools required to run through the guide should be available in [this toolbox image](https://github.com/operate-first/toolbox).
We will appreciate any feedback that you could give us for the docs.

**Comment by durandom** [comment]
The 2nd response is what we're looking for. I suggest a namespace on smaug for a fedora team with @mattdm as the single team member for now.

@mattdm would be great if you'd try to come up with a PR based on the documentation at 

https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html and
https://github.com/operate-first/hitchhikers-guide/blob/main/pages/onboarding_project.ipynb 

cc @4n4nd @HumairAK which one is correct? :)

**Comment by 4n4nd** [comment]
[The second one](https://github.com/operate-first/hitchhikers-guide/blob/main/pages/onboarding_project.ipynb) should be the easier guide to follow

**Comment by mattdm** [comment]
Yes. Just have had a lot going on and other things drawing my priority attention.

**Comment by Gregory-Pereira** [comment]
No Problem. I have made the PR so the work is done, and once it gets merged you should have access and can deal with it when you have time.

**Comment by mattdm** [comment]
Thanks!

-- 
Matthew Miller            ***@***.***             <http://mattdm.org/>
Fedora Project Leader  ***@***.***  <http://fedoraproject.org/>

**Comment by Gregory-Pereira** [comment]
Closing this issue as the namespace has been created and is availalbe.
