### ISSUE TITLE
Deploy grafana in osc cluster, leverage existing dashboards

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#502]
Ideally we would send osc cluster/app metrics to operate-first thanos so that we can just use the existing grafana instance and the dashboards to visualize metrics in the osc cluster, and also have long term storage for these metrics. 

However, there's currently no way to prevent non osc cluster users from seeing these metrics. In other words, anyone with access to the op1st grafana would be able to see the metrics on the osc cluster if we went this route. I'm guessing that's a no. 

So the next step is to install grafana operator + grafana in osc, and leverage these same dashboards in the osc cluster. With kustomize we don't need to recreate these, and can continue to manage these centrally, but have them deployed in multiple locations.

**Comment by HumairAK** [comment]
I think this was briefly brought up in the last sig-ops meeting. So I'm going to bump this a bit and tag some folks to discuss this a bit further: 


@durandom @redmikhail @erikerlandson  @4n4nd 

Currently the osc-cl1/osc-cl2 cluster metrics are handled differently than other operate-first cloud clusters. That is to say...they are not really being monitored at all. 

As mentioned in the original post, ideally we would unify how we monitor all our clusters and not have any special cases. This would mean forwarding all osc-cl* metrics to our thanos central instances so we can use our grafana dashboards there to monitor all clusters, including osc-cl* clusters. 

The initial concern was that, we are very open to who gets access to grafana instance. And we would be forwarding all cluster metrics to this thanos instance, which would make them queryable by anyone with grafana access. **Is this fine?**

The pros are that this makes osc-cl* a lot easier to monitor, as we don't need to treat them as special cases. They will automatically benefit from all the dashboards we create.

**Comment by erikerlandson** [comment]
> And we would be forwarding all cluster metrics to this thanos instance, which would make them queryable by anyone with grafana access. Is this fine?

IMO, as long as we aren't leaking any data that could either (1) compromise any data commons access credentials, or (2) leak privileged data from trino or other data resources from the data commons, then I do not see a problem with that.
