### ISSUE TITLE
Add a way to label pull-request "needs squash" with a message prompt by sesheta on how-to

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#503]
**Describe the solution you'd like**

It is very common for first time contributors to send PRs without squashing their commits. It would be nice if I could add a label to such PR's and have sesheta leave a message linking to the [contributing doc]() about squashing their commits.

**Comment by GaryPWhite** [comment]
question from the thread that contributed: Why not use the `squash + merge` option for these cases?

**Comment by HumairAK** [comment]
@GaryPWhite we can do that, but that requires a person to manually do a merge, whereas for our ci we let the bot handle this via `/approve`, ensuring that merge's only happen once ci checks pass etc.

**Comment by GaryPWhite** [comment]
that makes sense! I would figure it's in the API somewhere, but that sounds like an edge case headache. Thanks for the extra context!

**Comment by HumairAK** [comment]
np, maybe there  is a way to use prow to squash + merge, I have not looked into this though @harshad16 any ideas?

**Comment by harshad16** [comment]
there is a option to squash and merge
if that is more preferred we can turn on the squash before merge feature.

**Comment by HumairAK** [comment]
@harshad16 pointed out that it's already enabled. So it should be auto squashing it. We should test and verify.

Then I suppose we will just need to ensure that commit messages are meaningful. Though this is handled by github's squash/merge, which allows the maintainer to fix up the messages as needed. Would be nice if we could do this with prow, but doesn't seem like we can... :shrug: 

Regardless, I don't think we need such a label, so closing.
