### ISSUE TITLE
Please create a clientId & Secret for morty cluster at https://keycloak-keycloak.apps.moc-infra.massopen.cloud/auth/realms/operate-first

### ISSUE THREAD

**Issue by rbo** [operate-first/support#504]
**User story**

I want to connect our new morty cluster https://console-openshift-console.apps.morty.emea.operate-first.cloud to https://keycloak-keycloak.apps.moc-infra.massopen.cloud/ for authentication

**Additional context**

**Acceptance Criteria**
- [ ] At least once acceptance criteria should be present

**Linked epics / issues**

**Comment by HumairAK** [comment]
done via https://github.com/operate-first/apps/pull/1470

**Comment by rbo** [comment]
Just for documentation: part of  https://github.com/operate-first/apps/issues/1471
