### ISSUE TITLE
NEW PROJECT: training-model namespace

### ISSUE THREAD

**Issue by cooktheryan** [operate-first/support#506]
### Target cluster

Smaug

### Team name

model-trainers

### Desired project names

training-model

### Project description

We need a namespace for the training VM to be ran. 

### Users needing access

cooktheryan,treeinrandomforest,michaelclifford

### Namespace Quota

Large

**Comment by 4n4nd** [comment]
@cooktheryan we have a small guide available [here](https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html). Can you follow the instructions in it and create a Pull Request to onboard your project?
