### ISSUE TITLE
Broken link on homepage

### ISSUE THREAD

**Issue by amfred** [operate-first/support#513]
**Describe the bug**

**To Reproduce**
(Google Chrome browser)
1. Go to ['Operate First'](https://www.operate-first.cloud/)
2. Scroll down near the bottom of the page and click on 'Find out about our resources'
3. The link https://www.operate-first.cloud/hitchhikers-guide/support/README.md opens
4. The page displays an error instead of the main content. "Not Found
You just hit a route that doesn't exist... the sadness."

**Expected behaviour**
A properly rendered webpage

**Screenshots**
"Find out about our resources" link:
![image](https://user-images.githubusercontent.com/1302432/151187493-0d6ee207-318d-4a20-bcf3-e36d6f5f4e2e.png)

Broken page:
![image](https://user-images.githubusercontent.com/1302432/151187614-7362b6c4-13e1-4876-b7f4-e001139a4f16.png)

**Additional context**

**Comment by larsks** [comment]
This was fixed by https://github.com/operate-first/operate-first.github.io/pull/355
