### ISSUE TITLE
https://www.operate-first.cloud/hitchhikers-guide/support/README.md is broken

### ISSUE THREAD

**Issue by billburnseh** [operate-first/support#517]
**Describe the bug**
The above like reports a 404...sadness as they say

**To Reproduce**
Click on the link and see that it's broken

**Expected behaviour**
Should get yo to the HitchHikers Guide support readme
 
**Screenshots**
N/A

**Additional context**
N/a

**Comment by larsks** [comment]
In fact, it's https://www.operate-first.cloud/ that is broken; it has  a stale link that needs updating. I'll submit a PR.
