### ISSUE TITLE
Onboard ManageIQ

### ISSUE THREAD

**Issue by durandom** [operate-first/support#518]
### Target cluster

Infra

### Team name

manageiq

### Desired project names

manageiq

### Project description

I talked to @fryguy and @chessbyte from the https://github.com/manageiq community to deploy an instance of ManageIQ to our environment.

The initial use-case would be to connect as many cloud accounts (providers) and display resource usage. Later it can serve a complimentary use-case as to ACM.

The instance can be deployed via an operator and the configuration should be deployed via ArgoCD.

### Users needing access

fryguy, chessbyte

### Namespace Quota

Large

**Comment by durandom** [comment]
@fryguy can you add some more resource requirements for a minimal instance?
@4n4nd can you point to docs and a PR that deploys an operator that is not part of operatorhub?

**Comment by durandom** [comment]
We can also start with smaug and later move the app to the infra cluster.

**Comment by chessbyte** [comment]
Exciting stuff!

**Comment by Fryguy** [comment]
cc @bdunne @agrare @jrafanie @kbrock

**Comment by 4n4nd** [comment]
@chessbyte @Fryguy you can start by onboarding your team/project to the moc/smaug cluster using [these instructions](https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html).

Once a namespace is available for your project, you can add a new application in the apps repo ([example PR](https://github.com/operate-first/apps/pull/628)) which deploys the operator in your project namespace.

Please let me know if you folks any help with this.

**Comment by Fryguy** [comment]
@bdunne can you comment here with resource requirements?  At least for, say, if we include 1 amazon provider to start?

**Comment by Fryguy** [comment]
Just noticed that https://github.com/operate-first/apps/pull/628 is @tumido's PR. Hi @tumido 👋

**Comment by bdunne** [comment]
Hi @durandom I think 2 cores, 10GB RAM and a 15GB PVC is probably a minimum starting point.

**Comment by 4n4nd** [comment]
@bdunne you should be able to choose the resource quota for your project if you follow the above mentioned process

**Comment by Gregory-Pereira** [comment]
Hi @Fryguy and @chessbyte, could you confirm that you are still interested in an Operate-First namespace?

**Comment by Fryguy** [comment]
Yes, we are interested, but we've been swamped with our release at the current time.

**Comment by Gregory-Pereira** [comment]
Yeah no problem, I made the PR so the work is done. You should have access once it gets merged and can deal with it at your leisure.
