### ISSUE TITLE
routes are created in a broken way

### ISSUE THREAD

**Issue by goern** [operate-first/support#52]
**Describe the bug**
have a look at https://prow.operate-first.cloud/ and https://console-openshift-console.apps.cnv.massopen.cloud/k8s/ns/opf-ci-prow/routes/deck/yaml routes seem to miss the certificate and the canonical host name is strange?!

**To Reproduce**
apply https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod/secret-generator.yaml#L7

**Expected behaviour**
valid certs are used to server https

/king bug
/sig devops
/assign @harshad16 
/assign @tumido

**Comment by harshad16** [comment]
This was fixed from our end (thoth-station), the manifest was missing some bytes. 
Thanks, closing this
