### ISSUE TITLE
need to improve onboarding_project.ipynb re authentication for git push

### ISSUE THREAD

**Issue by jeremychoi** [operate-first/support#521]
**Describe the bug**

Rather than a bug, this is feedback for the notebook to be improved.

'!git push' in the notebook (seen in https://www.operate-first.cloud/apps/content/notebooks/onboarding_project.html ) will require the user to put their username/password for Github authentication, which makes the notebook run hang, if simply running the notebook. (waiting for user input which doesn't seem to be possible to be provided)

I had to sort it out by manually pushing in the terminal via the "Open git Repository in Terminal" menu.  

It would be nice to add some comments(or instructions) to the notebook.

**To Reproduce**

Run the notebook as is(up to !git push), as a new github user.

**Comment by HumairAK** [comment]
same as: https://github.com/operate-first/support/issues/588 
 which is now addressed/resolved, closing.
