### ISSUE TITLE
NEW PROJECT: boatroackers

### ISSUE THREAD

**Issue by husky-parul** [operate-first/support#524]
### Target cluster

Smaug

### Team name

boatroackers

### Desired project names

boatrockers

### Project description

Testing volsync managed service on operate first.

### Users needing access

husky-parul

### Namespace Quota

Large

### Your GPG key or contact

86AA33D3B33DD202B2564EE5DCDA96433EA640A3 available from http://keyserver.ubuntu.com/

**Comment by HumairAK** [comment]
Hello @husky-parul ! 

How do you feel about self servicing this request? We have a jupyter notebook that you can use to onboard yourself (we're looking to improve this process as well so feedback is appreciated), it's all relatively automated, you just fill out some fields in the first codeblock and fork the repo (making sure main branch is sync'd with upstream master). 

https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_to_cluster.html 

Jupyterhub instance is here: https://jupyterhub-opf-jupyterhub.apps.smaug.na.operate-first.cloud/

**Comment by husky-parul** [comment]
Hi @HumairAK 
Sorry I am not understanding it correctly, the link you've shared is to onboard a project. I don't need to onboard projects, I am trying to use the projects/apps already present on operate first env. I just want to privilege to run a given workload in a namespace and use the hosted managed services. Do I need to onboard the workload I am wanting to run as a project?

**Comment by HumairAK** [comment]
@husky-parul onboard project in this context means to get an OCP namespace provisioned, with a quota set based on what cpu/memory/storage/etc you require for this namespace, as well ass the people that will need access to said namespace.

**Comment by husky-parul** [comment]
Yes that's right and thank you for putting the context. I get it now. So I need to follow this [notebook](https://www.operate-first.cloud/apps/content/notebooks/onboarding_project.html)

**Comment by HumairAK** [comment]
@husky-parul in this case it seems that @Gregory-Pereira has sorted our the pr for you, so you no longer need to do that, we just need to review/merge this pr: https://github.com/operate-first/apps/pull/1666

Once merged, our argocd instance will bring these changes to live and your should have your namespace privisioned w/ access.

**Comment by HumairAK** [comment]
@husky-parul namespace was provisioned, see if you can access it here: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/boatrockers/pods

**Comment by husky-parul** [comment]
I was able to access the namespace. Thank you.
