### ISSUE TITLE
Curator team unable to access https://github.com/operate-first/curator-operator

### ISSUE THREAD

**Issue by gagansk** [operate-first/support#526]
**Description**
The Curator team is unable to push commits to https://github.com/operate-first/curator-operator repository. We are also unable to create Milestones. 

**Additional context**

**Comment by tumido** [comment]
Hi @gagansk, you need to follow this guide https://github.com/operate-first/common/blob/main/docs/add_gh_member_and_access.md

And add a line like this to your GitHub team: 
https://github.com/operate-first/common/blob/eb94cb641abcac87fc7c8aa7e7dea178930ff783/github-config.yaml#L284

**Comment by gagansk** [comment]
@tumido I followed that guide and created this PR: https://github.com/operate-first/common/pull/70

I have added a new member and addressed your last comment in https://github.com/operate-first/common/pull/74

**Comment by HumairAK** [comment]
@gagansk an invitation was sent to @timflannagan once they accept, they should have write access to this repo

**Comment by timflannagan** [comment]
@HumairAK Interesting - I just checked and I didn't see any notifications for an invite.

**Comment by HumairAK** [comment]
Hrmm strange, it says it's pending here: 
![image](https://user-images.githubusercontent.com/10904967/156038976-a02631e2-2d53-4672-8cd4-8a53073953a4.png)

Where are you looking? I believe it also gets emailed out to whatever email is attached to your gh account.

**Comment by timflannagan** [comment]
It looks like I didn't get the notification but I just checked my personal email and it looks like that invite _just_ got routed through. I just accepted the invite so we should be good to go.

**Comment by HumairAK** [comment]
awesome!, let us know if you are able to push successfully!

**Comment by timflannagan** [comment]
Just pushed my local branch up to o-f/curator-operator: https://github.com/operate-first/curator-operator. I think we can close this out now. Thanks for the help :tada:

**Comment by HumairAK** [comment]
Npnp, closing.
