### ISSUE TITLE
chrisproject

### ISSUE THREAD

**Issue by metaversed** [operate-first/support#527]
### Target cluster

Smaug

### Team name

redhat-impact

### Desired project names

chrisproject

### Project description

Overview
ChRIS is a pervasively open source platform that utilizes cloud technologies to democratize medical analytics application development. It enables healthcare organizations to keep owning their data while benefiting from public cloud processing capabilities. ChRIS is developed as part of a collaborative effort between [Boston Children’s Hospital](https://childrenshospital.org/), [Red Hat](https://redhat.com/chris), [Boston University](https://bu.edu/rhcollab/projects/radiology), and [the Mass Open Cloud](https://massopen.cloud/) (MOC).

### Users needing access

metaversed

### Namespace Quota

Large

### Your GPG key or contact

-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEYh6R8RYJKwYBBAHaRw8BAQdAMeYsPKQEEqssxz2zCdkAXkcldbyRJZtBkpiS
96ssJo+0LlJhZ2h1cmFtIEJhbmRhIChhZGRlZCBncGcpIDxyYmFuZGFAcmVkaGF0
LmNvbT6IlAQTFgoAPBYhBDqV8M7Ra3NDfTlPdX/OxCjz/WMaBQJiHpHxAhsDBQsJ
CAcCAyICAQYVCgkICwIEFgIDAQIeBwIXgAAKCRB/zsQo8/1jGsznAPoD68BsMG6Z
QjxhZQh1tdbowwsWNIGLOrcDRetOt94rtQEAghtGZ9FtX4d6etYf4X9AlYeK4uPk
luJwFSPZ8ulPPQm4OARiHpHxEgorBgEEAZdVAQUBAQdAddjW7LUggYMglN+1T8hB
Pw5E7GzExsNWBtklHOJ+vSIDAQgHiHgEGBYKACAWIQQ6lfDO0WtzQ305T3V/zsQo
8/1jGgUCYh6R8QIbDAAKCRB/zsQo8/1jGtc2AP9WovS2+EuSOaqX6lgHBrfc/kwU
CyuJixHi3lbJRSVaYgEAtv7MpuswzSn6+KsZho9rvBapV6FFYcccijq6I1vddgM=
=96BY
-----END PGP PUBLIC KEY BLOCK-----

**Comment by HumairAK** [comment]
Hello @metaversed onboarding namespaces can be self serviced via jupyter notebooks, instructions are here: https://www.operate-first.cloud/apps/content/odh/jupyterhub/access_jupyterhub.html 

You can use our jupyterhub to provision the notebook found here: https://www.operate-first.cloud/apps/content/odh/jupyterhub/access_jupyterhub.html
