### ISSUE TITLE
Notebook cannot perform put operation on to s3 nooba bucket on Smaug

### ISSUE THREAD

**Issue by hemajv** [operate-first/support#529]
EDIT by @HumairAK : This looks like it's an issue at the s3 level, not trino, read comments in this thread for further context.
----

**Describe the bug**
Unable to upload data to `opf-datacatalog` bucket

**To Reproduce**
1. Spin up a notebook on opf smug jupyterhub
2. Connect to the `opf-datacatalog` s3 bucket
3. Try uploading data to the s3 bucket under a specified directory path

**Expected behaviour**
Connect to the `opf-datacatalog` bucket and upload files to the bucket

cc @HumairAK

**Comment by HumairAK** [comment]
@hemajv can you post the code snippet that fails in the note book here with the output?

**Comment by HumairAK** [comment]
We tried this via a jh notebook, connected to trino via python trino lib and were able to query a table successfully.

**Comment by hemajv** [comment]
@HumairAK I believe the error is when we try to upload something to the bucket, we get:
```
ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```
We are pre-processing a data frame in the notebook which we then want to store as a parquet file to the bucket. However, seems like we don't have the permissions to do so?

**Comment by HumairAK** [comment]
@hemajv is there a code snippet you could provide us so we could run it to replicate this issue?

**Comment by HumairAK** [comment]
Updated the title of the issue, the issue seems to be related to s3 storage on smaug, in particular the opf-datacatalog bucket. We should verify that we can connect to this bucket and store data in there, and other buckets created using noobaa. This may be related to the recent nooba issues we experienced

**Comment by hemajv** [comment]
> @hemajv is there a code snippet you could provide us so we could run it to replicate this issue?

So we are basically doing the following:
```
# init s3 connector
s3c = S3Communication(
    s3_endpoint_url, aws_access_key_id, aws_secret_access_key, s3_bucket
)

# Upload the processed df to s3 as a parquet file
s3c.upload_df_to_s3(
    df=<data frame>,
    s3_prefix="open-services-group/metrics/github/issues",
    s3_key=f"{ORG}-{REPO}.parquet",
)
```
The error we get is:
![Screenshot from 2022-03-08 15-22-41](https://user-images.githubusercontent.com/7343099/157318715-d7a593e6-6aff-43df-a753-91c87a468fbb.png)

(the s3 class we have defined [here](https://github.com/open-services-group/metrics/blob/main/notebooks/s3_communication.py))

**Comment by 4n4nd** [comment]
@hemajv do you still see this issue? I just tested connecting to the bucket and successfully uploaded an object to it.

**Comment by suppathak** [comment]
I think the issue is somewhat what I am also facing right now.  Hence I am posting over here. 

As I am trying to retrieve contents for opf-datacatlog bucket (using the credentials from [here](https://www.operate-first.cloud/apps/content/odh/trino/access_public_bucket.html) ) 
`s3cmd ls s3://opf-datacatalog/ --access_key=S3_ACCESS_KEY --secret_key=secret_key --host=s3_endpoint --host-bucket=s3_endpoint/opf-datacatalog/` 

I am still getting an error as shown below: 
![Screenshot from 2022-03-09 08-59-18](https://user-images.githubusercontent.com/30439457/157492030-9a4892c1-427f-4004-8592-29a90181f165.png)

**Comment by larsks** [comment]
Using the credentials from the `opf-datacatalog` secret and the information from the `opf-datacatalog` configmap, I am not able to reproduce this problem.

Writing a file:

```
AWS_ACCESS_KEY_ID="$(kubectl get secret opf-datacatalog -o json | jq -r '.data.AWS_ACCESS_KEY_ID|@base64d')" \
$ AWS_SECRET_ACCESS_KEY="$(kubectl get secret opf-datacatalog -o json | jq -r '.data.AWS_SECRET_ACCESS_KEY|@base64d')" \
aws s3 \
  --endpoint https://s3-openshift-storage.apps.smaug.na.operate-first.cloud \
  cp testfile s3://opf-datacatalog/test.lars/testfile
upload: ./testfile to s3://opf-datacatalog/test.lars/testfile
```

Reading a file:

```
$ AWS_ACCESS_KEY_ID="$(kubectl get secret opf-datacatalog -o json | jq -r '.data.AWS_ACCESS_KEY_ID|@base64d')" \
AWS_SECRET_ACCESS_KEY="$(kubectl get secret opf-datacatalog -o json | jq -r '.data.AWS_SECRET_ACCESS_KEY|@base64d')" \
aws s3 \
  --endpoint https://s3-openshift-storage.apps.smaug.na.operate-first.cloud \
  cp s3://opf-datacatalog/test.lars/testfile newfile
download: s3://opf-datacatalog/test.lars/testfile to ./newfile
```

**Comment by suppathak** [comment]
Update: 
I was able to access `opf-datacatalog` bucket, using boto3. However, I am not sure why I still cannot access the bucket through s3cmd from the command line using the following command.
```
s3cmd ls s3://opf-datacatalog/ --access_key=S3_ACCESS_KEY --secret_key=secret_key --host=s3_endpoint --host-bucket=s3_endpoint/opf-datacatalog/
```

**Comment by hemajv** [comment]
> @hemajv do you still see this issue? I just tested connecting to the bucket and successfully uploaded an object to it.
> 
> I was using the minio client

I am still unable to upload to the bucket. Im using the `boto s3` python module and still get an access denied error. The creds for the bucket Im using are [here](https://github.com/operate-first/apps/blob/master/docs/content/odh/trino/access_public_bucket.md)

**Comment by suppathak** [comment]
> I am still unable to upload to the bucket. Im using the `boto s3` python module and still get an access denied error. The creds for the bucket Im using are [here](https://github.com/operate-first/apps/blob/master/docs/content/odh/trino/access_public_bucket.md)

Hey @hemajv ,

With the same credentials, I was able to get access: what is did was,

```
s3 = boto3.client('s3', endpoint_url= s3_endpoint_url,
                       aws_access_key_id = s3_access_key,
                       aws_secret_access_key = s3_secret_key)
```

The to list all the files in the bucket: 

```
for key in s3.list_objects(Bucket=s3_bucket)['Contents']:
    print(key['Key'])
```

And to upload files in a bucket:

```
s3.upload_file(Filename="filename.csv",
              Bucket=s3_bucket,
              Key = 'path/filename.csv')
```

It worked for me. May be this could help.
