### ISSUE TITLE
Insufficient permissions to access Superset

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/support#531]
When I log in Superset with my username, I see following errors:
![Screenshot from 2022-03-03 14-21-15](https://user-images.githubusercontent.com/8916126/156638228-20f99e50-ce10-456e-a35b-b5c44b019b1d.png)
)

I think permissions have to be updated to get me access to the dashboards.
cc @HumairAK @hemajv

**Comment by HumairAK** [comment]
hello, docs here on how to get access: https://www.operate-first.cloud/apps/content/odh/superset/add_superset_users.html 
let us know if something isn't clear!

**Comment by Shreyanand** [comment]
> hello, docs here on how to get access: https://www.operate-first.cloud/apps/content/odh/superset/add_superset_users.html let us know if something isn't clear!

Thanks @HumairAK the docs are awesome :rocket:  I created the linked PR following them.

**Comment by HumairAK** [comment]
@Shreyanand let us know if it worked, pr was merged.

**Comment by Shreyanand** [comment]
@HumairAK I still see the same error messages :thinking:

**Comment by HumairAK** [comment]
taking a look

**Comment by HumairAK** [comment]
@Shreyanand can this be closed now?

**Comment by Shreyanand** [comment]
yes, the lowercase user name did the trick. I can access the dashboard now.
