### ISSUE TITLE
Secure Cross-site Analytics on OpenShift Logs

### ISSUE THREAD

**Issue by jliagouris** [operate-first/support#533]
**Description**

This [project](https://www.bu.edu/rhcollab/projects/security-privacy/secure-cross-site-analytics-on-openshift-logs/) aims to explore whether cryptographically secure Multi-Party Computation, or MPC for short, can be used to perform secure cross-site analytics on OpenShift logs with minimum client participation. MPC enables mutually distrusting parties (in our case Red Hat clients using OpenShift) to compute arbitrary functions (e.g., identifying common trends involving crashes or failures) over their collective private data (in our case OpenShift log files) while keeping their data siloed from each other and from unauthorized third parties, including Red Hat itself.

The project will focus on a setting where Red Hat clients _securely outsource_ certain queries on their logs to untrusted non-colluding entities (e.g., Red Hat and the Mass Open Cloud) while retaining the strong security guarantees of MPC.

**For the purposes of this project we need:**

**1. Access to OpenShift log files stored in the [Loki](https://github.com/grafana/loki#loki-like-prometheus-but-for-logs) instance running in Operate First.**

**2. Examples of common log analysis tasks that are of interest to Red Hat engineers.**

**Additional context**

The proposed research will build on [Secrecy](https://arxiv.org/abs/2102.01048), a novel MPC framework for secure outsourced analytics with no information leakage that we have been developing at BU. Secrecy relies on a secret-sharing protocol and makes no assumptions about the physical deployment: computing parties can seamlessly be deployed in commercial clouds, Operate First, or on-premise clusters managed by Red Hat.

**Comment by jliagouris** [comment]
@pechora please have a look into 1.

**Comment by 4n4nd** [comment]
@jliagouris docs for 1. should be available [here](https://www.operate-first.cloud/apps/content/observatorium/loki/README.html).

**Comment by durandom** [comment]
I dont have a concrete example. 
@4n4nd @iNecas @erana  do we have runbooks that depend on examining log files?

**Comment by iNecas** [comment]
I would recommend checking https://github.com/openshift/ops-sop/blob/master/v4/alerts/, where there are a lot of examples of runbooks and many are touching on using logs as well, just random example https://github.com/openshift/ops-sop/blob/master/v4/alerts/FluentdQueueLengthIncreasing.md (I'm sure there are more)

**Comment by jliagouris** [comment]
Links seem to be broken.

**Comment by eranra** [comment]
@durandom I am not sure that there is anything "special" in Loki in comparison to the behavior against any other log store solutions. Same with regards to RH in comparison to other SRE's.

**Comment by eranra** [comment]
@Periklis maybe you can help here. The internal customer using Loki/observatorium, did they document the queries/usage?

**Comment by jliagouris** [comment]
@durandom The Loki server has been down for more than a week and we cannot make any progress without access to the logs. Do you have an estimation of when the service will be up? In the meantime, can we have a log dump or something to work with? We have been looking into the above alerts but we also need to extract and explore some related logs. @pechora

**Comment by durandom** [comment]
@HumairAK can you point us to any runbooks on how to troubleshoot loki?
@periklis would you be able to help if we grant you access to the loki/observatorium namespace?

**Comment by HumairAK** [comment]
@durandom we do not have any runbooks on loki. We can grant access, but they will need to dig into the logs & search existing docs, loki issues, etc. to resolve any issues.

For this issue in particular it is not a loki issue but an issue with storage on the [smaug cluster ](https://github.com/operate-first/operations/issues/479)

I believe @harshad16 has been helping with moving to storage on morty.

**Comment by harshad16** [comment]
Loki service is up and running from past few days.
please retry the service, and lets us know if you face any more issues.

**Comment by durandom** [comment]
@jliagouris @pechora please also see https://github.com/operate-first/apps/pull/2094/files for some documentation improvements.
I was able to query loki via the command line, which would allow you to export logs.

**Comment by jliagouris** [comment]
@SuJingyu111 can you have a look?

**Comment by durandom** [comment]
@jliagouris @SuJingyu111 are you still working on this? Do you still need logs?

/assign @durandom

**Comment by jliagouris** [comment]
Yes, we're still working on this. So far we've been using logs generated by our own applications running on OpenShift but we'd be happy to use any real logs you may have.
