### ISSUE TITLE
Shaw University data science internship 

### ISSUE THREAD

**Issue by cdolfi** [operate-first/support#534]
**Description**
I met with Dr. Butler at Shaw University regarding their current data science internship and goals for the future for providing data science courses/minor. The two action items that came from the call was on data science learning materials (@langdon is helping with this) and on getting shaw the cloud resources they need. Overall from that conversation I thought it would be good at the very least for Dr. Butler to connect with Opt1st about understanding better what he would need cloud resources wise to support his students, determining if Opt1st cloud would be able to provide this, and if there is other ways that Opt1st could support Shaw in their work towards their goals in data science

**Additional context**

Tagging @butlereric to give more context and will be the person to connect to about this

@HumairAK @hemajv

**Comment by mimotej** [comment]
/remove-lifecycle rotten

@cdolfi Hi, is this relevant, is it something that is being discussed?

**Comment by cdolfi** [comment]
@butlereric is this something you are still interested in?

**Comment by durandom** [comment]
@cdolfi do you want to reach out to @butlereric via 📫  ?

/assign @cdolfi

**Comment by cdolfi** [comment]
as @butlereric is overloaded right now with current classes, closing
