### ISSUE TITLE
[TASK] Checkout google groups feature to share documents with an group and not persons.

### ISSUE THREAD

**Issue by rbo** [operate-first/support#535]
Based on Meeting March 15.2022 : https://docs.google.com/document/d/1uEcLGP_sBSNwTLPOo_2Nu6oTqPytOTBt0c0_pVUQJwo/edit#

"Create a red hat google group for managing docs access across op1st, look into restrictions for this Robert Bohne"

**Comment by rbo** [comment]
There is a group available: https://groups.google.com/a/redhat.com/g/operate-first 

But we can also create our own group in RedHat or public with @googlegroups?

**Comment by schwesig** [comment]
/assign @rbo
issue solved? still need to create another/ our own group?

**Comment by rbo** [comment]
Nope, and I don't have the time to work one next 1-2 Months - sorry for that.

**Comment by durandom** [comment]
we're using hackmd and google docs public sharing.

/close
