### ISSUE TITLE
Need access to a cluster for a demo during Operate First meeting next week

### ISSUE THREAD

**Issue by heyselbi** [operate-first/support#537]
### Team name

multinode-demo

### Desired project names

multinode-demo

### Project description

I will be presenting a demo on multi GPU node ML workload distribution using Kubeflow, Pytorch and GPU operator. For the demo, I needed a cluster that will have 2 nodes, each node containing 1 GPU (total of 2 GPUs). It could run just for a week since the meeting is next week, unless cluster creation requires a longer time.

Here is a link to the meetup issue:
https://github.com/aicoe-aiops/operate-first-data-science-community/issues/56#issuecomment-1065543057

### Users needing access

heyselbi --> my GitHub username

### Namespace Quota

Custom

### Custom quota

I need two nodes of GPUs, each node containing 1 GPU. Total of 2 GPUs.

**Comment by durandom** [comment]
@heyselbi do you have more background on the requirements for the demo?

@redmikhail do you have a status link on the GPU availability on os-cl2 ?

**Comment by durandom** [comment]
> I will need the GPU operator, NFD Operator and Kubeflow (or ODH since it comes with Kubeflow)

**Comment by heyselbi** [comment]
This is the yaml file I will need to deploy:
https://github.com/heyselbi/multi-node-pytorch/blob/main/pytorch-dist.yaml

And this is needed for DS community meet up ( @oindrillac )

**Comment by heyselbi** [comment]
For access time: the sooner the better :) But since presentation is on Tuesday March 22, the day before that (Monday the 21st) should work too. If it's not possible, I can look into postponing it to week after or try to see if I could find GPU cluster with other avenues.

**Comment by HumairAK** [comment]
AFAIK the `osc-cl2` only has 1 gpu node. But I'll let @redmikhail confirm.

**Comment by redmikhail** [comment]
@HumairAK osc-cl2 has currently only one GPU node but mostly due to practical reasons of not using resources unnecessarily.  Node count can be increased fairly easily. @heyselbi  NFD and NVIDIA operators are already on the cluster.  I can not comment on ODH compatibility with the test. From technical side I don't see problem using osc-cl2. We do need ,however, confirmation from OS Climate that they ok with cluster being used for this demo and that it will not interfere with OS Climate timelines or usage

**Comment by heyselbi** [comment]
@redmikhail sounds good to me! As long as they don't mind me installing the ODH operator (or at least Kubeflow) and using GPUs for 2-3 days (1-2 days for testing and 1 day for demo), that should be sufficient.

**Comment by heyselbi** [comment]
Bump, just checking if there were any updates

**Comment by oindrillac** [comment]
cc: @HumairAK

**Comment by HumairAK** [comment]
> As long as they don't mind me installing the ODH operator (or at least Kubeflow) 

We have odh operator installed. What components of kubeflow are you loooking for? We have ml-pipelines also available. 


We have GPU via notebooks available now on osc-cl2 as well though they are limited. But I'm sure 3 days of use is manageable. @redmikhail @erikerlandson ?

**Comment by heyselbi** [comment]
@HumairAK I needed PytorchJob from Kubeflow. I won't be using pipelines. 

I wouldn't need notebooks with GPUs, I just need a JH notebook via ODH (not super necessary though, I could resort to terminal as well) that runs on CPUs. As long as I can access the two nodes with at least 1 GPU each (for which I'll need NVIDIA GPU and NFD operators) via terminal or via logging into cluster in the notebook, it should be good.

**Comment by erikerlandson** [comment]
osc cl1 or cl2 would be fine, I think. I sent an invitation, including `odh-env-users`

**Comment by redmikhail** [comment]
I would recommend to try cl1 first (it should have enough resources) and if doesn't work go with cl2

**Comment by heyselbi** [comment]
I have presented my demo, thank you so much for the resources! My access to the cluster can be deleted, as well as the namespace. Or if there is a way I can do it myself, please let me know.

**Comment by mimotej** [comment]
/close

Since the demo is done closing this issue
