### ISSUE TITLE
NEW PROJECT: Object detection demo app

### ISSUE THREAD

**Issue by mamurak** [operate-first/support#538]
### Target cluster

Smaug

### Team name

emea-sa

### Desired project names

od-demo

### Project description

Deployment of a simple object detection app based on the [RHODS object detection workshop](https://redhat-scholars.github.io/rhods-od-workshop/rhods-od-workshop/index.html).

Contains a real-time image streaming part for which Kafka integration is required.

### Users needing access

mamurak

### Namespace Quota

Small

**Comment by Gregory-Pereira** [comment]
Hey all, Just wanted to notify you that [your namespace](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects/od-demo) is ready to go.
