### ISSUE TITLE
Facing 503 internal error for s3 object bucket connection

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#54]
**Describe the bug**
The application workload of the thoth-station saves the output to the s3 object bucket. 
while performing that action the connection is giving 503 
```
 msg="Saving from /mainctrfs/mnt/workdir/adviser-xxxx to s3 (endpoint: rgw-openshift-storage.apps.cnv.massopen.cloud, bucket: thoth, key: data/cnv-prod/adviser/adviser-xxxx)"
time="2021-01-25T19:29:41.103Z" level=warning msg="Failed to put file: 503 Service Unavailable"
```

**To Reproduce**
1. Go to 'https://api.moc.thoth-station.ninja/api/v1/ui/#/Advise/post_advise_python'
2. Click on 'try out'
3. Scroll down to logs, check the adviser id
4. Go to the `thoth-backend-prod` to See error

**Expected behaviour**
successfully store the result to s3.

**Comment by harshad16** [comment]
using the in-cluster host endpoint `http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local` worked successfully

**Comment by tumido** [comment]
@harshad16 Yes, I think you need to use the provided `BUCKET_HOST` as endpoint. 

https://github.com/operate-first/support/blob/main/docs/claiming_object_store.md#configmap

For external facing route we have an ongoing issue here (it kinda merged with policies) https://github.com/operate-first/support/issues/53 

Was your problem solved by using the internal route or do you want to keep this issue open?

**Comment by tumido** [comment]
@harshad16  can this issue be closed, does it work for you?

**Comment by harshad16** [comment]
> Was your problem solved by using the internal route or do you want to keep this issue open?

yes, this issue was solved with the internal route and correct secrets.
This can be closed. Thanks for your thoughts :)
