### ISSUE TITLE
BUCKET: team-pixel 

### ISSUE THREAD

**Issue by PixelJonas** [operate-first/support#540]
### Username

pixeljonas

### Desired bucket name

pixel-secrets-backup

### Maximal bucket size

250GiB

### Maximal bucket object count

25.000

### Your GPG key or contact

`16787415FA4A18A006599425A5D655E1C8499F03` available at https://keys.openpgp.org/vks/v1/by-fingerprint/16787415FA4A18A006599425A5D655E1C8499F03

**Comment by PixelJonas** [comment]
storage should be provided in `morty` cluster @rbo

**Comment by HumairAK** [comment]
AFAIK on morty if you have project admin (which you do for namespace `pixel-demo`) then you should be able to create an OBC in there and use it as you see fit.
