### ISSUE TITLE
Argo workflow request

### ISSUE THREAD

**Issue by hemajv** [operate-first/support#542]
**Description**

As part of https://github.com/open-services-group/metrics/issues/18, we would like to use argo workflows to help serve our automation needs.

**Additional context**

We want to execute our notebook daily that fetches and updates data in s3 and in turn update our Superset dashboards. To do this, we decided to use argo workflows/cron job, similar to the approach in the [Mailing List Analysis project](https://github.com/aicoe-aiops/mailing-list-analysis-toolkit) and would like to use the argo instance on operate first.

cc @Shreyanand @chauhankaranraj @HumairAK

**Comment by mimotej** [comment]
/remove-lifecycle rotten

@hemajv Hi, is this still wanted or can this be closed?
