### ISSUE TITLE
add 'action' subdomain to operate-first.cloud 

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#543]
**Is your feature request related to a problem? Please describe.**
We need a landing page for our summit demo "Operate First In Action" 

**Describe the solution you'd like**
We would like to have a subdomain for our summit demo landing page `action.operate-first.cloud`

**Describe alternatives you've considered**
One alternative that has been considered it to not create a subdomain, but simple add a new page like `operate-first.cloud/action`. Open to discussion about what is the best approach here :)

**Comment by goern** [comment]
no problem, to where shall the CNAME point? do we have a webserver deployed somewhere hosting a website? 

/unassign goern
/assign @Gregory-Pereira 
/assign @harshad16

**Comment by harshad16** [comment]
I don't have access to this, happy to help if any require
seems like this is over my permission levels.
@tumido will you be able to help with this?

/unassign harshad16

**Comment by MichaelClifford** [comment]
@goern 
> do we have a webserver deployed somewhere hosting a website?

No, not yet. My initial though would be that we'd use a meteor built jupyterbook for this. Any objections to that format? 
@durandom @schwesig

**Comment by schwesig** [comment]
@MichaelClifford  I could offer on of my webhoster domains, but I am not sure if this is the correct/regular way.
If meteor jptrbk works, I would go with that! +1

**Comment by MichaelClifford** [comment]
@goern @durandom @HumairAK or other OPF org admin. I'd like a new repo in this org called "operate-first-in-action" that I can use as the source for the content and jupyter book I'll be making for our summit video. Can one of you help me out with this? :smiley:  Or is there an alternative solution you'd prefer? LMK!

**Comment by HumairAK** [comment]
@MichaelClifford instructions here: https://github.com/operate-first/common/blob/main/docs/add_repo.md

**Comment by MichaelClifford** [comment]
Thanks @HumairAK PR submitted :smile: 

https://github.com/operate-first/common/pull/83
