### ISSUE TITLE
NEW PROJECT: rhosp-cloudops

### ISSUE THREAD

**Issue by csibbitt** [operate-first/support#544]
### Team name

rhosp-cloudops

### Desired project names

rhosp-cloudops

### Project description

I'm following the Elyra AIDevSecOps Tutorial to get acquainted with Operate First and AIOps at Red Hat. I do not know the correct target cluster or required quota for the tutorial.

### Users needing access

csibbitt

### Namespace Quota

Medium

### Your GPG key or contact

https://keys.openpgp.org/vks/v1/by-fingerprint/E5FED983740E38C732A37D0BD90BAE39D1495FC7

**Comment by mimotej** [comment]
/remove-lifecycle

@csibbitt Hi, from description I assume this was a part of a workshop/tutorial. Can this be closed or was it part of project that is needed? I expect same applies for #545 . Thank you

**Comment by csibbitt** [comment]
Yes, @mimotej, this was originally part of a tutorial I was following and I ended up using other resources instead. I will close this and #545
