### ISSUE TITLE
BUCKET: rhosp-cloudops

### ISSUE THREAD

**Issue by csibbitt** [operate-first/support#545]
### Username

csibbitt

### Desired bucket name

rhosp-cloudops

### Your GPG key or contact

https://keys.openpgp.org/vks/v1/by-fingerprint/E5FED983740E38C732A37D0BD90BAE39D1495FC7

**Comment by mimotej** [comment]
/remove-lifecycle rotten

@csibbitt  Hi, is this still relevant or is it no longer needed?

**Comment by csibbitt** [comment]
no longer relevant
