### ISSUE TITLE
[TASK] Configure & Deploy etcd backup on morty cluster

### ISSUE THREAD

**Issue by rbo** [operate-first/support#546]
During incident ticket https://github.com/operate-first/support/issues/541 we find out there is no etcd backup in place.  Let's finish this for morty,

**Comment by mimotej** [comment]
/remove-lifecycle rotten

@rbo Hi, was this resolved or it needs some work? Can this issue be closed?

**Comment by rbo** [comment]
With decommission of Morty, we can close the issue. https://github.com/operate-first/apps/pull/2341
