### ISSUE TITLE
[TASK] Update the issue and bug templates

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/support#547]
**User story**
With many changes having occured in Operate-First, particularly clusters coming and going, we would like to update our various templates to use up to date information (particularly the `onboarding_to_cluster.yaml` issue template). We also no longer use GPG keys with the move to using Github handles for account creation and authentication, so that should be deprecated.

**Comment by HumairAK** [comment]
Hrmm I'm a bit unclear, it seems like title/body is saying different things to me. These are the different tasks I'm seeing based on your title/body: 

1. Update cluster/env values in onboarding issue template [here](https://github.com/operate-first/support/issues/new?assignees=first-operator&labels=kind%2Fonboarding%2Carea%2Fcluster&template=onboarding_to_cluster.yaml&title=NEW+PROJECT%3A+%3Cname%3E)
2. Add cluster github labels to operate-first repos: i.e. https://github.com/operate-first/common/pull/81
3. Add functionality to @ tag users based on github labels: i.e.: https://github.com/operate-first/alertmanager-github-receiver/pull/1 

Is that right?

**Comment by Gregory-Pereira** [comment]
Yeah that is an accurate summary of what this issue was meant to be. Are you suggesting that I should either refactor the issue text or split this up into separate issues?

**Comment by HumairAK** [comment]
I think the scope for these varies greatly. #2 is already done. Based on the title this thread is more about #1, but that's also a easy fix. 

#3 is a bit more involved and can be it's separate issue.

**Comment by mimotej** [comment]
/remove-lifcycle rotten
@Gregory-Pereira @HumairAK Do we keep this issue opened or were/will this be handled in different issues?

**Comment by HumairAK** [comment]
@mimotej please review: https://github.com/operate-first/support/pull/624 
this will resolve this issue
