### ISSUE TITLE
[TASK] Better use of Github Labels to scope issues

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/support#551]
**User story**
It would be nice to make better use of Github labels to help scope our issues and bugs. We can accomplish this through two subtasks.
    1. [x] Create labels for each `env/cluster` to allow us to tag affected clusters per issue
        - see implementation [here](https://github.com/operate-first/common/pull/81)
    2. [ ] Add functionality to @ tag users based on github labels
        - implementation in progress, see [here](https://github.com/operate-first/alertmanager-github-receiver/pull/1) 

Rework of #547 to separate concerns.

**Comment by quaid** [comment]
Here is some content that can be scoped into this:
https://github.com/operate-first/community-handbook/blob/main/content/how-to-use-community-centric-labels.md

And a related issue:
https://github.com/operate-first/community/issues/49

**Comment by mimotej** [comment]
/remove-lifecycle rotten

@Gregory-Pereira Will someone work on this, is it in progress or is there different issue that is used for tracking? Can this be closed?
