### ISSUE TITLE
Authentication error when accessing OS-Climate CL1 cluster

### ISSUE THREAD

**Issue by tumido** [operate-first/support#552]
**Describe the bug**
Unable to log into https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/

**To Reproduce**
1. Go to https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/
2. Click on `githubidp`
3. See error

**Expected behaviour**
Can log in

**Screenshots**

https://user-images.githubusercontent.com/7453394/161970167-237047ff-2762-444a-89bc-d66a0a5a046c.mp4

**Comment by HumairAK** [comment]
From slack: 
>[Harshad](https://app.slack.com/team/U01SW975LQY)  [9:44 AM](https://operatefirst.slack.com/archives/C033W4E8ATA/p1649252641060039)
>any idea on this : https://github.com/operate-first/support/issues/552

>[Humair Khan](https://app.slack.com/team/U01RF5SASLX)  [9:44 AM](https://operatefirst.slack.com/archives/C033W4E8ATA/p1649252694754249)
unfortunately we haven't had the chance to move the osc clusters under our auth yet, they need to be invited into a github team on the osc org to get access
[9:44](https://operatefirst.slack.com/archives/C033W4E8ATA/p1649252697756339)
can you get a list of users
[9:45](https://operatefirst.slack.com/archives/C033W4E8ATA/p1649252709676439)
and send a message on gchat to eithe mikhail or erik
[9:45](https://operatefirst.slack.com/archives/C033W4E8ATA/p1649252733631629)
https://github.com/orgs/os-climate/teams/odh-env-users
they need to be in this team

>[Harshad](https://app.slack.com/team/U01SW975LQY)  [9:45 AM](https://operatefirst.slack.com/archives/C033W4E8ATA/p1649252738332469)
i see, ack

**Comment by harshad16** [comment]
More discussion on : https://operatefirst.slack.com/archives/C033W4E8ATA/p1649254002714969

**Comment by tumido** [comment]
Thank you, this solution worked. :+1:
