### ISSUE TITLE
As a potential OPF user, I would like an OPF service catalog, so that I may request access/onboarding to a service from this catalog

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#556]
### Additional context

The service catalog should display the following information in a user-friendly table format: 

- Service Name
- Service Description
- Link navigating to a form or docs on how to get access.
- SLA
- Support Path

### Acceptance Criteria

- [x] Identify a generic service catalog solution ([#560](https://github.com/operate-first/support/issues/560) )
- [ ] Catalog is **easily** accessible via [the opf website](https://www.operate-first.cloud/) with minimal number of clicks (less than 3).
- [ ] All services currently provided by the sig operations team

**Comment by durandom** [comment]
this is in the works
@tumido @SamoKopecky feel free to add additional info beyond https://github.com/operate-first/service-catalog and https://service-catalog.operate-first.cloud/

/close
