### ISSUE TITLE
Username changed and removed access to ressources

### ISSUE THREAD

**Issue by PixelJonas** [operate-first/support#558]
**Describe the bug**
It looks like my username got changed from `pixeljonas` to `PixelJonas` on the `morty` cluster which results in me not having access to my namespaces when logging in

**To Reproduce**
1. Login
2. Don't see any namespaces

**Expected behavior**
Have access to my namespaces

**Screenshots**
![image](https://user-images.githubusercontent.com/5434875/164414847-c5478509-814d-4b51-a117-92016bfde18b.png)

**Comment by HumairAK** [comment]
This is related to: https://github.com/operate-first/apps/issues/1885

@PixelJonas for now can you add PixelJonas to this list: https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/team-pixel/group.yaml 

This should resolve the issue

**Comment by HumairAK** [comment]
This should be now resolved https://github.com/operate-first/apps/issues/1885
