### ISSUE TITLE
As a potential user, I can start using an OCP project in Operate First by filling out a single issue form

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#561]
### Acceptance Criteria: 

- [ ] Implement the process for user passing information (via github issue) and converting this issue into a PR in a fully automated way
- [ ] Create a GitHub issue form template for this form (either refine existing, or create new & improved one).
- [ ] The process should allow for enabling of options available for onboarding, e.g. enabling argocd.

**Comment by durandom** [comment]
@mimotej @HumairAK I guess this is part of https://github.com/operate-first/robozome 🎉 

I'll
/close
this for now, I'm sure you'll have other issues soon in the other repo
