### ISSUE TITLE
As an OPF OCP user, I can start using OPF ArgoCD by filling out a single form, so that I can manage my OPF service via GitOps.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#562]
### Acceptance Criteria

- [ ] Implement the process for user passing information (via github issue) and converting this issue into a PR in a fully automated way
- [ ] Create a GitHub issue form template for this form (either refine existing, or create new & improved one).

**Comment by durandom** [comment]
@HumairAK this will be part of https://github.com/operate-first/robozome

/close
