### ISSUE TITLE
As an operate first user, I want to be able to add/adjust/manage my group's OCP project quota.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#564]
### Acceptance Criteria 

- [ ] Implement the process for user passing information (via github issue) and converting this issue into a PR in a fully automated way
- [ ] Create a GitHub issue form template for this form (either refine existing, or create new & improved one).
- [ ] Users should be able to change their tiers
- [ ] Have the option to define custom quotas (or be able to switch between tier and custom, and vice versa)

**Comment by durandom** [comment]
@HumairAK @mimotej robozome? https://github.com/operate-first/robozome

/close
