### ISSUE TITLE
As an operate first operator, I would like to have an extendible framework for automating user interactions.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#565]
### Acceptance Criteria 

- [ ] Framework should consumes data from github issues
- [ ] Results in a PR creation
- [ ] Changes manifests in operate-first apps/common
- [ ] Adding new scenarios is done in a declarative way (does not require direct, possibly code, changes to implementation of framework).

**Comment by durandom** [comment]
@mimotej @HumairAK hmm, robozome https://github.com/operate-first/robozome

/close
