### ISSUE TITLE
Propose an architecture for user interactions automation

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#566]
The architecture should be able to satisfy: https://github.com/operate-first/support/issues/565

**Comment by tumido** [comment]
I've put together some initial draft which I will convert into ADR. https://docs.google.com/document/d/1K7-lBRvYCrEbjKG0-G74vbE9xVlV1-v1HJncAotHMD4/edit?usp=sharing

**Comment by HumairAK** [comment]
The draft proposal completes this issue out. We will be looking to assign a RH intern to move this forward.
