### ISSUE TITLE
Onboard API Designer

### ISSUE THREAD

**Issue by riprasad** [operate-first/support#567]
### Target cluster

Smaug

### Team name

apicurio

### Desired project names

api-designer

### Project description

The API Designer project is an API design studio that can be used to create new or edit existing API designs (using the OpenAPI specification).

### Users needing access

carlesarnal, ericwittmann, craicoverflow, jsenko, paoloantinori, riprasad

### Namespace Quota

Large

**Comment by riprasad** [comment]
This is our second operate-first deployment. First one is [apicurio-registry](https://console-openshift-console.apps.smaug.na.operate-first.cloud/topology/ns/apicurio-apicurio-registry?view=graph) and therefore I have used the same team name `apicurio` but a different project name.

I hope I have done the right thing and this doesn't create any issue since the group [apicurio](https://github.com/operate-first/apps/tree/master/cluster-scope/base/user.openshift.io/groups/apicurio) already exists.

**Comment by HumairAK** [comment]
resolved https://github.com/operate-first/apps/pull/1937
see: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects/api-designer

**Comment by riprasad** [comment]
@HumairAK is this good enough to replace a user from the group?
PR: https://github.com/operate-first/apps/pull/1967

**Comment by riprasad** [comment]
Add team apicurio to operate first group: https://github.com/operate-first/common/pull/107 
More info about this: https://github.com/operate-first/common/blob/main/docs/add_gh_member_and_access.md#adding-github-members-and-managing-repo-access
