### ISSUE TITLE
Onboarding Kepler to Operate-First

### ISSUE THREAD

**Issue by husky-parul** [operate-first/support#569]
### Description

Hi Team,

We want to onboard our project [Kepler](https://github.com/sustainable-computing-io/kepler/tree/main/manifests/openshift) as a managed service on Operate-First. The list of manifests we would need to deploy comprises `MachineConfig` `ClusterRole` `ClusterRoleBonding` `SA` `SCC` etc. I understand we would need the ArgoCD to deploy these privileged CRs. Could you help us to get started with this?

@larsks @HumairAK @durandom

**Comment by durandom** [comment]
ACK 

@HumairAK can you have a look at the manifest and see if there any roadblockers? Since it seems to be a deeper change, maybe we start with rick/morty?

**Comment by durandom** [comment]
@4n4nd can you have a look please?

**Comment by HumairAK** [comment]
> MachineConfig
> ClusterRole
> SCC

Potentially concerned about the need for these. Can you show us what these look like? @larsks

**Comment by husky-parul** [comment]
[MachineConfig](https://github.com/sustainable-computing-io/kepler/tree/main/manifests/openshift/cluster-prereqs)
 [SCC](https://github.com/sustainable-computing-io/kepler/blob/main/manifests/openshift/kepler/00-kepler-scc.yaml)

**Comment by durandom** [comment]
@husky-parul do you need any more pointers on how to create a PR to add those manifests to the https://github.com/operate-first/apps repo? 

@HumairAK what cluster do you suggest to start with?

**Comment by husky-parul** [comment]
I have a PR WIP for this https://github.com/operate-first/apps/pull/2181 so going to close this issue. Thanks.
