### ISSUE TITLE
Duplicate Secret management key on Operate-first website

### ISSUE THREAD

**Issue by anishasthana** [operate-first/support#57]
**Describe the bug**

**To Reproduce**
1. Go to `https://www.operate-first.cloud/users/`
2. Click on `Onboarding`
3. You will notice two keys/items/headings called `Secret management`. The second one seems to be about s3 usage, so the title should probably be something different :-)

![image](https://user-images.githubusercontent.com/6526150/105855651-4fa78f80-5fb6-11eb-90f2-b1a063836de8.png)

**Comment by tumido** [comment]
Ah.. that slipped my attention. I broke it. I'll fix it :)
