### ISSUE TITLE
public operations project board

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/support#570]
### Description

I'm interested in being able to cross-link tickets into external project boards.  Part of my desired goal is to allow external communities to get a broader view into OPF activities, and where their particular tasks might be in the workflow.

However, one of the likely project boards for that purpose is private:
![image](https://user-images.githubusercontent.com/259898/166336041-e7f42c12-c589-4b33-97fe-b2deb8168740.png)

Is it possible to make operations tasks public, or is there another board where public issues are tracked for progress?
xref: https://github.com/open-services-group/community/issues/157

**Comment by HumairAK** [comment]
@erikerlandson this was a mistake on my part, operations board is public now

**Comment by erikerlandson** [comment]
Thanks @HumairAK !
