### ISSUE TITLE
Do we have a section describing how to update grafana dashboard once a new version of the JSON template is modified

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#574]
Describe the process on how to get a new version of the grafana dashboard updated:

1. Modify your grafana dashboards, making sure the ID is different
2. Modify the grafana operator CRD, changing version, so that the operator recognizes the change in the CRD
3. ??

**Comment by quaid** [comment]
@pacospace @4n4nd this seems like an open questions still, yes?

/remove-lifecycle stale
