### ISSUE TITLE
Deploy curator-operator in Smaug cluster

### ISSUE THREAD

**Issue by skanthed** [operate-first/support#575]
Earlier we have deployed the curator project in Smaug and it's up and running.  
We have built an operator using Operator-SDK for that and implemented the same functionality and will keep adding more features to curator-operator.

Curator operator repo - https://github.com/operate-first/curator-operator

Need to install this operator in Smaug cluster

**Comment by skanthed** [comment]
@dystewart

**Comment by schwesig** [comment]
@dystewart is this issue solved by https://github.com/operate-first/apps/pull/2007 ?

**Comment by dystewart** [comment]
@schwesig Thank you for calling to my attention!
Closing, resolved by [https://github.com/operate-first/apps/pull/2007](https://github.com/operate-first/apps/pull/2007)
