### ISSUE TITLE
Access to Smaug cluster

### ISSUE THREAD

**Issue by trachten** [operate-first/support#576]
Hi ... I'm interested in working on Jonathan Appavoo's jupyter text book project, and I'd like access to Smaug for these purposes.

**Comment by HumairAK** [comment]
Hello @trachten ! I personally don't know who that is or what textbook project you're referring to :) 

Do you have a link to a github issue? Or more details on the project? 

If there's a specific Operate First maintainer/admin that is aware of your request can you @ mention them here so they can respond accordingly (or link this to them). 

Is there a specific Openshift namespace you're looking for access to?

**Comment by trachten** [comment]
Sorry ... I'm referring to https://github.com/jappavoo/bu-cs-book-dev, which appears to require access to smaug.

**Comment by HumairAK** [comment]
If you're just looking to use this notebook you can log in to jupyterhub directly on smaug. Unfortunately smaug is expected to be down until tomorrow, see [here](https://github.com/operate-first/operations/issues/478) for details. I would try again then.
