### ISSUE TITLE
Unable to connect to opf-datacatalog using boto3 client

### ISSUE THREAD

**Issue by suppathak** [operate-first/support#579]
Unable to connect to opf-datacatalog bucket using boto3 client :
https://github.com/operate-first/apps/blob/master/docs/content/odh/trino/access_public_bucket.md. 
![Screenshot from 2022-05-26 06-45-48](https://user-images.githubusercontent.com/30439457/170500408-c2613274-61dd-4a47-85a4-37df5355f1f2.png)

**Comment by suppathak** [comment]
assign @larsks

**Comment by suppathak** [comment]
Related https://github.com/operate-first/operations/issues/479

**Comment by larsks** [comment]
@suppathak can you try again and let us know if the behavior has changed?

**Comment by HumairAK** [comment]
@suppathak bump

**Comment by suppathak** [comment]
@larsks @HumairAK , Thanks :) 
It is fixed now. 
Closing this issue now. 
/close
