### ISSUE TITLE
[TASK] Create docs for debugging and local manifest builds etc / toolbox guide

### ISSUE THREAD

**Issue by tumido** [operate-first/support#58]
**User story**
Kustomize can be tricky, toolbox is not an usual thing, etc. let's just sum it up how a person can get from a `git clone` to `oc apply` in a single doc. 

**Additional context**
https://github.com/operate-first/apps/issues/154

**Acceptance Criteria**
- [ ] A doc explaining how to use kustomize that can be used against our repos

**Comment by HumairAK** [comment]
++

Just to add, in this doc we should try to not explain things that can be explained via already existing Kustomize docs, but link to the appropriate external docs where applicable.
