### ISSUE TITLE
Unable to access curator cluster

### ISSUE THREAD

**Issue by ajinkyababar** [operate-first/support#580]
### Describe the Problem

Unable to access the curator development cluster.
https://console-openshift-console.apps.curator.massopen.cloud/

### Steps to Reproduce

NA

### Expected behaviour

We should be able to access the curator cluster

### Screenshots

![curator_issue](https://user-images.githubusercontent.com/19320305/170719712-78d9e250-97ac-4945-be11-8dbbeec1ef84.png)

### Additional context

NA

**Comment by larsks** [comment]
The curator cluster is back online. There are some temporary fixes in place that mean in the event of a reboot the nodes may require additional manual intervention. I'm investigating a more permanent fix, but things should be fine for now.

**Comment by HumairAK** [comment]
closing as this seems resolved.
