### ISSUE TITLE
ChrisProject Onboarding to smaug Cluster

### ISSUE THREAD

**Issue by veniceofcode** [operate-first/support#581]
**Cluster**
https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects

**Namespaces**

- [ ] ChrisProject-Dev

- [ ] ChrisProject-Staging

**Github Id**

- veniceofcode
- mairin
- ejsa13
- bretmullinix

**Operators** 

- [ ] OpenShift Pipelines

- [ ] OpenShift GitOps 

- [ ] Codeready Workspaces 

- [ ] Advanced Cluster Security 

Note 

If the namespaces /projects are not existing already on the cluster, please create them for us and provide access.

**Comment by HumairAK** [comment]
```
 Codeready Workspaces

Advanced Cluster Security
```

AFAIK these weren't discussed in our last call. 

So CodeReadyContainers afaik will create new namespaces in the cluster, and this goes against our gitops model of managing everything in the cluster via git. Do you know if there's a way to leverage this operator and confine all resource creation to the namespace ? What privileges does this operator need?

Not familiar with Advanced Cluster Security, could use some more insight on to this, and what sort of implications are can we expect to the rest of the workloads on the cluster. Seems like this requires some looking into as well. @larsks

**Comment by larsks** [comment]
[ACS](https://www.redhat.com/en/resources/advanced-cluster-security-for-kubernetes-datasheet) sounds interesting but it really looks like an admin-level tool. There's some notes on the architecture [here](https://docs.openshift.com/acs/3.67/architecture/acs-architecture.html). It sounds interesting, and has some features (such as a policy-based admissions controller) that we've talked about in the past, but I've only just looked at it briefly. We would need to decide whether or not this is something that would be useful for our management of the clusters (or @veniceofcode et al would need to investigate what options are available for setting up their own cluster for evaluating these tools).

**Comment by veniceofcode** [comment]
@larsks , @HumairAK  I think this could be worth looking at https://redhat-scholars.github.io/acs-workshop/acs-workshop/index.html , because this helps to have a dev secops pipeline , for example this one : https://github.com/rcarrata/devsecops-demo

**Comment by veniceofcode** [comment]
![image](https://user-images.githubusercontent.com/93591339/171204165-3a65e5fb-42bc-4beb-8886-027fcdf23a76.png)

**Comment by veniceofcode** [comment]
So if there is a central instance of ACS running and provided by OF team , i think its still possible to use it

**Comment by HumairAK** [comment]
> We would need to decide whether or not this is something that would be useful for our management of the clusters

@larsks -- how do you propose we go about this? I'm not sure we currently have the bandwidth to deploy / setup/ maintain this within a time frame that works for @veniceofcode. 

> or @veniceofcode et al would need to investigate what options are available for setting up their own cluster for evaluating these tools

I think an approach like this makes more sense to me.

**Comment by veniceofcode** [comment]
@HumairAK @larsks , I m happy to help getting some of these components deployed in collaboration with your team , in case if you do not have enough bandwidth

**Comment by harshad16** [comment]
@shreekarSS is working on the initial phase on onboarding the team, namespace and access to the cluster and argocd.

**Comment by HumairAK** [comment]
@veniceofcode the cluster operations team meets in an open call weekly on Monday to discuss cluster operations. If you would be willing to join I can put this on the agenda item for the upcoming meeting Monday. 

You can find the meeting here: https://calendar.google.com/calendar/u/0/embed?src=operate.first.community@gmail.com&ctz=America/Los_Angeles 

Look for `[Op1st] Sub Project Cluster Ops weekly sync`.

**Comment by veniceofcode** [comment]
@HumairAK , In the meantime, is it possible to get started with what can be given access to such as cluster, project

**Comment by harshad16** [comment]
@veniceofcode, yes . one of our team member is assigned and is working on it 
you should be expecting the within today

**Comment by traytorous** [comment]
So instead of putting the RHACS operator onto the cluster I am instead suggesting to put the sister project of the operator (stackrox) onto the cluster. As of right now I am testing out the full capablities of it on our test cluster and will update it this ticket as soon as I get more information.

**Comment by HumairAK** [comment]
that should be part of it, this should really be broken into multiple issues, @traytorous did you get a chance to make a separate issue for stackrox/acs?

**Comment by traytorous** [comment]
I did not let me create one right now @HumairAK
