### ISSUE TITLE
Access to MOC clusters

### ISSUE THREAD

**Issue by rd4398** [operate-first/support#583]
Hi, I am Rohan and I joined Red Hat as Software Engineer Intern this summer. I wanted to access the MOC clusters since I will be working on that during my internship. Can you please grant me the access?
My Red Hat email is: rdevasth at redhat dot com

**Comment by HumairAK** [comment]
@rd4398 you may need to elaborate on what sort of access you are looking for. If you don't know, then maybe you can elaborate on the sort of work/project you are planning to contribute towards, and we can figure out the type of access you will need, starting with the cluster.

**Comment by rd4398** [comment]
Hi Humair,

As of now, I don’t exactly know what type of access I am looking for.
However, I am currently working on ESI project and will work on NERC in
later half of my internship here at Red Hat

Thanks
Rohan

**Comment by HumairAK** [comment]
as per @tzumainn in slack: 

> ah, hi! regarding rohan's access; we've already arranged for him to have ssh access into kumo-hil, which should be sufficient for now

@rd4398 seems you have the access you currently require, closing this for now. If there is additional access required to ocp clusters/namespaces, please re-open or create a new issue specifying what resources you will need access to. Thanks!

**Comment by rd4398** [comment]
Oh okay, thanks for letting me know!
