### ISSUE TITLE
Codeready Workspaces

### ISSUE THREAD

**Issue by veniceofcode** [operate-first/support#585]
Please help with Codeready workspaces. This can be installed in a specific namespace so that it would not have impact to the cluster wrt other apps . 

If possible please install this in a new namespace 

The namespace can be called as devtools-infra and this can be used for any other operators that can be used in common 

Below is a screenshot to deploy in given namespace 

<img width="1429" alt="Screenshot 2022-06-04 at 12 16 11" src="https://user-images.githubusercontent.com/93591339/171996756-f83ad916-a64c-4ee5-ba35-32d075ba19c0.png">

**Comment by quaid** [comment]
Hi, this is an interesting idea. Is this something just you are looking for? Or is there some other group or initiative involved?

**Comment by veniceofcode** [comment]
At the moment , i would like to have this used for chris project along with me . We have a few red hat volunteers and teammates from chris project . For example a workshop like this can demonstrating the need for code ready workspaces  : https://redhat-scholars.github.io/inner-loop-guide/inner-loop/5.1/introduction.html

**Comment by HumairAK** [comment]
> This can be installed in a specific namespace so that it would not have impact to the cluster wrt other apps .

Codeready Workspaces will create new namespaces for users/workspaces, brief skim of the docs indicates you could possibly limit this [by steting CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT](https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.0/html/installation_guide/advanced-configuration-options_crw#one_namespace_for_all_workspaces_strategy) env var. @veniceofcode have you confirmed this?

**Comment by mairin** [comment]
@quaid We were interested in trying it out as a potential better way to onboard new contributors from the Red Hat Impact program as well as Outreachy.

**Comment by veniceofcode** [comment]
As an example , if the level of access provided with the code ready workspaces operator installed in smaug cluster can allow users to perform the steps in the following workshops : https://redhat-scholars.github.io/inner-loop-guide/inner-loop/6.1/developer-workspace.html , https://redhat-scholars.github.io/outer-loop-guide/outer-loop/5.0/index.html  then it can  be helpful.

**Comment by HumairAK** [comment]
>  i believe this will be for the dev files created every time a new workspace is created and it should be fine, Would that be okay to start using it ?

I can't say for sure as I don't have much exposure to codeready workspaces. I would suggest first deploying this in a dev cluster and checking for the following: 

- Can code ready workspaces' namespace/resource creations be limited to a single namespace?
- Is there multi tenancy? Can we restrict access + resource creation (e.g. via ocp rbac). As smaug is accessible via public internet -- we don't want just anyone to be able to go in and create/consume a bunch of resources.  
- Does installing the operator hand out any special permissions to project admins (we hand this role out to various users to operate their namespaces, sometimes operators can delegate additional permissions to them), if so what are they? 

Once we understand more about this. Then I think we can bring this into smaug. If you need access to a dev environment you can use quicklab (for redhatters): https://www.operate-first.cloud/apps/content/development/setup_quicklab.html

**Comment by veniceofcode** [comment]
@HumairAK - So i have deployed CRW in a namespace called crw. However i have configured to use one namespace for all workspaces. Please see the screenshot below 


<img width="1655" alt="Screenshot 2022-06-10 at 23 25 01" src="https://user-images.githubusercontent.com/93591339/173158447-2dcaa6bf-7b39-4b35-a982-1be2a395bced.png">



CR 

```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  creationTimestamp: '2022-06-10T22:21:54Z'
  generation: 1
  managedFields:
    - apiVersion: org.eclipse.che/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:auth':
            'f:identityProviderAdminUserName': {}
            'f:identityProviderClientId': {}
            'f:identityProviderURL': {}
            'f:identityProviderRealm': {}
            .: {}
            'f:externalIdentityProvider': {}
            'f:oAuthSecret': {}
            'f:oAuthClientName': {}
            'f:initialOpenShiftOAuthUser': {}
            'f:identityProviderPassword': {}
          'f:database':
            .: {}
            'f:chePostgresDb': {}
            'f:chePostgresHostName': {}
            'f:chePostgresPassword': {}
            'f:chePostgresPort': {}
            'f:chePostgresUser': {}
            'f:externalDb': {}
          'f:metrics':
            .: {}
            'f:enable': {}
          'f:server':
            'f:allowUserDefinedWorkspaceNamespaces': {}
            'f:proxyUser': {}
            'f:serverTrustStoreConfigMapName': {}
            'f:workspaceNamespaceDefault': {}
            'f:cheWorkspaceClusterRole': {}
            'f:tlsSupport': {}
            'f:cheFlavor': {}
            'f:gitSelfSignedCert': {}
            .: {}
            'f:cheClusterRoles': {}
            'f:serverExposureStrategy': {}
            'f:proxyURL': {}
            'f:proxyPassword': {}
            'f:nonProxyHosts': {}
            'f:proxyPort': {}
          'f:storage':
            .: {}
            'f:postgresPVCStorageClassName': {}
            'f:preCreateSubPaths': {}
            'f:pvcClaimSize': {}
            'f:pvcStrategy': {}
            'f:workspacePVCStorageClassName': {}
      manager: Mozilla
      operation: Update
      time: '2022-06-10T22:21:54Z'
    - apiVersion: org.eclipse.che/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:openShiftoAuthProvisioned': {}
          'f:dbProvisioned': {}
          'f:cheURL': {}
          'f:devworkspaceStatus':
            .: {}
            'f:message': {}
            'f:phase': {}
          'f:keycloakURL': {}
          'f:pluginRegistryURL': {}
          'f:cheVersion': {}
          .: {}
          'f:keycloakProvisioned': {}
          'f:cheClusterRunning': {}
          'f:message': {}
          'f:gitHubOAuthProvisioned': {}
          'f:devfileRegistryURL': {}
          'f:reason': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2022-06-10T22:21:57Z'
  name: codeready-workspaces
  namespace: crw
  resourceVersion: '370225'
  uid: af2555a0-fdac-4c84-9187-0a63238cd744
spec:
  auth:
    identityProviderURL: ''
    identityProviderRealm: ''
    oAuthSecret: ''
    identityProviderPassword: ''
    oAuthClientName: ''
    initialOpenShiftOAuthUser: true
    identityProviderClientId: ''
    identityProviderAdminUserName: ''
    externalIdentityProvider: false
  database:
    chePostgresDb: ''
    chePostgresHostName: ''
    chePostgresPassword: ''
    chePostgresPort: ''
    chePostgresUser: ''
    externalDb: false
  metrics:
    enable: true
  server:
    proxyURL: ''
    cheClusterRoles: ''
    proxyPassword: ''
    nonProxyHosts: ''
    proxyPort: ''
    tlsSupport: true
    allowUserDefinedWorkspaceNamespaces: false
    serverTrustStoreConfigMapName: ''
    proxyUser: ''
    cheWorkspaceClusterRole: ''
    workspaceNamespaceDefault: crw
    serverExposureStrategy: ''
    gitSelfSignedCert: false
    cheFlavor: codeready
  storage:
    postgresPVCStorageClassName: ''
    preCreateSubPaths: true
    pvcClaimSize: 10Gi
    pvcStrategy: common
    workspacePVCStorageClassName: ''
status:
  gitHubOAuthProvisioned: false
  devfileRegistryURL: ''
  keycloakProvisioned: false
  reason: InstallOrUpdateFailed
  cheClusterRunning: ''
  message: >-
    Namespace strategies other than 'per user' is not supported anymore. Using
    the <username> or <userid> placeholder is required in the
    'spec.server.workspaceNamespaceDefault' field. The current value is: crw
  cheURL: ''
  devworkspaceStatus:
    message: DevWorkspace CRDs are not installed
    phase: Inactive
  openShiftoAuthProvisioned: false
  dbProvisioned: false
  cheVersion: ''
  keycloakURL: ''
  pluginRegistryURL: ''
```

**Comment by durandom** [comment]
@veniceofcode @HumairAK are you still interested in getting Codeready Workspaces to operate first?

/assign @HumairAK

**Comment by veniceofcode** [comment]
Yes please @HumairAK eagerly waiting for it

**Comment by veniceofcode** [comment]
also ACS
