### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by veniceofcode** [operate-first/support#586]
**Cluster**
https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects

**Namespaces**

- [ ] demolab-dev

- [ ] demolab-staging

- [ ] demolab

**Github Id**

- veniceofcode

**Operators** 

- [ ] OpenShift Pipelines

**Comment by veniceofcode** [comment]
Resource Quota Tiers

Large

**Comment by durandom** [comment]
@veniceofcode can you provide more background on the project/code you intend to deploy and on the team/community you're coming from?

@HumairAK can you provide a link to the documentation on how to create a PR for namespace creation

**Comment by HumairAK** [comment]
You can use the notebook here: https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_project.html

**Comment by veniceofcode** [comment]
@HumairAK  @durandom - I would like to use these namespaces for long term demo purposes , also would like to create a template for interns (outreachy)who can be onboarded to be productive from day1 , please let me know if you need more info.
