### ISSUE TITLE
onboarding-project.ipynb !git push expects username/pw

### ISSUE THREAD

**Issue by EldritchJS** [operate-first/support#588]
### Describe the Problem

I ran `onboarding-project.ipynb` on the smaug jupyterhub instance using a hitchhikers guide image. All went well until the step where the changes are to be pushed to my fork via `!git push` 

A prompt for username appeared in the output section of the notebook, which I couldn't send input to AFAIA. My workaround was to open a terminal in JupyterHub and `git push` there. I'm not sure if this is a failing of understanding on my part or otherwise so I am bringing it to the team's attention.

### Steps to Reproduce

1. Start JupyterHub server with hithchikers guide image
2. Open onboarding-project.ipynb
3. Fill out variable fields in notebook appropriately
4. Run cells

### Expected behaviour

I expected `!git push` to simply push the changes.

### Screenshots

![Screenshot from 2022-06-09 09-34-07](https://user-images.githubusercontent.com/10504328/172860045-3e670783-5610-4ce0-b93b-b4bbc51903f3.png)

### Additional context

This is not blocking my project creation, the issue is filed simply to make the team aware of what I had to do as a workaround.

**Comment by HumairAK** [comment]
As we are looking to move away from notebooks to automate this onboarding process, we're likely not going to be able to investigate the issue. But we can add a disclaimer suggesting the above workaround if any issues are encountered. 

Thanks for bringing this to our attention @EldritchJS
