### ISSUE TITLE
Create namespaces for Mesh for Data

### ISSUE THREAD

**Issue by eletonia** [operate-first/support#59]
### Requested actions

Select all that apply:

- [ ] Create a user group
- [ ] Add users to a group
- [X ] Create a namespace

### Questionnaire

1. **Team name**:
   Mesh for Data

2. **Desired namespace names**:
  `m4d-system` and `m4d-blueprints`

3. **Users to add**:
   None for now

4. **Target cluster**:
   Choose an environment from [this list](https://github.com/operate-first/apps/tree/master/cluster-scope/overlays)
MOC CNV cluster

5. **Team or maintainer owned GPG key fingerprint along with a keyserver**:
   A GPG key we can use to encrypt sensitive data like usernames you want us to manage. Example: `0508677DD04952D06A943D5B4DC4116D360E3276` available from keys.gnupg.net
  No sensitive data to encrypt

---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the [docs/onboarding_to_cluster.md](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md) guide.

**Comment by tumido** [comment]
PR pending! :tada: https://github.com/operate-first/apps/pull/163

**Comment by HumairAK** [comment]
The namespaces were created, those in the OCP group `mesh-for-data` have admin access in the namespaces requested. Feel free to re-open if there are any issues.
