### ISSUE TITLE
Onboarding new service: NetObserv

### ISSUE THREAD

**Issue by jotak** [operate-first/support#590]
### Description

Hello team,

We would like to onboard a new monitoring service to operate-first: [NetObserv](https://github.com/netobserv/network-observability-operator/) (also on [OperatorHub](https://operatorhub.io/operator/netobserv-operator)). It consists of an operator that deploys a flow collection infra and network observability dashboards integrated in the openshift console. At the moment it includes a network flow table with many filtering options, and a topology view (you can check [this blog post](https://cloud.redhat.com/blog/a-guide-to-providing-insight-with-network-observability) to get more info).

It operates cluster-wide, and as of now, without multi-tenancy (users will be able to see all cluster traffic, not only from their namespaces). There's also a requirement on the cluster version, OpenShift 4.10 at least is needed.

The purpose for us is to get our product running in a live environment and collect feedback, and we think, for operate-first users, to provide more insight in (and between) their running workloads.

We had a preliminar discussion with @durandom - happy to continue the discussion when necessary.
cc @eranra @davegord

**Comment by durandom** [comment]
@HumairAK is any of our clusters on 4.10? If not, which one could be upgraded?

**Comment by HumairAK** [comment]
I'd say we can upgrade Morty. I don't think Smaug is in a state where it ought to be upgraded, as there are some pending issues that ought to be resolved first.

**Comment by eranra** [comment]
@HumairAK @durandom any progress on that area ???

**Comment by davegord** [comment]
@HumairAK @durandom  -- is there any updates here you can share with us?  Is there anything we can do to help?

**Comment by eranra** [comment]
@durandom Hi Marcel, any progress on this front?

**Comment by durandom** [comment]
@eranra @davegord @jotak glad you asked and sorry for letting this slip so long.
We have [jerry](https://www.operate-first.cloud/apps/content/README.html#emea) recently setup, which is a 4.10 cluster.

https://github.com/operate-first/apps/pull/1644/files is an example PR to add an operator.

**Comment by eranra** [comment]
@durandom YES !!!! THX :-)

**Comment by davegord** [comment]
@durandom --- this is great news - thank you!  What exactly are the next steps?

**Comment by durandom** [comment]
@davegord IIUC you want to install an operator to that cluster. Have a look at [operate-first/apps#1644 (files)](https://github.com/operate-first/apps/pull/1644/files) for an example PR.
I can also assist creating the PR

**Comment by durandom** [comment]
Oh, and you probably also want a namespace and a group. Create an issue here https://github.com/operate-first/support/issues/new?assignees=first-operator&labels=kind%2Fonboarding%2Carea%2Fcluster&template=4_onboarding_to_cluster.yaml&title=NEW+PROJECT%3A+%3Cname%3E
