### ISSUE TITLE
Minio Operator 

### ISSUE THREAD

**Issue by veniceofcode** [operate-first/support#591]
Please help with access to install operator (community) https://github.com/minio/operator.git on smaug cluster under below namespaces 

**Cluster**
https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/projects

- [ ] ChrisProject-Dev

- [ ] ChrisProject-Staging

Operator Screenshot

![Screenshot 2022-06-17 at 14 31 03](https://user-images.githubusercontent.com/93591339/174308248-cf27789e-506e-43f3-bdf0-c25b11a41ed5.png)

This will help us try an in cluster object storage before we could use nooba as it requires code changes to be use nooba at the moment and minio can be a solution for now to evaluate if it can work for chris purpose,

**Comment by veniceofcode** [comment]
Kustomize : https://github.com/minio/operator/tree/master/resources

**Comment by veniceofcode** [comment]
Helm : https://github.com/minio/operator/tree/master/helm/operator ,  Using existing persistence : https://github.com/minio/minio/tree/master/helm/minio#existing-persistentvolumeclaim

**Comment by HumairAK** [comment]
minio operator was added to smaug https://github.com/operate-first/apps/pull/2108
