### ISSUE TITLE
I want to add Kubescape integration

### ISSUE THREAD

**Issue by dwertent** [operate-first/support#595]
### Additional context

@durandom @schwesig 

### Acceptance Criteria

-

### Relevant links

https://github.com/armosec/kubescape

**Comment by schwesig** [comment]
@dwertent Hi David, how was OSS? Did you made it home safely?

**Comment by dwertent** [comment]
I have opened a PR ([operate-first/apps#2691](https://github.com/operate-first/apps/pull/2691)) with Kubescape integration :)
