### ISSUE TITLE
Jupyterhub spawner page cant select container size

### ISSUE THREAD

**Issue by oindrillac** [operate-first/support#599]
### Describe the Problem

Recently on smaug I am seeing the jupyterhub spawner page being quite buggy and not showing me the container size dropdown option often. This makes me unable to select a container size and I need to proceed with the last default setting.

### Steps to Reproduce

1. Go to https://jupyterhub-opf-jupyterhub.apps.smaug.na.operate-first.cloud/hub/
2. Login
3. Select any notebook image
4. Wait on the spawn screen and the container size dropdown doesnt show up

### Expected behaviour

Expect to see a dropdown menu option to select container size 

### Screenshots

<img width="746" alt="image" src="https://user-images.githubusercontent.com/32435206/176463839-7ff22e67-eda8-4547-88dc-5d4c5b76f6b3.png">

### Additional context

Sometimes it takes time to pop up on the menu. But sometimes it does not show up at all.

I am not sure if its being caused by the large list of items in the Notebook images

**Comment by HumairAK** [comment]
this is a problem we've noticed on the os-climate jupyterhub instance as well... https://github.com/operate-first/apps/issues/1918

**Comment by HumairAK** [comment]
just confirmed this continues to be an ossie on osc-cl2 and osc-cl1 

fyi @MichaelTiemannOSC 

will add this to the backlog as something that needs to be investigated -- might need to confer with ODH

**Comment by HumairAK** [comment]
issue doesn't seem to exist in our smaug>stage environment: https://jupyterhub-opf-jupyterhub-stage.apps.smaug.na.operate-first.cloud/hub/spawn 

might give clues as to the issue

**Comment by MichaelTiemannOSC** [comment]
I'm doing lots of starting and stopping today, and this issue is KILLING me as a wait minutes for the deployment size to become available.

**Comment by Gregory-Pereira** [comment]
Could you share some additional information on what you are encountering? As Humair said I don't see this issue on Smaug (see screenshot). Are you running this on one of the OSC clusters?
![Screen Shot 2022-07-10 at 7 40 57 AM](https://user-images.githubusercontent.com/19876404/178149641-170ef155-86d0-4100-9736-4e10e5bca1f2.png)

**Comment by MichaelTiemannOSC** [comment]
Yes, am seeing on odh-cl2.

Michael
