### ISSUE TITLE
Jupyterhub spawn failing coz of resource limits

### ISSUE THREAD

**Issue by oindrillac** [operate-first/support#600]
### Describe the Problem

```
Error: HTTP 500: Internal Server Error (Error in Authenticator.pre_spawn_start: ApiException (403) Reason: error HTTP response headers: HTTPHeaderDict({'Audit-Id': '88819dbc-309c-4683-a8f9-d0f5e984c325', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Warning': '299 - "spec.containers[0].env[17].name: duplicate name \\"MEM_LIMIT\\""', 'X-Kubernetes-Pf-Flowschema-Uid': '455b24cc-3b0e-4d7f-b9a0-ae84569826f1', 'X-Kubernetes-Pf-Prioritylevel-Uid': '08aa5218-91f5-42b2-abb6-cdd3a28cc286', 'Date': 'Wed, 29 Jun 2022 14:38:45 GMT', 'Content-Length': '331'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"jupyterhub-nb-oindrillac\" is forbidden: exceeded quota: opf-jupyterhub-custom, requested: limits.cpu=3, used: limits.cpu=139, limited: limits.cpu=140","reason":"Forbidden","details":{"name":"jupyterhub-nb-oindrillac","kind":"pods"},"code":403} )
```

### Steps to Reproduce

1. Go to https://jupyterhub-opf-jupyterhub.apps.smaug.na.operate-first.cloud/
2. Select any notebook image
3. Select any container size above small
4. Fails with the above error

### Expected behaviour

Should successfully spawn jupyter lab

### Screenshots

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/32435206/176465460-88d7802f-71eb-4800-80f2-8580f7a0f3f9.png">

### Additional context

happened recently as we were getting capped on resources https://github.com/operate-first/support/issues/593

**Comment by oindrillac** [comment]
@HumairAK looks like we are hitting cpu limits again, shall I increase it? and what do you recommend I increase it to?

**Comment by HumairAK** [comment]
@oindrillac sure let's increase it by 20 cpus (both limits/requests)
