### ISSUE TITLE
chris-store-dev, chris-store-staging , chris-store

### ISSUE THREAD

**Issue by veniceofcode** [operate-first/support#601]
### Target cluster

Smaug

### Team name

chris

### Desired project names

chris-store-dev, chris-store-staging , chris-store

### Project description

This is for deploying chris store ui (https://chrisproject.org/)

### Users needing access

veniceofcode, jennydaman

### Namespace Quota

Large

### Your GPG key or contact

rbanda at redhat dot com

**Comment by HumairAK** [comment]
As this is requesting [3x large quotas](https://www.operate-first.cloud/apps/content/cluster-scope/quotas.html), can we get an ack for this request? @durandom ? 

In the meantime @veniceofcode you can self service this request via: https://www.operate-first.cloud/apps/content/cluster-scope/onboarding_project.html

**Comment by durandom** [comment]
@veniceofcode is this still required - or is it already onboarded?

/assign @durandom
