### ISSUE TITLE
Loki service is not serviceable 

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#604]
### Describe the Problem

The Loki service seems to be not providing the right result.
This could be due to the Morty storage not being available which was being used for loki service.
As described here: https://github.com/operate-first/apps/issues/2064

### Steps to Reproduce

1. Go to https://grafana.operate-first.cloud/d/liz0yRCZz/cluster-logs-quick-search?orgId=1
2. see the result not being available

### Expected behaviour

Available Loki with logs from the cluster

### Screenshots

 https://operatefirst.slack.com/archives/C01RMPVUUK1/p1653679934280489?thread_ts=1653679934.280489&cid=C01RMPVUUK1

### Additional context

https://github.com/operate-first/apps/issues/2064
https://github.com/operate-first/apps/issues/2048

**Comment by harshad16** [comment]
@HumairAK  no not yet, Thanos and Prometheus are still having issues.
It is on WIP stage. 
will respond to this soon.

**Comment by harshad16** [comment]
This issue is happening because the cache is reaching its limits.
![Screenshot from 2022-07-25 13-22-17](https://user-images.githubusercontent.com/14028058/180837402-ff13ac15-18e2-4c97-a3f0-fa8b7d12a285.png)

The flow should empty the cache once the data is stored in the ceph block storage.

**Comment by Gregory-Pereira** [comment]
Loki cannot connect to ceph on morty for some reason, investigating this. Logs: ```level=error ts=2022-08-02T17:46:09.044431401Z caller=main.go:157 err="BaseFetcher: iter bucket: Get \"https://s3-openshift-storage.apps.morty.emea.operate-first.cloud/opf-observatorium-metrics/?location=\": dial tcp 46.4.65.182:443: i/o timeout\ncould not sync metas\nmain.runCompact.func8.1\n\t/home/circleci/project/cmd/thanos/compact.go:473\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/home/circleci/project/pkg/runutil/runutil.go:75\nmain.runCompact.func8\n\t/home/circleci/project/cmd/thanos/compact.go:470\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\ncompact command failed\nmain.main\n\t/home/circleci/project/cmd/thanos/main.go:157\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"```

**Comment by Gregory-Pereira** [comment]
The reason why loki cannot connect to S3 on morty is due to there being an issue with the `noobaa-operator` which deploys s3 in the `openshift-storage` namespace. It has an empty imagestream (with a tag name but no image) and cannot lookup the image from `registry.redhat.io` which could be related to redhat registry credentials or to basic networking. In either case I think we should wait on this as morty will be decomissioned by the  9th, and hopefully switching this over to another cluster will resolve our issue.

**Comment by schwesig** [comment]
/close
cleanup after change of organisation
