### ISSUE TITLE
Prow pre-commit check pod cannot connect to github

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/support#608]
### Describe the Problem

In the process of testing [this pr](https://github.com/operate-first/continuous-deployment/pull/149), I found that the pod running the pre-commit check from Prow cannot connect to Github. Not sure why this is happening.

### Steps to Reproduce

1. Go to any repo that uses prow in Operate-First or Thoth-Station.
2. Create a PR there and check the pre-commit pod.

* not sure if this issue is specific to `operate-first/continuous-delivery` or any repo that uses prow.

### Expected behaviour

pre-commit check should be able to run.

### Screenshots

Copy of pod logs:
```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: unable to connect to github.com:
    github.com[0: 140.82.113.3]: errno=Connection timed out
    
    
Check the log at /opt/app-root/src/.cache/pre-commit/pre-commit.log
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-07-09T18:34:58Z"}
```

### Additional context

NA

**Comment by harshad16** [comment]
@Gregory-Pereira based on our previous discussion.
I believe you can resolve this issue. right?

**Comment by Gregory-Pereira** [comment]
bump @Gregory-Pereira

**Comment by harshad16** [comment]
With the changes made in this pr https://github.com/operate-first/continuous-deployment/commit/2c46a491232ec56ed05e17749622c28377d9ae09
the issue is resolved.
Closing this.
