### ISSUE TITLE
Metrics Dashboard for Notebook Pods

### ISSUE THREAD

**Issue by durandom** [operate-first/support#61]
As an operator, I want to see how much CPU is used by a pod spawned from JupyterHub.

- [x] node-exporter? configured for OpenShift platform
- [x] grafana dashboard that lists notebook pods with CPU usage over time

@oindrillac IIRC we've had a similar dashboard
cc @accorvin @hemajv

**Comment by hemajv** [comment]
We are working on having these metrics made available in our Prometheus. 
You can track the progress here: https://github.com/operate-first/apps/issues/160

**Comment by accorvin** [comment]
@hemajv, @maulikjs is working on this on our current sprint, so he can definitely collaborate with you.

**Comment by durandom** [comment]
cc @sophwats @adrezni @TreeinRandomForest

**Comment by hemajv** [comment]
We now have a grafana dashboard [here](https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/YuYfkHYMk/jupyterhub-usage?orgId=1&var-user_id=aakankshaduggal745-40gmail-2ecom&from=1612181414558&to=1612203014558). 
Open to any suggestions on improving this further! :)

**Comment by maulikjs** [comment]
Hey @hemajv thats awesome!
Thanks!

**Comment by maulikjs** [comment]
So one interesting thing that came up is how do we use metrics to calculate the total run time for JH notebook pods for a given time frame in a reliable fashion. We have an internal tracker for that here:  [DATAHUB-2609](https://projects.engineering.redhat.com/browse/DATAHUB-2609).
I am not too keen on calculating it off Prometheus metrics, given Prometheus isn't designed for billing and any gaps in data there can cause problems given we will be using it for billing purposes.

One idea I had was writing a custom exporter that can maybe export a single metric `notebook_runtime` which calculates the total runtime for a user notebook pod which we can then get averages for over the month or any given time frame and get a sum for all the notebook pods.

This would involve fetching info form the kubernetes API directly and we can store the data in a PVC or some external storage location which solves our reliability problem.

I would like to hear peoples thoughts on the topic and possible alternatives and work on what the design for the setup would look like.

@hemajv @durandom @accorvin @4n4nd  @anishasthana  @accorvin and pretty much everyone else.

**Comment by anishasthana** [comment]
Does Jupyterhub not have a metric for this? @hemajv newer version of jupyterhub have something in a similar direction right?

**Comment by accorvin** [comment]
To add to @maulikjs's comment, it would be really nice if we could generate a usage metric that restarts at 0 each month.

**Comment by 4n4nd** [comment]
maybe we could check the duration for when the cpu usage for the pod was > 0.1 or some small value which means the pod was up

**Comment by hemajv** [comment]
> Does Jupyterhub not have a metric for this? @hemajv newer version of jupyterhub have something in a similar direction right?

The new version of jupyterhub metrics includes metrics like hub start time: https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/metrics.py#L53, but they don't seem to have anything defined for pods.

**Comment by maulikjs** [comment]
So what we want are probably notebook metrics which don't have much information, we can definitely work upstream and include them here: https://github.com/jupyter/notebook/blob/master/notebook/prometheus/metrics.py
But we don't know what the time-frame there would look like.

**Comment by maulikjs** [comment]
> maybe we could check the duration for when the cpu usage for the pod was > 0.1 or some small value which means the pod was up

# HELP container_cpu_user_seconds_total Cumulative user cpu time consumed in seconds.
# TYPE container_cpu_user_seconds_total counter

We do have this metric but for each user we will have to then keep a track of the cores used at each instance (given the no of cores can change for a notebook pod)

**Comment by maulikjs** [comment]
as per @4n4nd's note

```
sum(increase(container_cpu_usage_seconds_total{namespace="opf-jupyterhub",pod="jupyterhub-nb-fmurdaca-40redhat-2ecom"}[5m])) / sum(rate(container_cpu_usage_seconds_total{namespace="opf-jupyterhub",pod="jupyterhub-nb-fmurdaca-40redhat-2ecom"}[5m]))
```
We might be able to use a query similar to this which basically divides the total cpu seconds used over a time-frame by the total no of cpu cores used.

But this still leaves out the question about 'reliability'.

**Comment by accorvin** [comment]
If we were to create a recording rule based on a query like that, what happens to the metric value of the recording rule if Prometheus restarts? Will it survive a restart or get reset?

**Comment by maulikjs** [comment]
That would depend, if we have a PVC attached, it would persist after the restart but we might not scrape for the few seconds it takes to restart the pod (but we have some leeway there given we are using increase and irate which can account for such gaps in data.
What I am more concerned about is a robust thanos service given we will mostly be querying over 30days worth of data.

Also I tested this query for my pod and the number looks correct but I would definitely want to test it out with a couple other folks.

**Comment by accorvin** [comment]
Do we need to be able to query more than 30 days of data if we use a recording rule? We won't really need to be able to see what the total consumption was at an arbitrary point it time, just what it is now.

**Comment by maulikjs** [comment]
@aditya-konarde
@bwplotka
^

**Comment by 4n4nd** [comment]
> Do we need to be able to query more than 30 days of data if we use a recording rule? We won't really need to be able to see what the total consumption was at an arbitrary point it time, just what it is now.

I don't think you would need to store 30 days of data if you use a recording rule since it is calculated and stored (to the PVC) as a metric at scrape time.

**Comment by maulikjs** [comment]
So this is a lookback query, in this case
```increase( container_cpu_usage_seconds_total{container="POD", prometheus_replica="prometheus-k8s-0", namespace="opf-jupyterhub",pod="jupyterhub-nb-mshah-40redhat-2ecom"}[20m])/ irate(container_cpu_usage_seconds_total{container="POD", prometheus_replica="prometheus-k8s-0", namespace="opf-jupyterhub",pod="jupyterhub-nb-mshah-40redhat-2ecom"}[20m])
```
It looks back on the past 20m and reports how many seconds the specific notebook pod was running. 
Technically we need to store the metric `container_cpu_usage_seconds_total` for 30d to be able to answer the question how many seconds was the notebook for a specific user running in the past 30d.

**Comment by accorvin** [comment]
> Technically we need to store the metric container_cpu_usage_seconds_total for 30d to be able to answer the question how many seconds was the notebook for a specific user running in the past 30d.

I don't think this is true. We need to store the cumulative sum and be able to query what the total is at the end of the month. That's querying a metric for only a specific point in time - namely the end of the month. We don't need to be able to query, at the end of the month, what the value of the metric was for any arbitrary point in the month.

**Comment by durandom** [comment]
@accorvin @maulikjs I think we have accomplished what's in the original issue. I suggest we close this and start the discussion about the metrics usage in another issue. 
Either in this support repo here, or in https://github.com/operate-first/SRE where we track the dashboards.

@maulikjs can you do this and post an issue with the concrete user story / problem definition?

**Comment by durandom** [comment]
closed as per ^^

**Comment by durandom** [comment]
@maulikjs did you get a chance to create the follow up issue as per above?
