### ISSUE TITLE
I want to add stackrox to the smaug cluster

### ISSUE THREAD

**Issue by traytorous** [operate-first/support#614]
### Additional Context

Multiple end-users would like to add Stackrox to the smaug cluster so that they can have Kubernetes native security support for their projects. This project consists of two main parts. The first part consists of getting the central component of Stackrox on the smaug cluster. The central component is the control center of Stackrox. It is the portion that has the web interface that is used to interact with the managed cluster. It also is where the data stored collected using Stackrox. After the central portion of Stackrox is ready to be deployed you can start the second part. The second portion of Stackrox is the Secured Cluster. This portion of stackrox is used to connect different clusters to Stackrox and to send data to the Central endpoint.

### Acceptance Criteria Part 1
- [x] Test Stackrox on the test clusters
- [x] Create Stackrox namespace on smaug cluster
- [x] Add an OCP group for Stackrox
- [x] Audit manifests for Stackrox central component
- [x] Remove secrets from stackrox and place them in the vault them with External Secrets
- [ ] Check RBAC / SCCs that are in the Stackrox manifests (see [comment summarizing this](https://github.com/operate-first/apps/pull/2211#issuecomment-1234275067))
- [ ] Put Stackrox manifests in the app repo (still being reviewed by @HumairAK and @Gregory-Pereira)
- [x] Utilize Argocd to put the central component of Stackrox on the smaug cluster (There is already a pull request for this)

### Acceptance Criteria Part 2
- [ ] Create figure out how to automate the deployment of the Secured Cluster portion of Stackrox

### Documentation
- [ ] Create Documentation for Stackrox
###  Main repository for Stackrox and the links associated to Stackrox
* https://github.com/stackrox/stackrox
* https://docs.openshift.com/acs/3.71/installing/install-ocp-operator.html
### Issues that are linked to this issue
* https://github.com/operate-first/support/issues/581
* https://github.com/operate-first/apps/issues/1876
### Pull requests 
* https://github.com/operate-first/apps/pull/2211 ( Manifests for the central component)
* https://github.com/operate-first/apps/pull/2209 (  Argocd )
### Notes for Stackrox
* https://docs.google.com/document/d/1Ckq9EyT0m8rUFgOMDBEOTWZqTEkZKG-vE4Dwn77Xy-A/edit?usp=sharing

**Comment by traytorous** [comment]
Pull request has been made for the central component of stackrox.
https://github.com/operate-first/apps/pull/2211

**Comment by durandom** [comment]
@traytorous IIUC you created https://github.com/operate-first/apps/pull/2211 by applying a helm chart and then extracting the manifests. I wonder how maintainable this is. If the helm chart gets updated, who will update this PR? 🤷 

1. is there an helm / argoc integration?
2. is there another maintained stackrox deployment available? operators? whats the product line? @jeremychoi ?

**Comment by durandom** [comment]
https://argo-cd.readthedocs.io/en/stable/user-guide/helm/ for managing helm charts with argocd

**Comment by traytorous** [comment]
Hi @durandom I think that you are right. I looked through the documentation and created a pull request with the documents that you created. Is this what you meant? With this we can just keep track of the version and it should work in theory.
- https://github.com/operate-first/apps/pull/2389
