### ISSUE TITLE
sesheta not merging

### ISSUE THREAD

**Issue by durandom** [operate-first/support#615]
https://github.com/operate-first/operate-first.github.io/pull/159 is not being merged.

> we should be able to see the reasoning in tide history: https://prow.operate-first.cloud/tide
> however it seems that tibe webhook couldnt attach itself to this pr.
> https://github.com/thoth-station/thoth-application/blob/3ca0ae85ea75868acd23d41cf1298a4c57cbd571/prow/overlays/smaug/config.yaml#L272
> https://github.com/thoth-station/thoth-application/pull/2602/files

**Comment by durandom** [comment]
@harshad16 @goern  looks like we included the repo again in https://github.com/thoth-station/thoth-application/commit/62b44852bbac52b800f0c922131fd44dc42117c9 - but it's not deployed yet
At least the https://prow.operate-first.cloud/tide says it's excluded.

Looking at https://argocd.operate-first.cloud/applications/ci-prow-prod-smaug?resource=&operation=true it's not synced and syncing it gives an error

<img width="1929" alt="image" src="https://user-images.githubusercontent.com/161888/182546355-d61df1d5-eebc-4d93-b806-cb1b6b742101.png">

**Comment by durandom** [comment]
I managed to deploy all out-of-sync components by selecting them. 
There's still the issue with plank and horologium stuff not able to be applied. Any ideas?

**Comment by harshad16** [comment]
With [morty](https://console-openshift-console.apps.morty.emea.operate-first.cloud/dashboards) cluster down 
none of the component using object bucket from Morty are able to function
list of the component can be found here: https://github.com/operate-first/apps/issues/2064

once the object bucket issue is fixed. These issues should fix themselves.

**Comment by goern** [comment]
any update on this?
