### ISSUE TITLE
ODH-Highlander onboarding

### ISSUE THREAD

**Issue by guimou** [operate-first/support#617]
### Context
ODH Highlander is a project to bring modular dynamic libraries and applications to OpenShift. It solves the issue of container images sprawling in large shared environments.
The project is described here: https://github.com/guimou/odh-highlander
with a more detailed story here: https://towardsdatascience.com/unlimited-scientific-libraries-and-applications-in-kubernetes-instantly-b69b192ec5e5
and a recording of a presentation at last Kubecon here: https://www.youtube.com/watch?v=qexssjXrW8Y

The goal of this demand is to enable Highlander in Operate First, which may be beneficial for projects like OS-Climate as per this issue: https://github.com/os-climate/physrisk/issues/86

### What's required?
- CephFS to create RWX volumes
- A namespace to install the library and the builder container.
1. The PVC for the library should be large enough to handle packages and applications. The current size for a base library with some apps is ~40GB. So a 100GB volume should be OK to start with.
2. The library builder, which runs only for creating new packages should be large enough to compile some heavy packages from source like Tensorflow or Pytorch. At least 8 CPUs and 32GB of RAM. Again, it runs only intermittently and does not always consume all of these resources. If not possible, builds could be done elsewhere and brought back.
- Cluster admin access will be needed to enable the library in other namespaces as it requires manually creating PVs/PVCs pointing to the same CephFS volume as the shared library. This is a special configuration that allows to share RWX PVCs acrosse namespaces.
- Then a special notebook ImageStream has to be simply added to any ODH installation where the PVC is present to make it accessible. The library can also be used with simple Python code in non-Jupyter containers.

**Comment by durandom** [comment]
@HumairAK can wee the above requirements in os-climate or smaug?

**Comment by MichaelTiemannOSC** [comment]
Following...

**Comment by guimou** [comment]
@HumairAK Hi! Following up on this. Do you need any other info?

**Comment by durandom** [comment]
@guimou lets try this on smaug. I'll go ahead and create `highlander` namespace with you as the group member.

**Comment by durandom** [comment]
I needed to kick argo to actually deploy the changes, it's there now.

`ocs-external-storagecluster-ceph-rbd` on smaug

```yaml
ind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ocs-external-storagecluster-ceph-rbd
  uid: 90347e12-a1a4-43a1-ae36-4f7e92ff8124
  resourceVersion: '212530839'
  creationTimestamp: '2021-10-14T19:42:14Z'
  labels:
    app.kubernetes.io/instance: cluster-resources-smaug
  annotations:
    description: 'Provides RWO Filesystem volumes, and RWO and RWX Block volumes'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"description":"Provides
      RWO Filesystem volumes, and RWO and RWX Block
      volumes","storageclass.kubernetes.io/is-default-class":"true"},"labels":{"app.kubernetes.io/instance":"cluster-resources-smaug"},"name":"ocs-external-storagecluster-ceph-rbd"},"parameters":{"clusterID":"openshift-storage","csi.storage.k8s.io/controller-expand-secret-name":"rook-csi-rbd-provisioner","csi.storage.k8s.io/controller-expand-secret-namespace":"openshift-storage","csi.storage.k8s.io/fstype":"ext4","csi.storage.k8s.io/node-stage-secret-name":"rook-csi-rbd-node","csi.storage.k8s.io/node-stage-secret-namespace":"openshift-storage","csi.storage.k8s.io/provisioner-secret-name":"rook-csi-rbd-provisioner","csi.storage.k8s.io/provisioner-secret-namespace":"openshift-storage","imageFeatures":"layering","imageFormat":"2","pool":"moc_rbd_1"},"provisioner":"openshift-storage.rbd.csi.ceph.com","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
    storageclass.kubernetes.io/is-default-class: 'true'
  managedFields:
    - manager: ocs-operator
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2021-10-14T19:42:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:allowVolumeExpansion': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:description': {}
        'f:parameters':
          'f:csi.storage.k8s.io/controller-expand-secret-name': {}
          'f:clusterID': {}
          'f:imageFeatures': {}
          'f:csi.storage.k8s.io/controller-expand-secret-namespace': {}
          'f:csi.storage.k8s.io/fstype': {}
          .: {}
          'f:csi.storage.k8s.io/provisioner-secret-namespace': {}
          'f:pool': {}
          'f:csi.storage.k8s.io/node-stage-secret-name': {}
          'f:csi.storage.k8s.io/node-stage-secret-namespace': {}
          'f:csi.storage.k8s.io/provisioner-secret-name': {}
          'f:imageFormat': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
    - manager: argocd-application-controller
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2021-11-02T16:24:05Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:storageclass.kubernetes.io/is-default-class': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
provisioner: openshift-storage.rbd.csi.ceph.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  imageFormat: '2'
  clusterID: openshift-storage
  imageFeatures: layering
  csi.storage.k8s.io/controller-expand-secret-namespace: openshift-storage
  pool: moc_rbd_1
  csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

on os-climate we have `gp2`

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  uid: f95d6e5c-d954-4b4c-8275-533dbebb8218
  resourceVersion: '4475'
  creationTimestamp: '2021-06-29T21:52:47Z'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  managedFields:
    - manager: cluster-storage-operator
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2021-06-29T21:52:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:allowVolumeExpansion': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:storageclass.kubernetes.io/is-default-class': {}
        'f:parameters':
          .: {}
          'f:encrypted': {}
          'f:type': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
provisioner: kubernetes.io/aws-ebs
parameters:
  encrypted: 'true'
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```

and `gp2-csi`

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-csi
  uid: 599b6dc0-3517-4f7c-8fbd-6cd1cedc39be
  resourceVersion: '5280'
  creationTimestamp: '2021-06-29T21:52:53Z'
  managedFields:
    - manager: aws-ebs-csi-driver-operator
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2021-06-29T21:52:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:allowVolumeExpansion': {}
        'f:parameters':
          .: {}
          'f:encrypted': {}
          'f:type': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
provisioner: ebs.csi.aws.com
parameters:
  encrypted: 'true'
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```

**Comment by durandom** [comment]
@guimou can you let me know how to enable RWX or what the requirements are?

**Comment by MichaelTiemannOSC** [comment]
OS-Climate does not intend to be "AWS only", but wants to be cloud-neutral.  If a given technology solution is tied too tightly to a specific cloud, we don't want to tie that too deeply into the architecture.  OpenShift is cloud-neutral, and thus attractive.

**Comment by guimou** [comment]
Highlander itself is totally agnostic. The requirement is to have RWX volumes to be able to mount the shared library in many pods simultaneously. This can be achieved in different ways depending on the underlying infrastructure:
- On Smaug, you have an external Ceph Cluster, so CephFS should be available as a suitable storage. However it's odd that it does not appear directly in ODF. According [to the doc](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.10/html/deploying_openshift_data_foundation_in_external_mode/deploy-openshift-data-foundation-using-red-hat-ceph-storage#creating-an-openshift-data-foundation-cluster-service-for-external-storage_ceph-external), it may may be that MDS has never been deployed on the Ceph Cluster, or that you had updated Ceph from an older version at some point, and the resources have then to be created manually (see 2.3.1 and 2.3.4 in referred doc). I you can give me the different versions of OCP, ODF, Ceph,... I can help with proper instructions.
- on AWS, if ODF is not deployed (because, yes, you could always deploy ODF in AWS, there are multiple advantages doing that), you can use AWS EFS as filesystem backend for RWX-capable PVCs ([doc here](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html)).

**Comment by guimou** [comment]
As per previous discussions, because CephFS is not available on Smaug, I have adapted and tested a method that will allow to properly provision RWX volumes based on NFS. It's an implementation of an NFS provisioner and server from the k8s-sig-storage group.
All the instructions are documented here: https://github.com/odh-highlander/nfs-server-and-provisioner
Only the Deployment section has to be implemented, with a main PVC size (`export-pvc-claim` at step 3) of 500GB.
With this implementation, it will also be really easy to create shared RWX volumes on Smaug for shared data, notebooks,...
