### ISSUE TITLE
Mailing list web login not working for some users

### ISSUE THREAD

**Issue by quaid** [operate-first/support#618]
### Describe the Problem

A number of people were auto-subscribed to the community@lists.operate-first.cloud mailing list. There seems to be a dynamic where the email address receives email, but it's not recognized as a full user account.

For example, `tschwesi@redhat.com` is a subscribed address, but when you go to https://lists.operate-first.cloud/accounts/password/reset/ and put in that address to reset/set the password, it returns with the error, "The e-mail address is not assigned to any user account".

By comparison, I can do the password reset for my `kwade@redhat.com` and `quaid@iquaid.org`, with the former I believe being an auto-subscribe. But both of those have usernames 'kwade' and 'quaid', which is what I login with. The password reset is by email address only.

Another strange thing that may be related, when I am logged in to my admin account (quaid) and look at a subscriber, all of the boolean values are unset. If I set them e.g. 'Enable' for delivery, they report as saved, but the page reloads showing them as blank, even my own:
![Screenshot from 2022-08-08 09-35-32](https://user-images.githubusercontent.com/112760/183468247-43879036-e2a3-41af-86f0-ae25039c6e74.png)
 

### Steps to Reproduce

1. Go to https://lists.operate-first.cloud/accounts/login
2. Clock the __Forgot Password?__ link
3. Enter your subscriber email address in the __E-mail__ field and click __Reset My Password__
4. Receive an error message, __The e-mail address is not assigned to any user account
__
5. If you don't get the error, explore how your account was created compared the bulk of others

### Expected behaviour

Since the email address is indeed subscribed, it should simple send a password reset and inform the user it was done. I'm able to make this happen with my user accounts.

### Screenshots

![Screenshot from 2022-08-08 09-40-15](https://user-images.githubusercontent.com/112760/183469126-6ca76723-6717-4f7f-9a0d-73f8df05b25b.png)

### Additional context

This service is run by @mscherer and @duck-rh

**Comment by schwesig** [comment]
thanks @quaid for issuing this

**Comment by duck-rh** [comment]
@quaid being a member of the list does not mean you have an account in the web UI. Now if you register and validate using the same email address then you get to control your subscriptions and other settings, but this is not compulsory as you can simply request membership of the list (certain users prefer this in fact). In this case they were auto-added, do not have an account and need to register if they want to enjoy the UI. By email you can basically only subscribe and unsubscribe, no options etc.

As for blank settings this means these are default settings but this default is not displayed in this version of the software (will come when we upgrade).

Hope this helps.
\\_o<
