### ISSUE TITLE
Kubeflow components' deployment

### ISSUE THREAD

**Issue by tumido** [operate-first/support#62]
**Is your feature request related to a problem? Please describe.**
As per our meeting with mesh-for-data today, there's a requirement to have a Kubeflow deployment up.

**Describe the solution you'd like**
A proper Kubeflow deployment on Openshift

**Describe alternatives you've considered**
n/a

**Additional context**
Related to: https://github.com/operate-first/support/issues/6 https://github.com/operate-first/apps/issues/10

cc @eletonia

**Comment by goern** [comment]
how does that relate to some kubeflow being part of ODH?

**Comment by tumido** [comment]
@goern No idea, rn. This is a requirement we collected from the m4d team. I think we would definitely like to leverage ODH's expertise in deploying Kubeflow, though I'm not sure if we want to stash everything into a single namespace and how to handle multi-tenancy in Kubeflow which doesn't support it much... This is just a kick off, right now, feel free to suggest options. :slightly_smiling_face:

**Comment by goern** [comment]
We should strive for an architectural decision: is Kubeflow something we deploy per namespace or cluster-wide? is it a service of the platform or something the application owner brings on his own? Is there any interferences to be expected if multiple kubeflow versions are deployed on the cluster but separated by namespaces?

/sig documentation
/sig devops

**Comment by tumido** [comment]
I totally agree with you. :+1: I actually don't know if Kubeflow can be successfully deployed to any other namespace than`kubeflow` or if it can be split into multiple namespaces yet if there can be multiple Kubeflow deployments... This requires quite a lot of experimentation and testing before we have even the foundation for any decision.

**Comment by HumairAK** [comment]
We most likely can't do a cluster-wide deployment since both Kubeflow and ODH operatoe on the same set of APIs, it will likely have to be namespace scoped. We could do _multi-namespaces_ in the sense we can have multiple single namespace deployments, but we can't do a multi namespace operator group as per [this adr](https://github.com/operate-first/blueprint/pull/26/files#diff-b339fc9e1d4835a1ffad044d13b71bdd133ad6d825b1f15b13693dd4cf96cec8R86)

**Comment by eletonia** [comment]
Since we are only using Kubeflow notebooks, is it possible for `mesh-for-data` to get access to the ODH namespace so we can use Jupyter notebooks instead?

**Comment by tumido** [comment]
The ODH JupyterHub is publicly available to all users (you don't have to have a OpenShift project access even):

https://www.operate-first.cloud/users/support/
https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/hub/login

Is that what you're asking? We will still plan on deploying the Kubeflow anyways :wink:

**Comment by eletonia** [comment]
Yes thank you!

**Comment by 4n4nd** [comment]
@tumido I think there is some confusion here, I don't think we need to deploy kubeflow (as in the controller) because we already have the odh operator set up. We can just have the odh operator deploy Kubeflow components (like the kf dashboard/kf pipelines).

**Comment by tumido** [comment]
I don't think there's much confusion. This ticket is about deploying the Kubeflow components and application via the ODH operator. The users don't care how we deploy it, they want to have the user facing applications available and we should coordinate that.

@goern and @eletonia, FTR:
Yesterday we had a meeting about Kubeflow and decided that there are some technical limitations on the Kubeflow side - most importantly the hardcoded `kubeflow` namespace in multiple components. We can't overcome that right now, which means we can't federate the deployment to multiple namespaces or to have multiple isolated deployments. That means we decided to experimentally deploy the Kubeflow as is, to the `kubeflow` namespace and provide that as a shared platform to all users.

We also require all the cluster-scoped resources of Kubeflow, like Istio, Argo/Tekton, etc. to be deployed separately since users may want to interact with those outside of Kubeflow.

@4n4nd is working on that.

**Comment by HumairAK** [comment]
> I don't think there's much confusion. This ticket is about deploying the Kubeflow components and application via the ODH operator. The users don't care how we deploy it, they want to have the user facing applications available and we should coordinate that. 

Whoops, the confusion is from my part. When I read "Kubeflow Deployment" I think the actual deployment of the Kubeflow operator. The way I understand it, we're talking about specific components deployed by kubeflow, but we'll be deploying via ODH.  And these namespaces are hardcoded, Yes?

**Comment by tumido** [comment]
yes, user doesn't care by how we deploy the Kubeflow. And ODH operator is basically the same as Kubeflow operator (`kfdef` in, deployments out). So I would suggest for us using the ODH operator to have a `kfdef` for Kubeflow.

> And these namespaces are hardcoded, Yes?
Yes. The Kubeflow specific components are the ones requiring hardcoded namespace - this limitation originates in the kustomize manifests upstream. Which is a shame, but unless we fix this upstream or fork it, there's not much to do with it. And that's an adventure for another time, I think...

**Comment by HumairAK** [comment]
**Multi-user Isolation**

I took a bit of a gander over at [Kubeflow's  multi-user isolation](https://www.kubeflow.org/docs/pipelines/multi-user/) and it looks.  like this is how they handle multi-tenancy.

For those unfamiliar, basically Kubeflow has "user profiles" which they use interchangeably with k8s namespaces that are mapped to these "user profiles" (the profile itself is a CRD). Automatic user profile creation is enabled by default. A user can create their profile via the dashboard, then kubeflow will go ahead and create a namespace along with it for this profile. Of course [we will have to turn this off](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#automatic-creation-of-profiles). Kubeflow gives us options to manage user [profiles manually](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#manual-profile-creation). 

We also don't need to have one user mapped to one user profile (which is mapped to one namespace), a user profile can have multiple k8s/ocp users be able to use a single user profile. This means that multiple users can choose the same profile as "active" while in the dashboards, and the components that support namespace isolation, will be deploying artifacts to that active user profile (hence namespace). This can also be managed manually (declaritively) as described [here](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-through-the-kubeflow-ui). 

Now when I say managed manually within this context, that doesn't necessarily mean we can manage the namespaces (and other artifacts created by kubeflow when creating the userprofile) in these particular contexts declaratively (maybe we can). Instead, we can manage, at the very least, some of the rbac and assets mentioned in that doc linked above.

**Comment by pvaneck** [comment]
Hi all,
I was pointed to this issue in one of the email threads going on regarding Operate First and KFServing.

In regards to KFServing on OpenShift, the latest version of KFserving (v0.5.0) was just recently released, and from what I have tested so far, should work fine. Some OpenShift related documentation for installation can be found here: https://github.com/kubeflow/kfserving/blob/master/docs/OPENSHIFT_GUIDE.md. However, much of this was geared more towards a standalone KFServing install. 

The manifest for KFserving integrated with the rest of Kubeflow isn’t available just yet for the newest version (work in progress). Currently there is work being done to refactor the Kubeflow manifests repo, so any KFdefs pulling from master might see some breakage until the refactoring is completed. But if you are using an older fork/branch of manifests before the refactoring  started (3 days ago), KFServing v0.4.1 can be integrated by just adding the `path: kfserving/installs/generic` kustomizeConfig to your kfdef file since it seems you already have the istio and knative requirements in your kfdef. Let me know if there is anything specific I can assist with.

**Comment by tumido** [comment]
yes, we're an using older fork, so it should work. Thank you! cc @4n4nd

**Comment by pvaneck** [comment]
FYI, the community manifests for Kubeflow 1.3, which will be released later this month, is planning to include updated Istio/Knative versions (Istio 1.9 and Knative 0.17.4) and also KFServing 0.5.1. The updated Istio version will likely lead to better compatibility of KubeFlow components with Red Hat Service Mesh if that is on the roadmap.

Not sure if anyone here tried deploying KFServing yet, but, again, it should just be a matter of adding kfserving to the kfdef.yaml. While updating the KFdef is probably the easiest way, an alternative can be installing via the [kubeflow overlay](https://github.com/kubeflow/kfserving/tree/master/config/overlays/kubeflow) in the KFServing repo. This will integrate KFServing into a Kubeflow environment, and this overlay will be used to generate a kubeflow specific install yaml [here](https://github.com/kubeflow/kfserving/tree/master/install/v0.5.1) which can simply be applied.

**Comment by goern** [comment]
Cc: @harshad16
