### ISSUE TITLE
Vault Integration Required

### ISSUE THREAD

**Issue by riprasad** [operate-first/support#620]
### Description

As of now we're storing our  SSO credentials and other sensitive tokens as secrets. Also, currently we are manually creating the secret on the cluster since we cannot push the secret manifests to github. We would like to avoid doing that and use vault for storing our sensitive data, to avoid information leak and manual creating of secrets in our namespace.

Chat Thread: https://app.slack.com/client/T01SKMNPRUG/C01RMPVUUK1/thread/C01RMPVUUK1-1659357915.770019

**Comment by riprasad** [comment]
@mimotej could you please assign this to the relevant person?

**Comment by mimotej** [comment]
I'll go ahead and setup what is necessary.

**Comment by HumairAK** [comment]
this is now resolved @riprasad please re-open or create a new issue if anything is still left pending
