### ISSUE TITLE
'No data' shown by Grafana on main "Community Cloud" page

### ISSUE THREAD

**Issue by quaid** [operate-first/support#622]
### Describe the Problem

Grafana is displaying zero data, as if it's source is empty or it's not connecting to a service. This service was working a few weeks ago. Grafana shows flags that it is working and updating the charts, but nothing is displayed.

### Steps to Reproduce

1. Go to https://www.operate-first.cloud/community-cloud
2. Scroll down to the "Workloads" section
3. Note the lack of charts and graphs

### Expected behaviour

Grafana will pull the latest data and display it.

### Screenshots

This is how the page looks after the Grafana logo timer finishes:
![Screenshot from 2022-08-09 10-10-41](https://user-images.githubusercontent.com/112760/183720394-ff4d4aec-0411-41b9-ba2f-bea5a2a75517.png)

It's clear Grafana service is running and attempting to gather data to display, as these flags show:
![Screenshot from 2022-08-09 10-07-07](https://user-images.githubusercontent.com/112760/183720400-45c73a84-7128-4f07-801a-6df00c987efb.png)

### Additional context

This seems to be on the other side of a working Grafana instance, such as an empty data source or a source service connecting properly but not feeding any data over the connection.

**Comment by durandom** [comment]
@schwesig I think we should just remove them and the services tiles as well.
Let's just link to the https://www.operate-first.cloud/apps/content/README.html and https://service-catalog.operate-first.cloud/

**Comment by schwesig** [comment]
/closed by https://github.com/operate-first/operate-first.github.io/pull/195
instead of removing the services tiles (yet), I added the link to https://service-catalog.operate-first.cloud/
reason: the tiles have still some additional links/ info that may be useful, until the service-catalog is full blown or we add the information to another part of the website
