### ISSUE TITLE
Request to include CI/CD process for repo: https://github.com/redhat-et/homomorphic-learning 

### ISSUE THREAD

**Issue by suppathak** [operate-first/support#627]
In order to include automated processes like assigning reviewers for PR, merging PRs after approval, I would like to have a setup for the repo: https://github.com/redhat-et/homomorphic-learning

**Comment by suppathak** [comment]
cc @harshad16 
cc @aakankshaduggal

**Comment by harshad16** [comment]
The repo is now being watched by operate-first prow instance.
Here is example pr : https://github.com/redhat-et/homomorphic-learning/pull/20
closing the issue.
