### ISSUE TITLE
NEW PROJECT: next-security-demo

### ISSUE THREAD

**Issue by lukehinds** [operate-first/support#628]
### Team name

next-security-demo

### Desired project names

next-security-demo

### Project description

A cluster for the OCTO-ET Security Team to stand up a demo for the Next! Event staged in Dallas

### Users needing access

lukehinds

### Namespace Quota

Small

**Comment by durandom** [comment]
@lukehinds can you elaborate on the size and features of the cluster? I have an idle single node cluster deployed at https://github.com/operate-first/ionos-openshift
I could hand out `cluster-admin` 
If you just need namespaces and nothing fancy, I'd recommend a namespace on `smaug`

**Comment by durandom** [comment]
you're already part of groups [rekor](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/rekor/group.yaml) and [sigstore](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/sigstore/group.yaml) but I dont see any namespaces for both teams.

Should we create a new security team or re-use one of those?

**Comment by lukehinds** [comment]
> you're already part of groups [rekor](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/rekor/group.yaml) and [sigstore](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/sigstore/group.yaml) but I dont see any namespaces for both teams.
> 
> Should we create a new security team or re-use one of those?

I am not sure what those are from, it might been efforts a few years ago. A new team would be useful I think, and start un-opinionated.

**Comment by lukehinds** [comment]
> @lukehinds can you elaborate on the size and features of the cluster? I have an idle single node cluster deployed at https://github.com/operate-first/ionos-openshift I could hand out `cluster-admin` If you just need namespaces and nothing fancy, I'd recommend a namespace on `smaug`

I don't really have any size requirements. At the most I might be running 10 containers or so. This will be for a demo and prototyping.
