### ISSUE TITLE
Request: Kubernetes/Openshift Audit logs for a Master's Thesis

### ISSUE THREAD

**Issue by roastdeer** [operate-first/support#629]
### Description

Hello,
@durandom asked me to open this issue. 

I'm currently in research/data hoarding phase of my upcoming Master's Thesis on _Kubernetes/Openshift log anomaly analysis_ (using Machine Learning) and if possible I'd like to receive all kinds of logs that you could provide to me so that I can train my algorithms as best as I can.

I already have some Openshift audit log dumps from two clusters and I'd love to get as much as possible from different sources. Perhaps you could include Prometheus logs or anything else that might be useful to better differentiate events happening on the clusters.

Anything you can share will surely help.

**Comment by Gregory-Pereira** [comment]
Firstly nice PFP. To the issue at hand. We're currently moving bits of our monitoring stack around, so i'm not sure if we have a single centralized point for logs from every cluster, but we do have OBCs which store our logs for each cluster. Why don't we start with accessing our  logs from our semi-production Smaug cluster and we can always give you links to access our other logs

Here are the steps to gain access:

1. Petition to join the operate-first organization by adding yourself to its members list [here](https://github.com/operate-first/common/blob/main/github-config.yaml#L19-L148). This will give you the permissions to run the presubmit checks on your other PRs, allowing them to pass so you can request access. 

2. Join an operate-first group with the correct RBAC permissions. We have a `clusterrolebinding` known as [`cluster-logs-reader`](https://github.com/operate-first/apps/blob/master/cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-logs-readers/clusterrolebinding.yaml) which is what kind of access I think you are looking for. From there it applies the `cluster-logs-reader` role to 3 groups: `operate-first`, `open-aiops`, and `data-science`, of which I think you are best suited to `open-aiops`. Make a pr to add yourself to [said group](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/open-aiops/group.yaml#L8) (you can replace the commented line, it shouldn't be there to begin with) with your GitHub handle.

3. After both of these two PRs get merged you can attempt to access the logs which will be available in the S3 bucket backed by the `opf-observatorium-logs` objectBucketClaim. I have a link here for [what that would be on the smaug cluster](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-observatorium/objectbucket.io~v1alpha1~ObjectBucketClaim/opf-observatorium-logs) and [how you can access it](https://www.operate-first.cloud/apps/content/odf/buckets-external-access.html?highlight=external%20bucket#accessing-a-bucket-from-outside-the-cluster) if you are unfamiliar with S3 buckets.

Feel free to reach out with any questions, hope this helps

**Comment by roastdeer** [comment]
Thank you.
(The PFP is DALL-E generated btw)

**Comment by durandom** [comment]
Thanks @Gregory-Pereira for the detailed response.
I don't think any of those groups are a good fit, since they're all functional teams.
Let's see if we can help without joining a group.

@roastdeer - now that you're part of the operate-first GH org you should be able to access https://grafana.operate-first.cloud/?orgId=1 - but I might be wrong.
Have a look at the data sources and explorer and see if there's data you need.
You can also export logs from loki https://www.operate-first.cloud/apps/content/observatorium/thanos/thanos_programmatic_access.html 

if you're saying `Audit Logs` - is that just general cluster logs or something produced by a special operator?

**Comment by durandom** [comment]
@roastdeer right, you need more permissions.
Please create a PR to add you to https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/grafana-viewer/group.yaml as per https://www.operate-first.cloud/apps/content/grafana/docs/map_groups_to_roles.html and https://www.operate-first.cloud/apps/content/observatorium/thanos/request_grafana_access.html

But I just realized we currently have issues with loki and cluster log storage anyway, so the logs are not available :(
And we're revamping the whole metrics/logging system

What is the timeframe you need those logs?

**Comment by roastdeer** [comment]
@durandom thanks for the assistance. I opened the PR.

I have some logs I can work with so far so let's say I'd like to get some more within 1-2 months? Though I'd like to get more ASAP and the 2 months are a pretty hard limit for me. Does that sound doable?

**Comment by durandom** [comment]
@roastdeer I'll help you getting access to our logging, but I'm not sure how much there currently is, as we're revamping the monitoring and logging stack. 
Let's get you access and then see :)
