### ISSUE TITLE
Istio deployment

### ISSUE THREAD

**Issue by tumido** [operate-first/support#63]
**Is your feature request related to a problem? Please describe.**
As per our meeting with mesh-for-data today, there's a requirement to have an Istio deployment up and running

**Describe the solution you'd like**
A proper Istio deployment on Openshift

**Describe alternatives you've considered**
n/a

**Additional context**
Related to: https://github.com/operate-first/apps/issues/10

cc @eletonia

**Comment by tumido** [comment]
Also @eletonia mentioned something about Istio version in Kubeflow to be outdated and having a preference for a newer one? Do I recall it correctly?

**Comment by eletonia** [comment]
Yes Kubeflow currently comes with Istio 1.3.1 but the latest version of Istio is 1.8.2

**Comment by tumido** [comment]
Closing, will be managed by ServiceMesh operator. https://github.com/operate-first/support/issues/111
