### ISSUE TITLE
[INCIDENT][Smaug] - Smaug facing networking issues

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/support#631]
### Clusters Affected

Smaug

### Users Affected

Everyone using smaug.

### Incident Description

Hello Operate-First Users,

Smaug is currently facing some networking issues. It has been identified something is wrong with the switches Smaug is using. It seems that it's not completely inaccessible, which would imply to me that only some of the switches are affected, but more information on this will be provided when it is confirmed. 

As for the services / pieces that are affected, firstly Openshift authentication itself is affected which my prevent generating an openshift token / authenticating via the api. As a result of this, access to routes that require permission scoping from identitatum or dex would also be affected. Sometimes pod logs are not available as well.

Thank you for your patience,
- Operate-First Team

### Relevant Links

https://operatefirst.slack.com/archives/C01RT0S2WKX/p1662044430508329?thread_ts=1662039633.437399&cid=C01RT0S2WKX

**Comment by durandom** [comment]
still ongoing https://github.com/CCI-MOC/ops-issues/issues/691
