### ISSUE TITLE
Openmetadata Airflow scheduler pod is crashing due to logs filesystem saturation

### ISSUE THREAD

**Issue by redmikhail** [operate-first/support#638]
Size of PVC for airflow scheduler is set to 1GB and fills up fairly quickly causing Airflow Scheduler pod to fail. By default AirFlow doesn't have limit on number of logs that it can produce.  In following article https://stackoverflow.com/questions/43548744/removing-airflow-task-logs/54195537#54195537 users had to resort to writing script that would rotate/clean log files. As temporary solution we need to increase size of PVC to at least 5GB. As it is just temporary workaround we need to find the way to limit number of logs.

**Comment by durandom** [comment]
@redmikhail is this still relevant?

/assign @redmikhail
