### ISSUE TITLE
Decouple central ops and abstract from MOC

### ISSUE THREAD

**Issue by quaid** [operate-first/support#647]
This is probably a longer-term goal but it would be great if it were substantively in place for the next MOC multi-day power outage.

As a cloud environment provider, we need to design our cloud so it is not dependent on one region or one data center.

The vision here is, when the next MOC multi-day planned power outage occurs, the Op1st project is able to maintain uptime throughout and does not need to announce an outage to our users and contributors.

**Comment by durandom** [comment]
we're hybrid 🎉 

MOC bare metal + AWS + IONOS

/close
