### ISSUE TITLE
Options for per-cluster and per-namespace notifications

### ISSUE THREAD

**Issue by larsks** [operate-first/support#650]
During incidents such as the current MGHPCC power outage, we would like a mechanism for sending targeted notifications to the affected audience: that is, we want to be notify Smaug users of the downtime without bugging people using Rick or the OSC cluster. We would like even more granular channels, so that if we are forced to disabled resources on a cluster due to a problem, we would like to be able to notify the owners of the particular namespaces involved.

This is related to operate-first/support#651, because in order to enable this we need to collect email addresses or other contact information as part of our onboarding process.

Questions related to this issue:

- What notification channel(s) should we use? Slack? Email? Both? Something else?
- If we use email, should we have a mailman server and synchronize list membership with onboarding information?

**Comment by durandom** [comment]
similar to https://github.com/operate-first/operate-first.github.io/issues/61
and the decision whether to use GitHub discussion or not

@schwesig any updates on the latter?

/assign @schwesig

**Comment by schwesig** [comment]
@durandom no updates I know of, I need to get into this again
