### ISSUE TITLE
Configure ODF (OCS) using NESE storage on Infra cluster

### ISSUE THREAD

**Issue by larsks** [operate-first/support#652]
In order to use volume storage on the moc-infra cluster, we need to configure access to the NESE ceph storage cluster.

**Comment by tumido** [comment]
ODF GChat thread: https://chat.google.com/room/AAAABTq-uCM/xE4cR1lCRDk

ODF cluster provisioning is stuck on `External CephCluster error: failed to get external ceph mon version: failed to run 'ceph version'. . timed out: exit status 1`.

Rook ceph operator logs show:

```
2022-09-20 13:22:45.515870 I | ceph-cluster-controller: reconciling ceph cluster in namespace "openshift-storage"
360
2022-09-20 13:22:45.532229 I | op-mon: parsing mon endpoints: ceph0=10.255.116.11:6789
361
2022-09-20 13:22:45.536040 I | op-mon: found the cluster info to connect to the external cluster. will use "client.healthchecker-moc-infra-rbd" to check health and monitor status. mons=map[ceph0:0xc001d768a0]
362
2022-09-20 13:22:45.539697 I | cephclient: writing config file /var/lib/rook/openshift-storage/openshift-storage.config
363
2022-09-20 13:22:45.539868 I | cephclient: generated admin config in /var/lib/rook/openshift-storage
364
2022-09-20 13:22:45.539888 I | ceph-cluster-controller: external cluster identity established
365
2022-09-20 13:22:45.601209 I | ceph-csi: successfully created csi config map "rook-ceph-csi-config"
366
2022-09-20 13:22:45.615621 I | ceph-cluster-controller: successfully updated csi config map
367
2022-09-20 13:23:00.924833 E | ceph-cluster-controller: failed to reconcile CephCluster "openshift-storage/ocs-external-storagecluster-cephcluster". failed to reconcile cluster "ocs-external-storagecluster-cephcluster": failed to configure external ceph cluster: failed to get external ceph mon version: failed to run 'ceph version'. . timed out: exit status 1
```

That made me suspicious of the credentials used/passed to the operator. If I try executing this in the operator pod it indeed timeouts:

```
$ oc rsh rook-ceph-operator-84bbdbbbdb-xrjhg
sh-4.4$ cat /var/lib/rook/openshift-storage/openshift-storage.config
[global]
fsid                = 6de96983-eef7-4690-9a6d-9124d3707a30
mon initial members = ceph0
mon host            = [v2:10.255.116.11:3300,v1:10.255.116.11:6789]

[client.healthchecker-moc-infra-rbd]
keyring = /var/lib/rook/openshift-storage/client.healthchecker-moc-infra-rbd.keyring

sh-4.4$ cat /var/lib/rook/openshift-storage/client.healthchecker-moc-infra-rbd.keyring

[client.healthchecker-moc-infra-rbd]
        key = KEY

sh-4.4$ ceph -n client.healthchecker-moc-infra-rbd --keyring /var/lib/rook/openshift-storage/client.healthchecker-moc-infra-rbd.keyring --conf=/var/lib/rook/openshift-storage/openshift-storage.config version
2022-09-20T13:15:28.947+0000 7f107aefd700  0 monclient(hunting): authenticate timed out after 300
```

However if I copy the keyring from the operator into Ceph Tools pod I get proper answer:

```
$ oc rsh rook-ceph-tools-787676bdbd-x6j52
sh-4.4$ cat /etc/ceph/ceph.conf
[global]
mon_host = 10.255.116.11:6789

[client.admin]
keyring = /etc/ceph/keyring

sh-4.4$ cat /tmp/client.healthchecker-moc-infra-rbd.keyring
[client.healthchecker-moc-infra-rbd]
        key = KEY

sh-4.4$ ceph -n client.healthchecker-moc-infra-rbd --keyring /tmp/client.healthchecker-moc-infra-rbd.keyring version
ceph version 14.2.12 (2f3caa3b8b3d5c5f2719a1e9d8e7deea5ae1a5c6) nautilus (stable)
```

Both pods are running on the same node.

Our external cluster configuration has following content:

```
[
  {
    "name": "rook-ceph-mon-endpoints",
    "kind": "ConfigMap",
    "data": {
      "data": "ceph0=10.255.116.11:6789",
      "maxMonId": "0",
      "mapping": "{}"
    }
  },
  {
    "name": "rook-ceph-mon",
    "kind": "Secret",
    "data": {
      "fsid": "6de96983-eef7-4690-9a6d-9124d3707a30",
      "admin-secret": "admin-secret",
      "mon-secret": "mon-secret"
    }
  },
  {
    "name": "rook-ceph-operator-creds",
    "kind": "Secret",
    "data": {
       "userID": "client.healthchecker-moc-infra-rbd",
       "userKey": "KEY"
    }
  },
  ...
]
```

What else can I check? I'm really stuck on this one, so any hits will help. I can give you direct access to the cluster if needed, it's an Operate First community cloud cluster.

**Comment by tumido** [comment]
Slack thread:

> **Tom Coufal wrote:**
> Storage on infra update: It's still not working but I've managed to verify it's neither permission or networking issue. Something's up with the operator. I've reached out to the ODF support people and we'll see where that goes. :confused: (also.. I hate it with passion now :smile: )
> 
> **Humair Khan wrote:**
> 
> 
> **Tom Coufal wrote:**
> Actually it may be pod networking issue.. The problem is that I have one pod which can access the remote cluster and a different pod which can't.. even if they use the same configuration (as far as I can tell)... :confused: I really don't want to know this much about it... :smile:
> 
> **Humair Khan wrote:**
> hrmm that is strange
> 
> **Humair Khan wrote:**
> what if you put both pods on the node that worked
> 
> **Humair Khan wrote:**
> (i.e. could it be some nodes have issues connecting to the remote cluster?)
> 
> **Tom Coufal wrote:**
> they are on the same node from the start.. :smile:
> 
> **Humair Khan wrote:**
> ...
> 
> **Humair Khan wrote:**
> which pods?
> 
> **Tom Coufal wrote:**
> nope.. the only thing I'm suspecting there is OVN... but I really don't understand that... :smile:
> 
> **Tom Coufal wrote:**
> `rook-ceph-tools` and `rook-ceph-operator`
> 
> **Tom Coufal wrote:**
> tools connects just fine, but operator doesn't
> 
> **Tom Coufal wrote:**
> ```$ oc rsh rook-ceph-tools-787676bdbd-x6j52
> sh-4.4$ cat /etc/ceph/ceph.conf
> [global]
> mon_host = 10.255.116.11:6789
> 
> [client.admin]
> keyring = /etc/ceph/keyring
> 
> sh-4.4$ cat /tmp/client.healthchecker-moc-infra-rbd.keyring
> [client.healthchecker-moc-infra-rbd]
>         key = KEY
> 
> sh-4.4$ ceph -n client.healthchecker-moc-infra-rbd --keyring /tmp/client.healthchecker-moc-infra-rbd.keyring version
> ceph version 14.2.12 (2f3caa3b8b3d5c5f2719a1e9d8e7deea5ae1a5c6) nautilus (stable)```
> vs
> ```$ oc rsh rook-ceph-operator-84bbdbbbdb-xrjhg
> sh-4.4$ cat /var/lib/rook/openshift-storage/openshift-storage.config
> [global]
> fsid                = 6de96983-eef7-4690-9a6d-9124d3707a30
> mon initial members = ceph0
> mon host            = [v2:10.255.116.11:3300,v1:10.255.116.11:6789]
> 
> [client.healthchecker-moc-infra-rbd]
> keyring = /var/lib/rook/openshift-storage/client.healthchecker-moc-infra-rbd.keyring
> 
> sh-4.4$ cat /var/lib/rook/openshift-storage/client.healthchecker-moc-infra-rbd.keyring
> 
> [client.healthchecker-moc-infra-rbd]
>         key = KEY
> 
> sh-4.4$ ceph -n client.healthchecker-moc-infra-rbd --keyring /var/lib/rook/openshift-storage/client.healthchecker-moc-infra-rbd.keyring --conf=/var/lib/rook/openshift-storage/openshift-storage.config version
> 2022-09-20T13:15:28.947+0000 7f107aefd700  0 monclient(hunting): authenticate timed out after 300```
> 
> **Tom Coufal wrote:**
> I'm contemplating switching <https://docs.openshift.com/container-platform/4.10/networking/cluster-network-operator.html#gatewayConfig-object_cluster-network-operator>
> 
> **Tom Coufal wrote:**
> 
> 
> **Tom Coufal wrote:**
> But I really don't understand the implications :smile:
> 
> **Humair Khan wrote:**
> sounds like it would scale poorly
> 
> **Humair Khan wrote:**
> _I too don't know much about this however_
> 
> **Tom Coufal wrote:**
> I'm grasping straws here but the only difference I see between tools and operator pod are their annotations, where operator is being fed some extra stuff from OLM (I think) like this one:
> 
> **Tom Coufal wrote:**
> The operator pod *doesn't contain any* network analysis binaries like `ip`, `ping`, `ipconfig`...  so it's really hard to tell if it "just" can't connect or uses wrong config
> 
> **Humair Khan wrote:**
> can you spin up duplicate pods w/o the annotations?
> 
> **Humair Khan wrote:**
> to rule it out?
> 
> **Tom Coufal wrote:**
> ok.. when trying that out.. how do I run a pod without ovn annotations? :smile:
> 
> **Tom Coufal wrote:**
> tools pod:
> 
> **Tom Coufal wrote:**
> when I try running the operator as a standalone like this:
> ```oc run -i -t --rm temp --command --image <http://registry.redhat.io/odf4/rook-ceph-rhel8-operator@sha256:dfe11ebccdc711a0b303d78c93998dac5fa41e8946beb7536b8a5e42c6d9ad05|registry.redhat.io/odf4/rook-ceph-rhel8-operator@sha256:dfe11ebccdc711a0b303d78c93998dac5fa41e8946beb7536b8a5e42c6d9ad05> -- /bin/sh```
> 
> **Tom Coufal wrote:**
> I get a pod with all OVN annotations despite all my hopes and wishes.. :D
> 
> **Tom Coufal wrote:**
> 
> 
> **Humair Khan wrote:**
> how come the `openshift-storage.config` is different in operator vs tools `ceph.conf`  ?
> also I'm guessing it's not specified in the tools cmd because the `/etc/ceph/ceph.conf` is the default path?
> 
> **Humair Khan wrote:**
> in ceph tools it seems you specified the keyring for the admin user, whereas it seems like it's for the `healthchecker-moc-infra-rbd` user?
> 
> **Humair Khan wrote:**
> what if it were also for the admin user in the operator conf?
> 
> **Tom Coufal wrote:**
> both are generated by the operator, however even if you try `/tmp/ceph.conf` in the operator pod the result is the same
> 
> **Tom Coufal wrote:**
> we don't have admin creds, so those are stub values not used by the operator, it tries to use healthchecked (I know this from the operator logs)
> 
> **Tom Coufal wrote:**
> in operator pod you can try `ceph -n client.healthchecker-moc-infra-rbd --keyring /var/lib/rook/openshift-storage/client.healthchecker-moc-infra-rbd.keyring --conf=/tmp/ceph.conf version` This is exactly the same as `ceph -n client.healthchecker-moc-infra-rbd --keyring /tmp/client.healthchecker-moc-infra-rbd.keyring version` in the tools pod
> 
> **Tom Coufal wrote:**
> because tools will default to `/etc/ceph/conf.conf` config file
> 
> **Tom Coufal wrote:**
> I can't get unprivileged operator pod without those OVN annotations no matter what I try. Please advise if you know more...
> 
> **Humair Khan wrote:**
> uhh no idea
> 
> **Humair Khan wrote:**
> can you send the pod manifest you tried
> 
> **Tom Coufal wrote:**
> I've tried interactive only.. something like this one.. <https://operatefirst.slack.com/archives/C01RT0S2WKX/p1663684301998709?thread_ts=1663681175.319589&amp;cid=C01RT0S2WKX>
> 
> **Tom Coufal wrote:**
> but even if I pass `--privileged=false`  it's still SCC privileged and gets those OVN annotations... Maybe if I try different namespace to fool OLM?
> 
> **Humair Khan wrote:**
> yeah try it
> 
> **Tom Coufal wrote:**
> Applying:
> ```apiVersion: v1
> kind: Pod
> metadata:
>   name: temp
>   namespace: helloworld
> spec:
>   containers:
>     - name: temp
>       command:
>         - /bin/sleep
>         - '1000000'
>       image: &gt;-
>         <http://registry.redhat.io/odf4/rook-ceph-rhel8-operator@sha256:dfe11ebccdc711a0b303d78c93998dac5fa41e8946beb7536b8a5e42c6d9ad05|registry.redhat.io/odf4/rook-ceph-rhel8-operator@sha256:dfe11ebccdc711a0b303d78c93998dac5fa41e8946beb7536b8a5e42c6d9ad05>```
> Results in:
> 
> **Tom Coufal wrote:**
> What do I do now? :smile: :smile:
> 
> **Humair Khan wrote:**
> what is happening
> 
> **Humair Khan wrote:**
> how is it getting these perms!?
> 
> **Tom Coufal wrote:**
> something is intercepting that image hash and enforcing it I guess...
> 
> **Tom Coufal wrote:**
> I can try retaging the image locally but I can't pull it since it's available to "RH subscribed accounts only"
> 

_Transcript of Slack thread: https://operatefirst.slack.com/archives/C01RT0S2WKX/p1663681175319589?thread_ts=1663681175.319589&cid=C01RT0S2WKX_
