### ISSUE TITLE
[Ops-docs] Create labels related to documentation 

### ISSUE THREAD

**Issue by carlosGimeno** [operate-first/support#657]
This suggestions was brought up during an Ops-docs meeting. The idea would be to add labels such as needs-documentation and has-documentation as a way to make sure that new features or changes are correctly documented (specially within the ops-docs) prior to the approval and merger of a PR.

**Comment by durandom** [comment]
great idea, but we dont have the critical mass to maintain all the labels 😱 
therefore 
/close
