### ISSUE TITLE
Decide on a dev osc cluster for new odh component development (starting with BYON)

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#671]
In the [OSG devsecops WG](https://github.com/open-services-group/devsecops) it was brought up that the [BYON WG](https://github.com/open-services-group/byon/issues/20) requires a dev/stage environment for BYON development. the `devsecops` WG is not responsible for cluster management, and this is under the purview of cluster-ops subproject in Operate First. 

The OSC clusers were identified as the ideal candidates for this, though there were some concerns. 

Currently there are 2 OSC clusters: 

### osc-cl1 
First OSC cluster provisioned. Has users, but these should (and probably are slated to be) migrated to `osc-cl2`. 

### osc-cl2 
New cluster, not prod, but will have odh users (jh/trino/superset/etc.). It is a "dev cluster" in the sense that there is development happening at the service facing level (developing runbooks, testing dashboards in superset, etc.). But some degree of cluster stability is desired. So probably not ideal for development that may destabilize cluster health/performance. 

Obviously `osc-cl1` seems like the better candidate here, but I think first we would have to ensure no one is relying on `osc-cl1`, and everything is available for users via `osc-cl2`. 

Assuming we're going with `osc-cl1`, these are my proposed action items to get `osc-cl1` ready for byon: 

Action items: 

- [x] deploy odh using odh-manifests fork in `osc-cl2` 
- [ ] move users from `osc-cl1` to `osc-cl2` 
- [x] convert odh deployment in `osc-cl1` to also use olm, and use odh-manifests fork 
- [x] give access to osc-cl1 to byon developers

If we decide otherwise, I'll reflect discussion points here and update action item list.

**Comment by codificat** [comment]
The only remaining item here, as far as I can see, is:

- [ ]  move users from osc-cl1 to osc-cl2

What is the status of this?

**Comment by goern** [comment]
@tumido could you have a look at the last remaining task? thx!

**Comment by durandom** [comment]
I think @HumairAK and @redmikhail might know better about moving users. What does moving users entail? I thought they can choose whatever cluster they like to work on?
