### ISSUE TITLE
Grafana regular backups of dashboards to external storage

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#676]
Since grafana operator will reboot grafana on CR changes (e.g. when a grafana datasource/dashboard CR) is added. We should consider if there's an easy way for us to setup periodic external backups for grafana in case someone loses critical work during one of these deployments.

**Comment by durandom** [comment]
TBH, I think it is good that the grafana dashboards get reset/cleaned up every now and then, otherwise we'd have a lot of stale dashboards.
If somebody actually requests a persistent grafana, we can create such an instance. until then
/close
