### ISSUE TITLE
Jupyterhub Admins

### ISSUE THREAD

**Issue by anishasthana** [operate-first/support#69]
Jupyterhub has support for "admins" in the jupyterhub interface. The admin interface gives access to some neat features, so we should set up some operate-first team members as admins on the MOC jupyterhub.

**Comment by tumido** [comment]
I think this goes hand in hand with the #66 and https://github.com/operate-first/apps/issues/100 We should coordinate this by having a common user-data application or something, that would allow setting the user profiles and PVCs etc. It may be required to keep this within the ODH jupyter hub overrides, right? :confused:

**Comment by anishasthana** [comment]
Yeah I think we'll need to use overrides here too

**Comment by martinpovolny** [comment]
I wonder what are those neat features.

Googling I've found:
 * killing other people's servers
 * (optionally) accessing other people's notebook
 
 Are those the features you are after?

**Comment by HumairAK** [comment]
@martinpovolny AFAIK, datahub uses admin privileges to help them diagnose/fix issues for their JH users. For example if a server is stuck, you are able to also see it from your side and try to kill it/restart it before going into the openshift console and messing around in there.

**Comment by anishasthana** [comment]
We can also create dummy users for testing purposes. It's been useful in the past.
