### ISSUE TITLE
JupyterHub Spawn Request with GPU Stuck

### ISSUE THREAD

**Issue by chauhankaranraj** [operate-first/support#70]
**Describe the bug**
JupyterHub pod spawn request gets stuck when requesting a GPU.

Probably not a major issue, because after I waited for a while, the request got killed (I think) and I was able to make a new request without GPUs and it worked.

**To Reproduce**
1. Go to [https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/](https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/) and sign in
2. Enter any non-zero value for the `GPU:` field
3. Click `Spawn`

**Expected behaviour**
Definitely open to possible solutions, but some ideas are
- GPU option should be greyed out if there are no GPU nodes
- Some documentation or error message telling the user to just wait it out and make another request without GPUs coz none are currently available

cc @4n4nd

**Comment by 4n4nd** [comment]
Since there are no GPUs available in the environment, he solution for this issue is to wait for JH to fail which should just take a few minutes and respawn your server with 0 GPUs
