### ISSUE TITLE
Upgrade kustomize in argocd to 4.5.0

### ISSUE THREAD

**Issue by larsks** [operate-first/support#704]
[Kustomize 4.4.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.4.0) has much improved support for YAML anchors and aliases, which can help reduce repetitive code in our YAML manifests. Let's upgrade our argocd environment to use this version of `kustomize`.

**Comment by durandom** [comment]
@Gregory-Pereira kustomize in our [toolbox](https://github.com/operate-first/toolbox/blob/ccede05a689e3a15d732f253b1f6ec7d9a4b6393/Dockerfile) is from 
https://quay.io/repository/viaductoss/ksops?tab=tags&tag=latest

Is the kustomize used by argocd a different one? 
Can you provide a link where it's defined?

TBH I would only update if we have a problem :)

/assign @Gregory-Pereira
