### ISSUE TITLE
Onboard to the thoth group in cnv agrocd  

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#71]
i would like to request for adding @pacospace to the **thoth** group present on cnv argocd. So that Francesco can also be able to access the https://argocd-server-argocd.apps.cnv.massopen.cloud/applications and view all the apps accessible to the **thoth** group

**Comment by HumairAK** [comment]
Talked with @harshad16  offline, seems like @pacospace is already in the group. Either he's logging in with a different email, or something else is going on.  @pacospace can you tell us a bit more what happens when you try to log in? Thanks.

**Comment by HumairAK** [comment]
We should also have an issue template where we can direct users for requests like these.

**Comment by harshad16** [comment]
@pacospace can you share the screenshot of the UI, at the point where once you have logged in and you cant view any of the thoth apps.

**Comment by pacospace** [comment]
Thanks @harshad16 @HumairAK for looking into it. Apparently was my issue in logging in. I can see all applications. We can close the issue :)
