### ISSUE TITLE
Black flake onboarding

### ISSUE THREAD

**Issue by tumido** [operate-first/support#76]
### Requested actions

Select all that apply:

- [ ] Create a user group
- [ ] Add users to a group
- [x] Create a namespace

### Questionnaire

1. **Team name**:
   data-science

2. **Desired namespace name**:
   ds-black-flake, ds-example-project (already in place, lacking rbac)

3. **Users to add**:
   n/a

4. **Target cluster**:
   moc

5. **Team or maintainer owned GPG key fingerprint along with a keyserver**:
   n/a

cc @martinpovolny @MichaelClifford 
---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the [docs/onboarding_to_cluster.md](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md) guide.

**Comment by HumairAK** [comment]
Projects were created, please re-open if there's anything else.
