### ISSUE TITLE
Run ML Workshop on Operate First

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#77]
As Workshop Speaker,

I would like to run my workshop on an open environment running on Openshift and using Open Data Hub (ODH) components -> `Operate First`

**Event**: https://www.mlprague.com/ 
**Dates**: Friday 26  February 2021, 14:00 – 17:30

**Workshop topic**: Cloud-native AI on OpenShift

**Workshop description**: Ever thought of doing a cloud-native AI work? What does that even mean? This workshop will introduce you to running AI related services like Spark Seldon or Jupyter on Kubernetes as part of a project Open Data Hub. You will learn how to move your AI workloads to the cluster and implement a basic data science workflow. As Jupyter notebooks have become the de facto standard in data science we will show you how to use them and adopt some of the best practices that we’ve developed over time.

@vpavlin @durandom @tumido @martinpovolny @harshad16 @4n4nd 

Reference Document: https://docs.google.com/document/d/1VOCBgJDjgvpmaO4lsY5K6EbcKiFJXnHdNIJx6aa_h08/edit#

**Comment by tumido** [comment]
Pending PRs:
- Created user group `workshops` with @pacospace @vpavlin @martinpovolny and me as the users (https://github.com/operate-first/apps/pull/207)
- Created `ws-ml-prague` namespace with `workshops` users as project admins (https://github.com/operate-first/apps/pull/207)
- Created `workshops` ArgoCD project (https://github.com/operate-first/continuous-deployment/pull/104) managed by the `workshops` openshift users group

To do:
- Create `ml-prague-app-of-apps` pointing to some additional repository with @pacospace and @vpavlin as admins, I need to consult some technicalities with @HumairAK..

**Comment by durandom** [comment]
Regarding resources: 
42 participants * 8GB RAM == 336GB
42 participants * 2-4Cores == 84 - 168 cores 

IIUC this is well within the limits of the cluster
cc @larsks

**Comment by tumido** [comment]
@pacospace @vpavlin I have set up the https://github.com/operate-first/workshop-apps repo for you. All applications placed within the `ml-prague-2021` folder will be consumed by ArgoCD, placed into `workshops` ArgoCD project and deployed to `ws-ml-prague` namespace on MOC.

I've also set up a Github Actions CI that verifies the application manifests that are expected to be added via PR from the attendees. This uses the OPA policy to check the Argo CD project and Openshift namespace, so it doesn't compromise the cluster.  

All the instructions on how to add an application are in a readme of that repo. Sounds good?

I've also made you (@pacospace and @vpavlin) both approvers on that repo and enabled bots there, so you can `/approve` PRs etc.

**Comment by pacospace** [comment]
> @pacospace @vpavlin I have set up the https://github.com/operate-first/workshop-apps repo for you. All applications placed within the `ml-prague-2021` folder will be consumed by ArgoCD, placed into `workshops` ArgoCD project and deployed to `ws-ml-prague` namespace on MOC.
> 
> I've also set up a Github Actions CI that verifies the application manifests that are expected to be added via PR from the attendees. This uses the OPA policy to check the Argo CD project and Openshift namespace, so it doesn't compromise the cluster.
> 
> All the instructions on how to add an application are in a readme of that repo. Sounds good?
> 
> I've also made you (@pacospace and @vpavlin) both approvers on that repo and enabled bots there, so you can `/approve` PRs etc.

Thank you very much @tumido. Sounds awasome!!

**Comment by tumido** [comment]
@pacospace all the operate first ArgoCD pieces should be in place. Feel free to test by adding application to:

https://github.com/operate-first/workshop-apps

The app would appear at:
https://argocd-server-argocd.apps.cnv.massopen.cloud/applications?proj=workshops

**Comment by pacospace** [comment]
> @pacospace all the operate first ArgoCD pieces should be in place. Feel free to test by adding application to:
> 
> https://github.com/operate-first/workshop-apps
> 
> The app would appear at:
> https://argocd-server-argocd.apps.cnv.massopen.cloud/applications?proj=workshops

Thanks @tumido.

**Comment by pacospace** [comment]
Related-To: https://github.com/opendatahub-io/odh-manifests/issues/327

**Comment by pacospace** [comment]
I think we can close this issue. It was a nice event and we got positive feedbacks from organizers and participatans.

Thanks @vpavlin @tumido @harshad16 @4n4nd @durandom @martinpovolny @goern.

It is available at https://www.operate-first.cloud/users/elyra/README.md.

**Comment by HumairAK** [comment]
Great work everyone!
