### ISSUE TITLE
Remove monitoring-rbac component

### ISSUE THREAD

**Issue by tumido** [operate-first/support#785]
After: operate-first/support#788

Since there's no custom prometheus deployment in `opf-monitoring`, there's no need to keep this rbac.

Remove the component and cleanup kustomization files for namespaces in cluster scope which included it. If there's nothing left in such kustomization file, this namespace kustomization can be removed as well (e.g. in namespaces like `openshift-operators`).

**Comment by durandom** [comment]
nobody seems to care about leftofers

/close
