### ISSUE TITLE
set scc priviledge true for serviceaccount aicoe-ci in opf-ci-pipelines

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#81]
### Requested actions

Some of the tekton pipelines required scc privileges for executions. 
The following command can be performed with cluster-admin privileges to fix this:
`oc adm policy add-scc-to-user privileged -z aicoe-ci -n opf-ci-pipelines`

Error log from a pipelinerun: 
```
tag-release-2jmx4-tag-release-run-lvx29": pods "tag-release-2jmx4-tag-release-run-lvx29-pod-2k9j2" is forbidden: unable to validate against any security context constraint: [spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[2].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[3].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed  Maybe missing or invalid Task opf-ci-pipelines/tag-release
```

This would be required if any user runs into similar issue on other namespaces.

#### Operator Details

1. **Name of the Operator**: tekton-pipelines

2. **Operator version**: v0.14.0
   Desired operator version. If left blank we assume the latest version released by the operator maintainer.

3. **Operator scope**: it is cluster wide 
   Should the Operator be visible to a Single Namespace or All Namespaces

4. **Documentation and links**:
https://github.com/tektoncd/pipeline/blob/v0.14.3/docs/install.md

**Comment by tumido** [comment]
Does it really need `privileged`? The docs you've linked mentiones only `anyuid` scc.

**Comment by tumido** [comment]
PR pending: https://github.com/operate-first/apps/pull/226

**Comment by harshad16** [comment]
> FTR, docs talk about the tekton controler itself, Harshad is talking about the workload task which executes `buildah`. And `buildah` needs to be `privileged`. Is that correct?

yes,  that is correct. I was pointing at the docs, as it starts with some of the descriptions. 
thanks @tumido for having a look at this.
