### ISSUE TITLE
Find out/implement a way for a bot to tag people on a given set of labels within a repo.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#838]
Due to operate-first/support#842 , we'll be moving all alerts to a single repo. This will make the repo _very_ noisy, so everyone is likely going to mute it to avoid alert fatigue. 

Unfortunately afaik github does not allow you to mute by labels. 

I've noticed that we have some bots that can recognize labels like `lgtm` etc.,  Could we extend this functionality to tag people when a certain label exists within a certain repo? This could then be used to notify people via @mentions.

**Comment by durandom** [comment]
let's see if this is still relevant after https://github.com/operate-first/apps/issues/2472 
until then
/close
