### ISSUE TITLE
deploy "Red Hat OpenShift Serverless Operator" to op1st clusters

### ISSUE THREAD

**Issue by goern** [operate-first/support#84]
**Is your feature request related to a problem? Please describe.**
As a User of OpenShift,
I would like to utilize Serverless features,
so that I can show off an object detection demo.

see https://github.com/sa-mw-dach/manuela-visual-inspection

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
This is a requirement to run Emanuela demos on Operate-First

/kind feature

**Comment by pacospace** [comment]
What is the status of this issue? when do we plan to have this in Operate First? Thanks!!

**Comment by tumido** [comment]
It is currently in our backlog. We can schedule this for next sprint I think. Would that work for you, @pacospace ?

**Comment by pacospace** [comment]
> It is currently in our backlog. We can schedule this for next sprint I think. Would that work for you, @pacospace ?

That would be awasome @tumido, thanks!

**Comment by tumido** [comment]
@pacospace we've installed the operator. Do you want us to deploy the Knative Serving and Knative Eventing or is the current state enough for you?
https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-openshift-serverless.html#installing-openshift-serverless-next-steps

https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-knative-serving.html#installing-knative-serving
https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-knative-eventing.html#installing-knative-eventing

**Comment by pacospace** [comment]
> @pacospace we've installed the operator. Do you want us to deploy the Knative Serving and Knative Eventing or is the current state enough for you?
> https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-openshift-serverless.html#installing-openshift-serverless-next-steps
> 
> https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-knative-serving.html#installing-knative-serving
> https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-knative-eventing.html#installing-knative-eventing

Thanks a lot @tumido!!! 🍻  

That would be greate to have it actually, I wanted to start working on one example for deployment using KF Serving to extend the demo we have: https://github.com/thoth-station/elyra-aidevsecops-tutorial/blob/master/docs/source/deploy-model.md

**Comment by tumido** [comment]
knative-serving is not behaving after intial deployment. Will debug on Monday.

**Comment by pacospace** [comment]
> knative-serving is not behaving after intial deployment. Will debug on Monday.

What is the status here @tumido? Thanks!

**Comment by tumido** [comment]
@pacospace still investigating.. seems kubeflow is touching things, but it's hard to debug locally, since the kubeflow manifests treated differently by the operator than by the local kfctl. :slightly_frowning_face:

**Comment by pacospace** [comment]
> @pacospace still investigating.. seems kubeflow is touching things, but it's hard to debug locally, since the kubeflow manifests treated differently by the operator than by the local kfctl.

Thanks for the update @tumido :)

**Comment by tumido** [comment]
@pacospace knative is synced. Kubeflow's Istio was making a fuss about it, but in the end I've convinced it! :tada: 

https://github.com/knative/serving/issues/8323#issuecomment-644250918

Knative serving is reporting as "ready", hope it works. :smile:

**Comment by pacospace** [comment]
> @pacospace knative is synced. Kubeflow's Istio was making a fuss about it, but in the end I've convinced it! 
> 
> [knative/serving#8323 (comment)](https://github.com/knative/serving/issues/8323#issuecomment-644250918)
> 
> Knative serving is reporting as "ready", hope it works.

NIce!!! Thanks @tumido 💯 🥇 I will create a simple app to verify that everything works!!

**Comment by pacospace** [comment]
> > @pacospace knative is synced. Kubeflow's Istio was making a fuss about it, but in the end I've convinced it!
> > [knative/serving#8323 (comment)](https://github.com/knative/serving/issues/8323#issuecomment-644250918)
> > Knative serving is reporting as "ready", hope it works.
> 
> NIce!!! Thanks @tumido   I will create a simple app to verify that everything works!!

and in the future extend the tutorial for deploying a model with serverless: https://github.com/thoth-station/elyra-aidevsecops-tutorial/issues/124
