### ISSUE TITLE
ODH weekly Z Stream releases

### ISSUE THREAD

**Issue by durandom** [operate-first/support#89]
**Is your feature request related to a problem? Please describe.**
@nakfour wrote
> After some discussions, the ODH team will be releasing a Z stream every Friday starting next week for repos:odh-manifest and operator. The plan is to manually trigger a release (TAG and operator image build) by opening an issue for a patch release. We will automate this process and add more repos as we move ahead. There will be exceptions to this release if we find hot issues or bugs that need to be fixed before a release. 

**Describe the solution you'd like**
Operate First should deploy each z-stream release into production, with the ability to rollback if problems are detected.

**Additional context**
IIUC z-stream is an update to a stable channel, hence it should not introduce disruptions 🤞 
As of now we don't have a staging environment 😢 

How do we run tests? Should we start running the ODH upstream tests? And then add additional tests on top?

cc @crobby @vpavlin @tmckayus

**Comment by durandom** [comment]
@nakfour do you have some links where this discussion was tracked? How are z-stream releases tagged?

**Comment by tumido** [comment]
This Z-stream should be a bug fix release, so the only expected change on our end is to bump all `kfdef` resources from:

```diff
*** 25,28 ****
    repos:
      - name: manifests
!       uri: "https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.0"
!   version: v1.0.0
--- 25,28 ----
    repos:
      - name: manifests
!       uri: "https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.1"
!   version: v1.0.1
```

I'd want to have these updated at least semi-automated. We don't want to manually do repetitive PRs changing those 2 lines every week.

It would be nice if we can set up a pipeline/bot that would apply a template based on a release and open a PR. And if we can host the "auto-bump" templates in our repos and the bots would just read and apply them, it would be even better.

I think this is not the only case we would do repetitive tasks (yet it's the first one), hence having it set in a configurable and extendable fashion would be the best.

I've opened an issue for this here: https://github.com/thoth-station/thoth-application/issues/896

/cc @goern

**Comment by nakfour** [comment]
@durandom Z stream releases are done by a bot and initiated by manually creating an issue for patch release, see here: https://github.com/opendatahub-io/opendatahub-operator/issues/new/choose
Creating the issue right now is manual, hoping to get it automated at some point.

**Comment by goern** [comment]
@harshad16

**Comment by tmckayus** [comment]
sounds good to me, as long as they are limited to bug fixes and no API or functionality changes to align with the Semver definition of z-stream.

**Comment by HumairAK** [comment]
We now have automation that will create a PR updating all kf-defs after a tag-release in odh-manifests. 
- odh-manifests tags new release
- automation triggered, updates all kfdefs in Operate-First to latest release, creates PR 
- manual review of pr/merge (only manual step, and we'll keep it this way for a while I think) 
- argocd auto deploys changes to live system.
