### ISSUE TITLE
Error spawning JH Server

### ISSUE THREAD

**Issue by oindrillac** [operate-first/support#90]
**Describe the bug**
I tried to stop my server and on restarting it, it is stuck on the spawn screen and timed out twice.

**To Reproduce**
1. Go to 'https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/hub/home'
2. Click on 'Stop Server'
3. Now Spawn a new server and select 's2i-minimal' image and 'Large' size.
4. Spawn Fails and times out
4. Click 'Relaunch Server'
5. Spawn Fails again

**Expected behaviour**
The JH notebook server should have spawned succesfully

**Screenshots**

![image](https://user-images.githubusercontent.com/32435206/107977313-e26d9580-6f88-11eb-8769-9b450f1c4f2f.png)

![image](https://user-images.githubusercontent.com/32435206/107977368-ff09cd80-6f88-11eb-8d2b-ae38a07f1b2c.png)

**Comment by tumido** [comment]
Thank you for raising this ticket! We're facing some issues with OpenShift networking and pod scheduling. https://github.com/operate-first/SRE/issues/62

This issue is caused by this problem, therefore I'm gonna mark this issue as `duplicate` though I'm gonna keep it open and pin it for visibility.

**Comment by oindrillac** [comment]
Update on this: I still see an issue spawning my NB Server with my existing RH account. I re-spawned and tried logging out during the long spawn process to sign back in with my external personal account and it spawned fine for me with the external account :+1:

**Comment by tumido** [comment]
May be related: https://github.com/operate-first/support/issues/91

**Comment by oindrillac** [comment]
My MOC JH Account is still having issues while spawning. It times out trying to spawn each time. Is this still expected?
I am currently using JH with my external personal account which spawns fine but has only 2 Gigs PVC and hence is a blocker for my work.

**Comment by tumido** [comment]
@oindrillac it's spawning just fine for me now, I'm unable to find any logs on your failure. Wanna ping me once you're online today and we can try sorting it out? :slightly_smiling_face:

**Comment by HumairAK** [comment]
I see that a PR was made w.r.t to this -- was the issue resolved?

**Comment by tumido** [comment]
I wouldn't say resolved, the PR is rather a workaround. @oindrillac's original user profile is still not usable and I couldn't figure out why. I've decided it's not worth fixing, because it would eventually be resolved by the cluster reinstall.

I think this issue may be closed as a wontfix (?) probably. WDYT?

**Comment by oindrillac** [comment]
This was fixed with the cluster reprovisioning :tada: closing :)
