### ISSUE TITLE
Cannot access JH with my personal external account

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#91]
**Describe the bug**
Cannot access JH with my personal external account. After login it is stack on white page. (using Firefox)

If I try with Chrome, I receive an error reported in the Screenshots section below.

**To Reproduce**
1. Login https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/
2. Select google email

**Expected behaviour**
Access correctly JH

**Screenshots**
![Screenshot from 2021-02-17 10-34-21](https://user-images.githubusercontent.com/27498679/108185233-60a67500-710c-11eb-8c93-e333fcfb0e5e.png)

**Additional context**

**Comment by tumido** [comment]
@pacospace I've tried with my personal account and it worked just fine for me. :confused: 

Was it your first log in?

Were you met with the "Authorize access" screen?
![image](https://user-images.githubusercontent.com/7453394/108190930-d4e41700-7112-11eb-8974-8dfda3999a51.png)

**Comment by pacospace** [comment]
> @pacospace I've tried with my personal account and it worked just fine for me. 
> 
> Was it your first log in?

Actually no, two days ago I was working with that without problems, but now I cannot access it anymore, even deleting all cookies.
> 
> Were you met with the "Authorize access" screen?
> ![image](https://user-images.githubusercontent.com/7453394/108190930-d4e41700-7112-11eb-8974-8dfda3999a51.png)
> 
Yes all procedure done the first time I logged in.

> I can see your user and identity are populated just fine on the cluster, so I have no idea what happened... The auth logs are not showing anything suspicious for your account either.

**Comment by tumido** [comment]
@pacospace it seems like a JH single user server is still running for that user just fine. I have no idea what is going on in there.

Can you try accessing it directly please?

```
https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/user/<USER_EMAIL>/tree?
```

**Comment by pacospace** [comment]
> @pacospace it seems like a JH single user server is still running for that user just fine. I have no idea what is going on in there.
> 
> Can you try accessing it directly please?
> 
> ```
> https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/user/<USER_EMAIL>/tree?
> ```

I can see that and I actually shutdown what was running, then I tried going back to panel and to the server again, but it has blank page at `https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/user/<USER_EMAIL>/lab?` and nothing happens.

**Comment by pacospace** [comment]
> > @pacospace it seems like a JH single user server is still running for that user just fine. I have no idea what is going on in there.
> > Can you try accessing it directly please?
> > ```
> > https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/user/<USER_EMAIL>/tree?
> > ```
> 
> I can see that and I actually shutdown what was running, then I tried going back to panel and to the server again, but it has blank page at `https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/user/<USER_EMAIL>/lab?` and nothing happens.

I stopped the server and started new one and now it is working, Thanks @tumido !

**Comment by tumido** [comment]
This doesn't seem like a standard behavior, I think it might be related to the current cluster instabilities and/or https://github.com/operate-first/support/issues/90 https://github.com/operate-first/SRE/issues/62

**Comment by HumairAK** [comment]
Since the issue is resolved, let's close this for now, as we already have an issue for cluster instabilities. We can re-open again once cluster is stable and if we encounter this problem again.
