### ISSUE TITLE
cdolfi requests larger pvc 

### ISSUE THREAD

**Issue by cdolfi** [operate-first/support#93]
User details:
cdolfi

Desired resource change:
I would like my JH PVC limit to be increased from 2Gb to 8Gb

The size of my pipenv cache is 1.5 and I am getting a "disk quota exceeded" error when trying to run notebooks

**Comment by HumairAK** [comment]
@cdolfi  I've increased your pvc to 8Gi. Can you confirm?

**Comment by tumido** [comment]
I think you can also delete the pipenv cache. It's not needed at all.

**Comment by HumairAK** [comment]
I think this issue is resolved, feel free to re-open if there's more.
