### ISSUE TITLE
How to free the PVC for a user?

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#96]
**Description**
I spawned an image on JH and didn't cloned anything inside, but my PVC result as full. How to free the PVC memory?

**Additional context**

**Comment by 4n4nd** [comment]
I found a `.cache` dir in your PVC that was taking a lot of your PVC storage (8Gi)
```
(app-root) sh-4.4$ du -sh .cache
6.8G    .cache
```

**Comment by HumairAK** [comment]
@pacospace did that resolve your issue? If so can we close this issue?

**Comment by pacospace** [comment]
> @pacospace did that resolve your issue? If so can we close this issue?

Yes @HumairAK, thanks! and thanks @4n4nd, I ll remember to do that If I see my PVC is going full again due to pipenv cache.
