### ISSUE TITLE
PROJECT: cnbi-bot

### ISSUE THREAD

**Issue by goern** [operate-first/support#968]
### Select all that apply

- [X] Create a new ArgoCD project for existing team
- [X] Enlist an application to be deployed automatically via ArgoCD
- [ ] Add a new user to an ArgoCD Project

### Team name

thoth

### Target cluster

Smaug

### Managed namespaces

thoth-cnbi-bot-stage, thoth-cnbi-bot-prod

### Application source git repository

https://github.com/goern/cnbi-bot

### Path to manifests within the repository

manifests

**Comment by goern** [comment]
anything I need to do to move this forward?

**Comment by schwesig** [comment]
ping
