### ISSUE TITLE
Namespace for A Ray+ODH deployment on MOC

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/support#97]
### Requested actions

Select all that apply:

- [ ] Create a user group
- [ ] Add users to a group
- [x] Create a namespace

### Questionnaire

1. **Team name**:
AICOE

2. **Desired namespace name**:
ray-odh-integration

3. **Users to add**:
eerlands@redhat.com

4. **Target cluster**:
moc

5. **Team or maintainer owned GPG key fingerprint along with a keyserver**:
I do not believe I will require any encryption
---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the [docs/onboarding_to_cluster.md](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md) guide.

**Comment by tumido** [comment]
Hey @erikerlandson ! We currently don't have a AICOE user group in operate-first right now, I will create a new user group for you, though I think AICOE name is too general, would you mind if I name it `ray`? :slightly_smiling_face:

**Comment by erikerlandson** [comment]
@tumido, `ray` should be fine :+1:
