### ISSUE TITLE
NEW PROJECT: IPFS

### ISSUE THREAD

**Issue by RobotSail** [operate-first/support#971]
### Target cluster

Smaug

### Team name

redhat-et

### Desired project names

ipfs

### Project description

This project is for experimenting with various IPFS Nodes. We are currently interested in deploying [Estuary](https://github.com/application-research/estuary), and having it operate as an IPFS node within Operate First.
Eventually we would like to share this with the broader community, and integrate with the ArgoCD flow. 

Link:
- [Estuary](https://github.com/application-research/estuary)
- [Estuary Website](https://estuary.tech/)

### Users needing access

- sallyom
- djach7
- cooktheryan
- guymguym
- jsawaya

### Namespace Quota

Small

**Comment by durandom** [comment]
@RobotSail @sallyom I created https://github.com/operate-first/apps/pull/2421

please note that I changed the group name to be redhat-et-platform to be more discriptive

**Comment by RobotSail** [comment]
Thanks @durandom, `redhat-et-platform` is perfect
