### ISSUE TITLE
NEW PROJECT: Kruize HPO

### ISSUE THREAD

**Issue by rbadagandi** [operate-first/support#972]
### Target cluster

Smaug

### Team name

kruize

### Desired project names

openshift-tuning

### Project description

[Kruize HPO](https://github.com/kruize/hpo) Hyper parameter optimization is a machine learning performance tool for tuning Kubernetes and Native applications, where it takes a user defined Objective function (SLO) and uses Optuna framework to arrive at the most optimal configurations to help SREs tune their applications.

Initially incorporated as part of [Kruize Autotune](https://github.com/kruize/autotune), which is an autonomous performance optimization tool for Kubernetes applications, we realised Kruize HPO can be used in non-kubernetes applications as well like OS tuning, tuning Openshift itself and made it a separate REST API service to be consumed by our customers.

We want to deploy kruize HPO on operate first to enter community cloud and gain more user traction, to understand real production user issues and gain operations insights.

### Users needing access

rbadagandi, khansaad, dinogun, chandrams, kusumachalasani

### Namespace Quota

Medium

**Comment by rbadagandi** [comment]
Tracking this as part of https://github.com/operate-first/community/issues/205

**Comment by durandom** [comment]
@rbadagandi let me know if you have a PR to create the namespace and groups. Otherwise I'm happy to take care of it and create one

**Comment by durandom** [comment]
@rbadagandi can we close this, now that the namespaces are deployed?

**Comment by schwesig** [comment]
/close
can be closed, see comment before
