### ISSUE TITLE
Enable vault for secrets management for copilot-ops

### ISSUE THREAD

**Issue by tumido** [operate-first/support#973]
OCTO Copilot ops bot team would like to get access to Vault for secret management for their [copilot-ops](https://github.com/operate-first/apps/tree/master/cluster-scope/base/core/namespaces/copilot-ops) namespace on Smaug.

Please enable a SecretStore + grant them access to Vault UI.

/cc @RobotSail
/assign @mimotej

**Comment by HumairAK** [comment]
compelted, see linked prs above
