### ISSUE TITLE
onboard fridolin to moc-cnv cluster

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#98]
### Requested actions

Select all that apply:

- [ ] Create a user group
- [x] Add users to a group

### Questionnaire

1. **Team name**: Thoth

2. **Desired namespace name**:  All already present

3. **Users to add**: fpokorny@redhat.com

4. **Target cluster**: moc-cnv(moc-base)

5. **Team or maintainer owned GPG key fingerprint along with a keyserver**: NA

**Comment by tumido** [comment]
Resolved via #293

Thank you @harshad16 ! :slightly_smiling_face:
