### ISSUE TITLE
Superset route in dashboard doesn't work, and first/last name need to be set 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#999]
As per @rimolive : 

> btw, first and last names are required fields.

So we should set these in oauth set up in superset config, they can be usernames for now since we don't get first/last names  via github (iirc). Also, the secure route is not used in dashboard so we should update that as well, maybe just patch the original route to use acme.

**Comment by durandom** [comment]
/assign @HumairAK 

is this still an issue?
does it relate to os-climate?
are any users affected?
